### ISSUE TITLE
Pyscript windows 11 install error

### ISSUE THREAD

**Issue by romperstomper** [pyscript/pyscript#100]
The latest LTS version didn’t work. google suggested using 16.13.2 as it used older version of npm. That managed to get past ‘npm install’, however the next command ‘npm run dev’ introduced a new error:

![image](https://user-images.githubusercontent.com/1248548/166159291-8e39c8cf-2e96-47e6-9721-dbc883eb82ec.png)

**Comment by romperstomper** [comment]
Seems OK in ubuntu 20.04 running on same Windows 11 host via WSL2:

![image](https://user-images.githubusercontent.com/1248548/166160540-1f3f876c-e3a2-48f8-8e74-65d068197378.png)

**Comment by verhulstm** [comment]
interesting,

we built on ubuntu and mac, i am looking into windows build support

sometimes nodejs apps dont build on ntfs based file systems becouse the node deps are very deeply nested and NTFS cant see file that are that deep. its related to max file path length i think

**Comment by romperstomper** [comment]
so much for windows being posix compatible i guess. just for lolz, I'm getting the exact same 'broken' html page whether in native windows (where I can't get the node app to run) OR in ubuntu where the node app is running fine. Here is a screenshot from WSL:

![image](https://user-images.githubusercontent.com/1248548/166160789-0b420cbd-df56-44ab-93d0-747fe7f63746.png)

**Comment by verhulstm** [comment]
yes, that screen should means your page cant find the pyscript.js file

**Comment by fpliger** [comment]
@romperstomper   thanks for reporting! Are you trying to use pyscript or to build it on your machine from source?

**Comment by romperstomper** [comment]
Hi Fabio, I have not tried building it from source. Are there instructions
to build it on Windows 11? I am happy to try

**Comment by tedpatrick** [comment]
`npm run dev` works cross-platform on release 2022.09.1. Closing issue.
