### ISSUE TITLE
cannot Deploy py-script Web App on Github Pages

### ISSUE THREAD

**Issue by RizmyAbdulla** [pyscript/pyscript#1003]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I published my project to **github pages** and if I go to the web page it says download this file(https://cdn.jsdelivr.net/pyodide/v0.21.3/full/pyodide_py.tar).And then It says Loading runtime... infinitely

### What browsers are you seeing the problem on? (if applicable)

Microsoft Edge, Other

### Console info

```shell
Failed to https://cdn.jsdelivr.net/pyodide/v0.21.3/full/pyodide_py.tar
load resource: net::ERR_BLOCKED_BY_CLIENT

Uncaught (in promise) TypeError: compat.ts:153
Failed to fetch
    at loadBinaryFile (compat.ts:153:24)
    at loadPyodide (module.ts:115:17)
    at async PyodideRuntime.loadInterpreter (pyscript.js:sourcemap:27680:32)
    at async PyodideRuntime.initialize (pyscript.js:sourcemap:27602:13)
```

**Comment by JeffersGlass** [comment]
Hi @RizmyAbdulla ! I see you’ve closed this issue - were there any settings or adjustments or fixes that you needed to make to (hopefully) get this working? Asking for the sake of others who may have similar issues down the road.

**Comment by RizmyAbdulla** [comment]
@JeffersGlass i tested my py-script web app on Brave and edge and it didn't work, but when I tested on Firefox it worked fine. I think the problem is in the browser.

project link : https://rizmyabdulla.github.io/ToolBox_Py-Script/
