### ISSUE TITLE
Add documentation for the splashscreen

### ISSUE THREAD

**Issue by FabioRosado** [pyscript/pyscript#1004]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a duplication
- [X] I already searched in Google and didn't find any good information or help

### What is the issue/comment/problem?

Our splashscreen is now a plugin thanks to the great work of Antonio. Over on discord we had two users that want to send custom messages to the load screen and knowing when the screen is gone.

we should add documentation for it under plugins and probably document the .log method

@antocuni any concerns about documenting the .log method?

**Comment by antocuni** [comment]
> @antocuni any concerns about documenting the .log method?

+1 for documenting it
