### ISSUE TITLE
Antigravity example is broken after stdout/display changes

### ISSUE THREAD

**Issue by fpliger** [pyscript/pyscript#1005]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

After the changes related to stdout/err and display, the antigravity example is broken. It currently fails with the following error:

```
Traceback (most recent call last):
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 435, in eval_code
    .run(globals, locals)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 304, in run
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 1, in <module>
  File "/home/pyodide/antigravity.py", line 44, in <module>
    _auto = Antigravity(append=True)
  File "/home/pyodide/antigravity.py", line 14, in __init__
    target = target or sys.stdout._out
AttributeError: '_io.TextIOWrapper' object has no attribute '_out'
```

This is due to the fact that we are not custom changing `sys.stdout` the same way.  

It seems like the best option here would be to implement the right `_repr_` method but would love to hear @philippjfr on this

**NOTE: ** goes without saying that we should add a test as well :)

**Comment by antocuni** [comment]
> **NOTE: ** goes without saying that we should add a test as well :)

what is not tested is broken ;)
