### ISSUE TITLE
Add fetch documentation

### ISSUE THREAD

**Issue by fpliger** [pyscript/pyscript#1007]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a duplication
- [X] I already searched in Google and didn't find any good information or help

### What is the issue/comment/problem?

Current fetch documentation is poor and lacking examples that could be useful to users. @JeffersGlass notes for the next release have some great information that we should add to the docs.

**Comment by madhur-tandon** [comment]
Assigning myself
