### ISSUE TITLE
Can you develop vue components?Or the vue plug-in

### ISSUE THREAD

**Issue by AndersonHJB** [pyscript/pyscript#1043]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project area (see the above section)

### What is the idea?

Can you develop vue components?Or the vue plug-in

### Why is this needed

For lower cost teaching, popularize Python teaching. Reduce the pressure on students and parents.

**Comment by FabioRosado** [comment]
Hello @AndersonHJB  I've started working on a [Vue starter with pyscript](https://github.com/FabioRosado/pyscript-vue-starter), would this address your request? Or are you thinking about something else?

Also, apologies for the long delay in getting back to you!

**Comment by WebReflection** [comment]
this looks like a relic of the previous state + it's rather a discussion than an issue.

Closing as maintainer duty. Feel free to re-open with more details based on latest PyScript, thanks!
