### ISSUE TITLE
Add support for pyscript.net/scratchpad/

### ISSUE THREAD

**Issue by antocuni** [pyscript/pyscript#1046]
I would like to to have `pyscript.net/scratchpad/` as a place where we can upload and host experiments which are meant to be temporary, throw-away, without any guarantee, etc.

My most immediate use case is that I want to start experimenting with custom pyodide builds and I need a place where to host them.

Suggestions for better names are welcome. My ideas so far:
- `pyscript.net/scratchpad/`
- `pyscript.net/experiments/`
- `pyscript.net/misc/`
- `pyscript.net/tmp/`

**Comment by WebReflection** [comment]
I *think* this is not a PyScript related issue, rather something for *pyscript.net* so that *maybe* I can close this.
