### ISSUE TITLE
Links to the code of examples from home page

### ISSUE THREAD

**Issue by vincentdavis** [pyscript/pyscript#1047]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a duplication
- [X] I already searched in Google and didn't find any good information or help

### What is the issue/comment/problem?

Google searches and New users land here [https://pyscript.net](https://pyscript.net) 
The examples here are great. As a new user of pyscript with little HTML experience I would really like to be able to see the code that generates the example. Actually, I think the code is almost more important than the output on the examples.

Solution: Have links from the example _cards_ and the examples themselves to the files in GitHub.

**Comment by vincentdavis** [comment]
@FabioRosado That is awesome!
I especially like the separation of HTML and backend python in some of the examples.

**Comment by FabioRosado** [comment]
@fpliger  worked on adding a `py_tutor` plugin that cleaned up the HTML code in [the examples](https://github.com/pyscript/pyscript/blob/main/examples/).  So you can also have a look at the examples folder in this repo. 

I'm closing this issue, but feel free to reopen if you think it's needed 😄
