### ISSUE TITLE
`<py-env>` ignores package extras in requirements spec

### ISSUE THREAD

**Issue by Zac-HD** [pyscript/pyscript#105]
```html
<html>
<head>
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
    <py-env>
        - hypothesis[cli]
    </py-env>
</head>
<body>
    <h1>Requires-extra Demo</h1>
    <py-script>
import hypothesis
from hypothesis.extra.ghostwriter import magic
    </py-script>
</body>
</html>
```
> Requires extra Demo
> JsException(PythonError: Traceback (most recent call last): File "/lib/python3.10/site-packages/_pyodide/_base.py", line 429, in eval_code .run(globals, locals) File "/lib/python3 .10/site-packages/_pyodide/_base.py", line 300, in run coroutine = eval(self.code, globals, locals) File "", line 2, in File "/lib/python3.10/site-packages/hypothesis/extra/ghostwriter.py", line 98, in import black ModuleNotFoundError: No module named 'black' )

The `[cli]` extra on `hypothesis` adds a dependency on Black, but this is not picked up by pyscript.  See also https://pip.pypa.io/en/stable/cli/pip_install/#requirement-specifiers and https://peps.python.org/pep-0508/#extras

**Comment by rth** [comment]
Opened upstream issue https://github.com/pyodide/pyodide/issues/2535. It's a feature that needs to be implemented in micropip. Once that is done this should also work in pyscript.

**Comment by amitsaha** [comment]
@Zac-HD  - FYI once pyodide fix is out, you will find that `black` imports/uses the multiprocessing module which is currently not supported in Python webassembly.

**Comment by Zac-HD** [comment]
I wrote https://github.com/psf/black/pull/3046 so that'll be fixed in the next release of black. In the meantime I'm using a custom wheel built with that patch.

**Comment by fpliger** [comment]
Closing this since https://github.com/pyodide/pyodide/issues/2535 has been closed (thanks @rth)! Now we just wait on the next release of Pyodide 😄
