### ISSUE TITLE
Without the Internet

### ISSUE THREAD

**Issue by Arashvscode** [pyscript/pyscript#1053]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project area (see the above section)

### What is the idea?

Is it possible that the offline feature of this project can be implemented, that is, the user can run Python codes without internet, of course, it should be noted that we import the required libraries.

**Comment by marimeireles** [comment]
Hi!
It is possible this is a dup of https://github.com/pyscript/pyscript/issues/581 so I'm going to close it to the benefit of having a centralized discussion. Let's move it there, I think Paul has an update on it.
cheers and thanks for opening the issue
