### ISSUE TITLE
Image tag not closing properly

### ISSUE THREAD

**Issue by NayanKhedkar** [pyscript/pyscript#1057]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a duplication
- [X] I already searched in Google and didn't find any good information or help

### What is the issue/comment/problem?

When image render form pyscript.py  image tag not closed properly.

**Comment by NayanKhedkar** [comment]
PR: https://github.com/pyscript/pyscript/pull/1058

**Comment by FabioRosado** [comment]
Closing the issue now since the PR was merged
