### ISSUE TITLE
py- attributes not reconized in html injected after page load

### ISSUE THREAD

**Issue by bleach86** [pyscript/pyscript#1059]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

py- attributes such as py-onclick and py-click are not reconized if the HTML is injected afterwards. In this same case the javascript onclick works as expected. example code follows.

```html

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="robots" content="follow,index" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>py-onclick bug</title>



    <link rel="stylesheet" href="https://pyscript.net/releases/2022.12.1/pyscript.css" />
    <script defer src="https://pyscript.net/releases/2022.12.1/pyscript.js"></script>
    <body>
    
    	<button id="py-button" py-onclick="print_hello()">py-onclick</button>
    	<button id="js-button" onclick="print_hello_js()">onclick</button><br><br>
    	
    	<div id="js-button-container"></div>
    	
    	<div id="py-button-container"></div>

    	<py-script>
    		import js
    		
    		py_button = Element("py-button-container")
    		js_button = Element("js-button-container")
    		
    		py_button.element.innerHTML = '<button id="py-button-injected" py-onclick="print_hello()">py-onclick-injected</button>'
    		js_button.element.innerHTML = '<button id="js-button-injected" onclick="print_hello_js()">onclick-injected</button>'
    		
    		def print_hello():
    			js.console.log("Hello from Python!")
    	</py-script>
    	
    	<script>
    		function print_hello_js () {
    			console.log("Hello from JavaScript!");
    		}
    	</script>
    </body>
</html>

```

In this code there are 4 buttons on page. 2 are coded directly into the HTML. One for py-onclick and one for onclick. 
These both work as expected. 

The other 2 buttons are injected after page load by pyscript. As before one for py-onclick and one for onclick.

While the onclick button works as expected, the py-onclick button does nothing. Interestingly, if you don't add an id to the injected HTML there is an error for missing id with py-onclick. However, the button is not functional even with an id.

### What browsers are you seeing the problem on? (if applicable)

Firefox, Chrome

### Console info

```shell
There is no console output.
```

**Comment by marimeireles** [comment]
Hey @bleach86 thanks for opening the issue.
I'm not super sure but I believe `py-onclick` was completed discontinued, please correct me if I'm wrong @FabioRosado.
I guess it was deprecated for a few weeks or months, but seems like it was completely removed now.

**Comment by FabioRosado** [comment]
Thank you forthe ping Mariana 😄  I think there's two things happening here. 

The correct `py-onclick` attribute is `py-onClick`, although we recommend using `py-click` instead.

Then we have the issue that *py- attributes such as py-onclick and py-click are not reconized if the HTML is injected afterwards.*. 

Currently, each `py-` attribute will create the event at page load only, so if you are trying to inject it once the page load happened, the attribute event won't work. If you want to do it afterwards once the page load happened you can do it manually. Here's an example:

```html
<py-script>
        from pyscript import Element, js
        from pyodide.ffi.wrappers import add_event_listener

        py_button = Element("py-button-container")
        js_button = Element("js-button-container")
        
        py_button.element.innerHTML = '<button id="py-button-injected">py-onclick-injected</button>'
        js_button.element.innerHTML = '<button id="js-button-injected" onclick="print_hello_js()">onclick-injected</button>'
        
        def print_hello(*args):
          js.console.log("Hello from Python!")

        # create event listener manually
        add_event_listener(py_button.element, "click", print_hello)

</py-script>
```

We currently have an issue to improve the `py-` attributes so we can dynamically add event listeners to address your use case, but perhaps this is a good workaround for now? 🤔

**Comment by marimeireles** [comment]
event expert 👊
can we fix that by observing the creation of `py-events` on the pyscript side?

**Comment by FabioRosado** [comment]
Ted was playing with the mutation observer in the research repo, but he mentioned that he saw some weird behaviour when tearing events down (if I remember correctly).  But yeah I think we probably should work on trying to get the dynamic events working 😄

**Comment by WebReflection** [comment]
The solution *is* the usage of *MutationObserver* but we need to change event initialization logic, or better, we need to trigger that logic every time an element not previously patched exposes or gets created with a `py-*` attribute.

The same should be done with any `<py-*>` custom element injected after the page loads or we have the same issue.

I'd be happy to fix this once the PR about events lands and my suggestion is to use [qsa-observer](https://github.com/WebReflection/qsa-observer#readme) which is behind the [custom-elements polyfill](https://www.npmjs.com/package/@ungap/custom-elements) and it's battle tested for both mobile and desktop browsers.

**Comment by WebReflection** [comment]
To whom it might concern, this is being tackled in here: https://github.com/pyscript/pyscript/pull/1435

The presented use case has been used, after little modification, to create the test too so thanks for that 👍
