### ISSUE TITLE
A simple example of NumPy and user interaction

### ISSUE THREAD

**Issue by tirthajyoti** [pyscript/pyscript#106]
I found the given examples either not related to Data science directly, or too involved (in terms of front-end code) for data scientists who want to **just run NumPy/Matplotlib code on the browser with simple user interactions with HTML widgets**. So, I created a simple example of random variable generation (which is foundational for data science work anyway).

Here is the HTML hosted on my Github page. An awesome nod to the power of PyScript that we can run this kind of computation on a Github static page w/o a single line of JS code actually doing anything :-)

https://tirthajyoti.github.io/pyscript_random_gen.html

**Comment by verhulstm** [comment]
this is really great, thanks for making such a nice demo site :)

**Comment by fpliger** [comment]
closing this as no action.
