### ISSUE TITLE
Problem loading multiple packages in py-env

### ISSUE THREAD

**Issue by tirthajyoti** [pyscript/pyscript#107]
When I have a single package name inside py-env tags, my script works. But more than one, and it cannot load anything and throws out exceptions.

This works,

```
...
<py-env>
- matplotlib
</py-env>
  </head>
```
But,

```
...
<py-env>
- matplotlib
- pandas
</py-env>
  </head>
```
gives,

```
JsException(PythonError: Traceback (most recent call last): File "/lib/python3.10/site-packages/_pyodide/_base.py", line 429, in eval_code .run(globals, locals) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 300, in run coroutine = eval(self.code, globals, locals) File "", line 1, in ModuleNotFoundError: No module named 'matplotlib' )
```

**Comment by tirthajyoti** [comment]
I think I figured it out. It is a bit surprising. It looks like that indentation matters here just like in the `py-script` tag. 
This worked. Note the zero indentation of the list of packages.
However, for a single package, I was using random indentation and it worked!
```
	<py-env>
- matplotlib
- pandas
	</py-env>
```

**Comment by TommyDew42** [comment]
Maybe we should add an error message to indicate there's indentation problem? Happy to work on it if we confirm this is what we want!

**Comment by fpliger** [comment]
just checked and this is fixed in current `main`
