### ISSUE TITLE
Builtin PyScript event when REPL Run Button is Clicked

### ISSUE THREAD

**Issue by limitcracker** [pyscript/pyscript#1074]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project area (see the above section)

### What is the idea?

Like `py-click` but for the REPL Run Button ▶️

When the REPL Run button is clicked to automatically get the values of the attached INPUT elements etc.

Maybe a timeout is needed also like React.

### Why is this needed

It great for making Programming courses

**Comment by JeffersGlass** [comment]
The work-in-progress PR linked to this issue adds Plugin hooks that execute immediately before/after a \<py-repl\> executes, which will provide access to the values you're looking for.

For example, if you want to have an event emitted every time a REPL executes, you can implement a small plugin which hooks into the new `afterPyReplExec()` lifecycle method and emits the appropriate event.

**Comment by limitcracker** [comment]
> The work-in-progress PR linked to this issue adds Plugin hooks that execute immediately before/after a <py-repl> executes, which will provide access to the values you're looking for.
> 
> For example, if you want to have an event emitted every time a REPL executes, you can implement a small plugin which hooks into the new `afterPyReplExec()` lifecycle method and emits the appropriate event.

is there a guide on how to make plugins? 
thanks in advance!

**Comment by JeffersGlass** [comment]
There's a decent getting-started guide at https://docs.pyscript.net/latest/guides/custom-plugins.html

**Comment by limitcracker** [comment]
> There's a decent getting-started guide at https://docs.pyscript.net/latest/guides/custom-plugins.html

I was studying the guide and I was wondering if I can listen to the `afterPyReplExec() ` event using Python and not JS ?

**Comment by JeffersGlass** [comment]
You can - if you make a Python plugin object as described in that guide, and it has an `afterPyReplExec` method, it will get called with the following keyword arguments:

```js
/**
     * @param interpreter  The interpreter object that will be used to evaluated the Python source code
     * @param src  {string} The Python source code to be evaluated
     * @param outEl  The element that the result of the REPL evaluation will be output to.
     * @param pyReplTag  The <py-repl> HTML tag the originated the evaluation
     * @param result The result of evaluating the Python (if any)
     */
```

We haven't had a release since that PR was merged, so you'll need to be using a bleeding edge (unstable) build or building from source yourself.

**Comment by limitcracker** [comment]
> You can - if you make a Python plugin object as described in that guide, and it has an `afterPyReplExec` method, it will get called with the following keyword arguments:
> 
> ```js
> /**
>      * @param interpreter  The interpreter object that will be used to evaluated the Python source code
>      * @param src  {string} The Python source code to be evaluated
>      * @param outEl  The element that the result of the REPL evaluation will be output to.
>      * @param pyReplTag  The <py-repl> HTML tag the originated the evaluation
>      * @param result The result of evaluating the Python (if any)
>      */
> ```
> 
> We haven't had a release since that PR was merged, so you'll need to be using a bleeding edge (unstable) build or building from source yourself.

Hi again! Can I use plugin code without making a new file? Cause I want to use it in a blog of mine where I can't upload files.

Br, John
