### ISSUE TITLE
Improve tutorials main page

### ISSUE THREAD

**Issue by FabioRosado** [pyscript/pyscript#1076]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a duplication
- [X] I already searched in Google and didn't find any good information or help

### What is the issue/comment/problem?

The [main tutorials page](https://docs.pyscript.net/latest/tutorials/index.html) in our docs is a big hard to understand, this is mainly caused by us showing the headings in each tutorial.

We should add sections to the tutorial page (and add more tutorials for each section), to make it easier to grasp.

Proposed outline:

- Getting Started
- Basics
  -  How to call a function on button click
  - How to write content to the page
  - How to fetch a resource (Make sure to link to the in-depth guide)
  - How to upload and manipulate images (idea stolen from Jeff's site 😄 )
  - ...
- Configuration
  - How to use `fetch`
  - How to set a different runtime
  - How to specify plugins (once #1065  is merged)
  - ...

**Comment by marimeireles** [comment]
I'm not sure if I understand what's the difference between the "basics" how to fetch a resource and the "configuration" how to use fetch...
If you're interested in having a look into the philosophy behind our docs we're basing ourselves in https://diataxis.fr/ and their main implementation example is https://docs.djangoproject.com/en/4.1/

**Comment by FabioRosado** [comment]
The idea behind this issue is to structure the main tutorial index page more since it's confusing at the moment. Something similar to what Django does with their guides page: https://docs.djangoproject.com/en/4.1/topics/

You have sections such as "[Models and databases](https://docs.djangoproject.com/en/4.1/topics/db/)" and then each article under it. Something like:

- Models and Databases
  - Models
  - Making queries
  - ...

Regarding the 'basics > fetch' and 'configuration > fetch', I was thinking about the two ways to fetch files. One is using the `py-config` to fetch a file or more, other is using pyodide or the js fetch to fetch a file and do something with it 😄

**Comment by marimeireles** [comment]
Hum, I see. Thanks for clarifying. Makes sense but at the same time I think this is a bike shedding problem 😅 I'll abstain here. No strong opinions one way or the other!
