### ISSUE TITLE
Add py-attributes to the reference docs

### ISSUE THREAD

**Issue by FabioRosado** [pyscript/pyscript#1077]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a duplication
- [X] I already searched in Google and didn't find any good information or help

### What is the issue/comment/problem?

We should add a section to mention all the `py-` attributes that users can use to our reference docs. Ideally, we should have a very basic example on how to use said attribute, for example:

```html
<button py-click='func()'>Click me</button>
<py-script>
    func():
       print("Hello world!")
</py-script>
```

**Comment by marimeireles** [comment]
This was completed by us.
