### ISSUE TITLE
Add Description of `src` attribute to `<py-script>` documentation

### ISSUE THREAD

**Issue by JeffersGlass** [pyscript/pyscript#1079]
The reference page for the `<py-script>` tag lists the `src` attribute for that tag and gives examples, but could use a description of what that attribute does.

That page is `docs/reference/elements/py-script.md`

**Comment by Kd-Here** [comment]
Hey @JeffersGlass can I add description about `src`

**But there is already small description available** 
![image](https://user-images.githubusercontent.com/90677747/210083064-8670a5c2-f27d-4794-ac79-f3958eb11b26.png)

Should I edit it to brief but short description what is:-
Absolute URLs
Relative URLs

**Comment by JeffersGlass** [comment]
Thanks @Kd-Here ! I was thinking more along the lines of clarifying that the contents of the resource retrieved from the URL are evaluated by the interpreter without being downloaded to the filesystem. There's been some confusion amoung users on that point.

**Comment by Kd-Here** [comment]
Is this sufficient?
When a Python file is reffered with `src` atribute, it is executed, and then added to the namespace where it was refer.
