### ISSUE TITLE
lxml package

### ISSUE THREAD

**Issue by tirthajyoti** [pyscript/pyscript#108]
Is `lxml` package installed with `pyodide`? Without it, I am having trouble reading HTML table into a Pandas DataFrame using `pd.read_html` method. I got this error,

`ImportError: lxml not found, please install it`

As you can imagine, in many use cases, Pandas must read an HTML table from a div section.

**Comment by rth** [comment]
You can see the list of packages built in Pyodide in https://github.com/pyodide/pyodide/tree/main/packages . lxml is one of them.

**Comment by tirthajyoti** [comment]
Thank you. It was resolved by adding `lxml` to py-env. Closing this issue now.
