### ISSUE TITLE
Add docs on how to access HTML elements from PyScript

### ISSUE THREAD

**Issue by luptior** [pyscript/pyscript#109]
Original question: Trying to move some of the JavaScripts to pyscript, its there a way to of something like this in pyscript now?

`var metas = document.getElementsByTagName('meta');`

There is! There are some examples in this very issue.
Adding docs for it would be very easy =)
I think it probably fits under the "How to" or the "Reference session", maybe?
Depending on how the person who chooses to tackle this one decides to go about it.
Probably easier to add it on the "how to" though because I think @tedpatrick has specific ideas on how the reference should go.

In case you need help for this, please let me know!
We have docs on how to contribute to the docs, but maybe they're not so clear.
Thank you!

**Comment by its-pablo** [comment]
ooh moving through the DOM with this tool will be cool

**Comment by taffarel55** [comment]
It'd be wonderful!

**Comment by cceyda** [comment]
`from js import document, DOMParser, setInterval`
saw this line in an example so there seems to be a thing, but would have to dig deeper into code. you can maybe get html from document and use a python DOM parser lib. which maybe a weird way to go about it. uncharted territory, much fun!

**Comment by tirthajyoti** [comment]
I am sort of using a mix of `Element` class and `document` class from `js`. Check out my Pandas demo HTML and look at the pyscript functions at the bottom where I grab a random HTML table generated by NumPy from a div above and read it back using these tricks (like `document.getElementbyId`) into Pandas to generate simple statistics.

https://tirthajyoti.github.io/pyscript_pandas.html

**Comment by cceyda** [comment]
`document.querySelector` seems to be a thing already!https://github.com/pyscript/pyscript/blob/6943304d6b763320a7a7cf0e7f5d1f60a18ca7fe/pyscriptjs/src/pyscript.py#L106

**Comment by philippjfr** [comment]
As mentioned by @cceyda this is possible by importing from the `js` package. If someone wants to contribute some guidance and clear examples demonstrating DOM manipulation that would be appreciated.

**Comment by renantescaro** [comment]
```
from js import document

inputTest = document.getElementById('test')
print(inputTest.value)
```

**Comment by fpliger** [comment]
Thanks all for contributing to this and for the patience while we work on better documentation. :)

PyScript provides a minimal higher-level API to make things easier than accessing pyodide's js interfaces and then using js directly. The intention is to make it very Pythonic and easy for users. So, we currently provide an `Element` class that you can use to declare an element with a specific `<id>`. Basically you can use it in the following way:

```
el = Element("myId")
``` 

this will return an object with a link to it's matching js object (returned by `document.querySelector('#myId')`), accessible through the `el.element` attribute, as well as some convenience methods like `write`, `clear`, `select`, `clone`, etc...

We plan to work hard this week to provide clear and better documentation on all of that this week and also expand that interface to also support mode patterns and features. So, I'll ask for a little patience while we try to catch up that work.

Also worth mentioning that this (as well as the whole project itself) is at its early stage so this API might break or change as we keep working on the project and reach a stable version.

**Comment by its-pablo** [comment]
no problem, thanks for building this awesome tool (:

**Comment by dkanze** [comment]
Can we or will be soon be able to generate HTML on the fly as can be done with JS?
```
  async buildValidGameTable(){
    let wordlecontainer = document.getElementById("wordlecontainer")

    let wordledata  = document.createElement("div")
    wordledata.classList.add("wordledata")
    wordlecontainer.appendChild(wordledata);
    wordledata.innerHTML = ''  //Initialize table

    let rows = document.createElement("div")
    rows.classList.add("rows")
    wordledata.appendChild(rows)

    rows.appendChild(this.gameRowHeading())

    for(var game = 0; game < 6; game++){
      let row = this.gameRowBuilder(game)
      rows.appendChild(row)
    }
    let focusoncell = document.querySelectorAll('.gameval')
    focusoncell[0].focus()  // Focus on first cell
  }
```

**Comment by fpliger** [comment]
@dkanze yes, you can. You can use the same APIs by importing from js `from js import <something>` and the using it. For instance, the example above should just work after you did `from  js import document` and replaced typescript with python syntax

**Comment by marimeireles** [comment]
So I guess this is a documentation issue, correct?
I'll add it under an umbrella issue and reword it for folks.
Thanks for the contributions here! ✨

**Comment by hemangjoshi37a** [comment]
Hello everyone,

I've found a solution to access HTML elements from PyScript. You can use the `js` package to import `document` and manipulate the DOM as you would in JavaScript. Here's an example:

```python
from js import document

# Get an element by its ID
input_test = document.getElementById('test')
print(input_test.value)

# Query elements using CSS selectors
element = document.querySelector('#element_id')
```

To generate HTML elements on the fly, you can use the same approach. For instance, the following example creates a new div element and appends it to another element:

```python
from js import document

# Create a new div element
new_div = document.createElement('div')
new_div.textContent = 'This is a new div element.'

# Append the new div to an existing element with the ID 'container'
container = document.getElementById('container')
container.appendChild(new_div)
```

I hope this helps! If you have any questions or need further clarification, feel free to ask. Happy coding!

**Comment by FabioRosado** [comment]
You can also use the pyscript `Element` api to do this (the tutorials from the docs tend to use this)

https://docs.pyscript.net/latest/reference/API/element.html

**Comment by WebReflection** [comment]
We currently offer `window` and `document` directly via `pyscript` module. See [our latest docs](https://pyscript.github.io/docs/2023.11.2/beginning-pyscript/) to know more.

**Comment by AlteriusOmega** [comment]
> You can also use the pyscript `Element` api to do this (the tutorials from the docs tend to use this)
> 
> https://docs.pyscript.net/latest/reference/API/element.html

Link is dead, just goes to 404. Did they remove Element from PyScript?
