### ISSUE TITLE
Update the docs once we change pyscript's versioning in the website

### ISSUE THREAD

**Issue by marimeireles** [pyscript/pyscript#1105]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a duplication
- [X] I already searched in Google and didn't find any good information or help

### What is the issue/comment/problem?

Once the following issue changes: https://github.com/pyscript/pyscript.net/issues/39
Update docs

**Comment by WebReflection** [comment]
We're trying to keep changelog and docs updated as much as we could ... so this feels like one issue to be closed.
