### ISSUE TITLE
Clear example of external CSV or JSON file read

### ISSUE THREAD

**Issue by tirthajyoti** [pyscript/pyscript#111]
It would be great to have a clear, short example of an external CSV or JSON file read using `open_url` or `pyfetch` and process it through some numerical routines like NumPy or Pandas. This will be bread and butter for data science folks.

**Comment by verhulstm** [comment]
hi, thanks for your interest in our new project. :)

take a look at this

https://github.com/pyscript/pyscript/blob/main/pyscriptjs/examples/folium.html

#####

url = (
    "https://raw.githubusercontent.com/python-visualization/folium/master/examples/data"
)
state_geo = f"{url}/us-states.json"
state_unemployment = f"{url}/US_Unemployment_Oct2012.csv"
state_data = pd.read_csv(open_url(state_unemployment))
geo_json = json.loads(open_url(state_geo).read())

**Comment by psychemedia** [comment]
Can you also declare (as with imported packages) local data files and then load them as "local" files?

**Comment by tirthajyoti** [comment]
@verhulstm thanks but I am getting `No 'Access-Control-Allow-Origin' header is present on the requested resource` error.

**Comment by verhulstm** [comment]
take a look at this 

https://verhulstm.github.io/pyscript-demo/
https://github.com/giswqs/pyscript-demo

https://github.com/verhulstm/pyscript-demo
https://github.com/giswqs/pyscript-demo

**Comment by verhulstm** [comment]
is it possible for you to share the url to your data source? if not you need to edit the server. some data sources dont allow this browsers to  connect. 

see:
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by verhulstm** [comment]
if you cannot change the configs of the data source server you can proxy the data. use a python app in conda in std cpython and have you pyscript python call your proxy an in turn you proxy get the data from the source. standard python does not have CORS security rules in place. since pyscript is in a browser we still have to deal with CORS

**Comment by tirthajyoti** [comment]
Actually, with the raw GitHub file link, this was resolved. Thanks for the pointer.

Here is my Pandas demo with this code: https://tirthajyoti.github.io/pyscript_pandas.html

**Comment by marimeireles** [comment]
I believe @ptmcg answered this one?
Feel free to reopen if you're still stuck, I'm tracking this kind of I/O issue on the linked issue though.
Thanks!
