### ISSUE TITLE
Additional Methods Required for User Plugins

### ISSUE THREAD

**Issue by JeffersGlass** [pyscript/pyscript#1110]
With the merge of #1065, PyScript can now fetch and run user plugins from URL. The documentation currently states that [only the `afterStartup` method is required](https://github.com/pyscript/pyscript/blob/bb5c59307a4f18f8d0a85ee379274008f15afb7e/docs/guides/custom-plugins.md#javascript-plugins) for default exports from user plugins; however, on trying it out, an external plugin's `afterSetup()`, `beforePyScriptExec()`, and `afterPyScriptExec()` methods are also called (assuming there's a \<py-script\> tag on the page).

![image](https://user-images.githubusercontent.com/1931111/212773066-3129d9cc-86d8-4b9a-96f0-e2b8c6574e34.png)

Personally, I think the way to solve this is actually to make all of the methods of Plugin objects optional, in the sense that we call them with the [optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) `?.` for the JavaScript plugins like we do with the Python ones.

**Comment by marimeireles** [comment]
Seems very reasonable to me.
