### ISSUE TITLE
display() of _repr_svg_ using append=False does not remove old <svg> element

### ISSUE THREAD

**Issue by cdelker** [pyscript/pyscript#1123]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

Using `display(obj, target='mydiv', append=False)` on an obj with `_repr_svg_` properly adds the <svg> tag to the div element the first time, but on a second call, the new <svg> tag is appended as a child of the first <svg> tag.

Full example:

```
<html>
  <head>
    <link rel="stylesheet" href="https://pyscript.net/latest/pyscript.css" />
    <script defer src="https://pyscript.net/latest/pyscript.js"></script>
  </head>
  <body>

    <py-script>
    class Circle:
        r = 0
        def _repr_svg_(self):
            return f'<svg height="{self.r*2}" width="{self.r*2}"><circle cx="{self.r}" cy="{self.r}" r="{self.r}" fill="red" /></svg>'          

    circle = Circle()
        
    def show():
        circle.r += 5
        display(circle, target="circle-div", append=False)

    </py-script>

    <div id="circle-div"></div>
    <div>
      <button type="button" py-onClick="show()" id="growbutton">Grow</button>
    </div>

  </body>
</html>
```

Click the button once, the svg is added to the div, and all is good:
`<div id="circle-div"><svg height="10" width="10"><circle cx="5" cy="5" r="5" fill="red"></circle></svg></div>`

Click the button again, and the expected result would be:
`<div id="circle-div"><svg height="20" width="20"><circle cx="10" cy="10" r="10" fill="red"></circle></svg></div>`

But the actual result, as verified in the browser's debug console, is:
`<div id="circle-div"><svg height="10" width="10"><circle cx="5" cy="5" r="5" fill="red"></circle><svg height="20" width="20"><circle cx="10" cy="10" r="10" fill="red"></circle></svg></svg></div>`

The new svg is added as a child element of the old svg, rather than replacing it.

### What browsers are you seeing the problem on? (if applicable)

Chrome

**Comment by FabioRosado** [comment]
Hello @cdelker  thank you for raising this issue with you! @marimeireles since you implemented the display API, do you think what could be happening? 🤔

**Comment by madhur-tandon** [comment]
Pushing a fix for this in a while
