### ISSUE TITLE
NameError: name 'py' is not defined

### ISSUE THREAD

**Issue by KingKrex69** [pyscript/pyscript#1124]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I tried rendering a py script

### What browsers are you seeing the problem on? (if applicable)

Chrome

### Console info

```shell
logger.ts:39 [pyexec] Python exception:
Traceback (most recent call last):
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 435, in eval_code
    .run(globals, locals)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 304, in run
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 1, in <module>
NameError: name 'py' is not defined
```

**Comment by FabioRosado** [comment]
hello @KingKrex69  thank you for raising this issue with us. Can you please share your code? The console info that you provided doesn't give much clues about what's happening.

Thank you

**Comment by marimeireles** [comment]
Hello, closing this issue as no response.
Unfortunately there's no way to figure out what's the issue without more info to narrow down the issue.
If willing to contribute more info., please open a new one or re-open this one.
Cheers!
