### ISSUE TITLE
Functions defined on javascript are not recognized when triggered by events that were remapped to match pyscript attributes

### ISSUE THREAD

**Issue by marimeireles** [pyscript/pyscript#1130]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

PyScript defined attributes aren't working when calling JS functions.

Easier to understand with an example:

```
<script>
        printing_emoji = () => {
            console.log('🦋')
        }
</script>

<button id="my-button" py-onClick="printing_emoji()">call js defined fun printing_emoji on click</button>
```

Won't call anything, instead it will throw the error:

```
Uncaught PythonError: Traceback (most recent call last):
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 435, in eval_code
    .run(globals, locals)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 304, in run
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 1, in <module>
NameError: name 'printing_emoji' is not defined
```

If I run:

```
<script>
        printing_emoji = () => {
            console.log('🦋')
        }
</script>

<button id="my-button" onclick="printing_emoji()">call js defined fun printing_emoji on click</button>
```

Code works as expected.

This is happening when I call `handler` functions that are being implemented on the JS side and called to handle functions decorators on the Python side... This is just for context as what's the goal I want to achieve with this. Not super relevant since this error is happening in a simpler scenario.

Didn't have the time to investigate it yet, opening the issue here in case someone has a clue on thsi behavior!

**Comment by marimeireles** [comment]
And similarly... If I try to call functions that were defined in the `global` space in the JS side using the custom `py-events` (defined by us) the functions will work, if the events are the native browser events, they won't work.

**Comment by marimeireles** [comment]
After talking to @tedpatrick about this, it seems like the reason why this kind of problem is happening is because the `py-*` events are only instantiated once (once the interpreter is initialized).
These events don't get updated if we remove the `py-*` events from our page, for example. So I'm guessing something related to this lack of interactivity is preventing this kind of behavior.
Wondering if you can chime in more info into this issue, Ted. Do we want to fix this? Is this fixable at all? From our conversation it didn't seem like it was.
Might add a warning to the docs I'm writing here: https://github.com/pyscript/pyscript/pull/1125

**Comment by WebReflection** [comment]
for what I understand, this looks very similar to [this other issue](https://github.com/pyscript/pyscript/issues/1059) and I wonder if we should close it as duplicated.

**Comment by hoodmane** [comment]
Isn't `py-onClick` supposed to indicate Python code? Why would it be able to see a JavaScript function?

**Comment by WebReflection** [comment]
it's `py-onclick` eventually, and only on main, closing this as current state covers this issue.
