### ISSUE TITLE
Latest PyScript REPL not showing results

### ISSUE THREAD

**Issue by radiantone** [pyscript/pyscript#1147]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I was previously using alpha pyscript but when I switched to latest
https://pyscript.net/latest/pyscript.js

Suddenly my REPL component is not printing the output when I press the green run button. The correct output is printed in the browser console but not in my <div>. 

### What browsers are you seeing the problem on? (if applicable)

Chrome

### Console info

```shell
[pyscript/main] Packages to install:  []
logger.ts:39 [pyscript/main] Paths to fetch:  []
logger.ts:39 [pyscript/main] All paths fetched
logger.ts:39 [pyscript/main] Python plugins to fetch:  []
logger.ts:39 [pyscript/main] All plugins fetched
logger.ts:39 [py-script] py-mount: found 0 elements
logger.ts:39 [py-terminal] Registering stdio listener
logger.ts:39 [pyscript/main] Executing <py-script> tags...
logger.ts:39 [pyscript/main] Initializing web components...
logger.ts:39 [pyscript/main] Startup complete
logger.ts:39 [py-splashscreen] Closing
logger.ts:39 [pyscript/main] PyScript page fully initialized
stdio.ts:37 1
stdio.ts:37 2
stdio.ts:37 3
stdio.ts:37 4
stdio.ts:37 5
stdio.ts:37 6
stdio.ts:37 7
stdio.ts:37 8
stdio.ts:37 9
```

### Additional Context

![image](https://user-images.githubusercontent.com/25509097/216790974-2ddd01f6-af38-4025-acb5-b4926ee3840e.png)

**Comment by radiantone** [comment]
The output div is empty
`<div class="py-repl-output" id="my-repl-3-3"></div>`

**Comment by chenchen100** [comment]
delete this code in 'repl2.html':
`<div style="margin-right: 3rem;">`
`  <py-repl id="my-repl" auto-generate="true"> </py-repl>`
`  <div id="output" class="p-4"></div>`
`</div>`
to:
`<div>`
`  <py-repl id="my-repl" auto-generate="true"> </py-repl>`
`  <div id="output" class="p-4"></div>`
`</div>`
in line 40;
this is a bug I think;

**Comment by radiantone** [comment]
Hi. Thanks for reply. I replaced the html I had before with what you wrote
`<div>
  <py-repl id="my-repl" auto-generate="true"> </py-repl>
  <div id="output" class="p-4"></div>
</div>`

But it didn't fix the problem.

**Comment by radiantone** [comment]
I'm trying to get it to behave how it did in `alpha` release.

**Comment by chenchen100** [comment]
![image](https://user-images.githubusercontent.com/95748110/216804956-b764efaf-9fed-4e0e-9677-a03259916643.png)
Maybe it's not the style problem. I succeeded this morning, but I tried again at 11:00, and it was not successful, whether it was the local deployment or the network(pyolide);
It is strange that it is working again at two o'clock;
I don't know whether it's the network or the bug

**Comment by FabioRosado** [comment]
Hello @radiantone  thank you for raising this issue with us. Since the alpha version, printing things will appear in a `py-terminal` by default if you don't have a `<py-terminal>` tag, pyscript should add one.  Are you simply adding a `py-repl` tag in your HTML file?

I've tried to run a for loop like you have on https://pyscript.net/examples/repl2.html and the numbers are shown in `py-terminal`.

Just wanted to double check, are you using the CSS file from pyscript?
Since you are using Vue, I wonder if either the py-terminal is hidden or if Vue didn't create the file yet. I've started working on a Vue starter and will give it a try 😄

**Comment by radiantone** [comment]
Let me check on the css again.

**Comment by radiantone** [comment]
Yeah, I pull the css in, but because the css in alpha was modifying some other classes outside of py-repl and distorting my app, I had to import it from my Vue component to make it work, but in latest, it now overrides other classes again.

@import "../css/pyscript.css";

I can try removing this and let pyscript.js import the css?

**Comment by radiantone** [comment]
![image](https://user-images.githubusercontent.com/25509097/216822844-dfcda78d-d57f-4d8d-8d23-62c0ac43e690.png)

**Comment by FabioRosado** [comment]
Do you see the numbers anywhere on the page? 
Do you have the code live somewhere so I could pull it and check?

**Comment by radiantone** [comment]
Only in the console. No where in the page

**Comment by marimeireles** [comment]
Hello, seems like you're using the old API (print)
If you want things to show in the screen you should use display.
old code: `print('abc')`
new equivalent code: `display('abc')`

**Comment by radiantone** [comment]
> Hello, seems like you're using the old API (print) If you want things to show in the screen you should use display. old code: `print('abc')` new equivalent code: `display('abc')`

I should hope a basic python print command still works as it should. Otherwise, that's a deal breaker.
But I wrote my own REPL terminal going straight to pyodide and it was pretty easy.

**Comment by JeffersGlass** [comment]
> I should hope a basic python print command still works as it should. Otherwise, that's a deal breaker.

If you have the bandwidth - I'd be curious if the branch from [this PR](https://github.com/pyscript/pyscript/pull/1106) works in the way you want it to - it restores REPL's prints to stdout to immediately underneath the REPL by default, in a 'notebook-like' fashion. If you don't have a workflow set up to build PyScript from that branch, let me know and I can build a static copy you can like to for testing.

*(This may be orthogonal to the issue - per Fabio's comments, this may be a conflict between PyScript's rendering and Vue, which is a little outside my wheelhouse.)*

**Comment by WebReflection** [comment]
our current py-terminal or py-editor is different *and* it should just work. I think we can close this now but if that's not the case, feel free to re-open the issue or file a new one, thank you!
