### ISSUE TITLE
Disable livereload

### ISSUE THREAD

**Issue by loretoparisi** [pyscript/pyscript#115]
I'm loading both `pyscript.css` and `pyscript.js` locally:

```
<link rel="stylesheet" href="/pyscript.css" />
<script defer src="/pyscript.js"></script>
``` 

I get this error in the demo files:

```
enviroment loading... undefined
pyscript.js:2          GET http://localhost:35729/livereload.js?snipver=1 net::ERR_CONNECTION_REFUSED
(anonymous) @ pyscript.js:2
(anonymous) @ pyscript.js:2
pyscript.js:887 creating pyodide runtime
```

Is `livereload.js` necessary? If not, how to disable it?

Thank you.

**Comment by wproteo** [comment]
Adding  
```
<script async="" src="" id="livereloadscript"></script>
```
after 
```
<script defer src="/pyscript.js"></script>
```
does not call `livereload.js` again

**Comment by loretoparisi** [comment]
@wproteo thank it worked:

```html
<link rel="stylesheet" href="../build/pyscript.css" />
<script defer src="../build/pyscript.js"></script>
<script async="" src="" id="livereloadscript"></script>
 ```

I would suggest you to add in this folder [here](https://github.com/pyscript/pyscript/tree/main/pyscriptjs) the `build` folder with the necessary libraries:

```
.
├── pyscript.css
└── pyscript.js
```

It's not trivial, and the zip you provide would *actually* be ready-to-use.

Thank you cannot wait to try more python packages!
