### ISSUE TITLE
User authentication and database connection secrets

### ISSUE THREAD

**Issue by pplonski** [pyscript/pyscript#117]
Is it possible to have user authentication in HTML+`py-script` apps?  Is it possible to keep secrets in the code for a database connection? I understand that all `py-script` code is on the client-side, how such things can be implemented?

**Comment by jlopezscala** [comment]
Not sure, but please DONT.

**Comment by Temepest74** [comment]
> @jlopezscala why? I think this can be handled with some external server and maybe templates.

Cuz it is clientside. If you need a database connection, do it in an old-fashioned way with php or other server-side architecture. A client will be able to see everything which is client-side.
