### ISSUE TITLE
Running the type() function inside the pyscript raises a JsException

### ISSUE THREAD

**Issue by gmjen** [pyscript/pyscript#120]
eg:
```
>>> type([1, 2, 3])

JsException(PythonError: Traceback (most recent call last): File "", line 156, in write File "", line 116, in write File "", line 79, in format_mime File "", line 54, in eval_formatter TypeError: descriptor '__repr__' of 'list' object needs an argument )
```

This appears to occur both when trying running `type()` from the repl and when used inside a `<py-script>` tag

```
<py-script>
type('A')`
</py-script>
```

<img width="859" alt="image" src="https://user-images.githubusercontent.com/104085438/166267860-150afe70-f538-40cc-ae92-f8eedeb46a53.png">

**Comment by mattkram** [comment]
Just for information, this appears to work fine in [pyodide](https://pyodide.org/en/stable/console.html)

![image](https://user-images.githubusercontent.com/11037737/166269050-21346281-924f-418d-bd96-4d9881011c3c.png)
