### ISSUE TITLE
Exceptions raised inside Python plugins are not displayed correctly

### ISSUE THREAD

**Issue by antocuni** [pyscript/pyscript#1215]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

if I write a Python plugin and there is a Python exception inside one of the lifecycle events (e.g. `afterStartup`) or in `connect()`, the traceback is displayed in the console but NOT in the DOM.
This is very confusing because the apparent result is that the code is just not executed.

The following two tests are currently failing, but they should pass:
```python
    def test_python_exception_in_custom_element_connect(self):
        src = textwrap.dedent("""
            from pyscript import Plugin
            from js import console

            plugin = Plugin('py-myplugin')

            @plugin.register_custom_element('py-xxx')
            class Xxx:
                def __init__(self, element):
                    self.element = element

                def connect(self):
                    raise Exception("this is an exception")
            """)
        self.writefile("myplugin.py", src)
        self.pyscript_run(
            """
            <py-config>
                plugins = [
                    "./myplugin.py"
                ]
            </py-config>

            <py-xxx>hello</py-xxx>
            """,
            wait_for_pyscript=False,
        )

        expected_msg = "this is an exception"
        assert self.assert_banner_message(expected_msg)


    def test_python_exception_in_custom_element_events(self):
        src = textwrap.dedent("""
            from pyscript import Plugin
            from js import console

            class MyPlugin(Plugin):
                def afterStartup(self, config):
                    console.log('afterStartup called')
                    raise Exception("This is an exception inside afterStartup")

            plugin = MyPlugin()
            """)
        self.writefile("myplugin.py", src)
        self.pyscript_run(
            """
            <py-config>
                plugins = [
                    "./myplugin.py"
                ]
            </py-config>
            """,
            wait_for_pyscript=False,
        )

        expected_msg = "This is an exception inside afterStartup"
        assert self.assert_banner_message(expected_msg)
```

This happens because we execute the Python code directly by using the pyodide FFI and calling the relevant PyProxy. This is the relevant code for `.connect()`:
https://github.com/pyscript/pyscript/blob/e2c24592907ad5c14f15085461910d3adbe3fa9b/pyscriptjs/src/plugin.ts#L171-L175

And this is for e.g. `afterStartup()`:
https://github.com/pyscript/pyscript/blob/e2c24592907ad5c14f15085461910d3adbe3fa9b/pyscriptjs/src/plugin.ts#L119-L123
Where `p` is a PyProxy for a Python instance, which is ultimately fetched from here:
https://github.com/pyscript/pyscript/blob/e2c24592907ad5c14f15085461910d3adbe3fa9b/pyscriptjs/src/main.ts#L351-L355

The correct solution is to use `pyExec` for all cases in which we execute user-defined code, so that exceptions are correctly handled and displayed.
It's very likely that the problem will be automatically solved during the process of migrating to web workers, because in that case we will no longer be able to call `PyProxy`s directly, but I want to make sure that we don't forget and that we write the tests for it

**Comment by WebReflection** [comment]
do we still want to work on this? 🤔

**Comment by JeffersGlass** [comment]
This is pretty specific to the old plugins architecture... I think if there are still issues with _hooks_ not showing errors correctly it would be a new issue with a new cause. I think this can close as irrelevant now.
