### ISSUE TITLE
WebAudio - how to collaborate?

### ISSUE THREAD

**Issue by styk-tv** [pyscript/pyscript#122]
Hi PyScript, for the record I just want to say: brilliant idea. Should have been started 30 years ago :)

Anyone scratching their heads over WebAudio implementation? Anywhere on the roadmap? Is there a place where we can start these discussions? At least get to know the people and share some ideas and implementations?  Discord? Slack?

**Comment by verhulstm** [comment]
hi,

thanks :) i am very excited to. i have wanted this for a very long time

join us for some tech discussion here https://community.anaconda.cloud/c/tech-topics/pyscript

**Comment by antocuni** [comment]
closing the issue since it seems that the question was answered
