### ISSUE TITLE
Deprecate `py-mount`

### ISSUE THREAD

**Issue by JeffersGlass** [pyscript/pyscript#1220]
We don't really document or make use of the `py-mount` functionality in the codebase - it's a 'convenience' function that finds all the elements on the page with the `py-mount` attribute, and dynamically creates Python objects pointing at those elements, where the object name is the `id` of the HTML element:

https://github.com/pyscript/pyscript/blob/e2c24592907ad5c14f15085461910d3adbe3fa9b/pyscriptjs/src/components/pyscript.ts#L225-L236

Let's deprecate and then remove this.

(This was something the team noticed during the Plugins discussion the morning of Friday Feb 24 at the offsite.)

**Comment by antocuni** [comment]
+1 for deprecating it.
I think it should be easy: in the next release, we show a deprecation warning in case we notice a `py-mount`. In the next next release, we kill it.
PRs are welcome ;)
