### ISSUE TITLE
Make `pyscript.py` into a Python package

### ISSUE THREAD

**Issue by hoodmane** [pyscript/pyscript#1226]
pyscript.py has a bunch of unrelated logic in it, some of which should probably be private. There should be a pyscript package with an `__init__.py` and multiple submodules with related logic. There are several ways to do this, personally I like `tar`ing the package folder and then loading the tar file with `fetch` and `pyodide.unpackArchive`. But you could also use rollup.

**Comment by marimeireles** [comment]
Did you attend to this already @hoodmane?
I've seen a related PR a few days ago.
Cheers.

**Comment by hoodmane** [comment]
I did a little bit of this. The next step is to make adjustments to `rollup.config.js`, which was somewhat untidily formatted. So I got distracted with setting up prettier.
