### ISSUE TITLE
Cannot use Regular Expression in py-script.

### ISSUE THREAD

**Issue by jjqtony** [pyscript/pyscript#1227]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

When I wrote: 
					
 

    
					<h2>Python Code</h2>
					<py-config>
      					packages = ["regex"]
    				</py-config>
					<div>
						<pre>
							<code id="helloworld">
							def hello_world():
								print("Hello, World!")
			
							hello_world()
							</code>
						</pre>
					<button id="click-btn"  py-click="handle_click()">Run</button>
					</div>
					<div id="output"></div>
					<py-script>
					import re
					def handle_click():
						code = Element("helloworld")
						code = code.element.innerText
						
						new_code = re.sub(r"print\((.*)\)", r"display(\1, target='output')", code)
						display(new_code, target="output", append=False)
					</py-script>
 

get the error:  
        File "<unknown>", line 7
    	            new_code = re.sub(r"print<span class="MathJax_Preview" style="color:......

It seems the regular expression 
       """re.sub(r"print\((.*)\)", r"display(\1, target='output')", code)"""
cannot be interpreted correctly.`

get the error:  
        File "<unknown>", line 7
    	            new_code = re.sub(r"print<span class="MathJax_Preview" style="color:......

It seems the regular expression 
       """re.sub(r"print\((.*)\)", r"display(\1, target='output')", code)"""
cannot be interpreted correctly.

### What browsers are you seeing the problem on? (if applicable)

Microsoft Edge

### Console info

```shell
File "<unknown>", line 7
    	new_code = re.sub(r"print<span class="MathJax_Preview" style="color: inherit;"></span><span class="MathJax" id="MathJax-Element-1-Frame" tabindex="0" ......
```

**Comment by JeffersGlass** [comment]
The code you provided worked fine for me, using PyScript version `2022.12.1`:

![image](https://user-images.githubusercontent.com/1931111/221735964-97c55a37-1a79-4f8b-a665-0a0304c98727.png)

From the mention of the MathJax classes, I'm guessing you're using React as a frontend framework, with some MathJax extension? You can see from the error message you provided ("`new_code = re.sub(r"print<span class="MathJax_Preview" style="color:......"`) which doesn't match your Python code that React or that component is mangling your HTML and causing the Python interpreter to fail.

First thing to try is moving your Python code to another file and using the [`src` attribute of the \<py-script\> tag](https://docs.pyscript.net/latest/reference/elements/py-script.html#attributes) to reference it.

**Comment by WebReflection** [comment]
I've [manually tested as React file](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAYTgWwA4IKZigCgEpEBvAKEUQCdsoQql8LLEAeDATwFoBnCKmBigA-ZpRiY4VKNWxjEAE2zBEACwCGYBQBtsAfQjaYEANZEAXPMoQ4SxAF5EAUV1pcBAESrs27XADuUtoKHoRWiDZ2jpHYAHQ-2G54sTBgYNhUACrYAB5QZOHp_ga22A6ysTwgAEb4VB4YAngAOvj4sQBUhM2EHgA01B4KMDwY2uoc-M0AjANQ6lQA5rT2AORwIFAYm6u9AzFhLCzDo-OTRSVKcwvLUPYeG1ub_YjqGBi4CvYAYuraPNhDixWAB6Ti8fiCETMQgAbjIAF8gA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env%2Creact&prettier=false&targets=&version=7.21.3&externalPlugins=&assumptions=%7B%7D) and I couldn't see any issue with the produced outcome.

It looks like [MathJax](https://jsbin.com/?html,output) doesn't mind its business when `\(` escapes are encountered, despite not being Math notation, just plain text in this case.

I suggest you configure that library adding `py-config` and `py-script` tags within the list of tags that should *not* be parsed:
https://docs.mathjax.org/en/latest/options/document.html#the-configuration-block
