### ISSUE TITLE
Add template for PRs

### ISSUE THREAD

**Issue by marimeireles** [pyscript/pyscript#1236]
This discussion seems to be ready to be turned into an actionable issue :)

### Discussed in https://github.com/pyscript/pyscript/discussions/1083

<div type='discussions-op-text'>

<sup>Originally posted by **FabioRosado** December 29, 2022</sup>
As I work on #1060 we will need to make sure that each PR has an entry to the changelog, this made me wonder if perhaps we should include a very basic template for new PRs. Something like:

```
Checklist:

- [ ] All tests pass locally
- [ ] I have updated `docs/changelog.md`
- [ ] I have created documentation for this(if applicable)
```

That way new folks will know what to do as soon as they open a PR.  Thoughts? 🤔 </div>

**Comment by Mr-Sunglasses** [comment]
I tried to solve this issue in #1279.

**Comment by FabioRosado** [comment]
Just merged the PR closing as complete, thank you again for working no this 👍
