### ISSUE TITLE
Upload file to pyscript application

### ISSUE THREAD

**Issue by ckavidas** [pyscript/pyscript#124]
I currently have some applications created in plotly dash, but I saw this project and thought this could be leveraged instead.

This issue is sort of related to #111 :

Would it be possible to create a form and upload a CSV file to a pyscript application? Similar to Dash's [upload](https://dash.plotly.com/dash-core-components/upload) component?

Example Scenario: 

I have a CSV file that I want to read and produce graphs from:

1. Submit an HTML form to upload the CSV file to the pyscript application
2. Pyscript application produces graphs and returns graphs to a div

**Comment by verhulstm** [comment]
hi,

we have a pending PR with some upload demo code

https://github.com/pyscript/pyscript/pull/39

**Comment by verhulstm** [comment]
i can help you create you example?

**Comment by ckavidas** [comment]
Yes I would be interested in that, please let me know what you need from me.

**Comment by verhulstm** [comment]
check out PR 39. its has more css then you might want. you can skip that and read the pyscript tag. is that about what you want?

**Comment by ckavidas** [comment]
I took a chance to read it, it seems fine to me.

**Comment by marimeireles** [comment]
Closing it as dup. please redirect any questions related to the topic to the [documentation issue](#756 ).
If you're facing a different problem or think might have encountered a bug please feel free to open a new issue.
If I misinterpreted your issue and you think it should still be open please reply here and we'll reopen it.
Thank you!
