### ISSUE TITLE
Cannot install pure python wheel packages that depends on numpy

### ISSUE THREAD

**Issue by xrmx** [pyscript/pyscript#1241]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

The following reproducer fails to install geometer that is a pure python wheel that depends on numpy. 

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Repro</title>
    <link rel="stylesheet" href="https://pyscript.net/latest/pyscript.css" />
    <script defer src="https://pyscript.net/latest/pyscript.js"></script>
      <py-config>
      packages = [
        "numpy",
        "geometer",
        ]
      </py-config>
  </head>
  <body>
  </body>
</html>
```

Since everything looks asynchronous could it be geometer gets installed before numpy is installed despite the order in packages? Installing a local geometer wheel seem to work though.

### What browsers are you seeing the problem on? (if applicable)

Firefox

### Console info

```shell
[pyscript/pyodide] PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 548, in install
    await transaction.gather_requirements(requirements)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 305, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 312, in add_requirement
    return await self.add_requirement_inner(Requirement(req))
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 420, in add_requirement_inner
    await self.add_wheel(wheel, req.extras)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 435, in add_wheel
    await self.gather_requirements(wheel.requires(extras))
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 305, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 309, in add_requirement
    return await self.add_requirement_inner(req)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 407, in add_requirement_inner
    wheel = find_wheel(metadata, req)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 275, in find_wheel
    raise ValueError(
ValueError: Can't find a pure Python 3 wheel for 'numpy<1.23,>=1.15'.
See: https://pyodide.org/en/stable/usage/faq.html#micropip-can-t-find-a-pure-python-wheel
You can use `micropip.install(..., keep_going=True)`to get a list of all packages with missing wheels.
logger.ts:39:19
    fn logger.ts:39
    installPackage pyodide.ts:87
    setupVirtualEnv main.ts:192
    afterRuntimeLoad main.ts:147
    loadRuntime main.ts:130
    (Async: EventListener.handleEvent)
    loadRuntime main.ts:129
    _realMain main.ts:89
    main main.ts:68
    pyscript main.ts:289
    <anonymous> pyscript.js:27252

```
```


### Additional Context

_No response_

**Comment by marimeireles** [comment]
Hi @xrmx thanks for opening this one.
Honestly the order doesn't seem to matter for this specific case, for whatever reason pyodide is not being able to fetch `geometer`. I've checked and the pypi distribution also distributes a python wheel.
I've tested with different ways of importing packages and importing different packages work (tested using `pyconfig` and also with `micropip.install`... So, unless it's a problem with our new async system and we have to do something new that I don't understand... This seems like an upstream problem with pyodide, and I'd advise to open an issue there.

Here are some of the things I tried:

```
import asyncio, micropip

async def main():
    await micropip.install('numpy, geometer')

asyncio.ensure_future(main())

#and then

from geometer import *
import numpy as np

# Meet and Join operations
p = Point(2, 4)
q = Point(3, 5)
l = Line(p, q)
m = Line(0, 1, 0)
l.meet(m)
```
Variations of these fail with the same pyodide error "geometer is not a pure python package".

**Comment by marimeireles** [comment]
Before closing it though maybe @hoodmane can take a look and say if we're missing something?

**Comment by hoodmane** [comment]
The problem is the version cap:
```
Can't find a pure Python 3 wheel for 'numpy<1.23,>=1.15'.
```
Pyodide 0.22.1 vendors '1.23.5' which is not <1.23.

**Comment by xrmx** [comment]
@marimeireles thanks for answering. I think this is more of a UX / DX issue for pyscript and not a pyodide issue though. The problem AFAIU is that install is asynchronous and not serialized with the order configured in py-config packages so that geometer warns about not being able to install numpy but numpy is shipped with iodide so a valid version would eventually be available.

@hoodmane last time i checked pyscript latest did not use latest pyodide and the version of numpy shipped was 1.22.4.

**Comment by hoodmane** [comment]
@marimeireles The error I see reads:
```
ValueError: Can't find a pure Python 3 wheel for 'numpy<1.23,>=1.15'.
```
which looks right to me...

**Comment by xrmx** [comment]
> Pyodide v0.20.x had Numpy 1.22.3, Pyodide v0.21.x released in september used Numpy 1.23.x. So Pyscript has been using Pyodide >= 0.21.0 (and hence Numpy 1.23.x) since release [2022.09.1](https://github.com/pyscript/pyscript/releases/tag/2022.09.1).

Here:

```
[pyscript/main] config loaded:
{
  "type": "app",
  "schema_version": 1,
  "runtimes": [
    {
      "src": "https://cdn.jsdelivr.net/pyodide/v0.21.3/full/pyodide.js",
      "name": "pyodide-0.21.3",
      "lang": "python"
    }
  ],
  "packages": [
    "numpy"
  ],
  "fetch": [],
  "plugins": [],
  "pyscript": {
    "version": "2022.12.1",
    "time": "2023-03-06T15:23:48.009Z"
  }
}
```
Downloads the following url:
https://cdn.jsdelivr.net/pyodide/v0.21.3/full/numpy-1.22.4-cp310-cp310-emscripten_3_1_14_wasm32.whl

and if i `print(numpy.__version__)` i get `1.22.4`

**Comment by hoodmane** [comment]
@xrmx my mistake you're correct. I think this is a bug which is still present in tot micropip but I have to investigate further.

**Comment by hoodmane** [comment]
Actually I take it back, I think this is fixed on tot. I made a test wheel with `dependencies = ['numpy<1.24,>=1.15']` and loaded it and it successfully installed numpy. So whatever the problem was, I'm pretty sure it's not around anymore.

**Comment by xrmx** [comment]
@hoodmane what's tot? top of tree?

**Comment by hoodmane** [comment]
Yes apologies for jargon tot is a synonym for the main development branch.

**Comment by xrmx** [comment]
Can confirm that with latest pyscript 2023.03.1.RC1 and an updated geometer with the numpy version upper bound removed everything work. Closing, thanks!

**Comment by hoodmane** [comment]
Thanks for the report @xrmx! I hope that there is indeed no problem, you had me worried a bit... But it's good to know that it is working for you.
