### ISSUE TITLE
How to run examples?  (" ../build/plugins/python/py_tutor.py failed with error 404")

### ISSUE THREAD

**Issue by marimeireles** [pyscript/pyscript#1272]
### Discussed in https://github.com/pyscript/pyscript/discussions/1259

<div type='discussions-op-text'>

<sup>Originally posted by **alewissocal** March  6, 2023</sup>

I am just starting, trying to run the examples locally. I successfully have the local python http.server running. When I open the local url, the browser (MS Edge) displays the example files I copied into a directory (hello_world.html, panel_kmeans.html, pandas.html). Clicking on any of them will partially execute, but then fail with the 404 error above. (See screenshot below)

Googling for "py_tutor.py" does not turn up anything except a few links to this github, so I am stuck. What am I doing wrong?

-alan 

![error](https://user-images.githubusercontent.com/127152950/223277766-f4990bf3-51c1-42d6-b799-dd093c80ac56.jpg)
</div>

**Comment by marimeireles** [comment]
Oh, it seems like
someone changed the html of the examples to contain this py-tutor tag which is a plugin that is not available in build.
But I wonder, now that we released the new version this problem should have gone away?

**Comment by marimeireles** [comment]
And it seems like the pyscript.net examples are being magically generated from pyscript (this repo) examples. 
So I'm guessing changing it here would trigger... Something (?) and update the examples in the website.

**Comment by antocuni** [comment]
yes, they are automagically generated. See https://github.com/pyscript/pyscript/pull/1275 for a more detailed explanation, and thanks for noticing the problem :)

**Comment by FabioRosado** [comment]
Yes examples are fixed :)
