### ISSUE TITLE
Broken CSS for text in errors

### ISSUE THREAD

**Issue by marimeireles** [pyscript/pyscript#1299]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

See the picture:

![Screenshot 2023-03-21 at 14 39 45](https://user-images.githubusercontent.com/17600982/226623818-8ac83b12-9ffb-43fe-89bd-290c6af9f9ab.png)

The box is responsive but the text isn't.
I'm guessing we just have to add the same classes to the text that the box has?

### Console info

```shell
Firefox
```

**Comment by JeffersGlass** [comment]
Is this the same as #1142 or a different thing?

**Comment by WebReflection** [comment]
the *same* got fixed 🥳
