### ISSUE TITLE
The "make tests" command in documentation for "Development Process" seems to be wrong

### ISSUE THREAD

**Issue by aneesh98** [pyscript/pyscript#1328]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

In the documentation for [development process](https://docs.pyscript.net/latest/development/developing.html#development-process), there is last step which says to run tests using `make tests` command.
Screenshot:

![image](https://user-images.githubusercontent.com/37235937/228556990-a00c2615-7728-422b-974a-c91ed818ba8a.png)

However upon running the command gives the result:
`make: Nothing to be done for 'tests'`
Should it be changed to `make test` as there is a target `test` in Makefile which runs all the tests:
https://github.com/pyscript/pyscript/blob/3ae4b3c4deb59887bff6dd5c6f17598d605a41a6/pyscriptjs/Makefile#L88-L92

Thanks

**Comment by JeffersGlass** [comment]
You're right, `make test` is the correct and the docs are wrong. Want to open a (teeny tiny) PR for that? 😄 Happy to do it as well if that's easier.

**Comment by aneesh98** [comment]
Hi @JeffersGlass, I would be very happy to work and open a PR for that :smile:
