### ISSUE TITLE
`%lt` leaking into "view code" examples

### ISSUE THREAD

**Issue by ericdill** [pyscript/pyscript#1341]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

in the [matplotlib example](https://pyscript.net/examples/matplotlib.html) on [pyscript.net](http://pyscript.net/) there’s an &lt that shows up in the code if you click “view code”. makes it not possible to just copy paste that code into [pyscript.com](http://pyscript.com/) and start playing around

![image](https://user-images.githubusercontent.com/6223243/229163068-49e6b991-7349-4b9d-ad16-dd4c2cfe90f8.png)

### What browsers are you seeing the problem on? (if applicable)

Chrome

### Console info

```shell
no errors in console
```

**Comment by WebReflection** [comment]
related: https://github.com/pyscript/pyscript/discussions/1326
