### ISSUE TITLE
Clean Up How Current Pyodide Version is Specified

### ISSUE THREAD

**Issue by JeffersGlass** [pyscript/pyscript#1349]
As @hood commented on #1346, the version number and URL for the version of Pyodide we're using is specified in roughly a dozen places throughout the docs and source at the moment. It would be nice to only specify Pyodide:

- one time in the changelog
- one time in the docs
- one time in environment.yml
- one time in package.json

so that there are only four edits needed to bump the version of Pyodide.

**Comment by jameshiebert** [comment]
I have [a branch](https://github.com/pyscript/pyscript/compare/main...jameshiebert:pyscript:i1349) that starts on this, but am running into a pain of a roadblock.

The [the MyST substitution rules](https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#substitutions-with-jinja2) are not assessed within code blocks, and code blocks contain the vast majority of the usage of the pyodide version number.

Any advice for how to work around this or other ways to inject substitutions aside from `myst_substitutions`?

**Comment by JeffersGlass** [comment]
I haven't tried it out myself, but [sphinx substitution extensions](https://github.com/adamtheturtle/sphinx-substitution-extensions)  looks promising. It's not entirely clear to me whether it with code fences and not just blocks... might be worth a play though.

**Comment by jameshiebert** [comment]
Yeah, that looked promising, though I can't get it to work. Since most of the docs are written in markdown, I suspect that they get bypassed the Sphinx substitution.

**Comment by JeffersGlass** [comment]
Hmmm yeah, it looks like there's an [open PR from a couple years ago](https://github.com/adamtheturtle/sphinx-substitution-extensions/pull/235) on that extension about extending it to markdown/code fences, that never got finished...

**Comment by hoodmane** [comment]
Looks like a pretty small patch, so maybe we could pick it up and finish it.

**Comment by JeffersGlass** [comment]
The docs have moved elsewhere, and the default version of Pyodide is set by the version of Polyscript we import.  I think the only place where versioning issues may live on is in the examples, and that's being handled/tracked by #1798. Closing as obsolete.

**Comment by adamtheturtle** [comment]
@JeffersGlass The latest release of [`sphinx-substitution-extensions`](https://github.com/adamtheturtle/sphinx-substitution-extensions) now has support for `code-block` with MyST.
