### ISSUE TITLE
Local Modules not being recompiled after changes. 

### ISSUE THREAD

**Issue by SquarishRectangle** [pyscript/pyscript#1350]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

In py-config I am importing a local module that is within a folder. 
```
      [[fetch]]
      files = ["/scripts/utils.py"]
```
I am still making changes to the module quite a bit, but whenever I do, pyscript seems to still use the old version of the module. Deleting pycache folders does not seem to work, but renaming the file and changing all my imports to the new file name works, but it is annoying to have to rename the module every single time a change is made. I could not find a way to force pyscript to recompile / detect changes made to local modules. 

### What browsers are you seeing the problem on? (if applicable)

Chrome

### Additional Context

OS: WSL > Ubuntu 20.04
Backend: FastAPI + Jinja2

**Comment by JeffersGlass** [comment]
Depending on your server setup, it may be necessary to go into your Chrome developer tools and check `Disable Cache` on the Network tab:

![image](https://user-images.githubusercontent.com/1931111/229372686-0011e194-d934-4fe6-a502-6d101f3c998b.png)

**Comment by SquarishRectangle** [comment]
Thank you so much! That seems to have been the issue.
