### ISSUE TITLE
Add docs to repl run code

### ISSUE THREAD

**Issue by marimeireles** [pyscript/pyscript#1352]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

Related https://github.com/pyscript/pyscript/pull/1292
@chenchen100 lmk if you're willing to do this, if you're busy, I can take this one.
Cheers and thanks!

**Comment by chenchen100** [comment]
@marimeireles Should I add docs to this:main/docs/reference/elements/py-repl.md? and open a new PR?

**Comment by marimeireles** [comment]
Yes please @chenchen100, if you're up for it!
I wanted to merge the other PR so we don't risk getting merging issues bc it was my mistake not to merge it earlier, sorry for that!

**Comment by chenchen100** [comment]
@marimeireles It's okay, it's just a small mistake, actually I forgot it too, until you @me.😂

**Comment by Anash3** [comment]
if this issue is solved can you close it
