### ISSUE TITLE
Support WebWorkers in PyScript

### ISSUE THREAD

**Issue by tedpatrick** [pyscript/pyscript#1355]
PyScript will support code execution in WebWorkers in order to make async and parallel execution better and more pythonic

**EDIT**

PR #1333 is on its way to be merged: it adds basic support for web workers. After it, I opened a number of sub issues to track individual features which are still missing, in some order of priority.

*Release blockers*
- #1476
- #1379
- #1380
- #1381

*Would be nice to have*
- #1382
- #1383

*Further refinements*
- #1384
- #1378
- #1312

**Comment by WebReflection** [comment]
we're good :partying_face:
