### ISSUE TITLE
Bokeh examples are broken with --dev because of CORS issues

### ISSUE THREAD

**Issue by antocuni** [pyscript/pyscript#1365]
Since the merge of #1258 , we have 4 examples (and the related tests in `test_zz_examples.py`) which are broken when we use `--dev` or `--no-fake-server`:
- test_bokeh
- test_panel_deckgl
- test_panel_kmeans
- test_panel_stream

This is a [test run](https://github.com/pyscript/pyscript/pull/1363/checks?check_run_id=12514717064) which shows the failures.

The problem is that now the dev server sets the following headers, but the bokeh CDN doesn't serve the files with the corresponding ones:
https://github.com/pyscript/pyscript/blob/088a26491088de1e59b33d31fe76b177c989ffde/pyscriptjs/tests/integration/conftest.py#L149-L151

The upstream bokeh issue is this: https://github.com/bokeh/bokeh/issues/13053

Currently on `main` the tests pass by default because our playwright-based fake server doesn't set those headers, but PR #1333 enables them, so this will become a bigger problem as soon as we want to merge it:
https://github.com/pyscript/pyscript/blob/8246bf73fbfa2ffe2f6cabab0a86be3e40224b1a/pyscriptjs/tests/integration/support.py#L790-L795

**Comment by hoodmane** [comment]
I think this can be closed, since the upstream issue was resolved.
