### ISSUE TITLE
[Worker support] Improve the build system

### ISSUE THREAD

**Issue by antocuni** [pyscript/pyscript#1378]
This is a follow-up of #1333 (once it's merged).

Currently, we build two targets,  `pyscript.js` and `interpreter_worker.js`:
https://github.com/pyscript/pyscript/blob/ef0e838ec0009da508e8b797cee3eb939241e34a/pyscriptjs/esbuild.mjs#L54-L69

I *think* that because of the way we build them, a lot of code is duplicated, so the browser needs to download/execute it twice. For example `RemoteInterpreter` is included in both builds.

I have no idea what is the proper solution using web technologies. Maybe we could have three modules, `main`, `shared` and `worker`, and import `shared` in both?

**Comment by hoodmane** [comment]
> import shared in both?

This is detrimental to load time in the main thread case...

**Comment by WebReflection** [comment]
Current core has no detrimental load time and it just works. This issue can be closed.
