### ISSUE TITLE
[Worker support] Fix plugins

### ISSUE THREAD

**Issue by antocuni** [pyscript/pyscript#1382]
This is a follow-up of #1333 (once it's merged).

Plugins are completely broken. `test_plugins.py` contains 6 skipped tests, for example:
https://github.com/pyscript/pyscript/blob/ef0e838ec0009da508e8b797cee3eb939241e34a/pyscriptjs/tests/integration/test_plugins.py#L196-L199

Complete list:
```
197:    @skip_worker("FIXME: relative paths")
198-    @prepare_test("py-upper", CE_PLUGIN_CODE, tagname="py-up", html="Hello World")
--
213:    @skip_worker("FIXME: relative paths")
214-    @prepare_test("hooks_logger", HOOKS_PLUGIN_CODE, template=HTML_TEMPLATE_NO_TAG)
--
246:    @skip_worker("FIXME: relative paths")
247-    @prepare_test(
--
269:    @skip_worker("FIXME: relative paths")
270-    @prepare_test(
--
294:    @skip_worker("FIXME: relative paths")
295-    @prepare_test("no_plugin", NO_PLUGIN_CODE)
--
309:    @skip_worker("FIXME: relative paths")
310-    def test_fetch_python_plugin(self):
```

**Comment by WebReflection** [comment]
We have plugins for both main and workers and the story is a bit different now as it's all about core hooks and main/worker bootstrap but also we have extra integration tests to check everything is fine. Closing as this looks not relevant anymore.
