### ISSUE TITLE
[Worker support] Kill _unwrapped_remote

### ISSUE THREAD

**Issue by antocuni** [pyscript/pyscript#1384]
This is a follow-up of #1333 (once it's merged).

We should kill the last remaining usage of `_unwrapped_remote`, because it works only in the main thread case and cannot work in the worker case.

AFAIK this is the last place where we use it:
https://github.com/pyscript/pyscript/blob/ef0e838ec0009da508e8b797cee3eb939241e34a/pyscriptjs/src/main.ts#L397-L402

Killing it should also make it possible to simplify and cleanup some ugly code such as this:
https://github.com/pyscript/pyscript/blob/ef0e838ec0009da508e8b797cee3eb939241e34a/pyscriptjs/src/main.ts#L220-L227

**Comment by antocuni** [comment]
I investigated a bit what's needed to kill `_unwrapped_remote`. I tried to apply to patch and run `test_plugins.py`:

```diff
diff --git a/pyscriptjs/src/main.ts b/pyscriptjs/src/main.ts
index 86eaf9e..e3e8a7f 100644
--- a/pyscriptjs/src/main.ts
+++ b/pyscriptjs/src/main.ts
@@ -415,7 +415,8 @@ export class PyScriptApp {
         //       interpreter API level and allow each one to implement it in its own way
 
         // eventually replace with interpreter.pyimport(modulename);
-        const module = interpreter._unwrapped_remote.pyimport(modulename);
+        //const module = interpreter._unwrapped_remote.pyimport(modulename);
+        const module = await interpreter._remote.pyimport(modulename);
         if (typeof (await module.plugin) !== 'undefined') {
             const py_plugin = module.plugin as PythonPlugin;
             py_plugin.init(this);
```

With `-m main`, they all pass apart these two:
```
test_pyscript_exec_hooks[main-chromium] FAILED
test_pyrepl_exec_hooks[main-chromium] FAILED
```

This is the traceback which I see in the console:
![image](https://github.com/pyscript/pyscript/assets/344507/a776111c-d367-4ccb-9834-1a55ddad3844)

The traceback is very obscure and I cannot even understand in which part of *our* code originates from. It seems an internal synclink problem, but I'm not really sure. @hoodmane do you have a clue?

**Comment by hoodmane** [comment]
Yes. It comes from Pyodide's callKwargs. The last argument is supposed to be an argument but instead it's a synclink proxy. I think the easiest fix is to make an extra transfer handler for kwargs objects. Probably add a symbol to mark an object as a kwargs.
