### ISSUE TITLE
Improve py-config parameter Validation

### ISSUE THREAD

**Issue by JeffersGlass** [pyscript/pyscript#1387]
#1323 added a couple of new general-purpose functions for validating user parameters from py-config (`validateConfigParameter`, `validateConfigParameterFromArray`). That PR only used those functions to improve the handling of parameters for the py-terminal plugin, but those functions could and should be used to improve the handling of parameters for the other internal plugins as well.

**Comment by madhur-tandon** [comment]
@JeffersGlass IIRC, we cannot validate nested properties, right? so for eg: while doing `options.config[options.name]`, what if `options.name` corresponds to nested keys i.e. we need to do `config.a.b.c`.

I guess this is not supported in the validation stuff you added right?

**Comment by JeffersGlass** [comment]
@madhur-tandon  Correct, currently the `name` parameter of `validateConfigParameter` and `validateConfigParamterFromArray`  must be the value of a top-level key in the config that presents a non-table value, i.e. string, number, or boolean. No reason it couldn't be made even more generic though.

**Comment by JeffersGlass** [comment]
This infrastructure around validating py-config values has been blown away by PyScript Next (not a bad thing)! Closing this as no longer relevant.
