### ISSUE TITLE
AttributeError: module 'pyodide_http' has no attribute 'patch'

### ISSUE THREAD

**Issue by manish7017** [pyscript/pyscript#1388]
Source: https://docs.pyscript.net/latest/tutorials/requests.html 
Last code snippet of this page of the Documentation

**Comment by FabioRosado** [comment]
Hello @manish7017  thank you for opening this issue, we already have one open and on our next release the tutorial will be fixed. Here's the right call:

`patch` should be `patch_all`
https://github.com/pyscript/pyscript/blob/main/docs/tutorials/requests.md?plain=1#L75 

Closing as duplicate of https://github.com/pyscript/pyscript/issues/1291

**Comment by manish7017** [comment]
Thank you @FabioRosado for the help.
