### ISSUE TITLE
cant use opencv-python?

### ISSUE THREAD

**Issue by Amith225** [pyscript/pyscript#140]
<py-env>
    - opencv-python
</py-env>

gives error in console, stating cant get pure python wheel:

Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 183, in install
    transaction = await self.gather_requirements(requirements, ctx, keep_going)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 173, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 286, in add_requirement
    raise ValueError(
ValueError: Couldn't find a pure Python 3 wheel for 'opencv-python'. You can use `micropip.install(..., keep_going=True)` to get a list of all packages with missing wheels.

**Comment by Rjtsahu** [comment]
Yeah, seems `opencv-python` package is not supported on `micropip` installer

**Comment by rth** [comment]
It will be supported as soon as the next Pyodide version is released (and pyscript updates to using it) see https://github.com/pyodide/pyodide/discussions/2424 for more details.

**Comment by MeloHenrique** [comment]
Pyodide already has a dev version that uses it, isn't it possible to override the default version Pyscript uses?

**Comment by marimeireles** [comment]
@MeloHenrique I think in this case you'll want to change the version of Pyodide that PyScript is using, right?
This might help: https://github.com/pyscript/pyscript/pull/328
I don't think we'll default the Pyodide version to be the most recent release. I think we'll keep having the stable one as default.

**Comment by ryanking13** [comment]
Recent Pyodide 0.21.0 release includes opencv-python :)

**Comment by marimeireles** [comment]
Cool! Thank you for reporting back @ryanking13.
Guess I'm closing this one then since we updated to this version.
Cheers.

**Comment by DamaniMC** [comment]
> Recent Pyodide 0.21.0 release includes opencv-python :)

I'm, having the same issue on 0.22.1 :(

**Comment by JeffersGlass** [comment]
@DamaniMC Are you having the same issue with it not importing? This works for me in PyScript 2023.03.1 / Pyodide 0.22.1:
```html
<py-config>
    packages = ['opencv-python']
</py-config>
<py-script>
    import cv2
    print(cv2.__version__) # 4.6.0
</py-script>
```
