### ISSUE TITLE
Is any way to import openai?

### ISSUE THREAD

**Issue by wpsoul** [pyscript/pyscript#1416]
### Discussed in https://github.com/pyscript/pyscript/discussions/1415

<div type='discussions-op-text'>

<sup>Originally posted by **wpsoul** April 26, 2023</sup>
I am trying to import openai with

import openai

but ModuleNotFoundError: No module named 'openai'

Tried on local machine and on pyscript.com</div>

**Comment by FabioRosado** [comment]
Hello since you have created a discussion I am closing this issue as duplicate. Will reply in the discussion thanks!
