### ISSUE TITLE
WordPress Implementation Issue  

### ISSUE THREAD

**Issue by x-kx** [pyscript/pyscript#1424]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I'm toying around with ideas for WordPress ideas and ran into a snag. 

I have added: 
    <link rel="stylesheet" href="https://pyscript.net/latest/pyscript.css" />
    <script defer src="https://pyscript.net/latest/pyscript.js"></script>

to the <head> in the header.php

and added the <py-config> for the python libraries to the body. 

I created the page: http://001.rf.gd/ide/ and receive the following error code below:

Traceback (most recent call last):
  File "/home/pyodide/pyscript/__init__.py", line 484, in uses_top_level_await
    return TopLevelAsyncFinder().is_source_top_level_await(source)
  File "/home/pyodide/pyscript/__init__.py", line 466, in is_source_top_level_await
    node = ast.parse(source)
  File "/lib/python3.10/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 4
    if not (form.has_key(“name”) and form.has_key(“age”)):
                         ^
SyntaxError: invalid character '“' (U+201C)

Please leave this as unsolved until the error no longer on   http://001.rf.gd/ide/

**Comment by hoodmane** [comment]
The problem is that you use the wrong quotation marks: you write &#8220;name&#8221;  but you should write "name". In the html 

HTML source:
```html
&#8220;name&#8221; vs "name"
```
Rendered:
&#8220;name&#8221;  vs "name"
