### ISSUE TITLE
Demo cases using Panel not working - blank screen

### ISSUE THREAD

**Issue by jaysonbarr** [pyscript/pyscript#1425]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

None of the Panel-using examples are actually working with clean / new setup.
As the simplest case, look at the "Simple Panel Demo":

Chrome, Windows, single html file:

```
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://pyscript.net/latest/pyscript.css" />
    <script defer src="https://pyscript.net/latest/pyscript.js"></script>
  </head>
  <body>
    <py-config>
        packages = [
          "https://cdn.holoviz.org/panel/0.14.3/dist/wheels/bokeh-2.4.3-py3-none-any.whl",
          "numpy",
          "panel==0.14.1"
        ]
        plugins = [
          "https://pyscript.net/latest/plugins/python/py_tutor.py"
        ]
    </py-config>
    <div id="simple_app" class="bk-root"></div>
    <py-script>
        import panel as pn

        slider = pn.widgets.FloatSlider(start=0, end=10, name='Amplitude')

        def callback(new):
            return f'Amplitude is: {new}'

        pn.Row(slider, pn.bind(callback, slider)).servable(target='simple_app');
    </py-script>
  </body>
</html>
```

Result is a blank, all-white, empty page in chrome. Literally nothing to see or select
You can see pyodide download, Python run, and the spinning wheel while loading, but then just an empty page.

### What browsers are you seeing the problem on? (if applicable)

Chrome

### Console info

```shell
No errors reported in console.

Just this warning is there among all the other log messages:
odide.asm.js:10 WARNING: This plugin is still in a very experimental phase and will likely change and potentially break in the future releases. Use it with caution.
hiwire_call_bound @ pyodide.asm.js:10
```

### Additional Context

Any help would be greatly appreciated!

I am able to use pandas, matplotlib, etc. all just fine.

But when I try to use Panel, I get nothing.

Thanks!

**Comment by FabioRosado** [comment]
Yeah I remember we had to make some changes to the panel example. I've tested your code with the headers that @JeffersGlass  linked and the example worked.

I wonder if there is anything we can do to make panel and bokeh work without the extra script import 🤔

**Comment by jaysonbarr** [comment]
THank you both, that did solve my problem.

FYI on the examples page it doesn't give all the code that's in the repo:
https://pyscript.net/examples/panel.html

In the examples page if you click on "View code" it only shows the
py-config and py-script tags' sections, so I didn't know I needed extra
stuff elsewhere. You may want to consider adding the rest of the needed
code to the examples page.

Thanks for the help!
It works great now!
