### ISSUE TITLE
Avoid accidental multiple initializazion of the same py-script elements

### ISSUE THREAD

**Issue by WebReflection** [pyscript/pyscript#1427]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

As described at the end of the description in https://github.com/pyscript/pyscript/pull/1396, we use `connectedCallback` to initialize/bootstrap our components but this callback can be invoked multiple times during a page life-cycle if any of the components is accidentally moved into another place on the page.

The main issue is that the element itself, in case of the `<py-script>` custom element, might gets populated with previously evaluated python code and, if that result gets re-evaluated, we might end up causing unpredictable issues, as the showed code might even be python code itself, or anything else able to break once evaluated.

### Additional Context

This issue would like to consider one of these approaches to solve the current state:
  * we use a *WeakSet* to flag already initialized nodes, avoiding multiple initialization if these are moved around the DOM
  * we use a `disconnectedCallback` that resets the `innerHTML` with the original content, so that whenever the node is moved it bootstraps again

I don't have any specific preference here and either approaches might lead to less confusion or accidents if some third party library move a node or if the user types a wrong element ID somewhere and so on.

**Comment by hoodmane** [comment]
I think we need to think about why it gets moved (presumably an entire subtree is moved and it came along). The main weirdness of the py-script tag is that each one comes with its own implicit display behavior. I think this should change if the script moves. But it would be nice to try to spec the behavior of py-script in more detail so we could get more righteous answers to questions like "what if it moves".

**Comment by WebReflection** [comment]
It’s really indeed a self-display behavior issue, something the scrip tag version doesn’t have but the script tag is also affected if moved, but in the worst case it just re-run the code (option 2 mentioned in the OP)

**Comment by WebReflection** [comment]
@hoodmane forgot to answer a specific point:

> I think we need to think about why it gets moved

beside the use case you presented, if we want PyScript to be easily integrated with 3rd party frameworks (React, Vue, Angular, Solid) we need also to take into account Virtual DOM manipulation and DOM diffing ... we don't get to control the mounting/unmounting part of any of these frameworks, and we don't get to control the life-cycle of any element that lands on a page. Think about an infinite scrolling timeline of demos, exercises, python snippets, jupyter sessions, we're currently assuming once a custom element (or a script) lands on a page it will stay there forever and/or it won't ever be moved/re-appended elsewhere, and it's a very "90's" assumption as that's not how the modern Web works.

Single Page Applications where sessions come and go at runtime, Remix Routing, incremental SSR, these are all stories that see elements on a page constantly moving, which is why I think the option 2 works well, but option 1 also works very well so that any PyScript element just preserves its state but it never bootstraps more than once.

This whole conversation can be solved with literally 2 lines of code, 1 to assign a `WeakSet` and one to add the current node if not already initialized (OK, 3 lines if we also early return if the weakset already knows the node.

Maybe I can provide already a PR that shows option 1 and use that PR until we discuss if that's the best we can do or the best we want to do in the future?
