### ISSUE TITLE
How to open a file inside <py-script>?

### ISSUE THREAD

**Issue by LakshmanKishore** [pyscript/pyscript#146]
Opening a file with `open(filename)` function throws FileNotFound Error.

```
app/
 - index.html
 - abc.txt
 - app.css
```

Inside the index.html file if we try to open the abc.txt file using ` <py-script> open("abc.txt","r") </py-script>` throws a FileNotFound Error.

**Comment by Rjtsahu** [comment]
You cannot read/open a file from a local disc, as the code is running in the browser and would not have access to the file system, but you can definitely download the given file over the network (using the native fetch function)

**Comment by ckavidas** [comment]
@LakshmanKishore 

That is exactly what he is saying, your py-script code is running in web assembly container which is separate from the files on disk.

You will need to upload/download files depending on your use case, see #111 and #124

**Comment by Shahin-rmz** [comment]
> @LakshmanKishore 
> 
> That is exactly what he is saying, your py-script code is running in web assembly container which is separate from the files on disk.
> 
> You will need to upload/download files depending on your use case, see #111 and #124 


Good to know, new to front end.

**Comment by LakshmanKishore** [comment]
@ckavidas  Thanks for the description.
If the file needs to be opened in a binary mode like `open('model.pkl','rb')` then `open_url(url)` does not provide the option of opening file with binary mode.
`open('model.pkl','rb')` opens a saved ML model that was dumped using pickle module.
Is there a way to open that pickle file within `<py-script></pyscript>`?

**Comment by Rjtsahu** [comment]
@LakshmanKishore you need to load the file from http/fetch 

```python
from js import fetch
response = await fetch(URL)
```
please share the snippet of what you are trying to achieve, so I can tell exactly what you can do.

**Comment by LakshmanKishore** [comment]
I have a KNN ML model that was built with scikit-learn and dumped to iris.pkl file using pickle module.

``` 
<py-script>
import pickle
from pyodide.http import open_url
url = "https://raw.githubusercontent.com/LakshmanKishore/irisClassification/master/iris.pkl"
model = pickle.load(open_url(url))
data = {"sl":Element("sl").value, "sw":Element("sw").value, "pl":Element("pl").value, "pw":Element("pw").value }
def predict(*ags, **kws):
    prediction = model.predict([[float(data["sl"]),float(data["sw"]),float(data["pl"]),float(data["pw"])]])
    classes = ["SETOSA","VERSICOLOR","VIRGINICA"]
    answer = classes[int(prediction)]
    print(answer)
</py-script>
```
I tried the above snippet but it was showing

`
JsException(PythonError: Traceback (most recent call last): File "/lib/python3.10/site-packages/_pyodide/_base.py", line 429, in eval_code .run(globals, locals) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 300, in run coroutine = eval(self.code, globals, locals) File "", line 4, in TypeError: a bytes-like object is required, not 'str' )
`

Since `pickle.load(file.pkl)` needs the file.pkl to be opened in binary mode, whereas open_url opens the file in str format.
Once the pkl file is loaded, I will use `model.predict()` to get the predictions of the new input data.

**Comment by ckavidas** [comment]
@LakshmanKishore 

See this [example](https://github.com/pyscript/pyscript/pull/39/commits/04fbd92ee0ca96bd084a74d4b1ca31c20597718c#diff-3bcc05905cca85183c9533f6e97bc8bb460da8a6e2880769ac25ca661568eeebR178)

**Comment by LakshmanKishore** [comment]
```
import pickle

class StrToBytes:
    def __init__(self, fileobj):
        self.fileobj = fileobj
    def read(self, size):
        return self.fileobj.read(size).encode()
    def readline(self, size=-1):
        return self.fileobj.readline(size).encode()

from pyodide.http import open_url
url = "https://raw.githubusercontent.com/LakshmanKishore/irisClassification/master/iris.pkl"
model = pickle.load(StrToBytes(open_url(url)))
```

I was able to convert the model into bytes format using the above `StrToBytes` class, but showing error when loading the model.

`
JsException(PythonError: Traceback (most recent call last): File "/lib/python3.10/site-packages/_pyodide/_base.py", line 429, in eval_code .run(globals, locals) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 300, in run coroutine = eval(self.code, globals, locals) File "", line 13, in _pickle.UnpicklingError: invalid load key, '\xef'. )
`

I don't know whether this error is due to pkl file or the usage of the pickle inside `<py-script>` tag.

**Comment by Rjtsahu** [comment]
@LakshmanKishore can you verify if it is working in normal mode (python3 standard version), you can try to read the file directly using `open`. 
Let's make sure it's not a pickle file issue.

**Comment by marimeireles** [comment]
Hey @LakshmanKishore, I'm not super knowledgeable with `pickle` stuff but it seems like this is no longer related to pyodide. A quick google search returned stuff like: https://github.com/leftthomas/ESPCN/issues/6.
Can you confirm this or the problem persists?
Thanks!

**Comment by LakshmanKishore** [comment]
Hello @marimeireles 
I updated the pickle file.
I'm still getting the same UnpicklingError.

**Comment by marimeireles** [comment]
Closing it as dup. please redirect any questions related to the topic to the [documentation issue](#756 ).
If you're facing a different problem or think might have encountered a bug please feel free to open a new issue.
If I misinterpreted your issue and you think it should still be open please reply here and we'll reopen it.
Thank you!

**Comment by LakshmanKishore** [comment]
I was able to open the file using 

[[fetch]]
-->url here

inside the pyscript.toml file,
which will fetch the file in the envirnoment, so that it can be loaded in the python code.

**Comment by JeffersGlass** [comment]
Excellent! For those finding their way here, starting in `2023.11.1.RC3` there is also the [files](https://docs.pyscript.net/2023.11.1.RC3/user-guide/configuration/#files) feature of py-config, which has a simpler interface.
