### ISSUE TITLE
All of `test_zz_examples` fails in CI on Main

### ISSUE THREAD

**Issue by JeffersGlass** [pyscript/pyscript#1469]
Sometime between last night and this afternoon (UTC-5), all of the tests in `test_zz_examples` started failing in CI, though they still pass locally.

For a clean exampe, see #1468 - that PR consists of a single comment added to main.ts, and the tests still fail.

All of the tests fail by timeout, with output like:
```
----------------------------- Captured stdout call -----------------------------
[  0.00 page.goto        ] examples/hello_world.html
[  0.01 request          ] 200 - fake_server - https://fake_server/examples/hello_world.html
[  0.04 console.error    ] Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by hoodmane** [comment]
I think they've always failed for me locally.

**Comment by JeffersGlass** [comment]
I suppose it could also be "Commits posted by @JeffersGlass fail in CI"... which would be rude of GitHub but possible?
