### ISSUE TITLE
TypeError: pyodide.runPythonAsync is not a function at PyButton.eval (base.ts:160:36)

### ISSUE THREAD

**Issue by John-Schreiber** [pyscript/pyscript#147]
This works fine on one computer, but not another, both running chrome 101.
```
<py-button id="getscans" label="Load Scans">
    def on_click(evt):
        print('clicked!')
</button>
```

**Comment by Shahin-rmz** [comment]
Maybe chrome version difference.

**Comment by John-Schreiber** [comment]
It works on firefox and edge on the machine where it works in chrome, and doesn't on the machine where it fails in chrome. All installations are full upgraded.

**Comment by Shahin-rmz** [comment]
Any error log something?

**Comment by John-Schreiber** [comment]
```
base.ts:165 TypeError: pyodide.runPythonAsync is not a function
    at PyButton.eval (base.ts:160:36)
```
is in the browser console. I can't find anything else. I'm new to frontend development, so its possible I'm missing something.

**Comment by Shahin-rmz** [comment]
I'm also pytjonist and new to front end, just trying to help others in community. 
But I can't catch anything from this logs.

**Comment by renantescaro** [comment]
Try to initiate with:
<py-button> and finish with </py-button>

Wouldn't that be?

**Comment by John-Schreiber** [comment]
I just tried that, no change. The `</button> was directly from an example.

**Comment by John-Schreiber** [comment]
Firefox gives a more detailed error:
```
TypeError: pyodide.runPythonAsync is not a function
    eval base.ts:160
    connectedCallback pybutton.ts:48
    promise callback*connectedCallback/< pybutton.ts:47
    setTimeout handler*connectedCallback pybutton.ts:46
    app main.ts:16
    <anonymous> pyscript.js:27776
```

**Comment by renantescaro** [comment]
try:
```
<div id="div_id"></div>
def on_click(evt):
        pyscript.write('div_id', 'Your message')
```

**Comment by renantescaro** [comment]
https://renantescaro.github.io/python-pyscript/

here it works.. try in your browser

**Comment by John-Schreiber** [comment]
Your example has the same error with the same line numbers.

**Comment by John-Schreiber** [comment]
I found a way that works:

First, instead of using a py-button, I used a regular button, then added an onclick event handler with the DOM.
```
<button type="button" id="button_id">DoStuff</button>
```
```
button = document.getElementById("button_id")
button.addEventListener("click", DoStuff(args))
```
this caused my function be run with its arguments on script load, instead of onclick. 

I had to wrap my python function in another python function, to create a python function that receives an [object PointerEvent], and calls DoStuff with my desired arguments. a simple button doesn't need to parse the PointerEvent, so I ignore it. 

```
def buttonwrapper(_):
    DoStuff(args)
    pass


button = document.getElementById("loadscans")
button.addEventListener("click", ButtonClickEvent)
```
That gave a different set of pyodide errors, which I was able to resolve with help from the pyodide docs. 
```
Uncaught Error: This borrowed proxy was automatically destroyed at the end of a function call. Try using create_proxy or create_once_callable.
The object was of type "function" and had repr <function DoStuff at 0xdeadbeef>
```
adding create_proxy gives us a working button:
```
from js import Image, XMLHttpRequest, document, console
from pyodide import create_proxy


def buttonwrapper(_):
    DoStuff(args)
    pass


ButtonClickEvent = create_proxy(buttonwrapper)

button = document.getElementById("loadscans")
button.addEventListener("click", buttonwrapper) 
```
I'm sure there is a more idiomatic way to do this, but this works.
