### ISSUE TITLE
Upgrade `pytest` to a Newer Version

### ISSUE THREAD

**Issue by JeffersGlass** [pyscript/pyscript#1478]
#1477 pins `pytest` to version 7.1.2, which was our version for a long time (while we were pinning to just ''7'). As seen in #1468 and #1469, pytest version 7.3.1 breaks all of the tests in `test_zz_examples`. We should figure out why so we can continue to keep up with pytest updates.

[The long discord thread about this issue](https://discord.com/channels/972017612454232116/1108339082825830432) has some assorted discoveries in it as far as what we noticed when things were breaking. The [pytest changelog](https://docs.pytest.org/en/7.3.x/changelog.html) also probably has some clues. I notice that the use of the `py` module was deprecated/de-dependencied in pytest 7.2, which we do make use of to find the ROOT path in support.py... just a thought, though.

**Comment by WebReflection** [comment]
We removed test_zz_examples and we have another issue about pinning more (updated?) dependencies.

I think we should tackle this within this one too: https://github.com/pyscript/pyscript/issues/1479

Closing to narrow down the amount of issues and group those related to each other.
