### ISSUE TITLE
Chore: Pin More Depencies in `environment.yml`

### ISSUE THREAD

**Issue by JeffersGlass** [pyscript/pyscript#1479]
Many of the dependencies in the conda environment files (environment.yml in both `src` and `docs`) are unpinned, or aren't pinned as tightly as they could be. We should tighten those up so we don't have more issues like #1469.

**Comment by WebReflection** [comment]
This is actually causing issues with pre-commit hook so I think we should escalate priority a bit

**Comment by WebReflection** [comment]
I think this was previously fixed, just not closed automatically.
