### ISSUE TITLE
script type="py-script" should keep id intact

### ISSUE THREAD

**Issue by bugzpodder** [pyscript/pyscript#1480]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

`<script type="py-script">`
generates a `<py-script-tag>` but the id attribute gets lost and the default internal unique id is generated (py-internal-n).  I'd like the new tag to keep the original id or with some kind of prefix if possible.

**Comment by WebReflection** [comment]
by "get lost" do you mean the created tag loses it (very weird, it's WeakLy related) or the script tag?

**Comment by bugzpodder** [comment]
Thanks for taking a look!  As you are aware, a new py-script-tag is created after the `script type="py-script"` tag with some attributes transferred such as the `output`, `stderr` attributes, but the id is not one of them.  At the time I was hoping to use the id as a stable reference, but I've since swiched to exec the python code directly and not use py-script tags.  As such it's no longer an issue for me.
