### ISSUE TITLE
js_errors may appear before or after `run_pyscript` completes

### ISSUE THREAD

**Issue by JeffersGlass** [pyscript/pyscript#1488]
Consider these two test runs in CI: [[1]](https://github.com/pyscript/pyscript/actions/runs/4980976639/jobs/8914584534) [[2]](https://github.com/pyscript/pyscript/actions/runs/4981330397/jobs/8915441467). No significant changes occured between the two runs/commits (a comment was added to the makefile). [1] passed and [2] did not. This is bad.

Looking at [2] which failed `test_py_script_src_not_found`: the console.js_error was not logged until after `[pyscript/main] PyScript page fully initialized` was printed. The js_error is expected, and the message matches the one we'd expect for this test (which tries to load a non-existing `src` file, and errors when it's not found), but the error message seems to variable as to whether it appears before or after `Pyscript page fully initialized` is printed. The current setup assumes it always appears _before_, but this is not the case.

This has been observed during tests; it's unclear whether it can happen 'live' in the browser.

We should identify the source of this timing flakiness and fix it. 

Tagging @antocuni, since we had a previous discussion of it in #1347.

**Comment by WebReflection** [comment]
I believe this is no more the case.

Feel free to ping me back if I am mistaken.
