### ISSUE TITLE
Docs 404 Page Not Working

### ISSUE THREAD

**Issue by JeffersGlass** [pyscript/pyscript#1492]
Currently, if you open a URL that doesn't exist on the docs site like https://docs.pyscript.net/a, you get a generic 404 Page Not Found:
![image](https://github.com/pyscript/pyscript/assets/1931111/90eea33c-f11a-44b4-8c4a-622a48e29ca1)
We have [error.md](https://github.com/pyscript/pyscript/blob/932756c7a0a4d219f4c3f6bcc9c1ad5332df667e/docs/error.md) set up as our error page, which does build to `error.html` successfully, so perhaps this is an infrastructure configuration issue? @pww217 is this something that falls in your domain?

**Comment by JeffersGlass** [comment]
Meant to open this in the pyscript.net repo, closing this one.

**Comment by FabioRosado** [comment]
Btw I have a PR that updates the pyscript.net to include a 404 page but it's been waiting for a review for a long time
