### ISSUE TITLE
Initial Tests - Examples Test

### ISSUE THREAD

**Issue by fpliger** [pyscript/pyscript#152]
We need to catch up on the big (embarrassing :P ) testing debt we currently have. I'd propose that, at the very minimum, we add a quick test that runs all the examples that verify that they load without errors. 

This is a meaningful indicator that, at least, major features didn't break when we add changes.

**Comment by marimeireles** [comment]
I wonder if this should be closed? Or maybe we should turn it into a umbrella issues about testing?
I figure it'd be nice to have visual testing. This sounds like a whole universe for the web. In the Jupyter ecosystem we used galata... but the web is a whole other universe. If anyone has opinions on good softwares for this, please feel free to chime in!

**Comment by marimeireles** [comment]
Today we had a discussion on how flimsy our testing system currently is and that's probably a priority to make it better.
Let's discuss it on the next opportunity!

**Comment by marimeireles** [comment]
We already have this, so we're closing in favor to create the umbrella issue #601
