### ISSUE TITLE
Baseline benchmark

### ISSUE THREAD

**Issue by fpliger** [pyscript/pyscript#153]
Follow task up from #152  issue. It'd be extremely helpful to have a baseline benchmark where we capture the following loading times on each example page:

* pyscript.js loading
* Pyodide loading
* Environment loading
* Total initialization (interpreter ready and all scripts ran)
* Total page

**Comment by marimeireles** [comment]
I wonder what's @antocuni's update on this?
Should we close this because of the work he has done?
Or you mean you'd like to have scripts for it @fpliger ?
Sorry, I'm confused.

**Comment by fpliger** [comment]
I think we are in a way better place for this but I think it still stands. The tldr; of it is that would be useful to capture these (or similar) metrics when we run our tests to have a good measure of deltas between releases or even just we merge PRs, so that we can understand how much we are making things faster overtime or early identify PRs that are significant performance regressions...

**Comment by WebReflection** [comment]
I think we should close this for the following reasons:

  * pyodide bootstrap is heavily bandwidth and hardware dependent ... any metric would be "*on my machine*"
  * MicroPython is almost instantly bootstrapped even on Mobile
  * we can't offer metrics for both Desktop and Mobile in a meaningful way
  * we could, using the same hardware and Internet bandwidth connection, provide the difference between pyodide and MicroPython ... but:
    * pyodide can take much longer as soon as some package is required
    * MicroPython could also take some extra time as soon as some package is required, whenever that will be available
    * pyodide will always take way longer than MicroPython to bootstrap by design so it's hard to understand how valuable that benchmark is if not for re-stating "*yeah, MicroPython is really fast at bootstrapping and it weight less*"
  * we don't get to control the size of neither projects but *npm* already provide their bundled size and CDNs (Network Panel) already provide size and time to parse ... so I am not sure, once again, how useful any of these details is, when the real-world usage variety is huge and full of different cases

**Comment by fpliger** [comment]
Agreed. Let's close.
