### ISSUE TITLE
Move PyScript high level language APIS to separate .py

### ISSUE THREAD

**Issue by fpliger** [pyscript/pyscript#154]
That logic is currently buried into TS but it's incredibly painful to edit and change... not to mention test and lint. We initially added it in TS because we had no support for loading separate files and because we were not sure about performance concerns (loading from external files during init) but it doesn't seem to happen and, if so, it'd probably be minimal compared to the interpreter init time. 

Let's move to a .py file and load in init time.

**Comment by MarcSkovMadsen** [comment]
Would also lower a barrier to entry for some contributors.

**Comment by fpliger** [comment]
Closed in #207
