### ISSUE TITLE
Add general App metadata

### ISSUE THREAD

**Issue by fpliger** [pyscript/pyscript#155]
We should add support for general application metadata that users can access and use for their own purposes. For instance, starting to log the running time for each script we run inside PyScript (with pyodide.runPythonAsync) so that we can have clear performance data and can be helpful to users for debugging.  Initial metadata for this task:

* scripts loading time (with id, time, interpreter)
* browser version
* os/platform

What else? :)

**Comment by verhulstm** [comment]
pyodide loading info
pyodide debug msg
pyodide version
lists of file served with pyodide.js

**Comment by marimeireles** [comment]
Doesn't this get into privacy issues though?
When we talk about browser version/platform.

**Comment by marimeireles** [comment]
Is this an issue for pyscript.com?
Is this still relevant @fpliger?

**Comment by fpliger** [comment]
@marimeireles no no, it's related to PyScript. I think it should be spelled differently now, after 9 months. I'll close this issue and open another one that is more relevant...
