### ISSUE TITLE
Simplify how scripts run

### ISSUE THREAD

**Issue by fpliger** [pyscript/pyscript#156]
Right now, we have added complexity when scripts run because we are making a difference between a script is sync or async (and calling pyodide.runPython or pyodide.runPythonAsync accordingly). The logic there is not great and unnecessary since pyodide is single threaded and scripts will not run concurrently anyway (and the differences are not that significant for our use case). 

With this proposal, pyodide.runPythonAsync becomes the default and only method. If we really really need we can add an attribute to allow the user to decide if they want to force running sync.

**Comment by philippjfr** [comment]
Strong +1, I don't think there's any downside here.
