### ISSUE TITLE
@When is mistargetting

### ISSUE THREAD

**Issue by Neon22** [pyscript/pyscript#1562]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I'm trying to replace my javascript side event management (for a dropdown), with python side event management.
The @when mechanism is putting the class on the wrong(child) element from the one I select.

E.g. in Js I had this - works - correctly toggles the additional class in the `#choose-swatch` element
```javascript
   let dropdown = document.getElementById('choose-swatch')
   dropdown.onclick = function() {
      dropdown.classList.toggle("active")
   }
```
in pyside I try to replace that with:
```python
@when("click", selector="#choose-swatch")
def swatch_dropdown(evt):
    """Actvate dropdown on swatch chooser
    """
    evt.target.classList.toggle("active")
    print(evt.target.id)
```
which toggles the child element `#swatch_choice` instead of the indicated `#choose-swatch`

Here is a snapshot of the dom before toggling:
The `::before` appears in the chrome inspection panel. I have added it manually as it appears in the Inspector.
```html
 <div id="choose-swatch" class="dropdown">
   ::before
   <input id="swatch_choice" class="text-box" type="text" placeholder="Select" readonly="">
   <div class="options">
     <div py-click="swatch_drop_show('Abstract')" id="py-internal-1">Abstract</div>
     <div py-click="swatch_drop_show('Layout1')" id="py-internal-2">Layout1</div>
   </div>
</div>
```
Here is a snapshot of the dom for js (working as `active` class is correctly assigned to `#choose-swatch`)
```html
<div id="choose-swatch" class="dropdown active">
   ::before
   <input id="swatch_choice" class="text-box" type="text" placeholder="Select" readonly="">
```
Here is the dom when using the pyside approach, and the click on the dropdown is performed (wrong class toggled)
```html
<div id="choose-swatch" class="dropdown">
   ::before
   <input id="swatch_choice" class="text-box active" type="text" placeholder="Select" readonly="">
```

If it helps to debug, the code is here: (but its not a concise example, its an entire project)
- https://d5127013-0d63-43cd-9926-95380d21cf67.pyscriptapps.com/dab7c27f-882a-4e8d-b88d-adf7ef49fa35/latest/
  - relevant lines are 327 in main.py and 103 in index.html
  - currently js is active and working.
  - swap commented code to see non-working pyside effect.

**Comment by JeffersGlass** [comment]
I believe `@when` is working correctly - there is an error in your use of the event parameter in the event handler.

`evt.target` is a reference to the DOM element that *originally triggered* the event - in your case, if the click registers on the `<input id="swatch_choice">`,that's what `evt.target` will refer to. It doesn't necessarily relate to anything that was specified in the original `selector` parameter.

If you want identical behavior to your JS example, you'll want to use `getElementById()` in your Python code as well:

```py
import js

@when("click", selector="#choose-swatch")
def swatch_dropdown(evt):
    el = js.document.getElementById("choose-swatch")
    el.classList.toggle("active")
    print(evt.target.id)
```

**Comment by Neon22** [comment]
oh, of course. Thanks Jeff. closing
