### ISSUE TITLE
[next] xworker isn't defined

### ISSUE THREAD

**Issue by ntoll** [pyscript/pyscript#1564]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

[This example app](https://3fd38942-d35c-4bf6-9b8a-37cec059f572.pyscriptapps.com/5015fe03-f3ea-4cbf-915e-e47dfc383164/latest/) demonstrates two problems:

1. In Firefox, I see the error:
```
Error: Unable to use SharedArrayBuffer due insecure environment.
Please read requirements in MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#security_requirements
```
2. In Chrome, I don't see the same problem, but a new one indicating that `xworker` isn't in global scope.
```
Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "worker_submodule.py", line 9, in <module>
NameError: name 'xworker' isn't defined

    at convert_mp_to_js_obj_jsside (micropython.mjs:5123:15)
    at convert_mp_to_js_obj_jsside_with_free (micropython.mjs:5164:17)
    at Object.runPython (micropython.mjs:5013:20)
    at Object.Ke [as run] (f3c1c009-16bd-4c0d-95a8-e1826f5dac6d:2:7485)
    at f3c1c009-16bd-4c0d-95a8-e1826f5dac6d:2:11912
```

Item 2 is cause by a sub-module. Inside the sub-module is:

```
"""
A module that wants to make use of the document object,
no matter if it's in the main thread or a worker.
"""

try:
    from js import document
except ImportError:
    document = xworker.window.document

... etc ...
```

The actual Python script run by the worker, imports this submodule.

I was expecting to see `xworker` in scope in the sub-module.

### What browsers are you seeing the problem on? (if applicable)

Firefox, Chrome

### Additional Context

Link to the example app:

https://3fd38942-d35c-4bf6-9b8a-37cec059f572.pyscriptapps.com/5015fe03-f3ea-4cbf-915e-e47dfc383164/latest/

**Comment by WebReflection** [comment]
you can't run SharedArrayBuffer without the right headers ... you need to fix that first as the error suggests ... alternatively, you should put this script at the root of your demo https://github.com/gzuidhof/coi-serviceworker

I can't work with non coi (*Cross origin Isolation*) enabled examples, there's nothing to do for me here.
