### ISSUE TITLE
Most of the examples on the documentation page seem broken

### ISSUE THREAD

**Issue by pnsvk** [pyscript/pyscript#1577]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

The output of most of the examples on official documentation link have dumps of exceptions: https://pyscript.net/examples/

![90504455-4DB2-42BC-935A-7887EDA40782](https://github.com/pyscript/pyscript/assets/30823233/49d5d8cc-128c-4051-a28f-e7925cd5982b)

![5AB39AAD-18C6-413F-9462-6AE83846AF3E](https://github.com/pyscript/pyscript/assets/30823233/c2820292-ca6f-48fc-b029-ec760e4d735c)

**Comment by shubhashis-k** [comment]
Created a pull request for this [here](https://github.com/pyscript/pyscript/pull/1627)

**Comment by KCommits** [comment]
Its still broken, did these changes get deployed?

**Comment by shubhashis-k** [comment]
I don't think these changes got deployed.
