### ISSUE TITLE
[next] The Fetch config fails when trying to place the loaded files in a subdirectory

### ISSUE THREAD

**Issue by e-nikolov** [pyscript/pyscript#1580]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I think it happens here:

https://github.com/pyscript/pyscript/blob/next/pyscript.core/esm/interpreter/_utils.js#L38C8
```js
export const writeFile = (FS, path, buffer) => {
    const { parentPath, name } = FS.analyzePath(path, true);
    FS.mkdirTree(parentPath);
    return FS.writeFile([parentPath, name].join("/"), new Uint8Array(buffer), {
        canOwn: true,
    });
};
```

The FS.analyzePath() returns an error if the target directory does not exist yet. I think FS.mkdirTree(dirname(path)) should be called first to make sure that the directory exists:

```js
export const writeFile = (FS, path, buffer) => {
    FS.mkdirTree(dirname(path));
    const { parentPath, name } = FS.analyzePath(path, true);
    return FS.writeFile([parentPath, name].join("/"), new Uint8Array(buffer), {
        canOwn: true,
    });
};
```

**Comment by WebReflection** [comment]
tackled in here, https://github.com/pyscript/pyscript/pull/1582 thanks for the report!

**Comment by WebReflection** [comment]
@e-nikolov I think this is fixed now but feel free to re-open if that's not the case, thanks!
