### ISSUE TITLE
I cannot even get the basic "hello world" example to work. Am I missing something obvious or is library broken?

### ISSUE THREAD

**Issue by josh-ashkinaze** [pyscript/pyscript#1598]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I am trying to get the basic "Hello World" example up and running. But when I open the HTML file it does not actually execute the script; the HTML file says: 

```
plugins = [ "https://pyscript.net/latest/plugins/python/py_tutor.py" ]
Hello world!
This is the current date and time, as computed by Python: from datetime import datetime now = datetime.now() display(now.strftime("%m/%d/%Y, %H:%M:%S"))```
```

Here's the basic example I tried to execute

```
 <py-config>
              plugins = [
                "https://pyscript.net/latest/plugins/python/py_tutor.py"
              ]
          </py-config>

          <section class="pyscript">
              Hello world! <br>
              This is the current date and time, as computed by Python:
              <py-script>
                  from datetime import datetime
                  now = datetime.now()
                  display(now.strftime("%m/%d/%Y, %H:%M:%S"))
              </py-script>
          </section>
 ```

### What browsers are you seeing the problem on? (if applicable)

Firefox, Chrome

**Comment by WebReflection** [comment]
@josh-ashkinaze would you please show the whole page? it's not clear how you're bootstrapping pyscript or from where

**Comment by chenchen100** [comment]
pyscript.net whether the domain name was added to Cloudflare and protected, was it identified as a crawler, or was the traffic limit, I saw Cloudflare's webpage that verifies that the visitor is a bot

**Comment by fpliger** [comment]
@josh-ashkinaze  @chenchen100 can you point us to (or paste) a fully reproducible example?  Thank you!
