### ISSUE TITLE
pyscript_base.css includes rules that are overly broad

### ISSUE THREAD

**Issue by freakboy3742** [pyscript/pyscript#1611]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

The `pyscript_base.css` stylesheet contains a number of styles definitions. Most of them are narrow in scope, or include a `py-` prefix which dramatically reduces the likelihood that they will impact on other sites.

However, there are rules for for the `.label`, `.spinner`, `.editor-box` and `.alert-banner` classes, plus site-wide rules for `html`, `button`, `input`, `optgroup`, `select` and `textarea`. 

While these may be useful styles for pages that PyScript itself is rendering, they can easily clash with other site stylesheets.

### What browsers are you seeing the problem on? (if applicable)

Safari

### Console info

None.

### Additional Context

I can see 2 possible solutions; there may be others:

1. Use a `py-` prefix on all Pyscript-provided styles. Rename the `.label` style to `.py-label` etc; and don't provide a style for `html`, only `html.py-html` (or similar).
2. Encourage third party sites to provide their own stylesheets, and *not* include `pyscript.css` in their own rendering. 

(2) seems like the better option personally - however, PyScript injects splash screen content during startup that must be styled, so the style requirements for this content must be clearly documented, or a minimalist stylesheet that is *very* tightly classed must be provided.

**Comment by WebReflection** [comment]
I agree using a prefix is desirable and acceptable, but it would break foreign modules not updating their classes, if ever used in the wild. This is a great hint to consider for *PyScript Next* though, so thanks for filing this issue!
