### ISSUE TITLE
Add PyScript loading log

### ISSUE THREAD

**Issue by fpliger** [pyscript/pyscript#163]
This issue builds on top of #159 and should offer the possibility to display logs of the operations being executed by PyScript. Proposal is that the text is on the bottom of the loading widget itself.

The design of the implementation should be pluggable (broadcasting to subscribers) so that users can also add new subscribers to capture logs or replace the default logs output )

**Comment by marimeireles** [comment]
I guess this can be closed as done, what's your opinion @fpliger ?

**Comment by fpliger** [comment]
Yup. Let's close it!
