### ISSUE TITLE
Angle bracket bug

### ISSUE THREAD

**Issue by Anymo123** [pyscript/pyscript#1630]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

![2023-08-10 124127](https://github.com/pyscript/pyscript/assets/17396854/4aa8b403-9b49-4fd0-8bdc-ace707b514a8)
![2023-08-10 125203](https://github.com/pyscript/pyscript/assets/17396854/f1475785-910c-40e3-8844-30ef811116db)
Hello, I encountered a bug while output，The content in the middle of the angle brackets disappears

Rof8+<Mvs                  ===>           Rof8+
Rof{;<Gy>N7yBhG        ===>           Rof{;N7yBhG

### What browsers are you seeing the problem on? (if applicable)

Chrome

**Comment by Anymo123** [comment]
Hello, I encountered a bug while output，The content in the middle of the angle brackets disappears

Rof8+<Mvs                  ===>           Rof8+
Rof{;<Gy>N7yBhG        ===>           Rof{;N7yBhG

**Comment by Anymo123** [comment]
Hello, I encountered a bug while output，The content in the middle of the angle brackets disappears

Rof8+<Mvs ===> Rof8+
Rof{;<Gy>N7yBhG ===> Rof{;N7yBhG

**Comment by Anymo123** [comment]
interesting，I found that angle brackets are also not displayed in the comments section

**Comment by chenchen100** [comment]
This may be because the angle brackets in this article are interpreted as HTML tags, causing the content to be invisible. Try using the following code or escaping the HTML entity before outputting it

```python
import js
displayElement = js.document.getElementById('targetElement')
displayElement.textContent = "Rof{;<Gy>N7yBhG"
# or displayElement.innerText = "Rof{;<Gy>N7yBhG"
```

**Comment by WebReflection** [comment]
try `<script type="py">` instead of `<py-script>` as the former won't ever be parsed by browsers
