### ISSUE TITLE
Pyscript adds a slash after less than sign

### ISSUE THREAD

**Issue by AashirSiddiqui** [pyscript/pyscript#1637]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

So I have this piece of code.
``nextBtn.innerHTML = '<py-click="on_start()">Continue'``

When this executes, I get a syntax error which reads:
```
  File "<unknown>", line 65
    </py-click="on_start()">
    ^
SyntaxError: invalid syntax (at transfer_handlers.ts:134:9)
```

I do not have a slash in the code, but it seems to be adding one.

### What browsers are you seeing the problem on? (if applicable)

Chrome

### Console info

```shell
File "<unknown>", line 65
    </py-click="on_start()">
    ^
SyntaxError: invalid syntax (at transfer_handlers.ts:134:9)
```

### Additional Context

I'm running pyscript through Flask on localhost, port 5000.

**Comment by WebReflection** [comment]
this code is invalid HTML too, I am not sure what you are trying to do there:

```js
nextBtn.innerHTML = '<py-click="on_start()">Continue'
```

if you forget about this project and just use `document.body.innerHTML = ...` you'll see:

```html
<py-click="on_start()">Continue</py-click="on_start()">
<!--  see that the element name is  the whole py-click="on_start()" -->
```

You cannot define an element as attribute assignment ... any HTML element needs a name and `py-click` is an attribute.

Accordingly, until your intent is clear, and the HTML code makes sense, we can help you out or fix what we need to fix.

**Comment by WebReflection** [comment]
it's not that `innerHTML` didn't work, that's a Web standard primitive, it's that you were naming a tag as an attribute instead of having an element with a name **and** a `py-click` attribute ... glad you solved though!
