### ISSUE TITLE
pyscript.com editor preview doesn't load on iPad Firefox browser

### ISSUE THREAD

**Issue by axiomtutor** [pyscript/pyscript#1638]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

On an iPad using the Firefox browser, when I bring up the PyScript website pyscript.com, and navigate to my project, the preview doesn't load.  It's interesting because, if I pop the preview into a separate tab, then the preview _does_ load.  But when it's in editor mode, with the preview panel to the right, the preview is just blank.  No error messages or any other content.  Saving and running both appear successful.

(Of course this is not the biggest deal in the world because I can shift over to the popout.  And I'm only editing on my iPad because my computer is being repaired, so it's a stopgap.  Also I haven't experimented with other browsers to see if it would work on them.  I did pull up the editor on a Linux computer and the preview works fine there, and after all it's just a "hello world", so I'm sure there's nothing wrong with the code.  Also, probably Pyscript isn't really designed with this kind of use in mind, but if it can be done, hey why not right?)  

### What browsers are you seeing the problem on? (if applicable)

Firefox

**Comment by FabioRosado** [comment]
Hello @axiomtutor  thank you for raising this issue, I have been working on pyscript.com for the last couple of months and will raise this issue with the team. 

I am currently unable to test this with my iPad as I am traveling, but once I am back home I will test it 😄 

As you mentioned, we expect that you should be able to edit your code on all platforms, I have even edited some code on my iPhone using the safari browser, so I would expect that Firefox would work the same. 

As soon as we have any updates on this, I'll update this issue 😄

**Comment by WebReflection** [comment]
Closing as unrelated to this specific GitHub project.
