### ISSUE TITLE
Matplotlib ImportError in Safari

### ISSUE THREAD

**Issue by pranavmahaadev** [pyscript/pyscript#1640]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

Importing matplotlib in Safari fails with an <code>ImportError: dynamic module does not define module export function (PyInit_ft2font)</code>. This issue seems to be specific to Safari. Chrome, Firefox and Microsoft Edge do not produce this error.

This is most likely a pyodide issue but I'm unsure.

Here is the relevant html code:
```html
<head>
<link rel="stylesheet" href="https://pyscript.net/releases/2023.03.1/pyscript.css" />
<script defer src="https://pyscript.net/releases/2023.03.1/pyscript.js"></script>
</head>

<body>
<py-config type = "toml">
  packages = ["matplotlib", "xarray", "numpy", "scikit-image"]

  [[fetch]]
  from = "pydpe_deploy_v3"
  files = ["guido.py", "utils.py", "angle_transformation.py"]
</py-config>

<py-script src = "./pydpe_deploy_v3/main.py">
</py-script>
</body>
```
I've also attached the traceback from the browser console. As indicated on the console, the local file `guido.py` (not attached) attempts to import matplotlib.pyplot and this fails.

Version details:
- PyScript v2023.03.01
- Safari v14.1.2

The latest stable version of PyScript also produces this issue (again, only on Safari). I was able to confirm this by attempting to run the matplotlib example on the PyScript website.

Device/OS: M1 Mac (2020)/ macOS Big Sur

### What browsers are you seeing the problem on? (if applicable)

Safari

### Console info

```shell
Traceback (most recent call last):
  File "/lib/python3.10/_pyodide/_base.py", line 460, in eval_code
    .run(globals, locals)
  File "/lib/python3.10/_pyodide/_base.py", line 306, in run
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 5, in <module>
  File "/home/pyodide/guido.py", line 6, in <module>
    import matplotlib.pyplot as plt
  File "/lib/python3.10/site-packages/matplotlib/__init__.py", line 208, in <module>
    _check_versions()
  File "/lib/python3.10/site-packages/matplotlib/__init__.py", line 193, in _check_versions
    from . import ft2font
ImportError: dynamic module does not define module export function (PyInit_ft2font)
```

**Comment by pranavmahaadev** [comment]
Update: Issue seems to be specific to this version of Safari. Later version work fine

**Comment by WebReflection** [comment]
@pranavmahaadev current version of Safari is 16.5 ... you are 2 major and few minor numbers behind and that lacks a lot of features for WASM or PyScript Next too (SharedArrayBuffer) ... I am not sure there's much we, or pyodide team, cna do about it so I am not sure this should stay open or just be flagged as "won't fix" because we can't support legacy browsers and we don't expect legacy browsers to be around long time neither.

**Comment by pranavmahaadev** [comment]
@WebReflection Thank you for confirming that this is a Safari version issue. It's not very practical to enable support for legacy versions like you pointed out, so I'm closing the issue :)
