### ISSUE TITLE
Issue in js console and pyscript code not executing

### ISSUE THREAD

**Issue by Mikeblackbelt** [pyscript/pyscript#1641]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

Unhandled Promise Rejection: ReferenceError: Can't find variable: Atomics

This happens when I try to run code

and the code doesnt run

### What browsers are you seeing the problem on? (if applicable)

Safari, Other

### Console info

```shell
Unhandled Promise Rejection: ReferenceError: Can't find variable: Atomics
Error: [plugin] Error while calling afterSetup hook of plugin PyTerminalPlugin DOMException {line: 27928, column: 28, sourceURL: "https://pyscript.net/latest/pyscript.js"}
```

### Additional Context

i ran this on replit

**Comment by JeffersGlass** [comment]
Can you post a full copy of your code here, in a code block?

**Comment by Mikeblackbelt** [comment]
> Can you post a full copy of your code here, in a code block?

`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Matchmaking Screen</title>
    <link rel="stylesheet" href="style.css">
   <link rel="stylesheet" href="https://pyscript.net/latest/pyscript.css" />
    <script defer src="https://pyscript.net/latest/pyscript.js"></script>
</head>
<body>
    <div class="matchmaking-container">
        <h1>Matchmaking</h1>
        <p>Searching for opponents... (0/3)</p>
        <div class="loader"></div>
    </div>
  <py-script> 
    try: 
       m = open('openroom.txt','r')
    except:
       f = open('openroom.txt','w')
       f.write('t')
       f.close()
  </py-script>
  <script src="matchmaking.js"></script>
</body>
</html>
`
its just test code rn

**Comment by madhur-tandon** [comment]
Hi, this is using PyScript `classic`. Can you please try using `PyScript Next` instead?

Even the imports have change and should be done the following way:
`<script type="module" src="https://pyscript.net/releases/2023.11.2/core.js"></script>`

More details here: https://jeff.glass/post/whats-new-pyscript-2023-11-1/

**Comment by WebReflection** [comment]
Closing as the current state has different constraints and logic.
