### ISSUE TITLE
[NEXT] Display append argument gets ignored if passed an HTML object

### ISSUE THREAD

**Issue by fpliger** [pyscript/pyscript#1642]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

The `append` attribute of `display` is ignored if an object with the `_repr_html_` method is passed. Example code:

```python
from pyscript import display
from datetime import datetime, timezone
from zoneinfo import ZoneInfo
import time
import pytz

class HTML:
    """
    Wrap a string so that display() can render it as plain HTML
    """

    def __init__(self, html):
        self._html = html

    def _repr_html_(self):
        return self._html

while True:
    utc_dt = datetime.now(timezone.utc) # UTC time
    now = utc_dt.astimezone() # local time
    res = [
        f"UTC {utc_dt}!",
        f"Your Local Time {now}!",
    ]
    for location in ["America/Los_Angeles"]:
        tz = pytz.timezone(location)
        res.append(f"{location} {utc_dt.astimezone(tz)}!")

    content = '\n'.join([f"<div>{x}</div>" for x in res])
    display(content, target="timer", append=False)
    
    time.sleep(1)
```

it always appends instead of replacing the content of `#timer`

**Comment by WebReflection** [comment]
what is `_repr_html_ ` if I might ask? also in your example you pass a string and you don't use `HTML` at all + you explicitly pass `append=False` (which is the default in next IIRC) ... I am a bit confused about your example, mind explaining a bit?

**Comment by fpliger** [comment]
Basically, `display` has been implemented based on some conventions also used by Jupyter Notebooks that help understanding how to render specific objects. Basically, if these objects implement [one of the known mime methods ](https://github.com/pyscript/pyscript/blob/be79f70f664467f0074e44309451e8aba6f84798/pyscriptjs/src/python/pyscript/_mime.py#L8-L20) then `display` use [one of the related mime renderers](https://github.com/pyscript/pyscript/blob/be79f70f664467f0074e44309451e8aba6f84798/pyscriptjs/src/python/pyscript/_mime.py#L47-L56) to render it.

We may change this implementation in time (I think there may be some other promising approaches) but for now it support what I linked above.

**Comment by WebReflection** [comment]
I know how display works, and the current code is a copy/paste of what we had before so I expect what worked before would just work now too ... your example still pass a string, not `HTML(content)` so I am not sure I understand what is the issue here.

**Comment by WebReflection** [comment]
I think this has been fixed. Closing it as done.
