### ISSUE TITLE
Issue in print("Hello World!")

### ISSUE THREAD

**Issue by RaphaelOliveira10r** [pyscript/pyscript#1643]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

does anyone know what is wrong with th
![Captura de tela 2023-08-18 190844](https://github.com/pyscript/pyscript/assets/129516305/0158db0c-496f-487e-ac3f-d6c167cb2b52)
is code to look like the result at the bottom of the screen?

### Additional Context

![Captura de tela 2023-08-18 190857](https://github.com/pyscript/pyscript/assets/129516305/7d022e41-b897-4191-a64a-eaabe7ec30f9)
This is code !

**Comment by FabioRosado** [comment]
Hello, 

from pyscript 2023.5.1 the terminal where you can see print statements is docked to the bottom of the page. You can change this behaviour by:
- setting `docked` to false on your py-config
- setting `terminal` to false on your py-config

For reference [here's an example to change the py terminal](https://docs.pyscript.net/latest/reference/plugins/py-terminal.html#examples).

Just putting it here in case it helps, if you don't want the terminal but just want to display text on the page, you can use the [`display` API](https://docs.pyscript.net/latest/reference/API/display.html), for example:

```
<py-script>
    def display_hello():
        # this works because we give an explicit target
        display('hello', target="helloDiv")
</py-script>
<div id="helloDiv"></div>
<button id="my-button" py-click="display_hello()">Click me</button>
```

**Comment by RaphaelOliveira10r** [comment]
Thank you Brother !
