### ISSUE TITLE
The d3 demo on the web page no longer works

### ISSUE THREAD

**Issue by axiomtutor** [pyscript/pyscript#1647]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

Just a heads-up, when I go to 

https://pyscript.net/examples/d3.html

I get an error message,

```
Traceback (most recent call last):
  File "/home/pyodide/pyscript/_internal.py", line 104, in run_pyscript
    result = eval_code(code, globals=__main__.__dict__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/_pyodide/_base.py", line 468, in eval_code
    .run(globals, locals)
     ^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/_pyodide/_base.py", line 310, in run
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<exec>", line 4, in <module>
AttributeError: d3
```

### What browsers are you seeing the problem on? (if applicable)

Firefox

**Comment by KCommits** [comment]
Also having the issue that this and many of the other interactive bokeh demos are broken. Having broken demos is like screaming "please don't use this, it is not reliable at all"

**Comment by madhur-tandon** [comment]
@axiomtutor @KCommits I am revamping the examples for the new release.
We have some of them here: https://pyscript-dev.com/@examples

More are gonna migrate soon...

**Comment by madhur-tandon** [comment]
Closing since d3 example has been migrated here: https://pyscript.com/@examples/d3-visualization/latest
