### ISSUE TITLE
Defining components loading priority

### ISSUE THREAD

**Issue by fpliger** [pyscript/pyscript#165]
As a user, I'd like to define the order of execution of components (of the same priority tier) to avoid random concurrent loading for components in the same tier (see #164 for the sequencing proposal).

One way to do it could be by providing an attribute that defines the loading priority of each component so that the user can manually tweak execution and avoid errors due to unpredictable loading.

**Comment by marimeireles** [comment]
What about this one?
Did we do enough in this front or should we still keep it open?
@fpliger

**Comment by fpliger** [comment]
We don't support this, even if we did a lot of work to make the order of execution more predictable. That said, it may be better to just close it and re-open it once the whole workers work is done.
