### ISSUE TITLE
py-config packages error

### ISSUE THREAD

**Issue by yyhk123** [pyscript/pyscript#1661]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

Hello,
I am trying to import packags all 4 together: ["Elasticsearch", "numpy", "pandas", "requests"] for react
but I am getting error like below:

<img width="1097" alt="Screenshot 2023-08-30 at 3 15 53 PM" src="https://github.com/pyscript/pyscript/assets/26759686/fd1e809c-a31f-40b4-82e1-676486a1f487">

however,
importing 3 below works, but
["Elasticsearch", "numpy", "pandas"]
[ "numpy", "pandas", "requests"]

importing 3 below gives me same error.
["Elasticsearch", "numpy", "requests"]
["Elasticsearch", "pandas", "requests"]
["Elasticsearch", "requests"]

does anyone know what might be causing this error?
is it because  importing Elasticsearch and requests together is messing up something?
i also tried import 
["Elasticsearch", "numpy", "pandas", "requests", "Pendulum"] but gives me the error but when i removed requests or elasticsearch the error is gone.

how can i resolve this issue?

thank you!

**Comment by JeffersGlass** [comment]
It does look like you have dependency conflicts - you may want to look at using an older version of either the elasticsearch library or requests?

**Comment by WebReflection** [comment]
As the error comes from pyodide and micropip side, I think we can close this as it's purely 3rd party dependencies issue to me. I hope it got solved by this time though.
