### ISSUE TITLE
Panel DeckGL NYC Taxi Demo not working

### ISSUE THREAD

**Issue by echidne** [pyscript/pyscript#1668]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I have error messages when i go to [https://pyscript.net/examples/panel_deckgl.html](https://pyscript.net/examples/panel_deckgl.html)

### What browsers are you seeing the problem on? (if applicable)

Chrome, Microsoft Edge

### Console info

```shell
errors : 
Task exception was never retrieved
stdio.ts:125 future: <Task finished name='Task-37' coro=<write() done, defined at /lib/python3.11/site-packages/panel/io/pyodide.py:129> exception=Error: Model 'panel.models.location.Location' does not exist. This could be due to a widget or a custom model not being registered before first usage.>
stdio.ts:125 Task exception was never retrieved
stdio.ts:125 future: <Task finished name='Task-38' coro=<write() done, defined at /lib/python3.11/site-packages/panel/io/pyodide.py:129> exception=Error: Model 'panel.models.location.Location' does not exist. This could be due to a widget or a custom model not being registered before first usage.>
```

**Comment by madhur-tandon** [comment]
@echidne I am revamping the examples for the new release.
We have some of them here: https://pyscript-dev.com/@examples

Panel examples are next...
