### ISSUE TITLE
Add User Guide and improve documentation

### ISSUE THREAD

**Issue by fpliger** [pyscript/pyscript#167]
Our README currently provides the bare bare minimum information to get onboarded with PyScript (arguably below minimum :). We need a real user guide/user documentation. Hope we can use this issue to capture the major sections of the user guide as well as the qualities that we want to prioritize for when creating it. PRs can come out of this issue or, eventually, we can generate new issues out of this one.

NOTE: The following work can be split in multiple PRs and even smaller issues.

# Principles

Every part of the documentation should keep in mind the vision of the project in mind:  programming for the 99%. So we should check that any addition aligns to the following principles:

* accessibility
* inclusiveness
* simplicity

# Main Sections

* Introduction/Description: what is PyScript, the goals, what PyScript is not, etc..
* Getting started: this should be really simple and short :). Should show hot so include PyScript in a page and how to have a simple `<py-script>` snipped running
* How to use it: this should be the continuation from the "getting started" sections and should show mode details on each component that can be added in PyScript:

**Update: these are solved:**
  * `<py-env>`
  * `<py-script>`
  * `<py-repl>`
  * Visual Components
    * `<py-inputbox>`
    * `<py-box>`
    * `<py-button>`
    * `<py-list>`
    * `<py-title>`
    
**These are still TBD:**
* Advanced:
  * understanding how PyScript works
  * registering your own PyScript components
  * components API
* Best practices: focusing a serious of things to do/account for when working with PyScript to have the optimal performance/experince possible  (i.e: browser versions, etc...)

Ideas very welcome in the comments.

**Comment by jezdez** [comment]
I'd would strongly suggest to follow the [Diátaxis Framework](https://diataxis.fr) in how to structure the docs to guide different levels of experience to the right place. This has been a pattern that was successfully applied to [many different OSS projects](https://diataxis.fr/adoption/) and should be a good starting point to build out.

**Comment by Nitishhh123** [comment]
Hey , I would be happy to work with this issue and creating a proper document for the newbies to understand about Pyscript

**Comment by ricardoprins** [comment]
I can work on this as well.

**Comment by verhulstm** [comment]
yes, my understanding is Sphinx is being considered. you should be seeing more docs in the next few days.  

can you tell me more about what you want to see or create?

**Comment by ricardoprins** [comment]
That depends, actually. If the core doc structure is being implemented in a near future, I guess I can wait before that happens to start contributing to it. 

From what I see right now, the focus should be on having more comprehensive documentation that permits people to have access to info about pyscript. The summary that @fpliger added here is a very good start. Each section could be a separate issue, and this way we would have the ability to elicit more people to work on it.

I could perfectly work on any of these sections from the info already available on the website, as well as from the many examples that have been published out there.

It's just a matter of knowing where to start, whether from an initial doc skeleton or from scratch...

**Comment by jezdez** [comment]
> That depends, actually. If the core doc structure is being implemented in a near future, I guess I can wait before that happens to start contributing to it.
> 
> From what I see right now, the focus should be on having more comprehensive documentation that permits people to have access to info about pyscript. The summary that @fpliger added here is a very good start. Each section could be a separate issue, and this way we would have the ability to elicit more people to work on it.
> 
> I could perfectly work on any of these sections from the info already available on the website, as well as from the many examples that have been published out there.

Let's use this ticket as a tracking ticket for the various sections Fabio outlined above so we don't duplicate work and coordinate in the various sections. Anaconda also has a number of technical writers that would be able to help with the review and keep consistency and structure.

> It's just a matter of knowing where to start, whether from an initial doc skeleton or from scratch...

You're right, we'll get the ball rolling for the doc infrastructure based on Sphinx with MyST (Markdown integration into Sphinx) on Friday (5/5).

**Comment by marimeireles** [comment]
This is outdated as these elements were removed from the code base.
