### ISSUE TITLE
[Next] `async` attribute works on `<script type="py">` but not `<py-script>` tags

### ISSUE THREAD

**Issue by JeffersGlass** [pyscript/pyscript#1675]
## Issue:

Not sure if this is an issue in the documentation or in execution... so I'll describe the symptom as best I can.

Providing the `async` attribute to a `<py-script>` tag does not allow code to run with top level await enabled, but [https://github.com/pyscript/pyscript/tree/next/pyscript.core/docs](https://github.com/pyscript/pyscript/tree/next/pyscript.core/docs) claims it should work:

## Example
```html
<!doctype html>
<html lang="en">
    <head>
        <script type="module" src="../core.js"></script>
    </head>
    <body>
        <py-script>
            import asyncio
            print('foo')
            await asyncio.sleep(1)
            print('bar')
        </py-script>
    </body>
</html>
```

## Results
```py
File "<exec>", line 4
SyntaxError: 'await' outside function
```

## Expected

Code is compiled as a coroutine and runs. This _does_ work for a `<script type="py">` tag. I'm guessing this is the desired behavior and the documentation is just lagging? But wanted to flag it either way.

**Comment by WebReflection** [comment]
The docs say [it should be an attribute](https://github.com/pyscript/pyscript/tree/next/pyscript.core/docs#tag-attributes-api) but your example doesn't have any attribute.

```html
<!doctype html>
<html lang="en">
    <head>
        <script type="module" src="../core.js"></script>
    </head>
    <body>
        <!--      here -->
        <py-script async>
            import asyncio
            print('foo')
            await asyncio.sleep(1)
            print('bar')
        </py-script>
    </body>
</html>
```

**Comment by JeffersGlass** [comment]
Whoops, apologies for the missing attribute in the example. Thanks for catching that and for the fix!
