### ISSUE TITLE
[NEXT] Error not passing through the io.stderr

### ISSUE THREAD

**Issue by fpliger** [pyscript/pyscript#1680]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

The following example generates an error raised during a call to click event handler and doesn't seem to properly dispatch the error to the `error` plugin (error can be seen only on the console and not on the DOM)

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>PyScript Next Plugin Bug?</title>
  <link rel="stylesheet" href="../dist/core.css">
  <script type="module" src="../dist/core.js"></script>
</head>
<body>
  <script type="py">
    from pyscript import display
    from datetime import datetime as dt
    import js
    from pyodide.ffi.wrappers import add_event_listener

    elements = js.document.querySelectorAll("#just-a-button")

    def on_click(event):
      print(f"Hello from Python! {dt.now()}")
      display(f"Hello from Python! {dt.now()}", append=False, target='eresult')

    add_event_listener(elements[0], "click", on_click)
  </script>

  <button id="just-a-button">click and check the console</button>

  <div id="result"></div>
</body>
</html>

```

**Comment by WebReflection** [comment]
It woul dbe great if we actually use PyScript Next for PyScript Next related bugs ... example:

```html

  <script type="py">
    from pyscript import display, document
    from datetime import datetime as dt
    from pyodide.ffi.wrappers import add_event_listener

    element = document.querySelector("#just-a-button")

    def on_click(event):
      print(f"Hello from Python! {dt.now()}")
      display(f"Hello from Python! {dt.now()}", append=False, target='result')

    add_event_listener(element, "click", on_click)
  </script>
```

Above code would work even with a `worker` attribute, your code would break because you still reach `js.document` which should *not* be used in next as `document` is provided by `pyscript`.

That being said, the plugin works as expected and it's tested already, what doesn't work here is the fact there is an error that doesn't passes through the `io.stderr` and that might be a *polyscript* issue instead, I will investigate this, but please don't mind if I'll change this issue title.

**Comment by WebReflection** [comment]
@fpliger this is indeed [a Pyodide bug](https://github.com/pyodide/pyodide/issues/3938#issuecomment-1709848457) to me but luckily enough I have a workaround ... yet I really don't understand what is pyodide `stderr` about at this point.

**Comment by WebReflection** [comment]
pinging @hoodmane for advice but I'll land the workaround regardless at it feels sensible anyway.

**Comment by WebReflection** [comment]
This MR fixes this and various other issues https://github.com/pyscript/pyscript/pull/1682

**Comment by hoodmane** [comment]
I think the Pyodide solution for this is that if errors propagate out of Python we should call `sys.excepthook`. The reason I've never implemented this is that we have to count the number of times we entered Python code to only make the call when the error exits the outermost python. I added `PY_ENTER` and `PY_EXIT` macros that wrap every entry to/exit from Python so we just have to increment/decrement a counter and if it reaches zero as an error is raised call the excepthook. I should probably just do that...

**Comment by WebReflection** [comment]
Closing as fixed by https://github.com/pyscript/pyscript/pull/1682

@hoodmane please read the rest of the discussion too before changing all the things :D https://github.com/pyodide/pyodide/issues/3938#issuecomment-1710045212

**Comment by hoodmane** [comment]
Yeah I did read that one, I'll post the comment over on that thread since it's on the Pyodide issue tracker it's the more appropriate place for this discussion.

**Comment by WebReflection** [comment]
@fpliger @hoodmane FYI I've tested the very same example/use case in *MicroPython* and it does the right thing, errors are passed along the `stderr` hook, whenever provided ... that fulfills "*our*" expectations.

**Comment by hoodmane** [comment]
We don't want to do that by default since a lot of our users like things quiet but there absolutely needs to be a simple way to opt into it.

**Comment by WebReflection** [comment]
> a lot of our users like things quiet

and who doesn't ... but then again, we went DOM BANNER by default :laughing: (joking, not joking, different users-base I suppose)

**Comment by WebReflection** [comment]
for history sake, this is also valid PyScript next code:

```html
  <script type="py">
    from pyscript import display, document
    from datetime import datetime as dt

    element = document.querySelector("#just-a-button")

    def on_click(event):
      print(f"Hello from Python! {dt.now()}")
      display(f"Hello from Python! {dt.now()}", append=False, target='result')

    element.onclick = on_click
  </script>
```

In case we'd like to have "quick and dirty" examples for issues reports
