### ISSUE TITLE
Great! But doesn't work for me

### ISSUE THREAD

**Issue by BruceSherwood** [pyscript/pyscript#171]
I just learned of this project and I'm excited about it. I'm the lead developer of Web VPython (webvpython.org or, equivalently, glowscript.org). You log into the site and can write VPython programs that are saved in the cloud. Click "Run this program" and your Python code is transpiled in the browser to JavaScript using RapydScript-NG, and execution of the JavaScript code is done in the browser, using WebGL 2 to produce the 3D scene. This environment is used by both programming novices and experts. It does have the limitation that you can't import Python modules, but you can run the same VPython programs with installed Python if you need other modules. The name of the VPython module for use with installed Python is vpython (see vpython.org). VPython makes it easy rather than very difficult to write Python programs that generate as a side effect of computations navigable real-time 3D animations. For example, run tinyurl.,com/vporbit, play with the camera controls, then click "View this program" to see how remarkably short it is. As you can see, it would be a Big Win if Web VPython could use your mechanism, thereby 1) being significantly more conformant to genuine Python and 2) making it possible to import Python modules. However, I just downloaded your files and tried running in Chrome the various .hml files in your examples folder, and none of them work properly. For example, double-clicking simple_clock.html makes this garbled display on Windows 10:
- paths: - ./utils.py
start time:
import utils utils.now() from utils import now import asyncio async def foo(): while True: await asyncio.sleep(1) output = now() pyscript.write("outputDiv2", output) out3 = Element("outputDiv3") if output[-1] in ["0", "4", "8"]: out3.write("It's espresso time!") else: out3.clear() pyscript.run_until_complete(foo())

**Comment by verhulstm** [comment]
hi, thanks for reaching out. currently the zip download does not include a pre-built pyscript.js file

you can build from source or change the html examples to point to the publicly hosted js file  

in your zip, you should find html like this (in the examples)

<link rel="stylesheet" href="../build/pyscript.css" />
<script defer src="../build/pyscript.js"></script>

change to

<link rel="stylesheet" href="https://pyscript.net/alpha//pyscript.css" />
<script defer src="https://pyscript.net/alpha//pyscript.js"></script>

**Comment by BruceSherwood** [comment]
Thanks much. I notice that for many (but not all) of the example programs, there is about a 10-second delay between double-clicking the html file and something happening. What is the source of the delay?

**Comment by Nitishhh123** [comment]
Hey can anyone tell me about the mailing list? Or the community where we can ask for help

**Comment by verhulstm** [comment]
the WASM payloads take a fair amount of time to load in the browser. they transfer in real fast when you double-clicking on a file in a local filesystem but then the WASM VM in the browser has to un pack and init the binaries, and setup memory and a virtual filesystem.

**Comment by verhulstm** [comment]
hi, Nitishhh123

you can post issues here on github or join us at 

https://community.anaconda.cloud/c/tech-topics/pyscript

**Comment by BruceSherwood** [comment]
A 10-second delay is pretty unfortunate for my purposes. For example, for a new edition of a physics e-textbook I'm looking forward to being able for the first time to insert Web VPython programs to illustrate issues in 3D, and a 10-second delay would I think be petty awkward. Can you foresee a way around this? Might there eventually be an option to "compile" the program?

**Comment by verhulstm** [comment]
Yes it does take a few seconds to load. Much of the code is already compiled. The interpreter is the c based cpython code compiled into WASM and you can use (and add in your own) python packages with c extensions. Compiling your python with c extensions will make apps run faster but it does not help much with setup and init times.

We do know the loading time is longer then is ideal and we are looking into ways to potentially make major speed ups.

**Comment by marimeireles** [comment]
Hey @BruceSherwood we're working on loading time. @antocuni and @ntoll made some interesting discoveries.
We're currently on a sprint to release pyscript.com but afterwards that should be one of our number one priorities.
I think your original issue is not reproducible anymore so I'm closing this one, but please feel free to open a new one on execution time. Also, if you want to help the team with your personal inputs, it'd be cool too!
Cheers and I hope we reach a point that PyScript is useful for you in the future!
