### ISSUE TITLE
Make it possible to support different version of Pyodide

### ISSUE THREAD

**Issue by fpliger** [pyscript/pyscript#172]
Users should be able to use different versions of Pyodide, either from CDN or locally build.

**Comment by MarcSkovMadsen** [comment]
It would be nice to specify a python version also.

It would be nice to import a minimum python distribution with a fast load time that enables importing pure python packages. To enable fast load times for simple use cases.

**Comment by fpliger** [comment]
@MarcSkovMadsen agree with you. With that said, for now, I don't think there's much PyScript can do until we are able to support other runtimes/languages entirely. THis means that, for now, the problem is upstream and will need to evolve as Pyodide and [CPython on wasm](https://github.com/ethanhs/python-wasm) evolve and build better support for this.

So, for now, I'd consider these 2 things as separate issues. (just to make it easier to make progress will stuck on the other)
