### ISSUE TITLE
Adding style to To-Do List

### ISSUE THREAD

**Issue by NitishKumar06** [pyscript/pyscript#176]
In the code of the To-Do list, It'd be better if we can add a little bit of styling as well so that a user can get properly engaged with what's happening in the code base.

**Comment by antocuni** [comment]
I'm not sure to understand. Are you proposing to enhance `todo.html` with custom styling?

**Comment by NitishKumar06** [comment]
Yes @antocuni  You're right. When I went through the todo.html for first time , it was not a good experience as a user so i thought of enhancing this site with CSS.
