### ISSUE TITLE
[EPIC] Fix all the remaining tests in the main thread

### ISSUE THREAD

**Issue by antocuni** [pyscript/pyscript#1761]
After we merge #1760, we have a number of tests which are skipped when running pyscript on the main thread.
I haven't investigated them in details yet, and I suspect/assume that some of them fail for the same/related reasons.
The goal of this issue is to give a rough explanation, try to group them into categories and serve as a starting point for further discussion, and to decide which ones we want to absolutely fix before the final release, and which ones can wait.

I expect that some of them will be uncontroversial, others will require more discussion, so depending on the case we might want to open separate sub-issues for them.

---
### Missing error banner and/or error message

*Note*: some of these tests explicitly try to locate the `.py-error` banner. It's probably a good idea to rewrite them to use the `self.assert_banner_message()` method.

* if the user specifies a package which doesn't exist, we should show a nice error in the DOM
https://github.com/pyscript/pyscript/blob/abb4598707a65c260f6595a4d42abea63b118f65/pyscript.core/tests/integration/test_01_basic.py#L206-L228

* this is similar to the above, but slightly different: in this case, the package exists but cannot be installed because it doesn't have a "pure python wheel". We should probably also write a relevant page in the docs and add a link to it in the error message
https://github.com/pyscript/pyscript/blob/abb4598707a65c260f6595a4d42abea63b118f65/pyscript.core/tests/integration/test_01_basic.py#L230-L251

* if the page contains two `<py-config>` tags, the 2nd is silently ignored. We should at least show a warning in that case:
https://github.com/pyscript/pyscript/blob/03c09f1c620bce884560fc65667bf7bf87709aad/pyscript.core/tests/integration/test_py_config.py#L106-L130

* if we try to `[[fetch]]` an URL which doesn't exist, we should show a nice error message in the DOM
https://github.com/pyscript/pyscript/blob/03c09f1c620bce884560fc65667bf7bf87709aad/pyscript.core/tests/integration/test_py_config.py#L155-L175

---
### Accessing pyodide from JS API

PyScript classes exposed an API to access the underlying pyodide from JS: we introduced it because some people requested the funcionality, which was needed for some advanced use case. I have a vague remembering that @JeffersGlass was involved with it, so maybe he remembers more.

If I understand correctly, pyscript next offers *another* way of achieving the same result. If so, we should just fix/adapt these two tests to use the new functionality and document the difference:

https://github.com/pyscript/pyscript/blob/03c09f1c620bce884560fc65667bf7bf87709aad/pyscript.core/tests/integration/test_01_basic.py#L296-L310

https://github.com/pyscript/pyscript/blob/03c09f1c620bce884560fc65667bf7bf87709aad/pyscript.core/tests/integration/test_01_basic.py#L312-L335

---
### JS API difference between `<script type="py">` and `<py-script>`:

I think we have already discussed this one, but I don't remember what was the outcome of the discussion :)

https://github.com/pyscript/pyscript/blob/03c09f1c620bce884560fc65667bf7bf87709aad/pyscript.core/tests/integration/test_01_basic.py#L337-L355

This is an entire test file which is completely skipped and seem to be related:
https://github.com/pyscript/pyscript/blob/c6aaacdbf17eb8e6d58f6d6cd8ccb4d511d211f0/pyscript.core/tests/integration/test_interpreter.py#L5-L12

---
### Accessing config

Another thing which we have already discussed: I think that now we have an official way to get the config from python, we should rewrite the tests to use that

https://github.com/pyscript/pyscript/blob/03c09f1c620bce884560fc65667bf7bf87709aad/pyscript.core/tests/integration/test_py_config.py#L34-L49

https://github.com/pyscript/pyscript/blob/03c09f1c620bce884560fc65667bf7bf87709aad/pyscript.core/tests/integration/test_py_config.py#L51-L68

---
### output and stderr attributes

These tests fail because `output` and `stderr` are no longer supported. Do we want to fix it, or we have decided to remove the functionality?

https://github.com/pyscript/pyscript/blob/03c09f1c620bce884560fc65667bf7bf87709aad/pyscript.core/tests/integration/test_script_type.py#L97-L108

https://github.com/pyscript/pyscript/blob/03c09f1c620bce884560fc65667bf7bf87709aad/pyscript.core/tests/integration/test_script_type.py#L110-L124

* this is related to the tests above: it tests that we raise an error if we use a non-existent target for `output`: if we decide to implement `output`, we should fix this test, and move it somewhere else, because it doesn't make sense to have a test for "warnings and banners" which contains a single test:
https://github.com/pyscript/pyscript/blob/c6aaacdbf17eb8e6d58f6d6cd8ccb4d511d211f0/pyscript.core/tests/integration/test_warnings_and_banners.py#L5-L32

---
### shadow root?

I have no idea what the following test is testing. It is skipped because `Element` is gone, but it also seems to test that we attach a shadow root to `<py-script>`?
My gut feeling is that this is no longer valid with pyscript next and we should just kill the test, but I'll let other people who knows more than me to comment :)

https://github.com/pyscript/pyscript/blob/03c09f1c620bce884560fc65667bf7bf87709aad/pyscript.core/tests/integration/test_shadow_root.py#L7-L32

---
### Other functionalities

On top of that, we have some `test_*.py` files which are skipped entirely, because their functionality has not implemented yet in NEXT:

- `test_py_terminal.py`: the consensus seems to be that we surely want py-terminal back before the final release:
https://github.com/pyscript/pyscript/blob/c6aaacdbf17eb8e6d58f6d6cd8ccb4d511d211f0/pyscript.core/tests/integration/test_py_terminal.py#L8-L15

- `test_stdio_handling.py`: this is very likely related to py-terminal, because in order to implement the terminal, we need to understand how we want to handle/redirect the standard streams:
https://github.com/pyscript/pyscript/blob/c6aaacdbf17eb8e6d58f6d6cd8ccb4d511d211f0/pyscript.core/tests/integration/test_stdio_handling.py#L5-L9

- `test_py_repl.py`: if we have py-terminal, we can easily offer a text-based REPL. The equivalent of the old `py-repl` will probably be called `py-notebook`, but I don't know if we want to have it before the final release or not: https://github.com/pyscript/pyscript/blob/c6aaacdbf17eb8e6d58f6d6cd8ccb4d511d211f0/pyscript.core/tests/integration/test_py_repl.py#L7-L13

- `test_splashscreen.py`: we discussed this elsewhere, I think we should have a splashscreen when we use pyodide:
https://github.com/pyscript/pyscript/blob/c6aaacdbf17eb8e6d58f6d6cd8ccb4d511d211f0/pyscript.core/tests/integration/test_splashscreen.py#L6-L10

**Comment by WebReflection** [comment]
I think this was done.
