### ISSUE TITLE
[EPIC] Fix all the remaining worker tests

### ISSUE THREAD

**Issue by antocuni** [pyscript/pyscript#1762]
This is the sister issue of #1761.
We currently have 14 tests marked as `@skip_worker`

The goal of this issue is to give a rough explanation, try to group them into categories and serve as a starting point for further discussion, and to decide which ones we want to absolutely fix before the final release, and which ones can wait.

I expect that some of them will be uncontroversial, others will require more discussion, so depending on the case we might want to open separate sub-issues for them.

---
### Missing error messages

These are all cases in which we display a nice error banner when we run in the main thread, but not when running in a worker:

https://github.com/pyscript/pyscript/blob/c6aaacdbf17eb8e6d58f6d6cd8ccb4d511d211f0/pyscript.core/tests/integration/test_01_basic.py#L87-L111

https://github.com/pyscript/pyscript/blob/c6aaacdbf17eb8e6d58f6d6cd8ccb4d511d211f0/pyscript.core/tests/integration/test_01_basic.py#L281-L294

https://github.com/pyscript/pyscript/blob/c6aaacdbf17eb8e6d58f6d6cd8ccb4d511d211f0/pyscript.core/tests/integration/test_when.py#L152-L178

---
### problems related to `display()`
- when we are inside a worker, `display()` doesn't take into account the `target` attribute of its surrounding tag: https://github.com/pyscript/pyscript/blob/c6aaacdbf17eb8e6d58f6d6cd8ccb4d511d211f0/pyscript.core/tests/integration/test_02_display.py#L75-L93

- these are for a different case: `display(..., target=x)` works fine is `x` points to e.g. a div, but not if it points to a `<script type="py">` tag. Note that this works in the main thread, not in the worker: 
https://github.com/pyscript/pyscript/blob/c6aaacdbf17eb8e6d58f6d6cd8ccb4d511d211f0/pyscript.core/tests/integration/test_02_display.py#L95-L112
https://github.com/pyscript/pyscript/blob/c6aaacdbf17eb8e6d58f6d6cd8ccb4d511d211f0/pyscript.core/tests/integration/test_02_display.py#L114-L136
https://github.com/pyscript/pyscript/blob/c6aaacdbf17eb8e6d58f6d6cd8ccb4d511d211f0/pyscript.core/tests/integration/test_02_display.py#L191-L206

- this is another case of `display(..., target=...)` not working:
https://github.com/pyscript/pyscript/blob/c6aaacdbf17eb8e6d58f6d6cd8ccb4d511d211f0/pyscript.core/tests/integration/test_02_display.py#L441-L464

---
### misc

- matplotlib-pyodide seems to have problems inside workers, we need to investigate:
https://github.com/pyscript/pyscript/blob/c6aaacdbf17eb8e6d58f6d6cd8ccb4d511d211f0/pyscript.core/tests/integration/test_02_display.py#L356-L385

- this is a sub issue, worth its own discussion:
https://github.com/pyscript/pyscript/issues/1763

- `test_escaping_of_angle_brackets` has a very weird behavior:
https://github.com/pyscript/pyscript/issues/1764

**Comment by WebReflection** [comment]
This comes from times we had a different core, so I think this should be closed, as current integration tests have different reasons about the why, while other tests via workers got implemented.
