### ISSUE TITLE
Fix escaping of <py-script>

### ISSUE THREAD

**Issue by antocuni** [pyscript/pyscript#1764]
This is a sub issue of https://github.com/pyscript/pyscript/issues/1762 and it's related to the following test:
https://github.com/pyscript/pyscript/blob/c6aaacdbf17eb8e6d58f6d6cd8ccb4d511d211f0/pyscript.core/tests/integration/test_01_basic.py#L162-L184

Something is very weird when it comes to `<py-script>` parsing. If you try to run this code:

```html
    <py-script>import js; js.console.log("C", 1<2, 1>2)</py-script>
    <py-script>import js; js.console.log("D <div></div>")</py-script>

    <py-script>
        import js
        js.console.log("E", 1<2, 1>2);
        js.console.log("F <div></div>")
    </py-script>
```

With PyScript classic, you get the following output, as expected:

```
C true false
D <div></div>
E true false
F <div></div>
```

With 2023.09.1RC1, something very weird happens: the "C" and "D" line are parsed correctly, but the "E" line causes troubles:
![image](https://github.com/pyscript/pyscript/assets/344507/4d6f9e62-9148-4890-823b-12e7304b0394)

You can see it in action here (and you can also see that by using 2023.05.1 it works):
https://pyscript.com/@antocuni/py-script-escaping/latest

I know that `<py-script>` parsing is fragile and bad things can happen, but if pyscript classic was able to deal with it correctly, then pyscript next should do the same.

For reference, this is the code which was responsible to decode the content inside `<py-script>` tags in classic:
https://github.com/pyscript/pyscript/blob/52bd64c80d92b721fe584d899e3f138ff4a61382/pyscriptjs/src/utils.ts#L9-L12

**Comment by WebReflection** [comment]
this was already fixed and it still works out of this smoke test https://github.com/pyscript/pyscript/blob/main/pyscript.core/test/html-decode.html

but I went ahead and noticed that we have issues *only* if there are repeated shenanigans:

```python
      <py-script>
        # works
        import js
        # js.console.log("E", 1<2, 1>2)
        js.console.log("F <div></div>")
      </py-script>
      <py-script>
        # works
        import js
        js.console.log("E", 1<2, 1>2)
      </py-script>
      <py-script>
        # fail
        import js
        js.console.log("E", 1<2, 1>2)
        # js.console.log("F <div></div>")
      </py-script>
```

So yes, this is a bug but it's a weird one.

**Comment by WebReflection** [comment]
P.S. just to provide some background:

> For reference, this is the code which was responsible to decode the content inside <py-script> tags in classic:

not that was not it, both `escape` and `ltrim` were slow and ugly and most importantly likely not necessary but surely this use case was somehow fixed ... we just need to figure out what is it that makes the conversion bananas now but the underlying code does pretty much the same as it used to be, just out of DOM primitives (less home-made code to maintain).

We need to do that right before reverting current code, imho.
