### ISSUE TITLE
Add `interpreter` in parsed configs

### ISSUE THREAD

**Issue by WebReflection** [pyscript/pyscript#1765]
### Discussed in https://github.com/pyscript/pyscript/discussions/1759

<div type='discussions-op-text'>

<sup>Originally posted by **WebReflection** September 26, 2023</sup>
With *polyscript* each script tag could have its own specific version out of an attribute, but this is not, and likely should never be, the case for *PyScript*, as we all know multiple config and multiple things mean multiple pyodide too + we can't guarantee anymore stuff "*just works*" because our code is developed and tested on specific versions of each interpreter ... **however** ... from a developer perspective, instead of having the `interpreters` array in `py-config` that never actually worked as meant because we inevitably run only one interpreter, I'd rather suggest an `interpreter ` field that would pass through *polyscript* and use whatever explicit version it is ... reasons:

  * it might be handy for testing purpose for both us and users / contributors ... a new version of Pyodide or MicroPython is out and we all would like to see if it breaks our App *before* updating to the latest/greatest (as we also recommend pinning versions of the library)
  * we can use it to eventually debug regressions out of interpreters we use
  * interpreters developers themselves can use fully qualified URLs to point at their local branch for bug fixes and tests

That's a lot of help for everyone to move forward with ease so that the proposal is:

```html
<py-config>
interpreter = "0.23.4"
</py-config>
<mpy-config>
interpreter = "0.1.239.X"
</mpy-config>
```

both options are passed along and we have easy life testing all we want from anywhere we like.

**Comment by ntoll** [comment]
@WebReflection - here's how I want to document this. Can you give it a read and feedback?

#### Interpreter

The `interpreter` option pins the Python interpreter to the version of the
specified value. This is useful of testing purposes (does my code
work on a specific version of Pyodide?), or to ensure the precise combination 
of PyScript version and interpreter version are pinned to known values.

The value of the `interpreter` option should be a valid version number
for the Python interpreter you are configuring, or a fully qualified URL to
a custom version of the interpreter.

The following two examples are equivalent:

```TOML title="Specify the interpreter version in TOML"
interpreter = "0.23.4"
```

```JSON title="Specify the interpreter version in JSON"
{
    "interpreter": "0.23.4"
}
```

**Comment by WebReflection** [comment]
> This is useful of testing purposes

I might show off my bad English all over the place here ... but wouldn't that be:

> This is useful for testing purposes

instead?

about the example, maybe also showing a fully qualified URL with that very same version would help ...

```js
{
    "interpreter": "https://cdn.jsdelivr.net/pyodide/v0.23.4/full/pyodide.mjs"
}
```

**Comment by ntoll** [comment]
Good spots. I'll update them now. :+1:
