### ISSUE TITLE
Is there an option to request REST Api?

### ISSUE THREAD

**Issue by mjgolda** [pyscript/pyscript#177]
I have tried to use simple requests module, but it doesn't work.

**Comment by verhulstm** [comment]
hi, yes you can do network calls. but not with requests 

check this out

https://github.com/pyscript/pyscript/issues/111

**Comment by verhulstm** [comment]
also, take a look at 

https://github.com/pyscript/pyscript/issues/91

**Comment by marimeireles** [comment]
Hey @mjgolda thanks for opening the issue. As @verhulstm said we don't have support for `request` but we do have docs on the workaround.
Please check them here: https://docs.pyscript.net/latest/howtos/http-requests.html
If you get stuck feel free to reach out!
