### ISSUE TITLE
ImportError when importing PyWorker from pyscript 

### ISSUE THREAD

**Issue by leriomaggio** [pyscript/pyscript#1777]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

Importing `PyWorker` from the `pyscript` module ends up in an `ImportError` exception:
```python
from pyscript import PyWorker
```
produces the following traceback (in the browser) - more accurate error info in the console info:
```
Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 499, in eval_code
    .run(globals, locals)
     ^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/_pyodide/_base.py", line 340, in run
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<exec>", line 3, in <module>
ImportError: cannot import name 'PyWorker' from 'pyscript' (/home/pyodide/pyscript/__init__.py)
```

Just FYI: the following

```python
from polyscript import XWorker
```

worked perfectly, instead.

### What browsers are you seeing the problem on? (if applicable)

Chrome

### Console info

```shell
PythonError: Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 468, in eval_code
    .run(globals, locals)
     ^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/_pyodide/_base.py", line 310, in run
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<exec>", line 3, in <module>
ImportError: cannot import name 'PyWorker' from 'pyscript' (/home/pyodide/pyscript/__init__.py)

    at new_error (pyodide.asm.js:9:14992)
    at pyodide.asm.wasm:0x152d67
    at pyodide.asm.wasm:0x152e6c
    at Module._pythonexc2js (pyodide.asm.js:9:656029)
    at Module.callPyObjectKwargs (pyodide.asm.js:9:75733)
    at Module.callPyObject (pyodide.asm.js:9:75942)
    at Function.apply (pyodide.asm.js:9:89846)
    at Object.apply (pyodide.asm.js:9:88624)
    at Object.runPython (pyodide.asm.js:9:123292)
    at Object.Ge [as run] (_python.js:12:28)
    at a.<computed> [as run] (custom.js:110:51)
    at onInterpreterReady (core.js:224:52)
```

### Additional Context

PyScript Release: `2023.09.1`
Tested on both `RC1` and `RC2`

**Comment by WebReflection** [comment]
@antocuni as you refactored out this part is there any reason [we don't export anymore](https://github.com/pyscript/pyscript/blob/main/pyscript.core/src/stdlib/pyscript/__init__.py) both `PyWorker` and `current_target()` from [magic_js.py](https://github.com/pyscript/pyscript/blob/main/pyscript.core/src/stdlib/pyscript/magic_js.py) ???

If it's just an overlook this looks like easy to "fix" (it's not a bug, we just don't export those names).

If there were other rasons, please share, thanks!

**Comment by antocuni** [comment]
> If it's just an overlook this looks like easy to "fix" (it's not a bug, we just don't export those names).

It's just an overlook.
But it also a good indication that we are missing a test

**Comment by WebReflection** [comment]
I don't think anyone tests exports are those intended ... but fair enough, I'll add one.

**Comment by antocuni** [comment]
No I meant that we should have a test which actually *uses* PyWorker: although maybe this should be part of polyscript?

**Comment by WebReflection** [comment]
@antocuni 

> No I meant that we should have a test which actually uses PyWorker: although maybe this should be part of polyscript?

there's no `PyWorker` in *polyscript*, it's our own export to propagate the custom script with ease ... *polyscript* has integration tests for its exports and all work as expected.

Here the issue is that *PyWorker* was not even exported ... once it is, there are already smoke tests around it and it works but also it does really nothing on top of raw *XWorker* so I am not sure we should duplicate tests in here ... still, the issue was different, it was about not exporting it, if you would like to follow up with tests for it, now that it's exported, please go ahead!
