### ISSUE TITLE
How to import Python packages?

### ISSUE THREAD

**Issue by sbonaretti** [pyscript/pyscript#178]
Hi, 

Thanks for this fantastic project! This is so exciting!!!

I have two quick questions.

From this blog: https://engineering.anaconda.com/2022/04/welcome-pyscript.html, I understand that I have to add Python packages in ```<py-env>```, like this:
```html
  <py-env>
- bokeh
- numpy
- paths:
  - /utils.py
  </py-env>
```
Q1: Do I have to specify a path to `utils.py`? Do I have to write it in my code?

I am asking because I tried the Matplotlib example locally (copied/pasted from here: https://github.com/pyscript/pyscript/blob/main/pyscriptjs/examples/matplotlib.html), and I got this: 

<img width="1040" alt="Screen Shot 2022-05-04 at 10 26 49" src="https://user-images.githubusercontent.com/13563701/166646510-85d3fa7b-495d-4bc6-903f-94401f8e7505.png">

In the header there is only:
```html
<py-env>
      - matplotlib
</py-env> 
```
Q2: Is it because there is no `utils.py`? Or is there another reason?

Thanks so much!!!
Serena

**Comment by JeffersGlass** [comment]
The matplotlib example assumes you're using a local copy of PyScript. If you tell the local HTML file to load PyScript from the CDN as follows, it should work:

Replace the line:
`<!--<script defer src="../build/pyscript.js"></script> -->`

With:
`<script defer src="https://pyscript.net/alpha/pyscript.js"></script>`

The `paths: ./utils.py` in the py-env tag is just an example of how you might include a local .py file into your project; it's not necessary for all projects. Check out the [simple_clock](https://github.com/pyscript/pyscript/blob/main/pyscriptjs/examples/simple_clock.html) example, which loads the [utils.py](https://github.com/pyscript/pyscript/blob/main/pyscriptjs/examples/utils.py) project from the /examples  folder.

**Comment by sbonaretti** [comment]
Fantastic! It all works! Thank you so much for the clear explanation!
