### ISSUE TITLE
Do not recycle lastElementChild in display

### ISSUE THREAD

**Issue by WebReflection** [pyscript/pyscript#1780]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

Instead of cleaning up the target container when `append=False` is used, we use the `lastElementChild` assuming that's the `div` we eventually previously created on *empty* containers.

The issues I see with this approach (this is PyScript classic too IIRC):

  * when `<py-script>` is a target, it's already a visual container
  * any element as target, is already a visual container
  * because of previous 2 points, it's never been too clear to me why we even need to create a `div` to append anything, but then all integration tests expect that so there must be a reason - **amend** [probably not](https://github.com/pyscript/pyscript/issues/1780#issuecomment-1742988864)
  * when `<script type="py">` is used, its `target` is already a visual container ... so that previous questions apply
  * in no circumstance, when `append=False`, we should reuse any previous content, as the new content goal is to replace it, whatever it was
  * checking for `lastElementChild` to then branch out logic when append means `element.append(new_content)` is also not super clear or useful, neither with new empty nodes, nor with already populated ones

Accordingly, we should (imho) improve the `display` `append` attribute story, as right now it's rather causing issues instead and weird edge cases, failing expectations.

**Comment by WebReflection** [comment]
I've removed the needs-triage label because we've been discussing this in Discord for a while so that @leriomaggio provided dozen variant of the issue and all of those variants were solved by cleaning up upfront when `append=False` was used.

**Comment by JeffersGlass** [comment]
If i had to guess... I would say that the fact that we're creating a `div` to append things probably *doesn't* have a good reason. The code for `_write` (which underlies `display`) goes back a loooong way. Actually, all the way back to PyScript Alpha!

https://github.com/pyscript/pyscript/blob/5d49c20ade547e8a4e1b9fcc4a6a40eb3dc0effe/pyscriptjs/src/pyscript.py#L111-L129

As such, I think it would be fair to say that `_write` has some bad parts that we should feel free to correct.

**Comment by WebReflection** [comment]
To whom it might concern, the current MR simply takes the easy approach by cleaning up the whole thing before applying any logic.

This *should* guarantee no breaking changes whatsoever, but I do believe the current `display` is full of potential improvements.

To track my thoughts:

  * a target that is a special contained that doesn't allow `div` element in it (`<picture>` or `<video>` to name a few) would break badly
  * it's not clear why `append` for a specific container *target* means `append` to its latest element child
  * if it was for me, the `_write` helper would've been 10LOC

```python
def _write(element, value, append=False):
    html, mime_type = _format_mime(value)
    if html == "\\n":
        return
    if not append:
        element.replaceChildren()
    if mime_type in ("application/javascript", "text/html"):
        script_element = document.createRange().createContextualFragment(html)
        element.append(script_element)
    else:
        element.innerHTML = html
```

that's it.
