### ISSUE TITLE
Developing process link in README is broken

### ISSUE THREAD

**Issue by leriomaggio** [pyscript/pyscript#1782]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

The `developing process` in the **Contributing** section is broken or outdated. 

In more details, this paragraph in README: 
```
Check out the [developing process](https://docs.pyscript.net/latest/development/developing.html) documentation for more information on how to setup your development environment.
```

The link goes `404`

Maybe a section in the doc that is still missing? 
Just reporting for traceability. :)

**Comment by leriomaggio** [comment]
Related: it seems that all instructions in `CONTRIBUTING.md` also refer to the same broken link - so there is no accessible doc to how to contribute.

**Comment by leriomaggio** [comment]
I reckon links should go here instead? https://docs.pyscript.net/2023.09.1.RC2/contributing/

**Comment by JeffersGlass** [comment]
@leriomaggio What is that misplaced link in? I'm not seeing in on `main` at the moment.

**Comment by shubhalgupta** [comment]
Please assign me this issue!

**Comment by shubhalgupta** [comment]
https://docs.pyscript.net/2023.09.1.RC2/contributing/ is this the correct link?

**Comment by shubhalgupta** [comment]
Please assign me this task @JeffersGlass
