### ISSUE TITLE
Restore the development docs

### ISSUE THREAD

**Issue by antocuni** [pyscript/pyscript#1783]
I open this issue so that we don't forget.

The old docs contained some valuable information on how to setup the dev environment and how to run tests.
In particular, there is a nice section which shows some useful options to use with pytest:
https://github.com/pyscript/pyscript/blob/classic/docs/development/developing.md#quick-guide-to-pytest

We need to make sure that this doesn't get lost.
Since the docs are now living in a separate repo, the old `developing.md` should probably be kept in *this* repo and merged with `CONTRIBUTING.md`.

**Comment by leriomaggio** [comment]
Perhaps also related to #1782

**Comment by shubhalgupta** [comment]
@antocuni kindly assign this task to me!

**Comment by WebReflection** [comment]
AFAIK this is meant to replace the previous MarkDown content:
https://pyscript.github.io/docs/2024.1.1/contributing/

closing as it looks like we covered this in the meantime.
