### ISSUE TITLE
`polyscript` relative imports prevent bundling `pyscript`

### ISSUE THREAD

**Issue by JeffersGlass** [pyscript/pyscript#1794]
When trying to bundle @pyscript/core into a new project, I ran into module resolution issues, which I think are caused by PyScript specifying some specific relative import paths in `core.js`. Tagging @WebReflection. 

## To Reproduce:

1. In a new folder, run `npm install esbuild @pyscript/core`
2. In this folder, create a new file called `test.js` with the contents:

```js
//test.js
import { PyWorker } from '@pyscript/core'
```

3. In a terminal, run the bundler: `./node_modules/.bin/esbuild test.js --bundle --outfile=out.js`
4. The observed errors are:
```
✘ [ERROR] Could not resolve "../node_modules/polyscript/esm/index.js"

    node_modules/@pyscript/core/src/core.js:10:7:
      10 │ } from "../node_modules/polyscript/esm/index.js";
         ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "../node_modules/polyscript/esm/script-handler.js"

    node_modules/@pyscript/core/src/core.js:11:28:
      11 │ import { queryTarget } from "../node_modules/polyscript/esm/script-handler.js";
         ╵                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "../node_modules/polyscript/esm/utils.js"

    node_modules/@pyscript/core/src/core.js:16:7:
      16 │ } from "../node_modules/polyscript/esm/utils.js";
         ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "../node_modules/polyscript/esm/worker/hooks.js"

    node_modules/@pyscript/core/src/core.js:17:21:
      17 │ import { Hook } from "../node_modules/polyscript/esm/worker/hooks.js";
         ╵                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "../node_modules/polyscript/esm/fetch-utils.js"

    node_modules/@pyscript/core/src/fetch.js:2:24:
      2 │ import { getText } from "../node_modules/polyscript/esm/fetch-utils.js";
```
(There are more errors if, for example. you create an iife or cjs output, but these resolution errors are the same regardless.)

## Thoughts

Perhaps PyScript is not meant to be re-imported/bundled in this way? It would be helpful for my use case (creating another project built on top of PyScript) if I could import PyWorker at bundle-time, and not dynamically in the browser.

**Comment by e-nikolov** [comment]
I am also getting this issue and as a temporary workaround I am using `yarn patch` to remove the relative imports from pyscript and to change polyscript's package.json to export the `./esm/` directory.

**Comment by WebReflection** [comment]
### Best Practice

Any module that uses PyScript should likely just leave the import un-bundled and exclude it from the final bundle, this would allow multiple projects to use the very same PyScript module and bootstrap without ever interfering with each other.

The only thing to do is to define an `importmap` in the page that always points at the very same PyScript core file so that the module won't be downloaded or bootstrapped more than once ever and it will grant that any file can use it.

There is a discussion about how to create plugins with working code out there in discord, please have a look: https://discord.com/channels/972017612454232116/1159868059025145928/1159924849226022993

**Comment by JeffersGlass** [comment]
Thanks @WebReflection - not bundling PyScript, and linking it in separately using an injected importmap works for my use case. 

I'll open a separate, more specific issue about adding those bundled exports to the exports field.
