### ISSUE TITLE
cleaning up and organising examples

### ISSUE THREAD

**Issue by madhur-tandon** [pyscript/pyscript#1798]
With the upcoming release of PyScript Next, it makes sense to think about the `examples`:

- All (or most examples) use the link: `https://pyscript.net/latest/pyscript.js`

We should consider the following:
- Removing examples from this repository
- Make them sync with what is present on PSDC (PyScript.com)
- Keep them versioned according to releases of PyScript

Further, we should do a sanity check on which of them work right away with PyScript Next and which of them need tweaks. We can also discard some of them if needed.

**Comment by fpliger** [comment]
We've discussed that a few weeks ago and the intention is to move examples to collective and maintain the source there. In addition to that, we should connect that repo to the @examples account we have on pyscript.com so that we can auto-publish when we make changes...

**Comment by madhur-tandon** [comment]
I guess we can leverage PSDC CLI to auto-publish examples in the CI.

**Comment by ntoll** [comment]
@madhur-tandon exactly. While the source is under GitHub control, we use the CLI for PSDC to push the (versioned) examples to the `@examples` account over there.

Also, there's a whole section (currently a place-holder) in the new user-guide just for these examples.

**Comment by madhur-tandon** [comment]
Remaining last examples are being tracked here: https://github.com/pyscript/examples/issues/7
