### ISSUE TITLE
Execution Order of Tags Not Guaranteed if Using `src`

### ISSUE THREAD

**Issue by JeffersGlass** [pyscript/pyscript#1804]
Try this in the current build (1):
```py
# foo.py
x = 1
```
```html
<!-- index.html -->
<script type="py" src="foo.py">
</script>
<script type="py">
    print(x)
</script>
```
This breaks, with `NameError: name 'x' is not defined`.

 I would have expected the scripts to run in DOM order per-type, regardless of whether they used `src` or not,

### (2) Using inline before `src` (WORKS)

```py
# bar.py
print(x)
```
```html
<script type="py">
    x = 1
</script>
<script type="py" src="bar.py">
</script>
```

### (3) Neither uses `src` (WORKS)
```html
<script type="py">
    x = 1
</script>
<script type="py">
    print(x)
</script>
```

### (4) Both use `src` (WORKS)
```py
# one.py
x = 1
```
```py
# two.py
print(x)
```
```html
<script type="py" src="one.py"></script>
<script type="py" src="two.py"></script>
```

### Using MicroPython (5)

All four of the samples above (the broken one and the ones which work) show the same behavior using `script type='mpy'` instead of `py`.

### PolyScript (6)

Doing the following in pure Polyscript works fine, so I _think_ it's an issue in PyScript specifically?

```
# foo.py
x = 1
```
```html
<script type="pyodide" src="foo.py"></script>
<script type="pyodide">
    print(x)
</script>
```

**Comment by WebReflection** [comment]
it's probably a matter of queue when it comes to custom types ... polyscript handles non-custom types slightly differently so that this might still be a polyscript issue after all, as PyScript just uses its registry to define the type.

Multiple scripts of same type are still a not super common use case though, so let's see if we want to prioritize this before the coming RC.

/cc @fpliger @ntoll

**Comment by JeffersGlass** [comment]
Investigating a little more, I _think_ this is PyScript specific. It seems the inline tags are _always_ executed before any `src` tags, but that's not the case in Polyscript. 

-----

In PyScript, I can mix up the following tags in any order:
```html
<script type="py" src="one.py"></script>         <!-- print('src one') -->
<script type="py">print('Inline one')</script>
<script type="py" src="two.py"></script>         <!-- print('src two') -->
<script type="py">print('Inline two')</script>
<script type="py" src="three.py"></script>       <!-- print('src three') -->
<script type="py">print('Inline three')</script>
```

And I always get:
```
Inline one
Inline two
Inline three
src one
src two
src three
```

But in PolyScript, they are executed in overall page order, regardless of whether they're inline or use `src`:
``` html
<script type="pyodide" src="one.py"></script>        <!-- print('src one') -->
<script type="pyodide">print('inline one')</script>
<script type="pyodide" src="two.py"></script>        <!-- print('src two') -->
<script type="pyodide">print('inline two')</script>
<script type="pyodide" src="three.py"></script>      <!-- print('src three') -->
<script type="pyodide">print('inline three')</script>
```

prints:

```
src one
inline one
src two
inline two
src two
inline three
```

**Comment by WebReflection** [comment]
I can solve this in PyScript but it's a polyscript custom type issue ... polyscript queue per interpreter all executing things:
https://github.com/pyscript/polyscript/blob/main/esm/script-handler.js#L160-L162

there's no such mechanism for custom types (IIRC) and I think if non custom type works like that, so should custom types too.

I'll try to fix this today, thanks for the investigation though!

**Comment by WebReflection** [comment]
@JeffersGlass this has been fixed and tested in *polyscript* so it will get in next time we update PyScript too ... which arguably could be today as well but ... you know, don't release on Friday and stuff :smile:

**Comment by WebReflection** [comment]
plot twist ... it might be today: https://github.com/pyscript/pyscript/pull/1805

**Comment by WebReflection** [comment]
it's in and published to `npm` ... you should be able to grab either latest from npm or from our CDN and verify your expectations now are met.
