### ISSUE TITLE
import python

### ISSUE THREAD

**Issue by d4nm0** [pyscript/pyscript#181]
is it possible to import libraries like on python?

```
import branca
        import csv
        import folium
        import hdfs
        import pandas as pd
        import json
        import requests
```

**Comment by ricardoprins** [comment]
The instructions in the [GETTING-STARTED](
https://github.com/pyscript/pyscript/blob/main/GETTING-STARTED.md#packages-and-modules) file can help with this; in case they haven't been read, it is a good place to start.

In a nutshell: specify your imports within the`<py-env>` tags and, if they are supported by pyodide, you should be fine.

**Comment by antocuni** [comment]
to expand ricarodo's answer: python libraries which are published as "pure python wheels" are automatically supported and can be included inside `<py-env>`.
Python libraries which rely on C extensions are available only if they are supported by pyodide. See the [pyodide documentation](https://pyodide.org/en/stable/usage/packages-in-pyodide.html) for more info.

I hope that this answers your question, feel free to reopen the issue if not.
