### ISSUE TITLE
MicroPython fails on main - works in worker

### ISSUE THREAD

**Issue by WebReflection** [pyscript/pyscript#1812]
Basically, all smoke tests around MicroPython (i.e. `mpy` scripts) fail if the `worker` attribute is not there.

Even the most basic test seems to fail and as we don't have any integration test for *mpy* custom type, I am not even sure where that issue comes from or since when.

In short, I believe we should test at least most basic expectations for `mpy` too as in *polyscript* that's done but in here the whole integration tests historically rotates around *pyodide* and nothing else.

I feel like this is **a blocker** for the incoming release.

**Comment by JeffersGlass** [comment]
+1 - it would be great to have some basic integration tests for `mpy` before release...
