### ISSUE TITLE
Pyscript already has py-click attribute, but what about py-submit for form?

### ISSUE THREAD

**Issue by Fundi1330** [pyscript/pyscript#1817]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I am using py script with flask admin. I want to run some py script on form submit. How to do it?

### What browsers are you seeing the problem on? (if applicable)

Chrome

**Comment by WebReflection** [comment]
literally any event that starts with `py-` is added as attribute so the exact same way you attach a `py-click` you can attach a `py-submit` within a `<form>` element.
