### ISSUE TITLE
Pyscript Website Issues

### ISSUE THREAD

**Issue by MarcSkovMadsen** [pyscript/pyscript#1818]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I went to PyScript docs.pyscript.net and it was not working as expected.

I would expect the web site to 

- have a search function
- optionally have a link to github as other MkDocs/ Material docs have

What I found was an exception in the browser console.

![image](https://github.com/pyscript/pyscript/assets/42288570/71aee0c0-02ef-48a4-a84e-c60287094437)

### What browsers are you seeing the problem on? (if applicable)

Microsoft Edge

### Console info

```shell
user-guide/:1  Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope ('https://docs.pyscript.net/2023.09.1.RC2/user-guide/') with script ('https://docs.pyscript.net/2023.09.1.RC2/javascripts/mini-coi.js'): The path of the provided scope ('/2023.09.1.RC2/user-guide/') is not under the max scope allowed ('/2023.09.1.RC2/javascripts/'). Adjust the scope, move the Service Worker script, or use the Service-Worker-Allowed HTTP header to allow the scope.
```

**Comment by WebReflection** [comment]
errors are gone now https://pyscript.github.io/docs/2023.11.2/beginning-pyscript/

the search looks like a feature request and not an issue. We might prefer a new issue but I think the site is statically generated and provide a search is not currently our highest priority but I ping @ntoll here, yet I think we can close this.
