### ISSUE TITLE
[2023.11.01_RC3] Syntax errors prevent terminal init

### ISSUE THREAD

**Issue by JoshuaLowe1002** [pyscript/pyscript#1831]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

Currently if Pyodide detects a syntax error when it goes to run the initial Python code, it seems that this is not being sent to the terminal (even though these errors are being sent through to stderr on the Pyodide side).

It seems as though the current code to send Stderr/Stdout to the terminal is not working in this scenario. 

You can test this by trying to execute the following Python code:

```python
print("Hello)
```

It does however seem to be a simple fix (by editing **py-terminal.js**), as I have tried the following and it appears to solve the issue.

I apologise for the hacky code, but just wanted to try and demonstrate a possible fix and let the experts take over 😄 

1. Add this inside `hooks.main.onWorker.add`

```javascript
xworker.sync.pyterminal_write_std = (value) => {
    readline.write(value);
};
```

2. Change `workerReady` so that it has access to `io`

```javascript
const workerReady = ({ interpreter, io }, { sync }) => {
```

3. Add this inside `workerReady`

```javascript
io.stdout = (value) => {
    sync.pyterminal_write_std(`${value}\n`);
};
io.stderr = (error) => {
    sync.pyterminal_write_std(`${error.message || error}\n`);
};
```

Let me know if anything does make sense here or if I can provide any extra context!

**Comment by WebReflection** [comment]
is this still anyhow relevant or broken? 🤔

**Comment by WebReflection** [comment]
I've just tested and I see the error in the terminal with latest PyScript.

**Comment by JoshuaLowe1002** [comment]
@WebReflection sorry for the lack of a reply here, yes you're correct this seems to work now out of the box
