### ISSUE TITLE
Difference with Pyodide ?

### ISSUE THREAD

**Issue by Conchylicultor** [pyscript/pyscript#184]
It looks like `pyscript` is based on [Pyodide](https://github.com/pyodide/pyodide). It would be nice to document what Pyscript bring in addition of Pyodide.

Is it just a convenience wrapper around Pyodide to adds the `<py-script></py-script>` ? Or is there more to it ?

**Comment by KenoLeon** [comment]
Yeah, quickly hit a wall on this as things like accesing JS Scope from Python and viceversa seem possible thorugh pyodide but are not documented in pyscript ( yet the landing page states it's possible) , so why use Pyscript ?

**Comment by yarikoptic** [comment]
I guess it is that time of the year -- I would also be very interested to know the answer.

**Comment by marimeireles** [comment]
We have a session on our docs about that!
Check it out: https://docs.pyscript.net/latest/reference/faq.html
Cheers!
