### ISSUE TITLE
PyScript polyglot example broken

### ISSUE THREAD

**Issue by i6y** [pyscript/pyscript#1854]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I've been trying to implement PyScript with external modules for basically 12 hours straight, and i haven't found a solution. I tried to learn from the given pirate language example and use it as a model. I followed all instructions, created a pyscript.json file, created an index.html file, and a main.py file. I followed all instructions and even pasted the code in for reassurance, but, to my surprise, it doesn't even work. My guess is it's either something wrong with "py-click" or the package system

### Console info

```shell
Failed to load resource: the server responded with a status of 404 ()
```

**Comment by JeffersGlass** [comment]
Moreover, when you say it doesn’t work - what is the error message you’re seeing, if any?

**Comment by fpliger** [comment]
Hi @i6y ! As @JeffersGlass , thanks for your perseverance! Here's a fully working example that you can use to start. There is indeed a bug in our docs and the link to the release is wrong. We'll fix asap.

In the meantime, [here's a working example](https://pyscript.com/@fpliger/polygot-pyrate/) that you can use to start playing around with it.

**Comment by fpliger** [comment]
@JeffersGlass @i6y I'm closing this as there was indeed a bug in our docs that pointed to the wrong link. It has been fixed in https://github.com/pyscript/docs/pull/47 . This and the link to the example above makes me think this issue has been closed. @i6y please lmk if it's not and we can reopen the issuel

Thanks again for your patience and for using PyScript!
