### ISSUE TITLE
core.css and core.js 404

### ISSUE THREAD

**Issue by pmmccorm** [pyscript/pyscript#1855]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

https://pyscript.net/snapshots/2023.11.1/core.css
and
https://pyscript.net/snapshots/2023.11.1/core.js

Appear to give a 404.

### Additional Context

When trying to create an example from the README.md and the docs.

**Comment by JeffersGlass** [comment]
For full releases, the links are `https://pyscript.net/releases/XXXX.XX.X/core.js` and `…core.css` respectively. (Note _releases_ not _snapshots_.)

**Comment by fpliger** [comment]
There was indeed a typo in our docs. Sorry for the inconvenience @pmmccorm and thanks for point it out. Docs have been fixed and deployed.

**Comment by pmmccorm** [comment]
Thanks for looking at this so quickly.

Yeah it was in the docs:
https://docs.pyscript.net/2023.11.1/beginning-pyscript/
And in the GH Readme

Appears to be fixed now.
