### ISSUE TITLE
pyscript website Issue

### ISSUE THREAD

**Issue by nasrin1748** [pyscript/pyscript#1866]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I went to PyScript https://pyscript.com/@examples/py-script-jokes/latest,https://pyscript.com/@examples/simple-panel-application/latest,https://pyscript.com/@examples/tic-tac-toe/latest and it was not working as expected.

I would expect the web site to

- to display @examples instead of 404(The page you're looking for does not exist).

### What browsers are you seeing the problem on? (if applicable)

Microsoft Edge

### Additional Context

<img width="944" alt="3" src="https://github.com/pyscript/pyscript/assets/79505893/80f9298e-f8f7-47ca-babc-9a75f7d2d94c">

**Comment by madhur-tandon** [comment]
Hey @nasrin1748 We are in the process of revamping examples due to the new release...
Some of them are present here: https://pyscript-dev.com/@examples
These will be uploaded soon to https://pyscript.com/@examples as well.

**Comment by madhur-tandon** [comment]
More of them are coming soon too...

**Comment by nasrin1748** [comment]
Even the "view code" wasn't taking me to the code page.
