### ISSUE TITLE
CHANGELOG missing 2023.11.01 release

### ISSUE THREAD

**Issue by mahmoud** [pyscript/pyscript#1869]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

Congrats on the release! Sounds like a big one. I was hoping to learn about it by reading the CHANGELOG, but instead I had to go through the GitHub Releases and Discussions pages to learn more. Would love to see an updated summary [like the one in this Discussion thread](https://github.com/pyscript/pyscript/discussions/1744) added to the CHANGELOG.md. Thanks so much!

**Comment by WebReflection** [comment]
We're way beyond this release version, so I think this can be closed.
