### ISSUE TITLE
loading issue

### ISSUE THREAD

**Issue by PrinceHatty** [pyscript/pyscript#187]
Hi i work well on print statement and the other python building function but having issue importing the modules and also it having issue lording it take to long to render things...

**Comment by antocuni** [comment]
Could you please provide an example of what code is not working for you, and what is the error that you are encountering?
Without these information it is a bit hard to guess what is the problem.

**Comment by marimeireles** [comment]
Alright, closing this one as no response from reporter.
Please provide more information if still seeing the behavior. I recommend opening an new issue and using the current template.
