### ISSUE TITLE
d3 example broken on PyScript examples page (CORS header)

### ISSUE THREAD

**Issue by mahmoud** [pyscript/pyscript#1870]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

Hey all! I was checking out [the official d3 example](https://pyscript.net/examples/d3.html), and I got a CORS error for the d3 dependency.

![image](https://github.com/pyscript/pyscript/assets/130193/2aee6084-1f3f-4d5f-a9d5-be2bf4e4b6cc)

### What browsers are you seeing the problem on? (if applicable)

Firefox, Chrome

### Console info

```shell
- The resource at “https://d3js.org/d3.v7.min.js” was blocked due to its Cross-Origin-Resource-Policy header (or lack thereof). See https://developer.mozilla.org/docs/Web/HTTP/Cross-Origin_Resource_Policy_(CORP)# d3.html
- Loading failed for the <script> with source “https://d3js.org/d3.v7.min.js”. d3.html:13:52
```
![image](https://github.com/pyscript/pyscript/assets/130193/628f5cb0-f01c-441c-a099-95b5c16a62b4)

**Comment by madhur-tandon** [comment]
Hi @mahmoud 

We are revamping the examples for the new release.
We have some of them here: https://pyscript-dev.com/@examples

They will soon be uploaded to https://pyscript.com/@examples as well
