### ISSUE TITLE
REPL should not generate a new copy if it's not the last child

### ISSUE THREAD

**Issue by fpliger** [pyscript/pyscript#189]
If a REPL is not the last one in a series of REPL components, it should not generate a new one. It should focus on the next one, the same what that happens for notebooks.

**Comment by marimeireles** [comment]
That's not really the behavior I observe.
If the REPL cell is not the last one when you run it it just keeps focusing on itself.
But I guess the idea is to focus on next, like notebooks.
And that's currently not happening.

**Comment by marimeireles** [comment]
This is being fixed by #1106

**Comment by madhur-tandon** [comment]
@JeffersGlass Is this fixed? I ask since your PR is linked here.

**Comment by WebReflection** [comment]
As things are different now and we won't support classic and we don't have an exact equivalent of REPL (editor + terminal) I think we can close this bug and eventually open a new one around our current offer or suggest improvements.
