### ISSUE TITLE
`<py-editor>` doesn't output newlines

### ISSUE THREAD

**Issue by JeffersGlass** [pyscript/pyscript#1890]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

Try this, in the current build:
```
<script type="py-editor">
    for i in range(3):
        print(i)
</script>
```
I would expect this to output something that looks like:
```
0
1
2
```
But instead I get (CSS issues aside):
![image](https://github.com/pyscript/pyscript/assets/1931111/24744b3a-f5ed-41df-84c8-5dc96b3619ab)

### Additional Context

In the old `py-repl` classic version, each time the standard out stream was flushed, we sent that output to a new child div in the output div, to ensure they appeared on "separate lines". Could do, or could translate newlines to `<br>` or similar?

**Comment by WebReflection** [comment]
OK, I've just double checked and indeed the styles have been lost in some MR ... will fix it ASAP

**Comment by WebReflection** [comment]
OK this is awkward ... I somehow lost the latest commit with all the CSS details and more changes ... I have no idea how this happened.

**Comment by WebReflection** [comment]
Thanks for spotting this @JeffersGlass now everything is actually as it was shown in here https://github.com/pyscript/pyscript/pull/1860#issuecomment-1836321250

Apologies for any inconvenience or surprise, I really don't understand why latest changes got lost or not merged.

**Comment by JeffersGlass** [comment]
Thanks @WebReflection, looks great! Sorry I didn't catch this in review - updated version looks swell.
