### ISSUE TITLE
js_modules not behaving like in Polyscript

### ISSUE THREAD

**Issue by WebReflection** [pyscript/pyscript#1899]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

Apparently `from pyscript.js_modules import Thing` doesn't work in *PyScript* the same way it does on *Polyscript*.

The main difference is that in *PyScript* that's exported within the Python code, as opposite of being registered as JS module like it is for *Polyscript* where *js_modules* use `registerJSModule` utility instead.

**Comment by JeffersGlass** [comment]
Yeah you can just do `from js_modules import xxx` in PyScript `2023.12.1`. [Example](https://jeff.glass/post/whats-new-pyscript-2023-12-1/#js-module-import).

I don't think registerJsModule allows registering a submodule of an existing package....

**Comment by WebReflection** [comment]
the `js_modules` is not directly registered or exported so I don't understand how that works ... in PyScript, AFAIK, you need to do `from pyscript.js_modules import thing ` because `js_modules` is a `pyscript` module reference ... in *polyscript* though, Pyodide does some magic there because `polyscript` is the only registered module but somehow `from polyscript.js_modules import ...` works .. .that **doesn't** in PyScript, which is the issue I am trying to solve.

To provide more context:

  * we agreed that having `js_modules` as registered module in the JS world *might* be the best approach so that your example/code would work as expected (but it shouldn't right now)
  * Python doesn't resolve modules entries as sub-modules so that `from numpy.array import dtype` makes no sense (thiswas just an example, the point here is that dictionaries don't resolve as modules)

Would you be OK if we remove `js_modules` from `pyscript` or `polyscript` and have this registered a part, like it is for the `js` reference everyone is already familiar with?

**Comment by WebReflection** [comment]
**Update** the *pyodide* approach is indeed, and intentional, magic: https://github.com/pyodide/pyodide/discussions/4346#discussioncomment-7895369

In *polyscript* though, I've managed to provide both behavior without issues: https://github.com/pyscript/polyscript/pull/74

The next thing to do is to bring a similar approach to PyScript too and align the dance in both *py* and *mpy* cases.

Meanwhile, MicroPython now (after that MR) also supports *js_modules* which is pretty good news.
