### ISSUE TITLE
Empty Directory doesn't create a new file.

### ISSUE THREAD

**Issue by nasrin1748** [pyscript/pyscript#1905]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

Should be able to create a new file in empty directory as well.

### What browsers are you seeing the problem on? (if applicable)

Microsoft Edge

### Additional Context

<img width="374" alt="7" src="https://github.com/pyscript/pyscript/assets/79505893/8be11352-ec71-43b9-8d55-5c7c6c5cd7ca">

**Comment by WebReflection** [comment]
pinging @FabioRosado here as this repository has nothing to do with pyscript.com, strictly speaking.

**Comment by WebReflection** [comment]
Closing as I believe no action can be taken in this repository.
