### ISSUE TITLE
pyscript issue

### ISSUE THREAD

**Issue by Mardan111** [pyscript/pyscript#1915]
(PY1001): Unable to install package(s) 'requests, pyodide_http, pyscript'. Reason: Traceback (most recent call last): File "/lib/python3.11/site-packages/micropip/externals/pip/_vendor/pkg_resources.py", line 312, in requires deps.extend(dm[safe_extra(ext)]) ~~^^^^^^^^^^^^^^^^^ KeyError: 'typer' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/lib/python3.11/site-packages/micropip/_micropip.py", line 576, in install await transaction.gather_requirements(requirements) File "/lib/python3.11/site-packages/micropip/_micropip.py", line 342, in gather_requirements await gather(*requirement_promises) File "/lib/python3.11/site-packages/micropip/_micropip.py", line 349, in add_requirement return await self.add_requirement_inner(Requirement(req)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/lib/python3.11/site-packages/micropip/_micropip.py", line 457, in add_requirement_inner await self.add_wheel(wheel, req.extras) File "/lib/python3.11/site-packages/micropip/_micropip.py", line 472, in add_wheel await self.gather_requirements(wheel.requires(extras)) File "/lib/python3.11/site-packages/micropip/_micropip.py", line 342, in gather_requirements await gather(*requirement_promises) File "/lib/python3.11/site-packages/micropip/_micropip.py", line 346, in add_requirement return await self.add_requirement_inner(req) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/lib/python3.11/site-packages/micropip/_micropip.py", line 457, in add_requirement_inner await self.add_wheel(wheel, req.extras) File "/lib/python3.11/site-packages/micropip/_micropip.py", line 472, in add_wheel await self.gather_requirements(wheel.requires(extras)) ^^^^^^^^^^^^^^^^^^^^^^ File "/lib/python3.11/site-packages/micropip/_micropip.py", line 210, in requires requires = self._dist.requires(extras) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/lib/python3.11/site-packages/micropip/externals/pip/_vendor/pkg_resources.py", line 314, in requires raise UnknownExtra("%s has no such extra feature %r" % (self, ext)) micropip.externals.pip._vendor.pkg_resources.UnknownExtra: rich-click 1.7.2 has no such extra feature 'typer' . Please open an issue at https://github.com/pyscript/pyscript/issues/new if you require help or you think it's a bug.

**Comment by WebReflection** [comment]
Your issue is about typer and rich-click version ... I suggest you to change version or file a (hopefully more readable) issue in Pyodide project. Closing as this doesn't look at all PyScript related.
