### ISSUE TITLE
Fix Button click.

### ISSUE THREAD

**Issue by nasrin1748** [pyscript/pyscript#1922]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

https://[_12.pyscriptapps.com/quiet-dawn/latest/](https://_12.pyscriptapps.com/quiet-dawn/latest/)
https://[_12.pyscriptapps.com/tiny-sunset/latest/](https://_12.pyscriptapps.com/tiny-sunset/latest/)
Button click result on terminal throws "cannot read the properties of undefined reading call" error, in the latest version of pyscript.
Even print doesn't seem to work inside the function.

### What browsers are you seeing the problem on? (if applicable)

Microsoft Edge

### Additional Context

<img width="464" alt="3" src="https://github.com/pyscript/pyscript/assets/79505893/ca1a01b8-5131-402a-b070-d17668f767ed">

**Comment by madhur-tandon** [comment]
Hi, Please modify the code to the following:

```
<button py-click="fun" id="get-time" class="py-button">button</button>
<p id="fun"></p>

<script type="py" terminal>
    def fun(event):
        print("hello")
</script>
```

Please Note:
- you cannot call a function in `py-click`, can only pass it's name...
- Use `display` for DOM, for terminal, `print` should be used
