### ISSUE TITLE
<script type="py" terminal worker> not working in chrome

### ISSUE THREAD

**Issue by IvanCobotic** [pyscript/pyscript#1925]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

running the following snippet
```
<!DOCTYPE html>
<html>
  <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width,initial-scale=1" />
      <title>pyscript</title>
      <script type="module" src="https://pyscript.net/releases/2024.1.1/core.js"></script>
  </head>
  <body>
    <script type="py" terminal worker>
      print("Hello World!")
    </script>
  </body>
</html>
```

i get an error in chrome console,
>Uncaught Error: Unable to use SharedArrayBuffer due insecure environment.

I saved the html code above as an html file and start it with vscode live server.
I can run other pyscript code, for example if i remove the worker from terminal above it works fine.

chrome Version 120.0.6099.200 (Officiell version) (64 bitar)

### What browsers are you seeing the problem on? (if applicable)

Chrome

**Comment by IvanCobotic** [comment]
if i try to use the editor with
```
<script type="py-editor">
      import sys
      print(sys.version)
</script>
```
i get the same error
>Uncaught Error: Unable to use SharedArrayBuffer due insecure environment.

**Comment by JeffersGlass** [comment]
The use of Workers in PyScript requires an environment with specific CORS headers - essentially, special security settings that allow for sharing data between the workers and the main thread in a specific way. The error about `SharedArrayBuffer` that you're getting is a byproduct of those headers not being present.

With a production webserver, these headers can usually be set. But for simple experiments, or in situations where the headers cannot be adjusted, a workaround is to use something like @WebReflection's [mini-coi.js](https://github.com/WebReflection/mini-coi) to "shim" the required headers in using a web worker.

That GitHub repo describes the usage, which is as simple as:

- Copy the contents of `mini-coi.js` into a JavaScript file, "adjacent" to your html file.
- Add `<script src="mini-coi.js">` to your HTML document.

**Comment by IvanCobotic** [comment]
This worked, thanks!
