### ISSUE TITLE
Import Files to Read With Pandas

### ISSUE THREAD

**Issue by ecowart99** [pyscript/pyscript#193]
Hi, I'm trying to use pandas in conjunction with matplotlib to create visualizations of a dataset I have. Below is a test file checking to see if the data is importing properly.

```
<!DOCTYPE html>
<html>
    <head>
        <script defer src="https://pyscript.net/unstable/pyscript.js"></script>
        <py-env>
            - pandas
            - paths:
                /data.csv
        </py-env>
        <meta charset="utf-8" />
        <title>Import Test</title>
    </head>

    <body>
        <h1>Hello World!</h1>
        <p>This is a test To see how my html code is.</p>
        <p>This is the 2nd line of the body.</p>

        <py-script>
        
import pandas as pd
data = pd.read_csv('data.csv')
print(data.head())

        </py-script>

    </body>

</html>
```

Originally, I was getting an error that the file could not be found, but now that it is in the same folder I am just seeing the "Hello World!" header and nothing being printed by python. I am guessing that the issue has to do with the file import, but am not receiving any error messages.

Any help is appreciated, thanks!

**Comment by RedSoul03** [comment]
is this working ?
