### ISSUE TITLE
Triple quotes throws error in pyscript.

### ISSUE THREAD

**Issue by nasrin1748** [pyscript/pyscript#1931]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

Was trying to write multiple lines in html
display(HTML(''' 
 "')
throws an error  in pyscript 
https://[_12.pyscriptapps.com/weathered-violet/latest/](https://_12.pyscriptapps.com/weathered-violet/latest/)
but works fine in .html
https://[nasrin1748.github.io/pyscrip/](https://nasrin1748.github.io/pyscrip/) 

### What browsers are you seeing the problem on? (if applicable)

Microsoft Edge

**Comment by WebReflection** [comment]
Closing as there's no follow-up action from our side, beside eventually documenting this but nothing we can ever fix.

If you have any follow up question, feel free to ask.

**Comment by WebReflection** [comment]
To whom it might concern, this is issue is the equivalent of:

```html
<script>
  console.log(`
    <script>nope</script>
  `);
</script>
```

That cannot work on the Web, but this can:

```html
<script>
  console.log(`
    <script>nope<\x2fscript>
  `);
</script>
```

**Comment by nasrin1748** [comment]
Morning it was working fine and how come it's blocking now??

**Comment by WebReflection** [comment]
@nasrin1748 your example uses an external file ... that never interferes with the parsing of the DOM within the browser.

Please note that this is not an opinion of mine, this is how the Web standards work.

If you write `</script>` inside a `<script></script>` tag and that's not the closing tag you will have errors in a way or another.

If you were referring to something else like putting a DOCTYPE node with html and body inside a `<div>` I am telling you that's not doing what you think it's doing ... and this is also defined by Web standards.

If you need any other clarification feel free to ask.

**Comment by WebReflection** [comment]
P.S. to explain further the issue, it's the exact same with multi line coments:

```js
/**
 * if you put */ here that's it
 */
```

See the broken highlight or try it in any JS, C, or any other PL context and see the result is not what you meant.

**Comment by nasrin1748** [comment]
Do ipywidgets work in pyscript?

**Comment by WebReflection** [comment]
we have [a discord channel](https://discord.com/channels/972017612454232116/972020206538997822) for questions related to PyScript. Let's please not discuss unrelated topics in here so that others might read or answer without needing to read into unrelated issues, thank you!
