### ISSUE TITLE
In the code editor ctrl+enter does not create a new line below

### ISSUE THREAD

**Issue by szabolcsdombi** [pyscript/pyscript#1933]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

The current behavior is to execute the code on `ctrl` + `enter`.
This is inconsistent with commonly used text editors.

**Comment by WebReflection** [comment]
> This is inconsistent with commonly used text editors.

**Comment by WebReflection** [comment]
Closing until a different behavior will be agreed among users and the team.

**Comment by ramalho** [comment]
CTRL+ENTER executes a code cell in Jupyter Notebook. That's reason enough to retain the current behavior.

Why would anyone use CTRL+ENTER to create a new line when ENTER already does it?
