### ISSUE TITLE
`PyDom[key: int]`  raises `AttributeError: 'int' object has no attribute 'indices'`

### ISSUE THREAD

**Issue by jorenham** [pyscript/pyscript#1938]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

The `PyDom.__getitem__` implementation for `key: int` is obviously incorrect:
https://github.com/pyscript/pyscript/blob/2024.1.1/pyscript.core/src/stdlib/pyweb/pydom.py#L421-L423

My guess is that this is supposed to be conditional on `key: slice` instead of `key: int`? 
For integer key `n`, am I correct to assume that the `n`-th element should be returned, instead of a sequence?

Additionally, I'd like to suggest that an `ElementCollection` is always returned, independent of the input type. Currently it can return `list[Element]` (potentially empty), `None`, or a (non-empty) `ElementCollection`.

**Comment by WebReflection** [comment]
There's an ongoing refactoring of the whole PyDom / PyWeb effort so I am going to ping @fpliger here but I think this can be closed, as it's part of legacy PyScript which is no longer maintained.

I hope this reasons well with you and thanks for the report!
