### ISSUE TITLE
Terminal does not show error message when using workers

### ISSUE THREAD

**Issue by joshdowning** [pyscript/pyscript#1939]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

when using the worker attribute and there's an error in my code, the terminal doesn't show any error, I can only see the error if I open up the console. When I don't use worker the terminal shows the error (2nd image)

![ps2](https://github.com/pyscript/pyscript/assets/59490159/f4117121-e7c2-4c21-8abb-e6967a96a03e)
![ps](https://github.com/pyscript/pyscript/assets/59490159/de8a5acc-81f5-4b24-9c8f-71fded072ead)

### What browsers are you seeing the problem on? (if applicable)

Chrome

### Console info

```shell
see image
```

**Comment by WebReflection** [comment]
I wonder if this issue is related https://github.com/pyscript/polyscript/issues/39 ... but I will have a look, thank you for iling this issue!
