### ISSUE TITLE
MicroPython doesn't support MethodType() from "types" module!

### ISSUE THREAD

**Issue by GoToLoop** [pyscript/pyscript#1956]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

When **MethodType()** is invoked MicroPython raises:
> "TypeError: can't create 'bound_method' instances"

We can see that bug happen in file "best.py" inside function **setup()** on this link:
https://PyScript.com/@gotoloop/unicode-letters-test/v2

Besides swapping to Pyodide instead:
https://PyScript.com/@gotoloop/unicode-letters-test/v3

By chance I've found out about function **partial()** from "functools" module:
https://PyScript.com/@gotoloop/unicode-letters-test

But I still think MicroPython should fix **MethodType()**, although **partial()** seems to do exactly the same; whether more performant or not I dunno.

### What browsers are you seeing the problem on? (if applicable)

Firefox, Chrome, Other

### Console info

```shell
MicroPython exception: Traceback (most recent call last):
  File "<stdin>", line 67, in sketch
TypeError: can't create 'bound_method' instances
```

**Comment by WebReflection** [comment]
I think this bug would better be in MicroPython repository using the `WebAssembly/PyScript - ` prefix as we're not working on MicroPython in here.

**Comment by WebReflection** [comment]
I've updated the example and I can reproduce: https://pyscript.com/@agiammarchi/unicode-letters-test-copy/latest?files=index.html,pyscript.toml,best.py

however, this is still something we can't fix in here ... so I am pinging @dpgeorge in case there's something else to consider around this issue.

**Comment by cclauss** [comment]
`sketch()`, `setup()`, and `draw()` are all normal Python functions, not class methods.

I believe that they should be defined under a user-defined class if we expect to use [`types.MethodType`](https://docs.python.org/3/library/types.html#types.MethodType).
> The type of methods of user-defined class instances.

**Comment by WebReflection** [comment]
re-stating what I wrote before:

> **this is still something we can't fix in here**

all these reports would have a better outcome if filed upstream: https://github.com/micropython/micropython/

Please remember to specify the WASM port in there ... and I am closing this as it's not under our responsibility.

**Comment by dpgeorge** [comment]
We could possibly fix this in MicroPython.  Is it common to construct `MethodType` instances?  I haven't seen that before.
