### ISSUE TITLE
MicroPython doesn't support alternative syntax to create a tuple outta comprehension

### ISSUE THREAD

**Issue by GoToLoop** [pyscript/pyscript#1957]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

In the file "mpy.py" @ **setup()** I'm creating a tuple from a generator comprehension:
`balls = tuple( Ball(p) for _ in BALLS )`
https://PyScript.com/@gotoloop/bouncing-colorful-balls

However if I change that to `balls = *( Ball(p) for _ in BALLS ),` it fails on μPython:
https://PyScript.com/@gotoloop/bouncing-colorful-balls/v4
> SyntaxError: *x must be assignment target

But if I swap it to Pyodide in "mpy.html" it works as expected w/ that alt. syntax:
`<script type=py src=mpy.py config=mpy.toml></script>`
https://PyScript.com/@gotoloop/bouncing-colorful-balls/v5

Of course it's not a big deal; but it saves 3 characters to fit everything in 80 cols.

### What browsers are you seeing the problem on? (if applicable)

Firefox, Chrome, Other

### Console info

```shell
MicroPython exception: Traceback (most recent call last):
  File "<stdin>", line 73, in setup
SyntaxError: *x must be assignment target

convert_mp_to_js_obj_jsside @ micropython.mjs:5532
```

**Comment by WebReflection** [comment]
I think this bug would better be in MicroPython repository using the **WebAssembly/PyScript - ** prefix as we're not working on MicroPython in here.

**Comment by WebReflection** [comment]
closing because there's nothing we can do on our side of affairs.

**Comment by GoToLoop** [comment]
> ```python
> # this doesn't
> balls = *( Ball(v) for v in BALLS )
> ```

We need a trailing comma: `balls = *( Ball(v) for v in BALLS ),`
