### ISSUE TITLE
terminal with worker not working

### ISSUE THREAD

**Issue by shakfu** [pyscript/pyscript#1969]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

A basic demo of the terminal as per the docs is not working for me, I have used safari and chrome on macOS and also launched the file via `python3 -m http.server` as well. The javascript console error (for chromium) is given below. It looks like a browser [security issue[(https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#security_requirements)

Any ideas on how to get this to work.

For `demo.html`:

```html
<!DOCTYPE html>
<html>
  <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width,initial-scale=1" />
      <title>PYSCRIPT DEMO</title>
      <link rel="stylesheet" href="https://pyscript.net/releases/2024.1.3/core.css">
      <script type="module" src="https://pyscript.net/releases/2024.1.3/core.js"></script>
  </head>
  <body>
    <script type="py" terminal worker>
      import code
      code.interact()
    </script>
  </body>
</html>
```

### What browsers are you seeing the problem on? (if applicable)

Chrome, Safari

### Console info

```shell
761e6c16-a697-44f8-b9e7-d0e49a33ce9c:2 Uncaught Error: Unable to use SharedArrayBuffer due insecure environment.
Please read requirements in MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#security_requirements
    at 761e6c16-a697-44f8-b9e7-d0e49a33ce9c:2:25267
(anonymous) @ 761e6c16-a697-44f8-b9e7-d0e49a33ce9c:2
```

**Comment by WebReflection** [comment]
> aunched the file via python3 -m http.server as well.

that's not good enough .. you need to enable the right headers to allow SharedArrayBuffer as documented in the link within the error.

If you have node you can try `npx static-handler --coi .` instead and see it working.

**Comment by shakfu** [comment]
@WebReflection 

Thanks very much for your help.  May I suggest to include this advice in the docs.
