### ISSUE TITLE
Unable to upload .mp4 file.

### ISSUE THREAD

**Issue by nasrin1748** [pyscript/pyscript#1978]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

@FabioRosado I am trying to upload .mp4 video file but upload shows blank after selection.

### What browsers are you seeing the problem on? (if applicable)

Microsoft Edge

**Comment by FabioRosado** [comment]
Hello @nasrin1748  I am going to move this issue to the [pyscript.com public issue tracker](https://github.com/anaconda/pyscript-dot-com-issues) and reply to you there
