### ISSUE TITLE
Cannot create a PyWorker from python using Pyodide

### ISSUE THREAD

**Issue by sakhalifa** [pyscript/pyscript#1979]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

Hello,

I am trying to adapt the [worker-input](https://github.com/pyscript/polyscript/tree/main/docs/examples/worker-input) example from polyscript to pyscript, but instead using Pyodide. According to the docs, I should be able to create a worker using `a_worker = PyWorker(file)`. I tried a simpler example, a python script that just spawns a PyWorker that prints "a" to the console. I also used `mini-coi` to make web workers actually work.

Here is the structure of this test project

pyscript.json:
```json
{
  "files": {
    "./a.py": "./a.py"
  }
}
```

index.html:
```html
<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://pyscript.net/releases/2024.1.1/core.css">
    <script type="module" src="https://pyscript.net/releases/2024.1.1/core.js"></script>
</head>
<body>
    <script type="py" config="./pyscript.json">
        from pyscript import PyWorker

        worker = PyWorker("./a.py")
    </script>
</body>
</html>
```

a.py:
```python
print("a")
```

From the docs, it should work. Unfortunately, it does not, and instead throws an error in the console. What's weird is that it works with micropython. With the following index.html:

```html
<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://pyscript.net/releases/2024.1.1/core.css">
    <script type="module" src="https://pyscript.net/releases/2024.1.1/core.js"></script>
</head>
<body>
    <script type="micropython" config="./pyscript.json">
        from polyscript import XWorker

        worker = XWorker("./a.py")
    </script>
</body>
</html>
```
it actually prints "a" to the console, with no error.

It seems to be a problem with the modules from what i've read in the stacktrace.

### What browsers are you seeing the problem on? (if applicable)

Firefox, Chrome

### Console info

```shell
[pyscript/main] PyScript Ready

TypeError: s is undefined
    get blob:http://localhost:8080/7b3e6a6f-c03e-49c4-8f55-61b5e83a3406:2
    Ft blob:http://localhost:8080/7b3e6a6f-c03e-49c4-8f55-61b5e83a3406:2
    promise callback*Ft blob:http://localhost:8080/7b3e6a6f-c03e-49c4-8f55-61b5e83a3406:2
    Ut blob:http://localhost:8080/7b3e6a6f-c03e-49c4-8f55-61b5e83a3406:2
    <anonymous> blob:http://localhost:8080/7b3e6a6f-c03e-49c4-8f55-61b5e83a3406:2
    value blob:http://localhost:8080/7b3e6a6f-c03e-49c4-8f55-61b5e83a3406:2
    Gt blob:http://localhost:8080/7b3e6a6f-c03e-49c4-8f55-61b5e83a3406:2
    <anonymous> blob:http://localhost:8080/7b3e6a6f-c03e-49c4-8f55-61b5e83a3406:2
error.js:15:15
    stderr error.js:15
    onerror core.js:112
    sn class.js:69
    (Asynchrone : EventListener.handleEvent)
    value main.js:67
    sn class.js:62
    l custom.js:89
    PyWorker core.js:111
    hiwire_call_bound pyodide.asm.js:9
    <anonyme> pyodide.asm.wasm:1421309
    <anonyme> pyodide.asm.wasm:1717908
    <anonyme> pyodide.asm.wasm:2532200
    <anonyme> pyodide.asm.wasm:2493051
    <anonyme> pyodide.asm.wasm:2481402
    <anonyme> pyodide.asm.wasm:1983178
    <anonyme> pyodide.asm.wasm:1717908
    <anonyme> pyodide.asm.wasm:2532200
    <anonyme> pyodide.asm.wasm:2548688
    <anonyme> pyodide.asm.wasm:1718788
    <anonyme> pyodide.asm.wasm:1717908
    <anonyme> pyodide.asm.wasm:1438814
    callPyObjectKwargs pyodide.asm.js:9
    callKwargs pyodide.asm.js:9
    runPython pyodide.asm.js:9
    Nt _python.js:12
    t utils.js:61
    nn/e[i]< hooks.js:65
    run utils.js:53
    onReady core.js:186
    queue custom.js:149
    (Asynchrone : promise callback)
    jn custom.js:146
```

### Additional Context

Adding to it, it seems pyscript is the actual offender, as even using "mpy" as the script type does not fix it.

```html
<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://pyscript.net/releases/2023.11.1/core.css">
    <script type="module" src="https://pyscript.net/releases/2023.11.1/core.js"></script>
</head>
<body>
    <script type="mpy" config="./pyscript.json">
        from polyscript import XWorker

        worker = XWorker("./a.py")
    </script>
</body>
</html>
```

This does not work for the same reason as the original post.

Another addition, is that pyodide is actually **not** the one at fault here. Using this snippet : 
```html
<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://pyscript.net/releases/2023.11.1/core.css">
    <script type="module" src="https://pyscript.net/releases/2023.11.1/core.js"></script>
</head>
<body>
    <script type="pyodide" config="./pyscript.json">
        from polyscript import XWorker

        worker = XWorker("./a.py")
    </script>
</body>
</html>
```

It actually works! This is quite a messy situation

**Comment by sakhalifa** [comment]
Adding to it, it seems pyscript is the actual offender, as even using "mpy" as the script type does not fix it.

```html
<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://pyscript.net/releases/2023.11.1/core.css">
    <script type="module" src="https://pyscript.net/releases/2023.11.1/core.js"></script>
</head>
<body>
    <script type="mpy" config="./pyscript.json">
        from polyscript import XWorker

        worker = XWorker("./a.py")
    </script>
</body>
</html>```

This does not work for the same reason as the original post

**Comment by WebReflection** [comment]
I am a bit confused ... if you want *polyscript* `XWorker` you should use *polyscript*, not PyScript, and also pass the `type` of interpreter to the worker or follow the documentation which states that the default interpreter is pyodide but on top of all this, the *PyScript* has config parsing and other things to deal with so that and in its latest version (on *npm*) you have `PyWorker` and `MPWorker` but **only from JS**.

If you want a worker in either MicroPython or Pyodide you just use:

```html
<script type="py" worker="a.py"></script>
<script type="mpy" worker="a.py"></script>
```

If you want to write code to execute on the worker you instead do:
```html
<script type="py" worker>
  print("I am a pyodide worker")
</script>
<script type="py" worker>
  print("I am a MicroPython worker")
</script>
```

Any worker script gets an `xworker` reference attached to itself so you can use an *id* or any other way to reach such script and find the interpreter but this is rather for JS <-> Python advanced use cases, which doesn't seem to be the case here, or better, it's not clear to me why you are importing from *polyscript* things not meant to be part of the*PyScript* offer/API 🤔

**Comment by sakhalifa** [comment]
Hello,

According to the [docs](https://pyscript.github.io/docs/2024.1.3/user-guide/builtins/), you should be able to do this snippet of code and it should work
```python
from pyscript import PyWorker


a_worker = PyWorker("./worker.py")
```

Maybe it is a mistake on the docs...

**Comment by sakhalifa** [comment]
Basically, what I want to be doing is a sort of graphical debugger. Unfortunately, I **cannot** use MicroPython as it does not support `bdb` from what I've seen (I may be wrong tho). I'd like to use it as it's way faster than Pyodide, but unfortunately that's a technical limitation.

To effectively stop at breakpoints using `bdb`, it would need a sort of loop that only stops when there is user interaction, so the debugger can continue execution. This is based on what I've seen in the `pdb` implementation. I can't do async as it's a sys.settrace, and the system will surely not await it.

I modeled this debugger with a simple counter. The counter is only a `while True`, and only continues execution after a button press. So it's basically an `increment` button but kind of multithreaded and it should not waste a lot of CPU (compared to a `while condition`).
Here is the example :

index.html:
```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>PyScript Next</title>
    <link rel="stylesheet" href="https://pyscript.net/releases/2024.1.1/core.css">
    <script type="module" src="https://pyscript.net/releases/2024.1.1/core.js"></script>

</head>
<body>
<script type="pyodide">
            from js import Promise, document
            from polyscript import XWorker

            deferred = Promise.withResolvers()

            def handle_increment(event):
                global deferred
                button = document.getElementById("incr")
                button.disabled = True
                deferred.resolve()
                deferred = Promise.withResolvers()

            # allows the worker to ask something as placeholder
            # resolves the returning on micropython-click event
            # non-blocking this thread, keeping the worker in idle
            # until such promise is not resolved
            def handle_cpt(newVal):
              button = document.getElementById("incr")
              button.disabled = False
              cptDiv = document.getElementById("cpt")
              cptDiv.textContent = str(newVal)
              return deferred.promise

            w = XWorker('./worker.py')

            # provide a synchronous input callback
            # to the polyscript's xworker utility
            w.sync.count = handle_cpt
        </script>
        <button pyodide-click="handle_increment" disabled id="incr">Increment</button>
        <div id="cpt">loading...</div>

<!-- this is only to test the non-blocking behavior -->
        <script>
          addEventListener('DOMContentLoaded', () => {
            const div = document.body.appendChild(
              document.createElement('div')
            );
            (function monitor() {
              const date = new Date;
              div.textContent = `${date.getSeconds()}.${date.getMilliseconds()}`;
              requestAnimationFrame(monitor);
            }());
          });
        </script>
</body>
</html>
```

worker.py:
```python
from polyscript import xworker

cpt = 0

while True:
	xworker.sync.count(cpt)
	cpt += 1
```

Right now, as you can see, i'm using polyscript's script types (`pyodide` instead of `py`).
I could use it as it is right now, but what I'm wondering is why when you copy paste the example from the docs, it does not work and instead throws an error.

Also, if you have a way to make what I'm trying to do with full pyscript support, please help me because I have no clue how to make it work.

Thank you for your detailed answers though!

**Comment by WebReflection** [comment]
@sakhalifa this is one way to go:

```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>PyScript Next</title>
    <!-- we are on 2024.1.3 now -->
    <link rel="stylesheet" href="https://pyscript.net/releases/2024.1.3/core.css">
    <script type="module" src="https://pyscript.net/releases/2024.1.3/core.js"></script>

</head>
<body>
    <script type="mpy">
        from pyscript import window, document

        Promise = window.Promise

        deferred = Promise.withResolvers()

        def handle_increment(event):
            global deferred
            button = document.getElementById("incr")
            button.disabled = True
            deferred.resolve()
            deferred = Promise.withResolvers()

        def handle_cpt(newVal):
            button = document.getElementById("incr")
            button.disabled = False
            cptDiv = document.getElementById("cpt")
            cptDiv.textContent = str(newVal)
            return deferred.promise

        document.getElementById("counter").xworker.sync.count = handle_cpt
    </script>
    <script type="py" id="counter" worker>
        from pyscript import sync

        cpt = 0

        while True:
	        sync.count(cpt)
	        cpt += 1
    </script>
    <button mpy-click="handle_increment" disabled id="incr">Increment</button>
    <div id="cpt">loading...</div>
</body>
</html>
```

**Comment by WebReflection** [comment]
one thing to keep in mind, is that in this example you are delegating the hard work on main and doing pretty much nothing on the Worker. I trust your example would actually do heavy computation in worker but if that's not the case, please re-consider your example or goals ... and worth mentioning, if you use `py` instead of `mpy` for both the `type` and the `py-click` things would still work as expected.

It's true that we need to improve both docs and examples around `PyWorker` as that doesn't really represent, in the current latest state, what we wanted to express before ... most notably:

  * the *JS* side has both `PyWorker` and `MPWorker` to disambiguate the interpreter out of the box
  * the *JS* side does not resolve neither synchronously so that this should be reflected on main whenever we want that to be the case

However, I think your example is much cleaner and easier to reason about now, but please do let me know if that's not the case.

**Comment by sakhalifa** [comment]
Thank you for this example!
It is much cleaner now yes, I did not know you could just get the underlying worker object from the html element...

And the problem is not a "who does the CPU work", it's more of "how can I block this code without hanging the main thread until a condition is met". Unfortunately, as it's calling my function with `sys.settrace`, I don't think there is a way to use async awaits in the debugger function which would kind of be the preferred way, so I need to be kind of dirty about it :/.

I need to do that to actually stop the debugger's code it is debugging. And as we're working on a GUI, I don't think the debugger could actually be in control like with `pdb`'s case. Because with `pdb`, there is a implicit `input()` function, but with a GUI it's waiting for a button to be pressed, and I have no clue how to block execution without async awaits or a while True (or in this case, using a promise and waiting for it to finish) :(.

**Comment by WebReflection** [comment]
> Unfortunately, as it's calling my function with sys.settrace, I don't think there is a way to use async awaits in the debugger function which would kind of be the preferred way, so I need to be kind of dirty about it :/.

You don't, the whole point of our *worker* solution is that it doesn't block the main and it enables anything sync on the worker code side of affari 😉

> but with a GUI it's waiting for a button to be pressed, and I have no clue how to block execution without async awaits or a while True (or in this case, using a promise and waiting for it to finish) :(.

you can add a `debugger` statement via JS but that devtool experience will be nightmare-ish to you as too much indirection would happen.

We are aware the debugging story is nowhere complete or usable in our project but both underlying projects are trying to help us forward, namely Pyodide and MicroPython interpreters, although we don't have any ETA to share.

> Still your solution would work wonders and thank you again for your help!

Glad it does and I think I might be able to close this at this point, but I will follow up with a dedicated issue around our `PyWorker` offer as it's clear it needs some change/better codumentation around or be dropped all together as my solution in here is actually (at least to my taste) preferred.
