### ISSUE TITLE
libraries are being installed on every reload

### ISSUE THREAD

**Issue by mn9142001** [pyscript/pyscript#198]
every time the page is reloaded it reinstall the libraries and takes long time like 3-5 seconds even the page is frozen, is this an issue will be fixed or I'm using it wrong?

**Comment by verhulstm** [comment]
hi,

i don't see any reason to think you are using it wrong. it does take a few seconds to load. we are working on making that faster

you might want to check this out

https://github.com/pyscript/pyscript/issues/171

thanks :)

**Comment by marimeireles** [comment]
I guess this is a caching problem. Feel free to open a more detailed discussion if you're interested in tackling this issue.
Closing this issue because it's not really a request nor a bug.
