### ISSUE TITLE
print() function does not work, but display() does

### ISSUE THREAD

**Issue by mrsamsonn** [pyscript/pyscript#1991]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

When I use:
 ```
<py-script>
       print("hi")
</py-script>
```
nothing shows up on my browser.

But when I use:
```
<py-script>
        from pyscript import display
        display("hello there")
</py-script>
```
"hello there" shows up in the browser.
<img width="678" alt="Screenshot 2024-03-11 at 1 16 42 PM" src="https://github.com/pyscript/pyscript/assets/98930957/de19c54c-c37f-4beb-8239-75a37ea2986b">

I'm wondering if some built in python functions don't work with py-script.

I tried chrome, firefox, safari, and all shows the same result.

### What browsers are you seeing the problem on? (if applicable)

Firefox, Chrome, Safari

**Comment by WebReflection** [comment]
have you checked your devtools console? it's a right click + inspect + console tab away from you ... we display on the page, we by default print in console unless you are using a terminal, in which case you'll see the print outcome.
