### ISSUE TITLE
cannot use cross origin 

### ISSUE THREAD

**Issue by dberardo-com** [pyscript/pyscript#2009]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

not clear from the doc how to fetch remote python scripts using CORS

### What browsers are you seeing the problem on? (if applicable)

Chrome

**Comment by WebReflection** [comment]
is it possible to have a minimal testable page that fails in here? it's not clear what's the scenario otherwise, thank you!

**Comment by dberardo-com** [comment]
well i am using 
<py-script crossorigin="use-credentials" src="remote_url..." output="_dfb3a762-1f77-451c-86f9-56d2bdd36fac_init" id="py-internal-0"></py-script>

and i cant see cookies being passed to the request

**Comment by WebReflection** [comment]
that's nowhere in our documentation and that attribute is nowhere parsed in current offer ... the `py-script` is also a custom element, but we suggest `<script type="py">` these days, still I am not sure what you expect in there ... it feels like fully misaligned with what is PyScript today ... happy to understand more.

**Comment by dberardo-com** [comment]
i see, i thought that <py-script> was a standard element used in the py-script library.
indeed i am using this implementation of pyscript in react: https://github.com/Py4Js/pyscript-react that automatically generates pyscript tags.

if i understand your answer, then using the crossorigin attribute in the <script type="py"> tag would work, whereas in the <py-script> tag that would not work. is that so ?

**Comment by WebReflection** [comment]
`script type="py"` is what you should use instead (or `script type="mpy"` for MicroPython) because:

  * it doesn't suffer layout parsing
  * it never needs related CSS
  * it's the right place to inject code/data, it's actually the only element that's not parsed that offers that

that being said, the `src` is parsed by our logic and it's not clear what you expect there ... should we pass that `crossorigin`, when explicitly specified, to the underlying `fetch` operation? 'cause in that case the values differ: https://developer.mozilla.org/en-US/docs/Web/API/fetch#credentials

omit, same-origin, include ... there's no such thing as crossorigin, although we could infer the value from here: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin

**Comment by dberardo-com** [comment]
well i believe the best approach could be emulating the same behavior as the original script tag: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin

but that is just my 50 cents on the matter.

am i right then? is the crossorigin attribute at the moment being totally ignorde by the script type=py tag ? or does it have any effect ?

**Comment by WebReflection** [comment]
`<script type="py" src="./code.py">` shares nothing with `<script src="./code.js">`:

  * unknown types are ignored by the browser
  * all scripts are ignored by the DOM parser, only their content, if known, is eventually parsed and executed
  * our `src` is a Python file, we are the one providing the runtime to execute that code after adding our namespace, modules, and the right amount of "*magic*"

Accordingly, the declarative approach we offer is fully managed by our core logic, not by the browser, os either we add that functionality or, behind the scene, it's just a `fetch(that.src)` operation.

The attribute `crossorigin` must be translated into something that `fetch` can do, and options are omit, include, same-origin ... with [use-credentials](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin#use-credentials) it looks like the counter-fetch option for crossorigin is `include` which is not the default `same-origin` regular fetch does. Would that solve? It's not clear how to bring in, in a semantic way, the `omit` option too ... but maybe that's not needed?

**Comment by dberardo-com** [comment]
* crossorigin: true --> fetch: mode: "cors"
* crossorigin: use-credentials --> fetch: mode: "cors" + credentials: "include"

could this work ?

**Comment by WebReflection** [comment]
what if you add this `<script>` at the top of your HTML **before** any other script you have in there?

```html
<script>
(g => {
  const { fetch } = g;
  g.fetch = function (resource, options) {
    options = {...options, mode: "cors", credentials: "include"};
    return fetch.call(this, resource, options);
  };
})(globalThis);
</script>
```

That should patch fetch globally so that other scripts will force that *use-credential* and you can check/answer yourself if that's going to work before we do ... could you please test that?

**Comment by WebReflection** [comment]
That being said we could offer the following, as the `crossorigin="true"` has no standard meaning:

  * `crossorigin="anonymous"` will use `credentials: "omit"` in *fetch*
  * `crossorigin="use-credentials"` will use `credentials: "include"` and `mode: "cors"` in *fetch*
  * `crossorigin` with no value will use only `mode: "cors"` in *fetch*

The last one is a stretch because by default an empty `crossorigin` is like `anonymous` but I rather explain that `crossorigin` in PyScript means the intent to enforce *cors* and that `same-origin` is the default for credentials ... this, of course, assuming your test works so that we're not just wasting time trying to fix the unfixable.

**Comment by WebReflection** [comment]
on a second thought maybe `anonymous` for `crossorigin` should result into `mode: "cors"` and `credentials: "same-origin"` which should cover already the last case so we don't need to diverge from the current standard and credentials will be sent only for non-corse related request ... I am not sure as this is the first time we have this request from our users.

**Comment by dberardo-com** [comment]
thanks for the clarification. i look forward for this implementation, although i am using a react specific project, so i hope the creators at https://github.com/Py4Js/pyscript-react/issues/1865 are also interested to address this use case

**Comment by WebReflection** [comment]
@dberardo-com I am actually waiting for you to test this and let me know if it solved anything:
https://github.com/pyscript/pyscript/issues/2009#issuecomment-2022285154

I won't work on this until I am sure I am actually solving the issue, thanks for your understanding and collaboration.

**Comment by WebReflection** [comment]
@dberardo-com any chance you tried what I've asked you to?

**Comment by WebReflection** [comment]
@dberardo-com we're close to a new release ... and I am still wondering if you got a chance to test what I've proposed before we implement something that might not fully solve the issue ... this is my last ping around this, then I will close the feature request as "*not interested in*".

**Comment by dberardo-com** [comment]
i believe you can close it for now and i can re open it as soon as i have more input to give. what do you think ?

**Comment by WebReflection** [comment]
That sounds great, and please do come back with extra inputs, still I hope you can try my temporary solution and tell us if that worked by any mean. Closing then!
