### ISSUE TITLE
Unable to connect to webpages with the requests library

### ISSUE THREAD

**Issue by SlothScript** [pyscript/pyscript#2045]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I was making something that can get the HTML of another website and display it, but it lets out a spew of errors.
<img width="889" alt="Screenshot 2024-05-03 at 6 31 08 PM" src="https://github.com/pyscript/pyscript/assets/106759481/fbae7856-4ab8-4c71-b106-db63e683808e"> (Safari)
<img width="556" alt="Screenshot 2024-05-03 at 6 35 45 PM" src="https://github.com/pyscript/pyscript/assets/106759481/a0114968-56d2-4e10-9af7-5302c2bf1e25"> (Chrome)

I have the requests module in the pyscript.json, but it still won't let me.

### What browsers are you seeing the problem on? (if applicable)

Chrome, Safari

### Additional Context

I'm running on MacOS

**Comment by JeffersGlass** [comment]
This is not so much a PyScript specific errors, but because of how permissions work on the web. See [MDN's CORS Erorrs [age](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors) for more info.

**Comment by WebReflection** [comment]
example.com doesn't accept cross origin requests ... you can fetch or request data only from websites that allow CORS on their side, like Jeff suggested. I am closing this as there's nothing we can do or nothing we work around as that's how the Web works, and PyScript is still Web based. Happy to answer anything else if needed, closing though 👋
