### ISSUE TITLE
How can I report a security issue?

### ISSUE THREAD

**Issue by rayjolt** [pyscript/pyscript#206]
I believe I have found a security issue in PyScript. What is the best way to report it?

**Comment by JeffersGlass** [comment]
Not a dev, but just asking - it's not the same as [Issue #123](https://github.com/pyscript/pyscript/issues/123#issuecomment-1115265873), is it?

**Comment by rayjolt** [comment]
> Not a dev, but just asking - it's not the same as [Issue #123](https://github.com/pyscript/pyscript/issues/123#issuecomment-1115265873), is it?

No, it's something else.

**Comment by fpliger** [comment]
@rayjolt thank you very much for reaching out! Can you please report to  [security@pyscript.net](mailto:security@pyscript.net) ?

**Comment by rayjolt** [comment]
Thank you for letting me know the email address to send security issues to. I don't think there is anything else that needs to be discussed for this issue, so I am closing it.
