### ISSUE TITLE
Adding Interactivity To the Py-Editor

### ISSUE THREAD

**Issue by JeffersGlass** [pyscript/pyscript#2074]
Currently, while the Py-Editor is running its code in a web worker, there's no visual indication that the script is running. We simply disable its "play" button and then re-enable it when the script completes.

A visual indication of running scripts would be great - either a spinner, a change in color, the word `running` or something... not sure on the details, but an experiment is probably due.

**Comment by JeffersGlass** [comment]
These changes can likely be made in the `py-editor.js` plugin.

**Comment by WebReflection** [comment]
never mind ... I see this MR goal is to fix this https://github.com/pyscript/pyscript/pull/2078 and I like the idea/proposal there

**Comment by WebReflection** [comment]
A proposed fix landed 🥳
