### ISSUE TITLE
Issue with printing class variables.

### ISSUE THREAD

**Issue by AdamFelle** [pyscript/pyscript#2079]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I made a web page that allows you to run python scripts in the browser using PyScript. 

In normal python the following script:
```py
class ExampleClass:
    varia = 1
    def __init__(self, val):
        ExampleClass.varia = val


print(ExampleClass.__dict__)
example_object = ExampleClass(2)

print(ExampleClass.__dict__)
print(example_object.__dict__)
```
Would output:
`{'__module__': '__main__', 'varia': 1, '__init__': <function ExampleClass.__init__ at 0x7f7cc4b490e0>, '__dict__': <attribute '__dict__' of 'ExampleClass' objects>, '__weakref__': <attribute '__weakref__' of 'ExampleClass' objects>, '__doc__': None}
{'__module__': '__main__', 'varia': 2, '__init__': <function ExampleClass.__init__ at 0x7f7cc4b490e0>, '__dict__': <attribute '__dict__' of 'ExampleClass' objects>, '__weakref__': <attribute '__weakref__' of 'ExampleClass' objects>, '__doc__': None}
{}`

But in PyScript it says 'name "ExampleClass' is not defined" meaning it does not understand the concept of printing globals from the class itself.

### Additional Context

Source code for my web python runner for context:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Interactive Python Editor with PyScript</title>
    <link rel="stylesheet" href="https://pyscript.net/latest/pyscript.css">
    <script defer src="https://pyscript.net/latest/pyscript.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.5/codemirror.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.5/theme/monokai.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.5/codemirror.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.5/mode/python/python.min.js"></script>
    <style>
        body {
            font-family: Arial, sans-serif;
        }
        #output {
            background-color: #f0f0f0;
            padding: 10px;
            margin-top: 10px;
            border: 1px solid #ccc;
            white-space: pre-wrap;
        }
        .CodeMirror {
            height: auto;
            border: 1px solid #ccc;
        }
    </style>
</head>
<body>
    <h1>Run Python Code in the Browser</h1>

    <!-- Textarea for user to write Python code -->
    <textarea id="pythonCode">print("Hello, PyScript!")</textarea>
    <br>
    <button id="runButton">Run Code</button>
    
    <!-- Div to display the output -->
    <div id="output"></div>

    <py-script>
        from pyodide.ffi import create_proxy
        from js import document, window
        import sys
        import io
        
        def run_code(event):
            # Clear the previous output
            output_div = document.getElementById("output")
            output_div.innerHTML = ''
            
            # Get the user code from the CodeMirror editor
            code = window.editor.getValue()
            
            # Redirect stdout to capture print statements
            old_stdout = sys.stdout
            sys.stdout = io.StringIO()
            
            try:
                # Execute the user code
                exec(code)
                # Get the output from stdout
                result = sys.stdout.getvalue()
                output_div.innerHTML = f"<pre>{result}</pre>"
            except Exception as e:
                output_div.innerHTML = f"<pre>Error: {e}</pre>"
            finally:
                # Reset stdout
                sys.stdout = old_stdout

        # Create a proxy for the run_code function to use as an event handler
        run_code_proxy = create_proxy(run_code)
        
        # Attach the event handler to the button click event
        document.getElementById("runButton").addEventListener("click", run_code_proxy)
    </py-script>
    
    <script>
        // Initialize CodeMirror
        window.editor = CodeMirror.fromTextArea(document.getElementById('pythonCode'), {
            mode: 'python',
            theme: 'monokai',
            lineNumbers: true,
            indentUnit: 4,
            tabSize: 4
        });
    </script>
</body>
</html>
```

**Comment by JeffersGlass** [comment]
It looks like you're linking to an older version of pyscript - Instead of linking to `/latest`, trying linking with `<script type="module" src="/https://pyscript.net/releases/2024.5.2/core.js></script>`

**Comment by AdamFelle** [comment]
> It looks like you're linking to an older version of pyscript - Instead of linking to `/latest`, trying linking with `<script type="module" src="/https://pyscript.net/releases/2024.5.2/core.js></script>`

I will update my post to include that but it still has the same issue.

**Comment by AdamFelle** [comment]
> It looks like you're linking to an older version of pyscript - Instead of linking to `/latest`, trying linking with `<script type="module" src="/https://pyscript.net/releases/2024.5.2/core.js></script>`

I have just tried this and now the program just doesnt work in general saying 'Failed to load resource: the server responded with a status of 404 (Not Found)' in console.

**Comment by AdamFelle** [comment]
Nevermind, that was an issue with the style sheet and I just imported everything correctly.
In the newest version this issue is still there.
`Error: name 'ExampleClass' is not defined`

**Comment by JeffersGlass** [comment]
Digging into this a little bit, I when I try your first section of example code, I do see successful prints:
```html
<link rel="stylesheet" href="https://pyscript.net/releases/2024.5.2/core.css">
<script type="module" src="https://pyscript.net/releases/2024.5.2/core.js"></script>
<script type="py">
    class ExampleClass:
        varia = 1
        def __init__(self, val):
            ExampleClass.varia = val


    print(ExampleClass.__dict__)
    example_object = ExampleClass(2)

    print(ExampleClass.__dict__)
    print(example_object.__dict__)
</script>
```
![image](https://github.com/pyscript/pyscript/assets/1931111/be4b7f5f-67e4-4493-a3f7-66e326c9b5a3)

As for your main issue, you need to pass the current `globals()` dictionary as the `globals` argument to `exec` so that you get access to the objects from the surrounding scope:

```py
#...
try:
    # Execute the user code
    exec(code, globals())
    # Get the output from stdout
    # ...
```

**Comment by JeffersGlass** [comment]
As an aside - this looks like a neat project and I'm curious to watch it as it develops 😁

**Comment by AdamFelle** [comment]
Alright yes that fix works thank you very much! And to the second thing you said it is not much as much of a project as just me testing around with pyscript though I might make a chromium based python IDE with this at some point. Thank you for your help.
