### ISSUE TITLE
Error: TypeError: Can't create an SSLContext object without an ssl module

### ISSUE THREAD

**Issue by cosmosanalytics** [pyscript/pyscript#2081]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

When I ran the pyscript in **https://pyscript.com/@adec3dd4-c366-46d3-9d45-84d3b0996a43/07a0de9f-afd1-4975-a65d-17dfb3bf7b4e/latest** with my OpenAI API key,

the following error shows up

Traceback (most recent call last):
  File "/lib/python3.10/_pyodide/_base.py", line 460, in eval_code
    .run(globals, locals)
  File "/lib/python3.10/_pyodide/_base.py", line 306, in run
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 3, in <module>
  File "/lib/python3.10/site-packages/requests/__init__.py", line 164, in <module>
    from .api import delete, get, head, options, patch, post, put, request
  File "/lib/python3.10/site-packages/requests/api.py", line 11, in <module>
    from . import sessions
  File "/lib/python3.10/site-packages/requests/sessions.py", line 15, in <module>
    from .adapters import HTTPAdapter
  File "/lib/python3.10/site-packages/requests/adapters.py", line 76, in <module>
    _preloaded_ssl_context = create_urllib3_context()
  File "/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 252, in create_urllib3_context
    raise TypeError("Can't create an SSLContext object without an ssl module")
**TypeError: Can't create an SSLContext object without an ssl module**

**Comment by cosmosanalytics** [comment]
same error encounter in the following pyscript
<py-config>
name = "Folium Copy"
description = "A simple application that uses pandas and folium to draw heatmaps on a map."
packages = [ "folium", "pandas",]  
</py-config>  
  
<py-script>
from pyscript import display
import folium
import json
import pandas as pd

from pyodide.http import open_url

url = "https://raw.githubusercontent.com/python-visualization/folium/master/examples/data"
state_geo = f"{url}/us-states.json"
state_unemployment = f"{url}/US_Unemployment_Oct2012.csv"
state_data = pd.read_csv(open_url(state_unemployment))
geo_json = json.loads(open_url(state_geo).read())

m = folium.Map(location=[48, -102], zoom_start=3)

folium.Choropleth(
    geo_data=geo_json,
    name="choropleth",
    data=state_data,
    columns=["State", "Unemployment"],
    key_on="feature.id",
    fill_color="YlGn",
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name="Unemployment Rate (%)",
).add_to(m)

folium.LayerControl().add_to(m)

display(m, target="folium")
  
</py-script> 

Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 499, in eval_code
    .run(globals, locals)
     ^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/_pyodide/_base.py", line 340, in run
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<exec>", line 43, in <module>
  File "/lib/python3.11/site-packages/folium/__init__.py", line 15, in <module>
    from folium.features import (
  File "/lib/python3.11/site-packages/folium/features.py", line 13, in <module>
    import requests
  File "/lib/python3.11/site-packages/requests/__init__.py", line 164, in <module>
    from .api import delete, get, head, options, patch, post, put, request
  File "/lib/python3.11/site-packages/requests/api.py", line 11, in <module>
    from . import sessions
  File "/lib/python3.11/site-packages/requests/sessions.py", line 15, in <module>
    from .adapters import HTTPAdapter
  File "/lib/python3.11/site-packages/requests/adapters.py", line 76, in <module>
    _preloaded_ssl_context = create_urllib3_context()
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 252, in create_urllib3_context
    raise TypeError("Can't create an SSLContext object without an ssl module")
TypeError: Can't create an SSLContext object without an ssl module

**Comment by WebReflection** [comment]
well, this seems to be a `create_urllib3_context` issue, hence upstream ... have you checked Pyodide project around this issue? I think `urllib` is fairly broken in Pyodide or PyScript in general because it's based on synchronous XHR and all its limitations imposed by browsers' vendors ... but if you can find the reason PyScript would fail there, as in: "it's pyScript doing something weird", please share!

**Comment by yk1ng** [comment]
I am having the same issue right now and would like to add something to this, which I hope will help:

The same error occurs when trying any of the demos on https://pyscript.net/examples/ that make use of Panel, i.e.:
- "Simple Panel Demo"
- "Panel Streaming Demo"
- "Panel KMeans Clustering Demo"
- "Panel DeckGL NYC Taxi Demo"

The same error occurs when trying the minimal example for PyScript & Panel on https://panel.holoviz.org/how_to/wasm/standalone.html

Based on the above, I would have reckoned it is some kind of incompatibility between PyScript and Panel, but I cannot see any mention of Panel in the OP's post.

For my own code, I hoped that an update to newest versions would resolve the issue. So I chose Bokeh version 3.4.1 and Panel version 1.4.3, and for PyScript, I would fetch the latest version as I usually do with:

    <link rel="stylesheet" href="https://pyscript.net/latest/pyscript.css" />
    <script defer src="https://pyscript.net/latest/pyscript.js"></script>

With these version, I get a different error as follows:

(PY1001): Unable to install package(s) 'https://cdn.holoviz.org/panel/1.4.3/dist/wheels/bokeh-3.4.1-py3-none-any.whl, https://cdn.holoviz.org/panel/1.4.3/dist/wheels/panel-1.4.3-py3-none-any.whl'. Reason: Can't find a pure Python 3 Wheel for package(s) 'https://cdn.holoviz.org/panel/1.4.3/dist/wheels/bokeh-3.4.1-py3-none-any.whl, https://cdn.holoviz.org/panel/1.4.3/dist/wheels/panel-1.4.3-py3-none-any.whl'.See: https://pyodide.org/en/stable/usage/faq.html#micropip-can-t-find-a-pure-python-wheel for more information.

**Comment by WebReflection** [comment]
> and for PyScript, I would fetch the latest version as I usually do with

@yk1ng we no longer maintain `latest` and these look like an issue with PyScript *classic* which is also deprecated, abandoned. The latest version of PyScript is a whole rewrite and documented in here: https://docs.pyscript.net/latest/

**Comment by WebReflection** [comment]
panel and bokeh got updated and so did our stack so I am closing this until there is a reason to re-open, based on latest version of all involved projects.
