### ISSUE TITLE
Deprecation Warnings

### ISSUE THREAD

**Issue by WebReflection** [pyscript/pyscript#2082]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I see this on a fresh fork:

```
npm warn deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
npm warn deprecated xterm@5.3.0: This package is now deprecated. Move to @xterm/xterm instead.
```

This requires a whole dependencies graph investigation because a lot of deprecation comes from packages that third party bring in out of the blue.

### Additional Context

We should always be able to update our dependencies or we risk to remain behind some major change/fix ... this is a bit of a rabbit hole though, but I'd be happy to investigate more and fix it as long as we're not using deprecated packages all over the place.

**Comment by arnavkejriwal** [comment]
working on this with @riyazrmp

**Comment by WebReflection** [comment]
I believe it's xterm that we need to update but that would require a lot of
manual testing to be sure special things aren't broken and everything else
keeps working, including the plugins we use with the current version.
