### ISSUE TITLE
Error while clearing the terminal from a module

### ISSUE THREAD

**Issue by Bot1-Pzon** [pyscript/pyscript#2096]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

While I was trying to clear a terminal worker from a python module I encountered this unexpected error in the terminal:
```
Traceback (most recent call last):
  File "/lib/python312.zip/_pyodide/_base.py", line 502, in eval_code
    .run(globals, locals)
     ^^^^^^^^^^^^^^^^^^^^
  File "/lib/python312.zip/_pyodide/_base.py", line 340, in run
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<exec>", line 7, in <module>
  File "/home/pyodide/module.py", line 2, in clear
    __terminal__.clear()
    ^^^^^^^^^^^^
NameError: name '__terminal__' is not defined
```
I encountered this error while on [pyscript.com](https://pyscript.com/) working on a [project](https://pyscript.com/@bot-1_pzon/test/latest).

If it can be helpful this are my files and their contents:
(They are all in the project directory)
- index.html
- main.py
- module.py
- pyscript.toml

### index.html
```
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Title</title>

    <!-- Recommended meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">

    <!-- PyScript CSS -->
    <link rel="stylesheet" href="https://pyscript.net/releases/2024.6.1/core.css">

    <!-- This script tag bootstraps PyScript -->
    <script type="module" src="https://pyscript.net/releases/2024.6.1/core.js"></script>
</head>
<body>
    <script type="py" src="./main.py" config="./pyscript.toml" terminal worker></script>
</body>
</html>
```
### main.py
```
import module

print("before")

input("> ")

module.clear()

print("after")
```
### module.py
```
def clear():
    __terminal__.clear()
```
### pyscript.toml
```
[files]
"./module.py" = ""
```

### What browsers are you seeing the problem on? (if applicable)

Chrome

### Console info

```shell
No console errors
```

### Additional Context

Output of the program:

![Immagine 2024-06-11 181801](https://github.com/pyscript/pyscript/assets/161156186/758c2941-a3c3-42a1-aea0-3030b104006c)

**Comment by WebReflection** [comment]
`__terminal__` exists in your code, you need to import it from `pyscript` in any other module like it is for anything Python related, right?

**Comment by WebReflection** [comment]
to clarify ...

```python
def clear():
    from pyscript import __terminal__
    __terminal__.clear()
```

**Comment by Bot1-Pzon** [comment]
@WebReflection I've followed your suggestion by updating my `module.py` to this:
```
def clear():
    from pyscript import __terminal__
    __terminal__.clear()
```
But I got this error this time:
```
Traceback (most recent call last):
  File "/lib/python312.zip/_pyodide/_base.py", line 502, in eval_code
    .run(globals, locals)
     ^^^^^^^^^^^^^^^^^^^^
  File "/lib/python312.zip/_pyodide/_base.py", line 340, in run
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<exec>", line 7, in <module>
  File "/home/pyodide/module.py", line 2, in clear
    from pyscript import __terminal__
ImportError: cannot import name '__terminal__' from 'pyscript' (/home/pyodide/pyscript/__init__.py)
```
I don't want to sound pretentious, waste anyone's time, or hide my inexperience, but from what I understand there is a problem with cleaning the terminal from a module.

**Comment by WebReflection** [comment]
@Bot1-Pzon actually I fooled myself as the `__terminal__` is indeed explicitly available only in the main file, it's not exported whatsoever via *pyscript* module because it cannot be known ahead of time.

We never had the request to use `__terminal__` via modules and I wonder why you need such as use case. It's also a *dunder* reference so it won't leak as main module export but one could decide to expose it explicitly?

```python
import sys
from test import log_terminal

class Module:
    def __getattr__(self, field):
        if field == "terminal":
            return __terminal__

sys.modules["pyscript.terminal"] = Module()

log_terminal()
```

Your `test.py` module:
```python
def log_terminal():
    from pyscript.terminal import terminal
    terminal.clear()

```

Would this work reasonably well? I think we did discuss about `__terminal__` before and it felt right to have it the way we have it know: scoped within the main terminal code and not leaking (indeed!) in the wild accidentally.

**Comment by WebReflection** [comment]
Closing as no follow up ever happened so I assume the proposed solution works.
