### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by NourEldin-Osama** [pyscript/pyscript#210]
My Code:
```
<html>
    <head>
      <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
      <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
      <py-env>
        - numpy
        - matplotlib
      </py-env>
    </head>

  <body>
    <h1>Let's Try py-script</h1>
    <div id="plot"></div>
    <py-script output="plot">
import numpy as np
print(np.random.randint(1,5))
import micropip
micropip.install('seaborn')
try:
    import seaborn
except ImportError:
    print('failed ')
seaborn.color_palette(palette=None, n_colors=2, desat=None, as_cmap=False)
    </py-script><py-repl></py-repl>
  </body>
</html>
```
the output:
![image](https://user-images.githubusercontent.com/58091991/166861164-ff70fb13-1310-4dd4-8e60-b80be882736e.png)

### how can i make the code wait until `micropip.install('seaborn')`  finish execution

**Comment by NourEldin-Osama** [comment]
JsException(PythonError: Traceback (most recent call last): File "/lib/python3.10/site-packages/_pyodide/_base.py", line 429, in eval_code .run(globals, locals) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 300, in run coroutine = eval(self.code, globals, locals) File "", line 9, in NameError: name 'seaborn' is not defined )

**Comment by WanjohiChristopher** [comment]
You can define the packages to install with this code inside the head tag:
<head>
 <py-env>
    
        - seaborn
      </py-env>
    </head>`
`

**Comment by WanjohiChristopher** [comment]
` 
<py-env>
        - numpy
        - matplotlib
        - seaborn
      </py-env>
    </head>`

**Comment by WanjohiChristopher** [comment]
This will install seaborn better.

**Comment by NourEldin-Osama** [comment]
it Worked Thanks
