### ISSUE TITLE
URLSearchParams proxy inconsistent in MicroPython vs Pyodide

### ISSUE THREAD

**Issue by kkinder** [pyscript/pyscript#2100]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

This code printw an empty dict (`{}`) in MicroPython, but a `{'foo': ['bar'], 'spam': ['eggs']}` in Pyodide:

```python
import js

url_search_params = js.URLSearchParams.new("foo=bar&spam=eggs")
print({key: list(url_search_params.getAll(key)) for key in url_search_params.keys()})
```

It appears that in Pyodide, `keys()` works as expected, while in MicroPython, it yields an empty iterable. `keys()` is a [documented part of the API](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams), and should return a list of "foo" and "spam" in this example.

You can see the issue here:

https://pyscript.com/@kkinder/pyscript-urlsearchparams-inconsistency/

Notice that there's a regular version and an mpy version, both pointing to the same 3-line Python script, returning different results.

### What browsers are you seeing the problem on? (if applicable)

Firefox, Chrome, Safari

### Console info

```shell
py-terminal.js:231 py-terminal is read only on main thread
e @ py-terminal.js:231
onReady @ core.js:181
await in onReady (async)
(anonymous) @ custom.js:165
Promise.then (async)
zn @ custom.js:162
await in zn (async)
define @ custom.js:252
(anonymous) @ core.js:294
Promise.then (async)
(anonymous) @ core.js:167
Show 3 more frames
Show less
core.js:228 [pyscript/main] PyScript Ready
```

**Comment by WebReflection** [comment]
This seems like an upstream issue for @dpgeorge but a workaround from our side could be something like:

```python
import js

def iterable(proxy):
    if hasattr(proxy, "next"):
        while True:
            next = proxy.next()
            if next.done:
                break
            yield next.value
    else:
        for value in proxy:
            yield value

url_search_params = js.URLSearchParams.new("foo=bar&spam=eggs")
print({key: list(url_search_params.getAll(key)) for key in iterable(url_search_params.keys())})
```

which works in both Pyodide and MicroPython.

**Comment by dpgeorge** [comment]
I think this is fixed now in MicroPython?

**Comment by WebReflection** [comment]
I think it is indeed, closing as released next!
