### ISSUE TITLE
Discrepancy around Pyodide and MicroPython JS Proxy handling

### ISSUE THREAD

**Issue by WebReflection** [pyscript/pyscript#2106]
After yesterday demo, where I've thought there was an issue in the way MicroPython handles *async*, I eventually investigated what was going on and it turns out that JS Proxy in *MicroPython* should be accessed via `js_proxy["key"]`, otherwise these fails via `js_proxy.key`, but in *Pyodide* it's the other way around: `js_proxy.key` works, while `js_proxy["key"]` throws a `'pyodide.ffi.JsProxy' object is not subscriptable`.

- - -

**[See example code per each interpreter](https://github.com/pyscript/pyscript/issues/2106#issuecomment-2182584646)**

- - -

This is a bit of a bummer because in *JS* there's literally no difference around the two ways to access proxy (or anything else, really) properties but we can't write portable code if we need to expose a proxy via `registerJsModule` API.

/cc @hoodmane @dpgeorge @ntoll around this issue, it's blocking our idea of named workers as there's no way to access `workers[name]` in a way that doesn't break in one interpreter or another ... should we monkey patch all the things or we can actually agree JS proxies should be accessible via both items and attributes like it is for most of the rest of the API?

Thanks in advance for any kind of outcome ... I might wrap one more time this on our side but it really feels weird to reason about.

**Comment by WebReflection** [comment]
## MicroPython failure:

```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <script type="module">
      const base = 'https://cdn.jsdelivr.net/npm/@micropython/micropython-webassembly-pyscript@latest';
      const { loadMicroPython } = await import(`${base}/micropython.mjs`);
      const interpreter = await loadMicroPython({ url: `${base}/micropython.wasm` });
      const { textContent } = document.querySelector('script[type=micropython]');
      interpreter.registerJsModule('js_proxy', {
        test: new Proxy(new Map, {
          get(map, name) {
            if (!map.has(name))
              map.set(name, Math.random());
            return map.get(name);
          }
        })
      });
      interpreter.runPython(textContent);
    </script>
    <script type="micropython">
      from js_proxy import test

      # this works
      print(test["a"])

      # this throws
      # AttributeError: 'JsProxy' object has no attribute 'a'
      print(test.a)
    </script>
  </head>
</html>
```

## Pyodide failure:
```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <script type="module">
      const base = 'https://cdn.jsdelivr.net/npm/pyodide@latest';
      const { loadPyodide } = await import(`${base}/pyodide.mjs`);
      const interpreter = await loadPyodide();
      const { textContent } = document.querySelector('script[type=pyodide]');
      interpreter.registerJsModule('js_proxy', {
        test: new Proxy(new Map, {
          get(map, name) {
            if (!map.has(name))
              map.set(name, Math.random());
            return map.get(name);
          }
        })
      });
      interpreter.runPython(textContent);
    </script>
    <script type="pyodide" async>
      from js_proxy import test

      # this works
      print(test.a)

      # this throws
      # TypeError: 'pyodide.ffi.JsProxy' object is not subscriptable
      print(test["a"])
    </script>
  </head>
</html>
```

If you'd like me to file an issue in each project I'd be happy to, I just want to be sure I am wasting nobody time if doing so.

**Comment by WebReflection** [comment]
If interested, this workaround looks "*good enough*" but it probably won't scale super well in the wild ... although it would scale in our use case:

```python
from js_proxy import test

import js
get = js.Reflect.get
def js_proxy(ref):
    class JSProxy:
        def __getitem__(self, name):
            return get(ref, name)
        def __getattr__(self, name):
            return get(ref, name)
    return JSProxy()

workaround = js_proxy(test)

# these both work
print(workaround["a"])
print(workaround.a)
```

**Comment by dpgeorge** [comment]
I would actually expect both ways to already work in MicroPython.  For example if you have `globasThis.test = {a:1}` then both subscript and attribute access work.

But testing shows that there's a bug in the `test.a` case for when `test` is a `Map`.  We are using `attr in obj` to test for attribute existence, and apparently that's false when `obj` is a `Map` as in the example above.

What test on the JS side should we be doing to check that `a` is in `test` for a `test.a` lookup?

Regarding the workaround: that looks pretty heavy to me, it will definitely have an impact on performance.  Would be best to get it working out-of-the-box with both interpreters.

**Comment by WebReflection** [comment]
@dpgeorge thanks for the quick answer/confirmation there is a bug but this sentence worries me:

> But testing shows that there's a bug in the `test.a` case for when test is a `Map`.

are you folks (asking to @hoodmane too here) *drilling* proxies, as opposite of just sing *Proxy* traps as these are meant to be used in the *JS* world?

Because behind a proxy, nobody can really tell what's inside it, except a few well known caveats around the *Proxy* API itself that side-effect internal drilling of the original proxied source.

I understand you want to know if a proxy is an Array, an *object*, a *function*, or a *primitive*, and you have `typeof` guard that to do so and eventually disambiguate only the *object* case VS `null`, generic object, or *Array* (via `Array.isArray(ref)`) but why do you need any other proxy to deal with anything else at all from the *JS* world?

All proxy traps are reflected on your side and those 4 types (+1 due `null`) are all you need to care about ... what other JS Class get privileged treatment in your code and why is that needed, if I might ask?

**Comment by hoodmane** [comment]
I think the problem is you should add:
```js
if (name === "get") {
     return Reflect.get(... arguments);
}
```
And to fix Damien's `in` check you should add a `has` trap. Seems to me that the ffis are behaving more or less reasonably but you gave a poorly behaved proxy.

**Comment by WebReflection** [comment]
@hoodmane 

> you gave a poorly behaved proxy.

I gave a proxy that works in JS and fails in foreign PLs, to be honest:

```js
const generic = new Proxy(new Map, {
  get(map, name) {
    if (!map.has(name))
      map.set(name, Math.random());
    return map.get(name);
  }
});

// it's true, no failure whatsoever
console.assert(
  generic.test === generic["test"]
);
```

So, the method you are exposing is named `registerJsModule` and nowhere I could find explicit documentation around **how** people should expose *JS* modules ... I gave you a very basic example on how the *ffi* fails at understanding exposed modules, you can blame that on *JS* developers, and I can use a `{}` literal instead of a *Map* (which is just convenient there) but how does this resolves as "*it's JS folks doing it wrong, we're good!*" ???

I was hoping for a bit more of insights around this but I guess we'll need to workaround this breaking expectation on our side, if I read you correctly.

We already did via *Python*, as the *JS* code, from a read-only *Proxy* *JS* perspective, is just fine, but I'll keep in mind *Pyodide* *ffi* doesn't like relaxed *Proxy* from *JS*, I just hope there was a chapter in your docs about it though.

**Comment by hoodmane** [comment]
Well I think your original code is working fine in Pyodide. In Python one doesn't write:
```py
import datetime

datetime["datetime"]
```
That will raise an error. Modules are accessed only through `.` not though `[]`. @dpgeorge the thing that Pyodide does is first look up the string like `jsobj[attr]` and then if this returns `undefined` we check if `attr in jsobj` and if it is true we return `None` whereas if it's false we raise `IndexError`. If you implement this logic, @WebReflection's proxy should work unchanged.

But the proxy really ought to implement a `has` trap imo. It doesn't work correctly in JavaScript because `x[a] !== undefined` ought to imply `a in x`.

**Comment by WebReflection** [comment]
@hoodmane again, this proxy cannot provide a `has` trap ... it's direct access and that's allowed in the JS world.

The proxy creates a `Promise.withResolvers()` if not known and it's resolved at distance via MutationObserver or scripts that create workers with as specific name ... in this scenario is not usable for `for k in workers` loops, it returns as expected always `false` in generic `in` checks, it just does what it's supposed to do from a *JS* world perspective.

You are commenting on Pyodide internals and I am questioning why you need at all to have an `in` check because that also drills into the prototype chaing but it doesn't mean that reference has *not* that property.

This proxy simply intercepts the same way `__getattr__` or `__getitem__` would intercept on the Python side, so why that's OK on Python world, and I've fixed the issue already via that indeed, but not acceptable in the JS one to you?

Again, this worked as workaround:

```python
import js
get = js.Reflect.get
def js_proxy(ref):
    class JSProxy:
        def __getitem__(self, name):
            return get(ref, name)
        def __getattr__(self, name):
            return get(ref, name)
    return JSProxy()

workaround = js_proxy(test)
```

There's no `in` trap needed in there, the thing *just works* and for our purpose wonderfully so.

**Comment by WebReflection** [comment]
If worth anything, an `in` check for `hasOwnProperty` would always return true, with Proxies that don't provide an explicit has trap, but once that `in` check is true, you gotta access `ref.hasOwnProperty` and be assured, that can be **anything or nothing** form a *JS* Proxy world ... the `in` check should be needed only for `in` checks or explicit `hasattr` to me, it's not an excuse to break every other Proxy, I hope this adds something to this discussion.

**Comment by hoodmane** [comment]
Well I think your original code is working fine in Pyodide. In Python one doesn't write:
```py
import datetime

datetime["datetime"]
```
That will raise an error. Modules are accessed only through `.` not though `[]`. @dpgeorge the thing that Pyodide does is first look up the string like `jsobj[attr]` and then if this returns `undefined` we check if `attr in jsobj` and if it is true we return `None` whereas if it's false we raise `IndexError`. If you implement this logic, @WebReflection's proxy should work unchanged.

But the proxy really ought to implement a `has` trap imo. It doesn't work correctly in JavaScript because `x[a] !== undefined` ought to imply `a in x`.

**Comment by hoodmane** [comment]
The in check is needed to distinguish between "key is present, value is undefined" and "key is absent".

**Comment by WebReflection** [comment]
@hoodmane I am not exporting `datetime`, I am exporting `datetime.something` ... `from datetime import something` and that something is any reference in the `datetime` module but I think I've got your mood right here ... thanks for chiming in, I was hoping for a better exchange. Enjoy your weekend.

> Wouldn't the hasOwnProperty trap just return map.has(prop)? Seems simple enough to me.

That's not the point ... that's why `in` checks are useless and you need to directly access the property before deciding it's there or not. I know JS Proxy specifications upside down and I am trying to make sense of this part but if not all of us are interested it's OK, we can workaround findings, it's just not extremely pleasant to have these useless exchanges as nothing changes the status quo which is broken.

A proxy can be any object literal property too, the "*it's a module, nobody does this*" is a bit of a missing point around what is the issue here, and why it matters for us or our users.

If somebody loops over the current dom with workers with a name attribute, they need eventually to access our `workers[name]` dynamically ... and then again, we can circumvent all Pyodide issues around that topic, but you just saying it's our fault won't play well with the rest of the *npm* modules able to land in PyScript.

**Comment by WebReflection** [comment]
Side note: I am really sad to feel a bit of "back-off" here but I've contributed to TC39 for ages and some of the Ecmascript standards landed thanks to my contribution and Proxy is likely the thing I know the most out of specs. If my attempt to hint "*something ain't right here*" disturbed you, I am really sorry about that, and I put that on me and my wordings, but I hope one day you'll read again **what** is the issue here and why your solution is currently as broken as the MicroPython one: both are **assuming** instead of "*passing through*" when it comes to foreign JS proxies.

You'll read about this issue again in the future, I am sure about it, just remember, please, I meant to help here 👋

**Comment by hoodmane** [comment]
Well I'm happy to change any behavior of Pyodide if it's wrong. I'm just not understanding what we're doing wrong here -- I think on a module access should work via `module.attribute` and not via `module["attribute"]` so I think your object is already behaving in the correct way in Pyodide. But maybe I am misunderstanding somehow.

**Comment by WebReflection** [comment]
@hoodmane ... does this move your focus? it fails exactly the same way!

```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <script type="module">
      const base = 'https://cdn.jsdelivr.net/npm/pyodide@latest';
      const { loadPyodide } = await import(`${base}/pyodide.mjs`);
      const interpreter = await loadPyodide();
      const { textContent } = document.querySelector('script[type=pyodide]');
      interpreter.registerJsModule('js_proxy', {
        test() {
            return new Proxy(new Map, {
                get(map, name) {
                    if (!map.has(name))
                        map.set(name, Math.random());
                    return map.get(name);
                }
            });
        }
      });
      interpreter.runPython(textContent);
    </script>
    <script type="pyodide" async>
      from js_proxy import test

      proxy = test()

      # this works
      print(proxy.a)

      # this throws
      # TypeError: 'pyodide.ffi.JsProxy' object is not subscriptable
      print(proxy["a"])
    </script>
  </head>
</html>
```

**Comment by WebReflection** [comment]
if missed in email, I'll write again the explicit goal of that code, as I've edited it after the code:

I want to create a new random number once per each property accessed to that proxy (real-world use case: a unique ID, a node to access, a random thing to show to users ... and so on ...)

**Comment by hoodmane** [comment]
Yeah this is the expected behavior. `__getitem__` and `__getattr__` are different operations in Python, it's not expected that they would behave the same. In particular, `__getitem__` is generally only implemented on containers. If you want to be able to subscript the proxy too you need to do:
```js
new Proxy(new Map, {
    get(map, name) {
        function lookup(name) {
            if (!map.has(name))
                map.set(name, Math.random());
            return map.get(name);
        }
        if (name === "get") {
            return lookup;
        }
        return lookup(name);
    }
})
```

**Comment by WebReflection** [comment]
I am not sure we are in sync, but that code simply keeps assuming my Proxy is a *Map* so that `get` is accessed ... in my *JS* code, `get` is used nowhere ... how would you reason about that workaround? I also get, in order:

  * `then` (nowhere asked for)
  * `constructor` (nowhere needed in my proxy)
  * `then` (again?)
  * `next` (generator sniffing?)
  * `next` (generator again?)
  * `get` ... finally ... I've just created 5 random numbers to get here!
  * `set` ... on an read-accessor?
  * `has` ... hello there, why on my Proxy get are you asking if I has something?
  * `includes` (an array brand check?)
  * `a` ... oh, look, the thing I was just aboud to ask for

Can you see the Proxy or brand check by accessing properties in Pyodide is a tad broken?

**Comment by WebReflection** [comment]
once again, to understand the *kind* of JS instance you start with `typeof` then you can go with `instanceof` operator ... that one I might reason about more than randomly accessing properties out of a foreign reference, imho. Still, the `get` procy trap would fail even the `getPrototype` trap once executed. Why is any of this needed at all?

**Comment by hoodmane** [comment]
All those checks occur here:
https://github.com/pyodide/pyodide/blob/main/src/core/jsproxy.c#L4056-L4118

I think `instanceof` is totally broken and I basically never use it. The problem is that if you transfer an object across realms, it won't be an `instanceof` the constructor in the new realm, only the original constructor in the original realm. And `typeof` just returns `object` for everything. We use `Object.prototype.toString.call()` for most brand checking and `obj.constructor.name` for some other stuff.

**Comment by WebReflection** [comment]
> Why is any of this needed at all?

to clarify, @hoodmane, your `in` suggestion fails short in implementation details.

If I check for `in` I don't get the `get` trap to work:

```js
'test' in new Proxy({}, {
  has: (_, name) => (console.log('has', name), false),
  get: (_, name) => (console.log('get', name), void 0)
});

// has test
// false
```

So all those `then` and `next` should be behind an `in` operation ... but it looks like you know that `in` might fail, so you go deeper on that `get` trap "*to be sure*" it's not really there, or unless you are not using `in` in there, you just scream for troubles when proxies are around.

The `constructor` has never been meaningful neither, an `insntanceof` would do a better job, but I am not sure what you are checking that constructor for.

For both typed arrays and generators you still have `instanceof` operator:

```js
// true
new Float32Array(0) instanceof Uint8Array.__proto__

// true
const GeneratorFunction = (function* test() {}).constructor;
(function* test() {}) instanceof GeneratorFunction;
```

the `Array.isArray` check won't trigger any *Proxy* trap and just drill to its value, same as `typeof p === "function"` does, without needing to access any `get` trap.

I don't know if I am stating the obvious here and there are deeper reasons to access all that things, but proxies these days in *JS* are fairly common, and irrelevant `get` traps check can be pretty side-effecting (our case) or dangerous.

**Comment by WebReflection** [comment]
> if you transfer an object across realms, it won't be an instanceof the constructor in the new realm

I am not doing that and yet I can do that without messing with proxies, *coincident* does all of that without bothering proxies in general.

> We use Object.prototype.toString.call() for most brand checking and obj.constructor.name for some other stuff.

that's your choice and I've asked already: why is that needed? there are only 4 kinds in JS + 1, object, array, function (relevant for drilling), and primitives ... the only exception, easy to rule out, is `null`, everything else will work with just those 3 kind of proxies ... nothing else is needed:

  * nothing is needed to deal with Promises
  * nothing is needed to deal with typed array (but that'd be the only immutable exception, like `null`, to me)
  * nothing is needed to deal with anything else coming from the JS world ... so what are all these checks about?
  * you can disambiguate both typed arrays and generators as suggested already, if that matters (I guess it does), still nothing needs a greedy `get` trap invocation, and the `in` check you suggested still doesn't hold your claim as I can trace all your *not `in` based* checks in your side of affair

Can you all live with that? Sure ... should you be aware you are overly-doing things that don't play well with modern JS libraries? I hope so.

That's it for me today, I hope you can think about this thread and maybe propose better approaches.

P.S. the `instanceof` is a better check than `.property`, if brand matters, and `Symbol.isInstance` is a way less used primitive than trashing any property to an object literal 👋

**Comment by hoodmane** [comment]
Well a PR is welcome if you have improvements for our feature detection logic. I'm sure there is a lot that can be improved since none of us are JavaScript experts.

**Comment by dpgeorge** [comment]
I have made a PR for MicroPython to allow `obj.attr` lookup to work the same as `obj["attr"]`.  See here: https://github.com/micropython/micropython/pull/15337

With that change, MicroPython will match Pyodide with how an attribute is retrieved (if the value is `undefined` then use `attr in obj` to see if undefined is really the value of the attribute, or if the attribute doesn't exist).

For MicroPython this change is pretty clear cut as a good improvement to make because:
1. It's hard to argue against the fact that if `obj.attr` works on the JS side then `obj.attr` should also work on the Python side when that object is proxied.
2. MicroPython now matches Pyodide in this respect.

**Comment by WebReflection** [comment]
@dpgeorge if I understood correctly that change breaks current working code for us ... ideally we want to handle proxies of generic values as dictionaries, as that's the most common case in Python. On top of that, we need a dynamic way to actually access `workers[by_name]` so ... if that works too, we're good and we need the Python proxy of the JS proxy only on Pyodide side of affairs, if now MicroPython breaks that instead, it will break likely also our attempt to provide a storage where we also use a key/value pair out of a proxy that, behind the scene, uses IndexedDB.

Am I understanding that change right? 'cause I'd rather have Pyodide follow MicroPython instead, not vice-versa here ...

**Comment by WebReflection** [comment]
@dpgeorge never mind, if you migrate current behavior with `["key"]` to `.key` it's all good, and **expected** in the JS world, as long as that doesn't randomly access all possible things out of the blue for no reason when a user just typed `ref.key`, thanks!

Commented in there too: https://github.com/micropython/micropython/pull/15337#issuecomment-2186432775

**Comment by dpgeorge** [comment]
> if you migrate current behavior with `["key"]` to `.key` it's all good, and **expected** in the JS world,

Yes, both `.key` and `["key"]` will work now, in the same way.



> as long as that doesn't randomly access all possible things out of the blue for no reason when a user just typed `ref.key`

It won't!

**Comment by WebReflection** [comment]
@hoodmane I would love to file an issue, but I need to understand everything you are doing there to do so in a meaningful way ... so far, I just focused on that chunk you pointed at and added some comment around that specific code, not much else except some utility around:

```js
// your hasMethod should be changed to something like:
function hasMethod(obj, prop) {
  try {
    // 'cause you shouldn't access random things on references ...
    // in Python these would all be throwned errors, I am not sure
    // why this is considered OK in JS ... hasattr() && getattr()
    // are a way better guard / unobtrusive way to do this
    // so if the first fails, you don't get to bother with the second
    // at all! You could also put hasProperty(obj, prop) in between
    // and that would also not touch the accessor, if any (or get trap)
    // but then again, you eventually want to access this for some reason
    return prop in obj && typeof obj[prop] === "function";
  } catch (e) {
    return false;
  }
}

const typeTag = getTypeTag(obj);

function safeBool(cb) {
  try {
    return cb();
  } catch(e) {
    return false;
  }
}

// you need this check once and reuse it as much as possible
// a function is a function ... it already tells you a lot!
const isFunction = typeof obj === "function";

// for instance ...
const isBufferView = !isFunction && safeBool(() => ArrayBuffer.isView(obj));
const isArray = !isFunction && safeBool(() => Array.isArray(obj));

// If we somehow set more than one of IS_CALLABLE, IS_BUFFER, and IS_ERROR,
// we'll run into trouble. I think that for this to happen, someone would have
// to pass in some weird and maliciously constructed object. Anyways for
// maximum safety, we double check that only one of these is set.
if (isFunction) {
  SET_FLAG_IF(IS_CALLABLE, isFunction);
}
else {
  SET_FLAG_IF_HAS_METHOD(IS_AWAITABLE, "then");
  SET_FLAG_IF_HAS_METHOD(IS_ITERABLE, Symbol.iterator);
  SET_FLAG_IF_HAS_METHOD(IS_ASYNC_ITERABLE, Symbol.asyncIterator);

  // the following is likely a bug: if `next` is there, you are checking *WHATEVER* ...
  // using `next()` does not make an object an iterator, it's just an object.
  // any object with a `next` method would pass this check if it doesn't have neither special Symbol cases
  // wut = {next(){}} to you is an iterator returned value ... is that correct?
  // 'cause wut[Symbol.iterator] is false, but also !wut[Symbol.asyncIterator] is ... true at the end,
  // and vice-versa for async generators!
  // so why isn;t this a typeTag === "[object Array Iterator]" instead?
  // or any typeTag that ends with ` Iterator]`?
  SET_FLAG_IF(IS_ITERATOR, hasMethod(obj, "next") && (hasMethod(obj, Symbol.iterator) || !hasMethod(obj, Symbol.asyncIterator)));
  SET_FLAG_IF(IS_ASYNC_ITERATOR, hasMethod(obj, "next") && (!hasMethod(obj, Symbol.iterator) || hasMethod(obj, Symbol.asyncIterator)));
  // it's simple here as you pass through getOwnProperty descriptor
  // however ... your hasProperty should also likely check the descriptor `value`
  // is *not* a function if this is used to disambiguate arrays or Map/Set like references
  // if it's a `get` it's also OK, as long as `value` is not a function.
  SET_FLAG_IF(HAS_LENGTH, hasProperty(obj, "size") || hasProperty(obj, "length"));
  // this one fails with XHR instances ... I have no idea what this `get` means to Pyodide
  // this will fail also with latest Symbol proposal with both get and set
  // ... honestly, what are these all about?
  SET_FLAG_IF_HAS_METHOD(HAS_GET, "get");
  SET_FLAG_IF_HAS_METHOD(HAS_SET, "set");
  SET_FLAG_IF_HAS_METHOD(HAS_HAS, "has");
  // similarly ... what does this mean? why all these flags?
  SET_FLAG_IF_HAS_METHOD(HAS_INCLUDES, "includes");
  SET_FLAG_IF(IS_BUFFER,
              (isBufferView || (typeTag === '[object ArrayBuffer]')) && !(type_flags & IS_CALLABLE));
  SET_FLAG_IF(IS_DOUBLE_PROXY, API.isPyProxy(obj));
  // why so many previous checks before deciding it's an Array? what [].get or [].set are supposed to do?
  SET_FLAG_IF(IS_ARRAY, isArray);
  SET_FLAG_IF(IS_NODE_LIST,
              typeTag === "[object HTMLCollection]" ||
              typeTag === "[object NodeList]");
  SET_FLAG_IF(IS_TYPEDARRAY,
              isBufferView && typeTag !== '[object DataView]');
  SET_FLAG_IF(IS_GENERATOR, typeTag === "[object Generator]");
  SET_FLAG_IF(IS_ASYNC_GENERATOR, typeTag === "[object AsyncGenerator]");

  /**
    * DOMException is a weird special case. According to WHATWG, there are two
    * types of Exception objects, simple exceptions and DOMExceptions. The spec
    * says:
    *
    * > if an implementation gives native Error objects special powers or
    * > nonstandard properties (such as a stack property), it should also expose
    * > those on DOMException objects
    *
    * Firefox respects this and has DOMException.stack. But Safari and Chrome do
    * not. Hence the special check here for DOMException.
    */
  SET_FLAG_IF(IS_ERROR,
    (
      hasProperty(obj, "name")
      && hasProperty(obj, "message")
      && (
        hasProperty(obj, "stack")
        || obj instanceof DOMException
      )
    ) && !(type_flags & (IS_CALLABLE | IS_BUFFER)));
}
```

I don't know if any of these added comments make sense to you or are worth reporting upstream, but if there's something that's trivial/obvious to you to, in terms of possible improvements, please let me know.

On a second thought, I've realized you use so may flags so you can't branch out that logic via if/else but then again, you are overly checking things that, once a previous check happened, would rarely give you any different result (see arrays or function as type) ... I would use a guard there, or more than one if needed, as `let` variable and just pass that without needing all that dance for every single reference that comes from JS ... it doesn't look fast to me neither, especially the while loop on prototypal chain used in `hasProperty` ... so many checks that feel a bit too much to me, but then again, I am sure there were other reasons previously discussed to need all of them, I don't have enough context to contribute meaningfully in that particular piece of logic.

**Comment by WebReflection** [comment]
to whom it might concern, I am going to talk about this in today community call because I would like everyone involved with this project to be aligned about the issue in here. The channel is https://discord.com/channels/972017612454232116/972017612454232119 and we'll start in ~1 hour, 10:30 CET time.

**Comment by WebReflection** [comment]
@hoodmane and (less relevant right now) @dpgeorge if you have 30 minutes to kill, please watch this community call from 30:32 (the link should start from there), even at double speed, and realize why this issue matters and why any further development of Python <-> JS interaction should consider the exposed issue which is **not just about proxies**, it's a general issue when it comes to either introspection or code used to brand-check any JS reference, including literal objects: https://youtu.be/uS85eB4ff3U?feature=shared&t=1823

**Comment by dpgeorge** [comment]
> if you have 30 minutes to kill, please watch this community call from 30:32 (the link should start from there), even at double speed, and realize why this issue matters and why any further development of Python <-> JS interaction should consider the exposed issue which is **not just about proxies**, it's a general issue when it comes to either introspection or code used to brand-check any JS reference, including literal objects

@WebReflection @ntoll I watched the video (from 30 mins onward).  I don't know much about JS so this was interesting for me to understand more about JS Proxy and introspection.  Thank you!

I'm glad that MicroPython is doing something sensible in regards to introspection.  And I'm now even more convinced that https://github.com/micropython/micropython/pull/15337 is the right thing to do (ie just access the attribute when requested instead of first checking its existence using `in`).
