### ISSUE TITLE
removeEventListener does not work as expected in MicroPython

### ISSUE THREAD

**Issue by kkinder** [pyscript/pyscript#2108]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I've created a demo of the issue here:

https://kkinder.pyscriptapps.com/bug-event-listeners-do-not-unregister/

When you create an event handler, then remove it, it does not actually remove:

```python

def e(event=None):
    print("Value is", js.document.querySelector("#my-text").value)

def start_observing(event=None):
    print('Starting observer...')
    js.document.querySelector("#my-text").addEventListener("input", e)
    
def stop_observing(event=None):
    print('Stopping')
    ###### THIS DOES NOTHING 👇 #######
    js.document.querySelector("#my-text").removeEventListener("input", e)
```

I suspect that whatever proxy is being created, it isn't the same as the one that was added.

### Console info

```shell
N/A
```

**Comment by WebReflection** [comment]
> I suspect that whatever proxy is being created, it isn't the same as the one that was added.

I've mentioned this to @dpgeorge in the past and he told me that was OK but clearly when identity matters, like in this case, we might have an issue.

**However** an easy workaround that we might as well document for the time being is to explicitly create a proxy and just pass that one instead, so that this works to me:

```python
from pyscript import document
from pyscript.ffi import create_proxy

def handler(event=None):
    print("Value is", document.querySelector("#my-text").value)

e = create_proxy(handler)

def start_observing(event=None):
    print('Starting observer...')
    document.querySelector("#my-text").addEventListener("input", e)
    
def stop_observing(event=None):
    print('Stopping')
    document.querySelector("#my-text").removeEventListener("input", e)

document.querySelector("#start").addEventListener("click", start_observing)
document.querySelector("#stop").addEventListener("click", stop_observing)
```

**Comment by dpgeorge** [comment]
Hmm, I see now why it's important to have identity work correctly across the JS-Python boundary.

It is possible to fix this on the MicroPython side, so that `PyProxy` objects are reused if they are the same object.  Would that be helpful?

**Comment by WebReflection** [comment]
> Would that be helpful?

IIRC that's how Pyodide does it too and since you have a FinalizationRegistry in place, that's easier on that regard as there will be less GC pressure due too many proxies created each time (loops or whatnot).

**Comment by ntoll** [comment]
> Would that be helpful?

Yes. :smile:

**Comment by WebReflection** [comment]
@dpgeorge if worth adding anything at all, in JS the usage of `WeakMap` is also quite common and having always new keys and no way to relate some Python thing to a JS thing can be troublesome and create a lot of extra "*init*" like calls for always same memory address behind the scene. Same with `Set` or any other API that can handle, or relate, identities in the code.

**Comment by dpgeorge** [comment]
See a fix for this here: https://github.com/micropython/micropython/pull/15349

**Comment by WebReflection** [comment]
@dpgeorge thanks, I've left a comment that, once addressed, would make that MR good to land to me.

**Comment by WebReflection** [comment]
the latest *npm* module should've solved this ... please try with `https://cdn.jsdelivr.net/npm/@pyscript/core@0.4.56/dist/core.js` as `script` module source, thanks.

**Comment by WebReflection** [comment]
you can check/confirm this in here: https://pyscript.com/@agiammarchi/bug-event-listeners-do-not-unregister-copy-copy/latest

I am closing this as it will be resolved within the next release. Until then, feel free to use our non official *npm* channel if blocked, otherwise wait for 2024.7.2
