### ISSUE TITLE
How to fix the following error when using briefcase run web

### ISSUE THREAD

**Issue by phamquymuoi** [pyscript/pyscript#2125]
I run the command "briefcase run web" in window and got the following error:

(PY1001): Unable to install package(s) '/static/wheels/absl_py-2.1.0-py3-none-any.whl, /static/wheels/astunparse-1.6.3-py2.py3-none-any.whl, /static/wheels/certifi-2024.7.4-py3-none-any.whl, /static/wheels/charset_normalizer-3.3.2-cp39-cp39-win_amd64.whl, /static/wheels/contourpy-1.2.1-cp39-cp39-win_amd64.whl, /static/wheels/cycler-0.12.1-py3-none-any.whl, /static/wheels/et_xmlfile-1.1.0-py3-none-any.whl, /static/wheels/flatbuffers-24.3.25-py2.py3-none-any.whl, /static/wheels/fonttools-4.53.1-cp39-cp39-win_amd64.whl, /static/wheels/gast-0.6.0-py3-none-any.whl, /static/wheels/google_pasta-0.2.0-py3-none-any.whl, /static/wheels/grpcio-1.65.1-cp39-cp39-win_amd64.whl, /static/wheels/h5py-3.11.0-cp39-cp39-win_amd64.whl, /static/wheels/idna-3.7-py3-none-any.whl, /static/wheels/importlib_metadata-8.0.0-py3-none-any.whl, /static/wheels/importlib_resources-6.4.0-py3-none-any.whl, /static/wheels/keras-3.4.1-py3-none-any.whl, /static/wheels/kiwisolver-1.4.5-cp39-cp39-win_amd64.whl, /static/wheels/libclang-18.1.1-py2.py3-none-win_amd64.whl, /static/wheels/Markdown-3.6-py3-none-any.whl, /static/wheels/markdown_it_py-3.0.0-py3-none-any.whl, /static/wheels/MarkupSafe-2.1.5-cp39-cp39-win_amd64.whl, /static/wheels/matplotlib-3.9.1-cp39-cp39-win_amd64.whl, /static/wheels/mdurl-0.1.2-py3-none-any.whl, /static/wheels/ml_dtypes-0.4.0-cp39-cp39-win_amd64.whl, /static/wheels/namex-0.0.8-py3-none-any.whl, /static/wheels/numpy-1.26.4-cp39-cp39-win_amd64.whl, /static/wheels/openpyxl-3.1.5-py2.py3-none-any.whl, /static/wheels/opt_einsum-3.3.0-py3-none-any.whl, /static/wheels/optree-0.12.1-cp39-cp39-win_amd64.whl, /static/wheels/packaging-24.1-py3-none-any.whl, /static/wheels/pandas-2.2.2-cp39-cp39-win_amd64.whl, /static/wheels/pillow-10.4.0-cp39-cp39-win_amd64.whl, /static/wheels/pm25prediction-0.0.1-py3-none-any.whl, /static/wheels/protobuf-4.25.3-cp39-cp39-win_amd64.whl, /static/wheels/pygments-2.18.0-py3-none-any.whl, /static/wheels/pyparsing-3.1.2-py3-none-any.whl, /static/wheels/python_dateutil-2.9.0.post0-py2.py3-none-any.whl, /static/wheels/pytz-2024.1-py2.py3-none-any.whl, /static/wheels/requests-2.32.3-py3-none-any.whl, /static/wheels/rich-13.7.1-py3-none-any.whl, /static/wheels/scipy-1.13.1-cp39-cp39-win_amd64.whl, /static/wheels/setuptools-71.0.4-py3-none-any.whl, /static/wheels/six-1.16.0-py2.py3-none-any.whl, /static/wheels/tensorboard-2.17.0-py3-none-any.whl, /static/wheels/tensorboard_data_server-0.7.2-py3-none-any.whl, /static/wheels/tensorflow-2.17.0-cp39-cp39-win_amd64.whl, /static/wheels/tensorflow_intel-2.17.0-cp39-cp39-win_amd64.whl, /static/wheels/tensorflow_io_gcs_filesystem-0.31.0-cp39-cp39-win_amd64.whl, /static/wheels/termcolor-2.4.0-py3-none-any.whl, /static/wheels/toga_core-0.4.5-py3-none-any.whl, /static/wheels/toga_web-0.4.5-py3-none-any.whl, /static/wheels/travertino-0.3.0-py3-none-any.whl, /static/wheels/typing_extensions-4.12.2-py3-none-any.whl, /static/wheels/tzdata-2024.1-py2.py3-none-any.whl, /static/wheels/urllib3-2.2.2-py3-none-any.whl, /static/wheels/werkzeug-3.0.3-py3-none-any.whl, /static/wheels/wheel-0.43.0-py3-none-any.whl, /static/wheels/wrapt-1.16.0-cp39-cp39-win_amd64.whl, /static/wheels/zipp-3.19.2-py3-none-any.whl'. Reason: Traceback (most recent call last): File "/lib/python3.11/site-packages/micropip/_micropip.py", line 576, in install await transaction.gather_requirements(requirements) File "/lib/python3.11/site-packages/micropip/_micropip.py", line 342, in gather_requirements await gather(*requirement_promises) File "/lib/python3.11/site-packages/micropip/_micropip.py", line 353, in add_requirement wheel.check_compatible() File "/lib/python3.11/site-packages/micropip/_micropip.py", line 118, in check_compatible raise ValueError( ValueError: Wheel platform 'win_amd64' is not compatible with Pyodide's platform 'emscripten-3.1.32-wasm32' . 

Please help me fix this error. Many thanks!

**Comment by WebReflection** [comment]
> I run the command "briefcase run web"

may I ask where such command is mentioned in any of our documentation?

**Comment by phamquymuoi** [comment]
> > I run the command "briefcase run web"
> 
> may I ask where such command is mentioned in any of our documentation?

I run the command in beeware. Following the template of Helloworld, I change the code. It is run well when I use the command briefcase run, but for briefcase run web, it give me the above error.

**Comment by phamquymuoi** [comment]
(beeware-venv) E:\beeware\pm25prediction>briefcase run web

[pm25prediction] Starting web server...
Web server open on http://127.0.0.1:8080

[pm25prediction] Web server log output (type CTRL-C to stop log)...
===========================================================================
127.0.0.1 - - [22/Jul/2024 09:53:07] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:07] "GET /static/css/briefcase.css HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:07] "GET /pyscript.toml HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/absl_py-2.1.0-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/anyio-4.4.0-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/astunparse-1.6.3-py2.py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/certifi-2024.7.4-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/et_xmlfile-1.1.0-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/cycler-0.12.1-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/flatbuffers-24.3.25-py2.py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/exceptiongroup-1.2.2-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/google_pasta-0.2.0-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/gast-0.6.0-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/h11-0.14.0-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/httpcore-1.0.5-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/httpx-0.27.0-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/idna-3.7-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/importlib_metadata-8.0.0-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/importlib_resources-6.4.0-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/keras-3.4.1-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/Markdown-3.6-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/markdown_it_py-3.0.0-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/mdurl-0.1.2-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/namex-0.0.8-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/openpyxl-3.1.5-py2.py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/packaging-24.1-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/opt_einsum-3.3.0-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/pm25prediction-0.0.1-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/pygments-2.18.0-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/pyparsing-3.1.2-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/python_dateutil-2.9.0.post0-py2.py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/pytz-2024.1-py2.py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/requests-2.32.3-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/rich-13.7.1-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/setuptools-71.1.0-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/six-1.16.0-py2.py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/sniffio-1.3.1-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/tensorboard-2.17.0-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/tensorboard_data_server-0.7.2-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/termcolor-2.4.0-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/toga_core-0.4.5-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/toga_web-0.4.5-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/travertino-0.3.0-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/tzdata-2024.1-py2.py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/typing_extensions-4.12.2-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/urllib3-2.2.2-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/werkzeug-3.0.3-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/zipp-3.19.2-py3-none-any.whl HTTP/1.1" 200 -
127.0.0.1 - - [22/Jul/2024 09:53:11] "GET /static/wheels/wheel-0.43.0-py3-none-any.whl HTTP/1.1" 200 -

**Comment by WebReflection** [comment]
I don't think this has anything to do with PyScript to be honest but, most importantly, I don't see any PyScript code.

This feels like a Pyodide and micropip related issue, I don't know how to help as I don't understand or know your stack there.
