### ISSUE TITLE
Specified version of interpreter doesn't work when running in a worker.

### ISSUE THREAD

**Issue by ntoll** [pyscript/pyscript#2145]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

Taken from a [report on discord](https://discord.com/channels/972017612454232116/1037015991416258602/1272978560872747090):

> The specified interpreter version is not used when i add the worker attribute. I am trying to pin an older version of pyodide and when used with the worker attribute it always loads 0.26.2, but as soon as i remove the worker attribute, it loads the pyodide version i want.
>
> https://pyscript.com/@sai1494/pyodide-version/
>
> This example as 2 script tags, one with worker attribute and one without. Both are pinned to 0.23.4. One of them is commented. swap them to test with and without worker attribute. The python code will display the pyodide version loaded.
>
>Searched if there is an existing bug report, but did not find any.

### Console info

```shell
None.
```

### Additional Context

Example of the issue here: https://pyscript.com/@sai1494/pyodide-version/
Latest version of PyScript (as of time of writing): 2024.8.2

**Comment by WebReflection** [comment]
@ntoll FYI this is fixed in latest PyScript already.
