### ISSUE TITLE
example code in user documentation for pyscript WebSocket fails with pyodide

### ISSUE THREAD

**Issue by gitozi** [pyscript/pyscript#2146]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

The example code for WebSocket given in the pyscript user documentation works without problems under micropython but gives an error with pyodide.

### What browsers are you seeing the problem on? (if applicable)

Chrome

### Console info

```shell
Traceback (most recent call last):
  File "/lib/python312.zip/_pyodide/_base.py", line 596, in eval_code_async
    await CodeRunner(
  File "/lib/python312.zip/_pyodide/_base.py", line 410, in run_async
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<exec>", line 17, in <module>
  File "/home/pyodide/pyscript/websocket.py", line 50, in __setattr__
    self._ws[attr] = value
    ~~~~~~~~^^^^^^
TypeError: 'pyodide.ffi.JsProxy' object does not support item assignment
```

### Additional Context

Using pyscript 2024.8.2

**Comment by WebReflection** [comment]
@gitozi you can try `https://cdn.jsdelivr.net/npm/@pyscript/core@0.5.6/dist/core.js` and see it working now.
