### ISSUE TITLE
How to get/edit a html tag with pyscript?

### ISSUE THREAD

**Issue by craii** [pyscript/pyscript#223]
[How to get/edit a html tag with pyscript?](https://community.anaconda.cloud/t/how-to-get-edit-a-html-tag-with-pyscript/20698/2)

**Comment by Rinshin-Jalal** [comment]
```python
task_list = Element("list-tasks-container")
```
this is from one of the examples

Here we can see We can get an element with an id using `Element`

```python
task_template = Element("task-template").select('.task', from_content=True)
task_list = Element("list-tasks-container")
```
And here we can see they are using `select` as querySelector

And you can get Tag's properties like classList and onClick like this👇‍

```python
element.element.onclick = func
element.element.classList
```

**Comment by Leonardo-teodoro** [comment]
Can we get the value of a field? 
E.g.: In a form with a text field labeled as "name", is it possible to use the value of that input inside the python script?
I want to use a prediction model in python that uses those inputs as parameters to predict a given class.

**Comment by Rinshin-Jalal** [comment]
> Can we get the value of a field? E.g.: In a form with a text field labeled as "name", is it possible to use the value of that input inside the python script? I want to use a prediction model in python that uses those inputs as parameters to predict a given class.

yes it is possible

```python
Element("id-here..").element.value
```

**Comment by amrrs** [comment]
@Rinshin-Jalal Did you try the `element.value` ? For me until element it works fine. but `value` is not found

**Comment by Rinshin-Jalal** [comment]
> @Rinshin-Jalal Did you try the `element.value` ? For me, until element, it works fine. but `value` is not fo
Yes it worked for me...
Can you share your code

**Comment by amrrs** [comment]
Actually it worked later I must have done something wrong. Sorry for the confusion!
