### ISSUE TITLE
documentation 10.2 duplication (workers)

### ISSUE THREAD

**Issue by Neon22** [pyscript/pyscript#2236]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

Duplication of information about Workers in 10.2 docs

### Additional Context

Under `Web Workers` in the `User guide` section there is some doc about Workers and a quiet link to the `Built-in APIs` section.
This `Web Workers` section is where this docs has 'traditionally' been found.

Now in `Built-in APIs` we see a lot more info, some duplicated from `Web Workers`, including new info e.g. about the `Donkey`.

My request is to move all the info with examples to one place. Manually comparing the different code in the two places to try to work out how it works and is the code fragment new or different in some way is difficult.

**Comment by WebReflection** [comment]
any particular reason this is not a bug for https://github.com/pyscript/docs ?

**Comment by Neon22** [comment]
sorry forgot it was a sep project... moving it
