### ISSUE TITLE
Need ability to be able to unzip multiple assets into the same directory.

### ISSUE THREAD

**Issue by ntoll** [pyscript/pyscript#2240]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I want to be able to unzip several zip files into the `~/.` directory. This is currently not allowed.

**Comment by WebReflection** [comment]
any basic example I could work on to enable that and test why it's not working as expected? We don't control the unzip library but last time I've checked it was working already with sub directories, so an example maybe might reveal a situation where either the 3rd party library is broken or we are, thanks

**Comment by ntoll** [comment]
Apologies, this was created from a comment made by our Anaconda colleague @mhsmith, who wasn't able to unzip two zip files into the single `~/.` directory via the `files` functionality in the config file.

Malcolm, can you supply the example you showed me on our video call? Thank you!

**Comment by WebReflection** [comment]
To clarify, I am not sure we support `~/` as directory qualifier at all ... hence my question/wonder around the original minimal example that would show the issue ... we have integration tests around unzipping, so I want to be sure we'll cover extra things too but right now those tests already cover sub-folders, hence my quest for an example to reproduce it.

`~/` in current Virtual FileSystem might not mean anything, and *maybe* that was the issue?

**Comment by mhsmith** [comment]
It wasn't `~/.`, it was `./*`. I had two ZIP files containing Python code which I wanted to make available for import. The documentation says:

> If the source part of the configuration is either a .zip or .tar.gz file and its destination is a folder path followed by a star (e.g. /* or ./dest/*), then PyScript will extract the referenced archive automatically into the target directory in the browser's built in file system.

But you can only unzip one ZIP into each directory:

```
touch a.py b.py
zip a.zip a.py
zip b.zip b.py
```

```
{
    "files": {
        "a.zip": "./*",
        "b.zip": "./*"
    }
}
```

```
Uncaught (in promise) SyntaxError: Duplicated destination: ./*
    at 607d9710-6c82-450b-a1cc-81399f5cadd6:1:18045
    at rn (607d9710-6c82-450b-a1cc-81399f5cadd6:1:18135)
    at cn (607d9710-6c82-450b-a1cc-81399f5cadd6:1:18524)
    at Object.engine (607d9710-6c82-450b-a1cc-81399f5cadd6:1:28141)
    at async 607d9710-6c82-450b-a1cc-81399f5cadd6:1:34183
```

**Comment by mhsmith** [comment]
Thanks, that works for me.
