### ISSUE TITLE
Pyscript stdout crops emojis

### ISSUE THREAD

**Issue by ramalho** [pyscript/pyscript#2242]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

When I print a string with emojis to stdout, they are cropped. If it's a circle, only the left 2/3 (or so) is rendered. A thin slice off the top of the emojis is also cropped.

Example code:

```python
print("\N{LARGE RED CIRCLE}")
print("\N{MOUSE FACE}")
print("\N{EARTH GLOBE AMERICAS}")
print("\N{NEUTRAL FACE}")
print("\N{NEUTRAL FACE}"*3)
print("\N{ARABIC LIGATURE BISMILLAH AR-RAHMAN AR-RAHEEM}")
print("\N{ARABIC LIGATURE BISMILLAH AR-RAHMAN AR-RAHEEM}\N{LARGE GREEN CIRCLE}")
```

### Actual output

Partial screenshot from Firefox 132.0.1 showing PyScript.com output:

![Screenshot 2024-11-05 at 16 36 31](https://github.com/user-attachments/assets/4598b19c-2fcf-4a45-adce-6887810ede17)

### Expected output

Partial screenshot from Firefox 132.0.1 showing PythonAnywhere.com output:

![Screenshot 2024-11-05 at 16 50 16](https://github.com/user-attachments/assets/223f0cd4-36b3-4012-88d8-6972193a8de9)

### Notes

1. The issue does not occur on PythonAnywhere 🤓.
2. The Arabic [basmala](https://en.wikipedia.org/wiki/Basmala) glyph is fully rendered. But the cursor does not advance correctly, so it is overwritten by text after it.
3. On Chrome, the right side of the emojis is only cropped when there's output after it on the same line. See below.
4. The top of the emojis is always cropped; easy to see on the face emojis.

Partial screenshot from Chrome 130.0.6723.92:
![Screenshot 2024-11-05 at 16 29 50](https://github.com/user-attachments/assets/e6b7ce85-ae7b-4085-8b50-435136d18640)

### What browsers are you seeing the problem on? (if applicable)

Firefox, Chrome

**Comment by ramalho** [comment]
> we don't control Xterm.js

Sure. Does PythonAnywhere use a more recent version of Xterm.js, or some other component?

Code link: https://pyscript.com/@ramgarlic/cropped-emojis-mpy/

I've rewritten the example with the same characters, but avoiding Unicode name escapes (`\N{...}`) so the code now runs on Micropython as well. The output is the same as before.

```python
import sys
print(sys.version)
RED = chr(0x1F534)  # LARGE RED CIRCLE
GREEN = chr(0x1F7E2)  # LARGE GREEN CIRCLE
MOUSE = chr(0x1F42D)  # MOUSE FACE
EARTH = chr(0x1F30E)  # EARTH GLOBE AMERICAS
FACE = chr(0x1F610)  # NEUTRAL FACE
BASMALA = chr(0xFDFD)  # ARABIC LIGATURE BISMILLAH AR-RAHMAN AR-RAHEEM

print(RED)
print(MOUSE)
print(EARTH)
print(FACE)
print(FACE * 3)
print(BASMALA)
print(BASMALA + GREEN)
```

**Comment by WebReflection** [comment]
this seems to be entirely Web browser dependent ... I start believing enforcing the right font compatible with emoji *might* be an easy solution for our terminal story ...

![Screenshot From 2024-11-07 17-16-31](https://github.com/user-attachments/assets/8232cbd8-6e10-4e5d-a43e-6ea6622b689c)

![Screenshot From 2024-11-07 17-16-41](https://github.com/user-attachments/assets/90a63009-2a9a-4953-b50a-17dd56a6647d)

![Screenshot From 2024-11-07 17-16-52](https://github.com/user-attachments/assets/4d23d244-cd62-4fd7-8d4f-bb5f6b6e56e5)

**Comment by nasrin1748** [comment]
I  think old terminal was better it used to display correctly.                                    
                     https://_12.pyscriptapps.com/cropped-emojis-mpy-copy/latest/

**Comment by WebReflection** [comment]
we just updated core to latest xterm and I'll try to see if that improved this situation too ... hopefully it does but the fact the old terminal has no issues makes me believe this is indeed a 3rd party issue we can't solve ourselves (and we shouldn't, as interfering with 3rd party would be potentially catastrophic).

I will come back with tests results

**Comment by WebReflection** [comment]
So ... this is an XTerm.js rendering issue but I might have found a workaround: https://github.com/pyscript/pyscript/pull/2248
