### ISSUE TITLE
toml package versions in  2024.10.2

### ISSUE THREAD

**Issue by Neon22** [pyscript/pyscript#2245]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

My existing page works in 2024.9.2
On udating to 2024.10.2 I get this error in the console:
```custom.js:182 Uncaught (in promise) Error: No known package with name 'pyscript-ltk>=0.1.2'```

Is it possible something was left out of the 2024.10.2 update ?
Example here:
 - https://neon22.pyscriptapps.com/working-copy/latest/
 - currently pointing at 2024.10.2 in the index.html file.
 - if you clone and change to 2024.9.2 the code works.

In Firefox we get a different error but lots more of them:
```Uncaught (in promise) Error: No known package with name 'pyscript-ltk>=0.1.2'
    yt https://cdn.jsdelivr.net/pyodide/v0.26.3/full/pyodide.asm.js:10
    dt https://cdn.jsdelivr.net/pyodide/v0.26.3/full/pyodide.asm.js:10
    ze https://cdn.jsdelivr.net/pyodide/v0.26.3/full/pyodide.asm.js:10
    kn https://cdn.jsdelivr.net/pyodide/v0.26.3/full/pyodide.asm.js:10
2 [pyodide.asm.js:10:89633](https://cdn.jsdelivr.net/pyodide/v0.26.3/full/pyodide.asm.js)
Source map error: Error: URL constructor:  is not a valid URL.
Resource URL: wasm:https://cdn.jsdelivr.net/pyodide/v0.26.3/full/pyodide.asm.js%20line%2010%20%3E%20WebAssembly.Module
Source Map URL: null```


### What browsers are you seeing the problem on? (if applicable)

Firefox, Chrome

### Console info

```shell
as above. more info on FF than chrome
```

**Comment by WebReflection** [comment]
we don't have anything to do with `pyscript-ltk` so be sure that's part of your packages? We also recommend a minimal example to check, not a whole application or it's impossible to nail the issue, thanks!

**Comment by Neon22** [comment]
ok. but the ltk is under pyscript on the github. It was under laffra but was moved. My assumption (which you point out is incorrect) is that pyscript had taken over some responsibility. Thanks for the clarification.

I will try to make a minimal example.

**Comment by WebReflection** [comment]
@Neon22 it's not about the ownership of the project, rather about the fact you cannot find, in this repository, any mention to `pyscript-ltk` and @laffra is still the owner/maintainer of that library, so if there is its own repository, which should be the case, I think any issue related to it should be filed in there ... if the issue has to do with PyScript breaking something, then it will eventually bounce back but right now we don't have anything at all about *pyscript-ltk* in here so it's even hard to test in integration stuff "just works".

Thanks for your understanding, the minimal example will be useful either ways so it won't be wasted time 🙏

**Comment by laffra** [comment]
I just tried upgrading to 2024.10.2 for PySheets, and that works just fine. I'm not sure how @Neon22's project is configured, but looks like he includes a dependency on a third party package, in this case `pyscript-ltk`, which is hosted on PyPI, latest version 0.1.43, See https://pypi.org/project/pyscript-ltk/. 

So, it looks like external package declarations that used to work in 2024.9.2 no longer work on 2024.10.2. To me, this looks like it has nothing to do with LTK, but more with how `custom.js` is loading packages?

**Comment by laffra** [comment]
@Neon22 Can you try installing some other packages, such as `chess` before you are trying to resolve `pyscript-ltk`? I would be curious to see if that import actually does work.

**Comment by WebReflection** [comment]
> it looks like external package declarations that used to work in 2024.9.2 no longer work on 2024.10.2.

we do update interpreters in the making, so maybe this is an issue about not pinned versions of the packages (that used to work) and that could be it? 🤔

**Comment by Neon22** [comment]
OK. made minimal example:
 - https://pyscript.com/@neon22/pyscript-ltk-10-2-fail/latest?files=pyscript.toml,index.html
 - all ok in 2024.10.1
 - fails with messages below in 2024.10.2
 - looks like its something to do with the version number - see below for details
 - @laffra I tried stacking it with other packages (chess) first
   -  chess works ok but stumbles on ltk with same messaging
   - but fails if I add a version to chess
   - so its the version number parsing somewhere... (IMHO)


**2024.10.2 using exact match to current release `["pyscript-ltk==0.1.43"]`
  - works

**2024.10.2 no version ` ["pyscript-ltk"]`
  - works


**2024.10.2 using >= match ` ["pyscript-ltk>=0.1.2"]`
```
custom.js:182 Uncaught (in promise) Error: No known package with name 'pyscript-ltk>=0.1.2'
    at addPackageToLoad (pyodide.asm.js:10:89633)
    at recursiveDependencies (pyodide.asm.js:10:89947)
    at loadPackage (pyodide.asm.js:10:92257)
    at initializePackageIndex (pyodide.asm.js:10:88988)
```

tried chess with version `packages = ["chess>=1.9.2", "pyscript-ltk>=0.1.2"]`
- fails on test for chess version - same kind of error

The example is set to chess with a version and ltk with a version.
Fails in 10.2
 - https://pyscript.com/@neon22/pyscript-ltk-toml-fail/latest?files=main.py,pyscript.toml,index.html

**Comment by Neon22** [comment]
OK. I am not sure anymore. some kind of caching was going on and now I'm getting indeterminate results.
So sorry - I think its something to do with the versioning but I just can't follow it anymore :(

**Comment by WebReflection** [comment]
I still think this is not a PyScript issue, strictly speaking, as we don't touch, deal, interfere, with packages or their versioning ... is there any chance this could be moved into LTK project?

**Comment by laffra** [comment]
This has nothing to do with LTK either 🤓. If anything, it would be best to
close this issue and reopen one on PyOdide.

**Comment by WebReflection** [comment]
btw, I don't believe this is a Pyodide issue neither ... they offer pinned versions and do a great job at that ... but I agree this is nothing we can tackle on our side, as the dependency graph is not stable so it's impossible to even understand why, what version, where, or how, it's failing.

Closing but happy to re-open if anything else comes along that is not:

  * a greater-than pinned version for a foreign module we don't control anyhow
  * a random github raw url we also don't strictly control and that could produce even an empty file or a 404 at any point in time, as that's not how production code should ever land in general, and it's also raw.GitHub dependent (if they won't allow foreign fetches tomorrow there's nothing we can do about it)

**Comment by WebReflection** [comment]
This is for @Neon22: I didn't mean to ignore your problem, I've tried to understand what was going on but there are too many moving parts in your configuration and basic example I don't think you, me, or Chris, should waste too much time on, specially when you have working solutions for your case. Thanks in advance for your understanding 🙏

**Comment by Neon22** [comment]
I gave you a new clean test version - I linked it above
I showed that the problem is the syntax for >= in the toml file

If you're not going to support that - then you should remove the syntax because it doesn't work - as illustrated by trying to use the chess package

Nothing to do with the ltk.
I will raise a new issue to remove the >= syntax from the toml file.
Absolutely every single toml file has this problem.
You should also update all the examples so they don't use it.

**Comment by WebReflection** [comment]
@Neon22 OK, as we haven't touched the toml library in ages and as the error happens in Pyodide, I have tried to understand what is going and **this** is going on ... if you don't use the cache, adding the following to your config:

```toml
packages_cache = "never"
```

then you'll never see the issue because indeed it seems that `micropip.freeze()` + Pyodide is not compatible with that syntax.

We did fix that because even the exact pinned version was causing issues so I've thought that was a fixed thing but it's clear with `>=` option we have the same issue.

The reason I was sure about being something else is that I have checked two different examples but they all came from your same account and I wasn't expecting the error at first run.

**Now**, because I can replicate the issue and I think I know what's going on (which should be the exact same story we already fixed for `==`) I can work on this.

Last, but not least, **apologies** but it sounds like there was simply some misunderstanding because a 3rd party library was mentioned, the TOML parser was mentioned, everything but the fact the non-cached version was just working was mentioned so it's good I eventually found the culprit which is not about Pyodide or LTK, it's about micropip freeze mechanism that is cool on one side but requires a lot of manual patching on the other one.

I will fix this ASAP and I am re-opening this as there are all details now that are relevant to the issue.

**Comment by WebReflection** [comment]
Re-opening as this was fixed in Polyscript and closed automatically

**Comment by WebReflection** [comment]
@Neon22 you can use `https://cdn.jsdelivr.net/npm/@pyscript/core@0.6.19/dist/core.js` and `https://cdn.jsdelivr.net/npm/@pyscript/core@0.6.19/dist/core.css` until we release next version of PyScript so that you can see this issue has been solved

/cc @ntoll

**Comment by WebReflection** [comment]
@Neon22 @laffra FYI, and to close the circle, this is a Pyodide opened issue with so far no resolution:
https://github.com/pyodide/pyodide/issues/5135#issuecomment-2441038644

We're handling stuff that (imho) should be handled in there as all we do is freezing and passing that frozen *micropip* blob to Pyodide but clearly that requires consumers handling around this relatively obscure blob generated by *micropip* which is then incapable to handle resolution from the very same package used to create it.

As a rule of thumb, if you think there's something wrong in the way Pyodide handles packages, always try to verify if adding:

```toml
packages_cache = "never"
```

in your config solves the issue. I believe we've now covered all possible use cases with versions, but who knows if there's something else that could possibly happen in there ... hopefully not.

**Comment by Neon22** [comment]
I very much appreciate the effort. Thanks Andrea
