### ISSUE TITLE
Cannot create username at pyscript.com/dashboard

### ISSUE THREAD

**Issue by goldentrianglemaths** [pyscript/pyscript#2262]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I'm trying to create a username at pyscript.com/dashboard, but I just get the error message "profile - username - Input should be a valid string." I've tried several usernames, all consisting of more than 3 lower case letters and nothing else, including one that I can't believe anyone else has taken ("sennendoko"). Can anyone explain why this doesn't work?

### What browsers are you seeing the problem on? (if applicable)

Chrome 130.0.6723.91 (Official Build) (64-bit) on Ubuntu 24.04.1

### Additional Context

![image](https://github.com/user-attachments/assets/a1a11dbb-d8b1-4d06-b4f1-e2dd50972656)

**Comment by WebReflection** [comment]
anything you can handle @FabioRosado ? 🤔 this is not, strictly speaking, a pyscript core module/project issue, thanks

**Comment by FabioRosado** [comment]
Hello thank you for the ping, we encountered an issue yesterday that caused temporary issues wit logging in and setting usernames. The issue has since been fixed and you should be able to choose our username if available, could you try again @goldentrianglemaths ?

**Comment by goldentrianglemaths** [comment]
Thanks, but I'm getting a different error message now. 
![image](https://github.com/user-attachments/assets/322e5a73-6232-4625-b0c4-70725e707778)

**Comment by FabioRosado** [comment]
Thank you for the update, I'm looking into it, can you attempt clear your cookies in pyscript.com as well?

**Comment by goldentrianglemaths** [comment]
Thanks - clearing cookies fixed it.

**Comment by FabioRosado** [comment]
Thank you for confirming, we will improve this code path to prevent issues in the future. Again thank you so much for reporting this to us
