### ISSUE TITLE
using pyodide npm package

### ISSUE THREAD

**Issue by mouhandalkadri** [pyscript/pyscript#228]
why pyodide is imported from the CDN instead of the [npm package](https://www.npmjs.com/package/pyodide).
I think this will help with the linting problem #208

**Comment by marimeireles** [comment]
I ran it locally with `npm` and made no difference.

**Comment by rth** [comment]
The 0.20.0 pyodide NPM package has a number of packaging issues, following the typescript migration.  [0.20.1-alpha.2](https://www.npmjs.com/package/pyodide/v/0.20.1-alpha.2) is better, but we are still fixing some of the remaining issues.

**Comment by mouhandalkadri** [comment]
@rth so for now the interfaces and types for ts version have to be written manually, right ?

**Comment by mouhandalkadri** [comment]
@marimeireles by the npm package you will get the TS version so all the interfaces and types will be available unlike JS CDN version.

**Comment by r2dev2** [comment]
> @rth so for now the interfaces and types for ts version have to be written manually, right ?

One potential solution could be to put the npm as a dependency and then typecast pyodide objects from windows to their npm-typed counterparts. That way, you get both the types of the npm version and the functionality of the cdn version.

**Comment by mouhandalkadri** [comment]
@r2dev2 yeah, I think this is the a good solution, we could add pyodide as a dev-dependency and import the types from the package 

@rth just out of curiosity, what kind of problems does it have ?

**Comment by marimeireles** [comment]
I think all the linting problems were fixed since this issue was opened.
So I'm closing as not relevant anymore, but please feel free to reopen if I'm mistaken.
