### ISSUE TITLE
Print losing output context

### ISSUE THREAD

**Issue by jim22k** [pyscript/pyscript#230]
These work as expected:
- Calling `print` inside `<py-script output="output-div">` will write to the output div, as expected.
- Creating a function which calls `print`, and calling that function within the py-script block works as expected.

This doesn't work as expected:
- Calling that same function which calls `print` from another context loses the knowledge of the output div.

Steps to show the issue:
1. Open a webpage with the content below.
2. Observe that two lines are printed initially (demonstrating the two working behaviors above).
3. Enter text in the first input box. This will append the text, demonstrating that `pyscript.write` is working.
4. Enter text in the 2nd input box. Nothing will appear in the output.
5. Open developer tools and look at the console. Observe that the text is attempting to be written to `undefined`.

```
<html>
    <head>
      <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
      <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
    </head>

  <body>
    <py-title>Two Ways to Print</py-title>
    <div id="print-here" style="height:200px;overflow-y:scroll;padding:25px;background-color:#EEE;"></div>
    <py-script output="print-here">
print("1. Initial output to show print is working...")

def foobar(text):
    print(text)

foobar("2. Also to show that foobar call is working...")
    </py-script>

    <label for="direct-input">Type input here for direct print:</label>
    <py-box width="2/5">
      <py-inputbox id="direct-input">
        def on_keypress(e):
          if (e.code == "Enter"):
            pyscript.write('print-here', direct_input.value, True)
            # Force the output div to scroll to the bottom
            print_here = Element("print-here").element
            print_here.scrollTop = print_here.scrollHeight;
            # Clear the input field to give feedback to the user that their
            # input was accepted and handled
            direct_input.clear()
      </py-inputbox>
    </py-box>

    <label for="foobar-input">Type input here to use foobar function:</label>
    <py-box width="2/5">
      <py-inputbox id="foobar-input">
        def on_keypress(e):
          if (e.code == "Enter"):
            foobar(foobar_input.value)
            foobar_input.clear()
      </py-inputbox>
    </py-box>
    <div style="margin-top:25px"><b>Note:</b> Using the 2nd input box doesn't work. Calling foobar will print, but the output location is undefined.</div>
  </body>
</html>
```

**Comment by marimeireles** [comment]
This will probably be fixed by https://github.com/pyscript/pyscript/pull/749

**Comment by marimeireles** [comment]
This falls under the case of unspecified target that throws an exception in case you try to write to an output that's not clear. So closing as fixed.
Thank you for the issue @jim22k!
