### ISSUE TITLE
16 MB Download?

### ISSUE THREAD

**Issue by x011** [pyscript/pyscript#233]
Do I have to download 16MB to use this on a browser or am I missing something?

https://cdn.jsdelivr.net/pyodide/v0.20.0/full/pyodide.asm.js - 1.91 MB
https://cdn.jsdelivr.net/pyodide/v0.20.0/full/pyodide.asm.data - 5.14MB
https://cdn.jsdelivr.net/pyodide/v0.20.0/full/pyodide.asm.wasm - 9.05MB

**Comment by rth** [comment]
These are uncompressed sizes. If you look for instance at https://pyscript.net/examples/hello_world.html you will get

![image](https://user-images.githubusercontent.com/630936/166981219-26d0b45a-d2c5-4c46-8978-9f28894aee63.png)

so the actual compressed sized sent via the network is 8.32 MB. It's still a lot, and there is work to reduce it further. But part of it is just that the Python interpreter and the standard library are large.

**Comment by IIMunchII** [comment]
It would be helpfull if the cdn could send appropriate headers for browser to cache the content. As it is now, every browser refresh results in a download of the same files.

**Comment by rth** [comment]
All large assets should already be correctly cached by the CDN. Reloading the above hello_world.html example we get for instance,

![image](https://user-images.githubusercontent.com/630936/166984226-2dbc7507-ce47-43ed-9376-1bac5e5eb02d.png)

so only 200kB are downloaded on page reload.

For more details about the returned headers, see

![image](https://user-images.githubusercontent.com/630936/166984349-be4f0aeb-944b-4652-bd49-a330df21a702.png)

**Comment by fpliger** [comment]
@rth , do you want us to open any issues on https://github.com/pyodide/pyodide as upstream and close this here or you already have issues capturing this (I think you do but just want to be sure..) ?

**Comment by jedie** [comment]
See: https://github.com/pyodide/pyodide/issues/646

**Comment by fpliger** [comment]
@x011 @jedie @rth given the discussion above, I'm closing this one. If there's any reason to, we can re-open

**Comment by rth** [comment]
Yes, thanks! There is a [series of issues in Pyodide](https://github.com/pyodide/pyodide/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+size+label%3A%22size+%26+load+time+optimization%22) discussing how we could reduce size and decrease load time.
