### ISSUE TITLE
python libraries

### ISSUE THREAD

**Issue by d4rk-n0153** [pyscript/pyscript#237]
Hi guys,
Many Python libraries, such as requests,scrapy,pandas, etc., do not exist and cannot be imported.

**Comment by ckavidas** [comment]
See #91 

You need to use some of the equivalent fetch methods which can be found [here](https://pyodide.org/en/stable/usage/api/python-api.html)

**Comment by kasusa** [comment]
requests lib , i need that too1

**Comment by marimeireles** [comment]
Unfortunately we don't have request yet, folks.
It's in our roadmap but we have docs on a good workaround.
Let me know if any of you get stuck!
Link to the docs: https://docs.pyscript.net/latest/howtos/http-requests.html
