### ISSUE TITLE
 ModuleNotFoundError: No module named 'geemap' 

### ISSUE THREAD

**Issue by abdalwhabSalahaldeen** [pyscript/pyscript#238]
hello everyone 
i am try to add geomap or any gis package to <py-env>  and i get erorr : 
example when i am trying import geomap.

JsException(PythonError: Traceback (most recent call last): File "/lib/python3.10/site-packages/_pyodide/_base.py", line 429, in eval_code .run(globals, locals) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 300, in run coroutine = eval(self.code, globals, locals) File "", line 4, in ModuleNotFoundError: No module named 'geemap' )

**Comment by mattkram** [comment]
Hi! `pyscript` is currently limited to dependencies that are either pure Python (i.e. no compiled dependencies), or are included by default in the Pyodide runtime. Unfortunately, that means that at this time `geemap` is not supported.

For reference, you can view the source of the error in your browser console: 
<img width="1733" alt="image" src="https://user-images.githubusercontent.com/11037737/167019929-e018187c-c259-43c5-9293-d3b1a3a95848.png">
