### ISSUE TITLE
Missing `Build` directory

### ISSUE THREAD

**Issue by abhijeetmote** [pyscript/pyscript#246]
I have observed that `pyscript-main\pyscriptjs\build` directory is missing which contains important files :
` pyscript.css` and `pyscript.js`

I know there is an alternative for this to use the following lines :

``` <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" / >```
``` <script defer src="https://pyscript.net/alpha/pyscript.js"></script> ```

this build directory needs to be generated or we need to create it manually and copy the following files ` pyscript.css` and `pyscript.js`

**Comment by verhulstm** [comment]
it needs to be built. cd into the the dir pyscript/pyscript  (the dir with the makefile) and run:

make setup
make build

**Comment by abhijeetmote** [comment]
Can we have proper documentation for it?

**Comment by verhulstm** [comment]
yes, more docs are coming soon :)

**Comment by Alii-isk** [comment]
you also need to install `Conda `& `make`

**Comment by Alii-isk** [comment]
> you also need to install `Conda `& `make`

**Comment by marimeireles** [comment]
@abhijeetmote I believe we now do.
Closing this issue, let us know if you're still stuck with something like this.
