### ISSUE TITLE
How do we parse HMTL or add html tag using pyscript?

### ISSUE THREAD

**Issue by KOSIDOCS** [pyscript/pyscript#253]
Currently can only change the innerText, but can not add HTML tag. Is there a way to already do this?

**Comment by JeffersGlass** [comment]
There is, though maybe not as a clean library feature. You can use document.createElement to create new elements, or embed new tags in the innerHTML if you escape the inner tags properly. ([JSFiddle](https://jsfiddle.net/7an9qr1g/))

```
<div id="target">
  <p>This is some text in the target div.</p>
</div>
<py-script>
child = document.createElement("div")
child.style.margin = "4px"
child.innerHTML = "This is a newly created div!"
child.innerHTML += '&lt;br&gt; You can also formatting tags &lt;b&gt;formatting tags!&lt;/b&gt; and &lt;a href="/"&gt;links&lt;/a&gt; if you replace "<" and ">" with & lt; and & gt; (without spaces)'

element = document.getElementById("target")
element.appendChild(child)
x = 0 #this is just here to prevent an extraneous print to screen
</py-script>
```

![image](https://user-images.githubusercontent.com/1931111/167165949-64cc4612-b628-433c-b5fb-9b6f47877a67.png)

**Comment by marimeireles** [comment]
Cool.
Thank you @JeffersGlass, guess I'm closing this as resolved.
As we're discussing on how to improve it as a PyScript feature in different issues.
