### ISSUE TITLE
Add issue forms/templates to separate types of issues

### ISSUE THREAD

**Issue by jezdez** [pyscript/pyscript#255]
I think there are a few areas where we need to separate general feedback, questions for help etc.

I'm thinking we should set up [GitHub issue forms](https://stefanbuck.com/blog/codeless-contributions-with-github-issue-forms) for a few categories (and auto-assign labels accordingly):

- Help requests
- Bug report
- Feature request
- Documentation issue
- Hosting and infrastructure
- Governance
- Security (but make that a link to https://pyscript.net/security

An example for GitHub issue forms is for example https://github.com/conda/conda/issues/new/choose

**Comment by jaynarayan-vaishnav** [comment]
I would like to work on this issue can you guide me how and where should I start with.

**Comment by abh139** [comment]
Hi @jezdez I can work on this issue as I know how to create the Issue template as I am familiar with it as well. Please assign this issue to me so that I will start work on this.

**Comment by antocuni** [comment]
I have already opened a PR for this :) #252 
My PR is very simple and does the bare minimum, and I agree that github forms are better.
But the main point is to automatically add the `needs-triage` label so that it's easier to keep track of existing issues.
So I propose to merge #252 soon, and later we can improve the templates.

**Comment by LtDan33** [comment]
(Closed my other dup issue) I actually suggest that we create a new PR as forms have a different file type and so #252 would be completely changed. I'm actively working on this :)

**Comment by antocuni** [comment]
> (Closed my other dup issue) I actually suggest that we create a new PR as forms have a different file type and so #252 would be completely changed. I'm actively working on this :)

works for me. Make sure to add `needs-triage` as the default label

**Comment by antocuni** [comment]
unless I am mistaken, I think that we can close this issue which was fixed by #264
