### ISSUE TITLE
Provide a better error if <py-env> paths is used in a local HTML file

### ISSUE THREAD

**Issue by antocuni** [pyscript/pyscript#257]
`paths:` can only be used if the page is being served out of a webserver, but not out of an HTML page on the filesystem.

This is for good reasons and it's related to #179, but currently py-script fails in a very obscure way and the page just looks broken to the user. This is the full traceback as seen in chrome's console:
```
Access to fetch at 'file:///home/antocuni/anaconda/pyscript/pyscriptjs/examples/utils.py' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.

utils.py:1          Failed to load resource: net::ERR_FAILED

pyodide.asm.js:14 Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 500, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 353, in run_async
    await coroutine
  File "<exec>", line 4, in <module>
  File "/lib/python3.10/site-packages/pyodide/http.py", line 231, in pyfetch
    url, await _jsfetch(url, to_js(kwargs, dict_converter=Object.fromEntries))
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
JsException: TypeError: Failed to fetch

    at new_error (pyodide.asm.js:14:238191)
    at pyodide.asm.wasm:0xedbcb
    at pyodide.asm.wasm:0xf1a0e
    at method_call_trampoline (pyodide.asm.js:14:238105)
    at pyodide.asm.wasm:0x134c2c
    at pyodide.asm.wasm:0x217a84
    at pyodide.asm.wasm:0x174a14
    at pyodide.asm.wasm:0x135149
    at pyodide.asm.wasm:0x135243
    at pyodide.asm.wasm:0x1352e6
    at pyodide.asm.wasm:0x1fff83
    at pyodide.asm.wasm:0x1f98b5
    at pyodide.asm.wasm:0x135329
    at pyodide.asm.wasm:0x201f1b
    at pyodide.asm.wasm:0x1ff9ff
    at pyodide.asm.wasm:0x1f98b5
    at pyodide.asm.wasm:0x135329
    at pyodide.asm.wasm:0xf16d8
    at Object.Module.callPyObjectKwargs (pyproxy.gen.ts:360:23)
    at Object.Module.callPyObject (pyproxy.gen.ts:384:17)
    at wrapper (pyodide.asm.js:14:205222)
```

We should intercept this error and show the user a clear message and a link to some documentation which explains the issue and how to solve/mitigate it.

There are many open issues which are all related to this problem, e.g.: 
https://github.com/pyscript/pyscript/issues/220
https://github.com/pyscript/pyscript/issues/217
https://github.com/pyscript/pyscript/issues/221

**Comment by SCrocky** [comment]
This error is also present whenever a  library install requires additional file on the PYPI server.
Ex:
```
<html>
    <head>
      <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
      <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
      <py-env>
 - msvcrt 
      </py-env>
    </head>
  <body>
	<div id="test"></div>
    <div id="test2"></div>
	<py-script output="test2">
import msvcrt 
print("keyboard OK")
	</py-script>
  </body>
</html>
```

We additionally get a CORS error:
```
Access to fetch at 'https://pypi.org/pypi/msvcrt/json' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

As well as a 301 error (CORS error) from `pyodide.asm.js` line 14.

**Comment by prasun3** [comment]
Do we need to update the documentation since this is not expected to work 

> Check out the [pyscriptjs/examples](https://github.com/pyscript/pyscript/blob/main/pyscriptjs/examples) folder for more examples on how to use it, all you need to do is open them in Chrome.

**Comment by formazione** [comment]
> **WORKAROUD** The easiest way to work around the issue is to use a local webserver. For example, suppose to have a file called `/tmp/pyscript-test/foo.html` which uses `<py-env> paths: ...`. If you open `foo.html` inside chrome, it will not work. To start a local webserver you can do the following:
> 
> ```
> $ cd /tmp/pyscript-test/
> $ python3 -m http.server
> Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
> ```
> 
> Now you can open http://0.0.0.0:8000 and select `foo.html` from there, and it should work.

YES, it worked this way, localhost:8000/foo.html
