### ISSUE TITLE
start white space from <py-script> tag

### ISSUE THREAD

**Issue by michavardy** [pyscript/pyscript#273]
would it be possible to change to something like this?

```
   <BODY>
      <h1>Hello world!</h1>
      <div id="dec" class="decorated"></div>
      <button id = b1 class = "button" onClick="sayHi"></button>
      <h1 id = resp class = "response"></h1>
      <py-script>
         pyscript.write('dec', 'Hello World decorated')
         pyscript.write('b1', 'BuTTon')
         def sayHi():
                  pyscript.write('resp','I have been clicked')
      </py-script>
   </BODY>
```

**Comment by verhulstm** [comment]
hi, i think you will like this

https://github.com/pyscript/pyscript/pull/130

https://github.com/pyscript/pyscript/issues/265

**Comment by mattkram** [comment]
As @verhulstm mentioned, this is completed in main but just not yet released. Closing the issue but please keep an eye out for when that release does roll out.

More info in #265
