### ISSUE TITLE
[FEATURE] Allow writing html with `markdown`

### ISSUE THREAD

**Issue by sugatoray** [pyscript/pyscript#276]
**It will be nice to be able to author a page by just writing it's contents with markdown**.

:arrow_right: **Describe the solution you'd like**
If you could provide an html tag for markdown content: `<py-md></py-md>`, that could go a long way for easily writing markdown content within the tag. 

:arrow_right: Perhaps it could behave as a `<div></div>` which could render the markdown with GitHub flavored markdown by default and alternatively with some other custom-defined css (either locally maintained or via a CDN).

- Custom GitHub markdown css: https://github.com/sindresorhus/github-markdown-css
  - CDN: https://cdnjs.com/libraries/github-markdown-css 

:arrow_right: **Describe alternatives you've considered**
Although you can still include markdown content currently as follows, perhaps a dedicated html tag `<py-md></py-md>` could make it rather convenient to author with markdown.

````html
<html>
<head>
<py-env>
	- markdown
	- emoji
<py-env>
</head>

<body>
<py-script>
import markdown
import emoji
md_text = f"""\
# Heading 1

This is some test content.

## Heading 2

This is some emoji: {emoji.emojize(":zap:")}

![image](https://user-images.githubusercontent.com/10201242/167243920-46aa83ae-735d-4af6-a841-3d787a7396ce.png)

```python hl_lines="1 3"
import numpy as np

x = np.arange(10)

print(x)
```
"""

html = markdown.markdown(md_text, extensions=['fenced_code', 'codehilite'])
print(html)
</py-script>
</body>
</html>
````

**Comment by sugatoray** [comment]
cc: @philippjfr @fpliger @verhulstm

**Comment by TusharNautiyal-web** [comment]
`<html>
<head>
<py-env>
	- markdown
	- emoji
<py-env>
</head>

<body>
<py-script>
import markdown
import emoji
md_text = f"""\
# Heading 1

This is some test content.

## Heading 2

This is some emoji: {emoji.emojize(":zap:")}

![image](https://user-images.githubusercontent.com/10201242/167243920-46aa83ae-735d-4af6-a841-3d787a7396ce.png)

```python hl_lines="1 3"
import numpy as np

x = np.arange(10)

print(x)
```
"""

html = markdown.markdown(md_text, extensions=['fenced_code', 'codehilite'])
print(html)
</py-script>
</body>
</html>`

Rather then using <py-md></py-md> We can in built this in <py-script> itself Whenever someone writes # or *** It should undestand it as markdown. This would be much easier and it will make things seamless.

**Comment by fpliger** [comment]
I think it's a great proposal and probably a component that should be in core...

**Comment by sugatoray** [comment]
@fpliger Could this requirement be discussed more so development on this starts sooner? Thank you.

I am quite sure, with this feature creating web pages out of PyScript and Markdown will become even more accessible and natural.

**Comment by marimeireles** [comment]
Yeah we have this half implemented in our code. We need a way to rendering `md`.
Doesn't seem too complicated to fix, but I guess all of this will undergo redesign. So.. Will keep this one open and keep track of it in our output rendering EPIC.
Thanks for the issue!

**Comment by marimeireles** [comment]
I guess this is resolved by the addition of the [markdown plugin](https://github.com/pyscript/pyscript/blob/main/examples/markdown-plugin.html).
Don't hesitate to open a discussion if you think this could be improved!
