### ISSUE TITLE
[BUG] Bokeh Example is not working

### ISSUE THREAD

**Issue by hedonistrh** [pyscript/pyscript#281]
**Describe the bug**
I tried to generate the [bokeh example](https://github.com/pyscript/pyscript/blob/main/pyscriptjs/examples/bokeh.html) in my local but that is not working. When I open to html file via latest chrome, it just shows the code in the text format.

**To Reproduce**
Need to create a .html file and copy [that example](https://raw.githubusercontent.com/pyscript/pyscript/main/pyscriptjs/examples/bokeh.html).

**Expected behavior**
Just text appearing.

**Screenshots**
![image](https://user-images.githubusercontent.com/34948815/167273436-9894b215-f869-4569-bed1-8c78f99278cc.png)

**Comment by michavardy** [comment]
Hey, 
did you copy this into the header section of the HTML?

<link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css"/>
<script defer src="https://pyscript.net/alpha/pyscript.js"></script>

try  this and try to load again

**Comment by hedonistrh** [comment]
Thanks for the answer. When I do that, still can not see plot but this time just title is appearing when I open the html file.
![image](https://user-images.githubusercontent.com/34948815/167291585-aa1189ed-8eeb-42ef-8754-bdc5da5a85d8.png)

**Comment by verhulstm** [comment]
did you build from source. the examples dont work unless you build the src or edit these lines:

<link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css"/>
<script defer src="https://pyscript.net/alpha/pyscript.js"></script>

**Comment by verhulstm** [comment]
better docs are coming :)

**Comment by antocuni** [comment]
> So still example in the repo is not working without that change

yes, the examples are meant to be served using `npm run dev` as explained by the README, but I agree it's not very clear.

Closing this as invalid because the example actually works, but thanks for bringing up the issue and to confirm that we need better docs.
