### ISSUE TITLE
[FEATURE]If I want to do the GUI program, Tkinter does not seem to be imported?

### ISSUE THREAD

**Issue by zhorsex** [pyscript/pyscript#289]
What "GUI" module is better as described in the title?

**Comment by maximlt** [comment]
PyScript depends on `Pyiodide` which [doesn't include tkinter](https://pyodide.org/en/stable/usage/wasm-constraints.html?highlight=tkinter#removed-modules). As shown in the examples, you could use [Panel](https://panel.holoviz.org/) to generate a user interface.

**Comment by zhorsex** [comment]
> PyScript取决于 `Pyiodide `哪一个 [不包括tkinter ](https://pyodide.org/en/stable/usage/wasm-constraints.html?highlight=tkinter#removed-modules)。 如示例所示,您可以使用 [面板 ](https://panel.holoviz.org/)生成用户界面。
think you！

**Comment by zhorsex** [comment]
> PyScript depends on `Pyiodide` which [doesn't include tkinter](https://pyodide.org/en/stable/usage/wasm-constraints.html?highlight=tkinter#removed-modules). As shown in the examples, you could use [Panel](https://panel.holoviz.org/) to generate a user interface.

thank you~

**Comment by antocuni** [comment]
Closing this a `wontfix` because it's very unlikely that we want and/or we will ever support Tkinter.

**Comment by DevScholar** [comment]
I ported Tkinter to WASM.

https://github.com/pyodide/pyodide/issues/6215

<img width="199" height="106" alt="Image" src="https://github.com/user-attachments/assets/69582fb7-67f2-442e-9f7f-c8a01d569ff3" />

<img width="404" height="468" alt="Image" src="https://github.com/user-attachments/assets/ac894e62-7308-4d59-9a9b-67b24f750480" />
