### ISSUE TITLE
If you don't see this as a bug, please see it as a feature request: Using sympy, I can't get the output to be acted by MathJax

### ISSUE THREAD

**Issue by deivyp** [pyscript/pyscript#290]
**Describe the bug**
Using sympy, the latex output can not  be acted by MathJax. That is, whatever is the output in the page it just comes out as text.
I am putting the example of the whole page for you to see the issue.

**To Reproduce**
```
<-! starting HTML page -->
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<title>Sympy</title>
	<meta name="generator" content="BBEdit 14.1" />
	<link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
      <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
     <script id='MathJax-script' async src='https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js'>
    </script>
 <py-env>
        - sympy
      </py-env>
</head>
<body>
<div id="SYMPY">
  Factoring \(x^3-x^2+x-1 \) yelds: 
</div><br/><br/><br/>
<py-script>
from sympy import *
from pyodide import to_js
init_printing()
x, y, z, t = symbols("x y z t")
y= x**3 - x**2 + x - 1
res=factor(y)
re=latex(res)
pyscript.write('factor',re )
child = document.createElement("div")
child.style.margin = "4px"
child.innerHTML = "\( " +re+" \)"
element = document.getElementById("SYMPY")
element.appendChild(child)
print(r"\( %s \)" %re)
z="x"
</py-script> 

&emsp;&emsp;Factoring \(x^3-x^2+x-1 \) yelds \( <label id='factor'></label> \)<br/><br/>

<!-- It works here-->&emsp;&emsp;Factoring \(x^3-x^2+x-1 \) yelds \( \left(x - 1\right) \left(x^{2} + 1\right)\)<br/><br/><br/><br/>

</body>
</html>
<!--End of HTML page-->
```
**Expected behavior**
The expected behavior is the behavior in the line .
Note that the output is correct. If one tries to use  methyl instead of LaTeX as the output the error is even worse.

**Screenshots**
If applicable, add screenshots to
<img width="593" alt="Screen Shot 2022-05-08 at 13 51 27" src="https://user-images.githubusercontent.com/105169393/167309057-27fea345-24f5-466d-afa8-1d05da4663fa.png">
 help explain your problem.

**Additional context**
Without a doubt, being able to use sympy and output the content with a proper Mathematical typeset, would be invaluable.

**Comment by marimeireles** [comment]
Thanks for the bug report, I get an additional error when I run your code on FF:
`JsException(PythonError: Traceback (most recent call last): File "/lib/python3.10/site-packages/_pyodide/_base.py", line 429, in eval_code .run(globals, locals) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 300, in run coroutine = eval(self.code, globals, locals) File "", line 14, in TypeError: not all arguments converted during string formatting )`.
I'm going to explore it a little bit and try to figure out what's up =)

**Comment by deivyp** [comment]
Hi Mariana,
I can confirm the error in Firefox, I tried 2 times and had the error on both.
Safari does not give me an error.
Brave and Opera had this error the first time I opened the file, but not on the second.

Running this on a Mac macOS Big Sur 11.6.6
I’ll try in Mac OS Monterey later.

Thanks for your attention.

> On May 9, 2022, at 09:09, Mariana Meireles ***@***.***> wrote:
> 
> 
> Thanks for the bug report, I get an additional error when I run your code on FF:
> JsException(PythonError: Traceback (most recent call last): File "/lib/python3.10/site-packages/_pyodide/_base.py", line 429, in eval_code .run(globals, locals) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 300, in run coroutine = eval(self.code, globals, locals) File "", line 14, in TypeError: not all arguments converted during string formatting ).
> I'm going to explore it a little bit and try to figure out what's up =)
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.
> 



Best, be safe, wear mask, get vaccinated and keep social distance.

Deivy Petrescu
http://www.dicas.com
workflow automation & data analysis
***@***.***

**Comment by fpliger** [comment]
Hi @deivyp , I think it's a non bug :) 

Basically, MathJax replaces all the valid expressions when the page is loaded. Since the content is generated after the page is loaded, MathJax needs to be explicitly called to typeset the page. So, you need to `from js import MathJax` and then add `MathJax.typesetPromise()` after your code. So, in this case, your example would look like something like this:

```
<-! starting HTML page -->
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<title>Sympy</title>
	<meta name="generator" content="BBEdit 14.1" />
	<link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
      <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
     <script id='MathJax-script' async src='https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js'>
    </script>
 <py-env>
        - sympy
      </py-env>
</head>
<body>
<div id="SYMPY">
  Factoring \(x^3-x^2+x-1 \) yelds: 
</div><br/><br/><br/>
<py-script>
from js import MathJax
from sympy import *
from pyodide import to_js
init_printing()
x, y, z, t = symbols("x y z t")
y= x**3 - x**2 + x - 1
res=factor(y)
re=latex(res)
pyscript.write('factor',re )
child = document.createElement("div")
child.style.margin = "4px"
child.innerHTML = "\( " +re+" \)"
console.log("\( " +re+" \)")
element = document.getElementById("SYMPY")
element.appendChild(child)
print(r"\( %s \)" %re)
z="x"
MathJax.typesetPromise()
</py-script> 


&emsp;&emsp;Factoring \(x^3-x^2+x-1 \) yelds \( <label id='factor'></label> \)<br/><br/>

<!-- It works here-->&emsp;&emsp;Factoring \(x^3-x^2+x-1 \) yelds \( \left(x - 1\right) \left(x^{2} + 1\right)\)<br/><br/><br/><br/>

</body>
</html>
<!--End of HTML page-->
```

Here's a link to a related [StackOverflow thread ](https://stackoverflow.com/questions/62501089/rendering-mathjax-after-data-is-received)for a similar problem related to a JS piece of code for reference.

Closing the issue based on the above. :)

**Comment by deivyp** [comment]
Thank you so much.
Forever indebted to you guys.
Also, if I didn’t say enough before, 

THANK YOU SO MUCH FOR PYSCRIPT!!!!

> On May 17, 2022, at 15:23, Fabio Pliger ***@***.***> wrote:
> 
> 
> Hi @deivyp , I think it's a non bug :)
> 
> Basically, MathJax replaces all the valid expressions when the page is loaded. Since the content is generated after the page is loaded, MathJax needs to be explicitly called to typeset the page. So, you need to from js import MathJax and then add MathJax.typesetPromise() after your code. So, in this case, your example would look like something like this:
> 
> <-! starting HTML page -->
> <!DOCTYPE html>
> <html lang="en">
> <head>
> 	<meta charset="utf-8" />
> 	<title>Sympy</title>
> 	<meta name="generator" content="BBEdit 14.1" />
> 	<link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
>       <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
>      <script id='MathJax-script' async ***@***.***/es5/tex-mml-chtml.js'>
>     </script>
>  <py-env>
>         - sympy
>       </py-env>
> </head>
> <body>
> <div id="SYMPY">
>   Factoring \(x^3-x^2+x-1 \) yelds: 
> </div><br/><br/><br/>
> <py-script>
> from js import MathJax
> from sympy import *
> from pyodide import to_js
> init_printing()
> x, y, z, t = symbols("x y z t")
> y= x**3 - x**2 + x - 1
> res=factor(y)
> re=latex(res)
> pyscript.write('factor',re )
> child = document.createElement("div")
> child.style.margin = "4px"
> child.innerHTML = "\( " +re+" \)"
> console.log("\( " +re+" \)")
> element = document.getElementById("SYMPY")
> element.appendChild(child)
> print(r"\( %s \)" %re)
> z="x"
> MathJax.typesetPromise()
> </py-script> 
> 
> 
> &emsp;&emsp;Factoring \(x^3-x^2+x-1 \) yelds \( <label id='factor'></label> \)<br/><br/>
> 
> &emsp;&emsp;Factoring \(x^3-x^2+x-1 \) yelds \( \left(x - 1\right) \left(x^{2} + 1\right)\)<br/><br/><br/><br/>
> 
> </body>
> </html>
> 
> 
> Here's a link to a related StackOverflow thread for a similar problem related to a JS piece of code for reference.
> 
> Closing the issue based on the above. :)
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.
> 



Best, be safe, wear mask, get vaccinated and keep social distance.

Deivy Petrescu
http://www.dicas.com
workflow automation & data analysis
***@***.***
