### ISSUE TITLE
[BUG] pyscript fails to send mail.

### ISSUE THREAD

**Issue by achaayb** [pyscript/pyscript#295]
pyscript fails to connect with gmail SMTP.
`

def send(*args, **kwargs):

    msg = EmailMessage()
    msg.set_content(final)
    msg['Subject'] = subject
    msg['From'] = email
    msg['To'] = rec_email

    s = smtplib.SMTP('smtp.gmail.com', 587)
    s.starttls()
    s.login(email, secret)
    s.send_message(msg)
    s.quit()
`
console :

![image](https://user-images.githubusercontent.com/76395276/167330557-25b4adf9-455e-4b22-be0d-36425bbcd460.png)
![image](https://user-images.githubusercontent.com/76395276/167330586-bc098665-75a1-4f35-9bfa-3cafb584327b.png)

**Comment by ckavidas** [comment]
Most likely the same reason that requests/urllib3 does not work see #91

**Comment by sugatoray** [comment]
You could access the JavaScript module and it's children as follows and then send the email. (I have not tested this yet; but this should work)

Source: https://pyodide.org/en/stable/usage/api/python-api.html

```
from js import window

window.open(f'mailto:{msg["email"]}?subject= {msg["subject"]}&body= {msg["body"]}');
```



Refer to: 

- https://stackoverflow.com/questions/7381150/how-to-send-an-email-from-javascript

**Comment by fpliger** [comment]
This is an upstream issue, that should be a duplicate of #91  and reflects the fact that sockets don't work in pyodide (yet). I'll close this as duplicate and leave #91 as an umbrella issue for all related bug issues. @achaayb  happy to be convinced otherwise, if you think the problem is different.

**Comment by fpliger** [comment]
This is an upstream issue, that should be a Duplicate of #91  and reflects the fact that sockets don't work in pyodide (yet). I'll close this as duplicate and leave #91 as an umbrella issue for all related bug issues. @achaayb  happy to be convinced otherwise, if you think the problem is different.
