### ISSUE TITLE
Python script in <py-script> content may render before script execution

### ISSUE THREAD

**Issue by timdream** [pyscript/pyscript#296]
Hi!

Interesting project! 

I didn't try to set it up but looking at [getting started](https://github.com/pyscript/pyscript/blob/main/GETTING-STARTED.md) it seems that a small browser behavior was overlooked. 

Since HTML could render without fully loaded and `<script defer>` only executes right before HTML was full loaded, the way the page is set up as suggested in the tutorial means with slow enough connection or large enough script text, browser may render the Python script on the page before JS execution & custom element registration.

One can avoid that by only construct `<py-script>` dynamically... but that's less preferable since people should be able to embed the Python script declaratively in HTML.

The mitigation I can think of is to wrap the Python code in comment blocks (`<!-- -->`). This was actually done for JS too, when `<script>` was first introduced: web devs were told to wrap JS in comment blocks to avoid old browsers without support of `<script>` from putting JS onscreen<sup>1</sup>. To this day, HTML5 parser could parse and execute JS wrapped in comment.

It would be nice if pyscript can also pull Python code in the comment node child in `<py-script>`, other than the text node child, and update the tutorial as such. This would apply to other custom elements as well.

Thanks!

1: I have never encountered a browser that would do that, except for Mobile IE 2 on a really old WinCE device 😅

**Comment by philippjfr** [comment]
I think we may want to consider this bit of CSS to pyscript.css to avoid this problem:

```css
:not(:defined) {
    visibility: hidden;
}
```

**Comment by timdream** [comment]
@philippjfr Nice! That would work too. Nitpick: it should be `display: none` instead of `visibility: hidden` (the later will still produce layout and taking up space.)

**Comment by timdream** [comment]
Moving away from custom element is less desirable, since you can't possibly intervene all the possible `<script>` DOM insertions.

Having a bit of blocking style is an issue too. This means the solution must be inlined in HTML. 

Other than wrap in comment, another thing I can think of is `<py-script hidden>`, which would have the same effect as setting `display: none`. 

We don't have to pick just one solution, we can deploy multiple solutions (at expense of adding code complicity a bit) to ensure the inlined script never renders.

**Comment by fpliger** [comment]
This is a very interesting discussion.. Not only the main topic in the issue (avoid content to render before script execution) but the relation between js and related styling (CSS). I've been thinking about that for the past few weeks and haven't come up with a good solution. (Planning on opening a discussion on that soon)

For the specific problem in this issue, since 

```
:not(:defined) {
    visibility: hidden;
}
```

is a global rule that we need independent of whatever style we use to display objects, we could inject that rule as part of the initial loading of `pyscript.js` and delegate any other styling elsewhere. This would detach this localized problem from the rest of the problem.

**Comment by timdream** [comment]
> we could inject that rule as part of the initial loading of `pyscript.js`

Won't work, sorry — as I said in the very beginning, `<script defer>` only executes when the entire HTML is loaded and parsed, while the browser can start rendering partially downloaded+parsed HTML anytime it likes.

A workable solution must block rendering, e.g. `<link rel=stylesheet>`, or inlined in the HTML markup.

**Comment by fpliger** [comment]
That's true today but I'm entirely sure it *needs* to be... The main reason (I think) we `<script defer>` now is related to the `Svelte` dependency. Right now that dependency is very thin (only for Svelte stores afaict) so, if we replace that with something else, we can avoid deferring. 

There's a related discussion around [theming](https://github.com/pyscript/pyscript/issues/340) that is likely to be close related to this topic and worth mentioning.

I think it's definitely worth thinking about the best option overall here, considering this issue in the context of the rest. I'm not opposed to setting the rule on a stylesheet, just think we need to consider all aspects. Definitely a great discussion. :)

**Comment by marimeireles** [comment]
I'm going to do it, but if anyone feel like this is different enough, please feel free to re-open it :)

**Comment by JeffersGlass** [comment]
I think it's good to leave closed, but I think it's more closely related to #810 - that issue is essentially looking to tidy up the solution proposed earlier in this issue.
