### ISSUE TITLE
ValueError: Couldn't find a pure Python 3 wheel for 'browser_cookie3'

### ISSUE THREAD

**Issue by mallamsripooja** [pyscript/pyscript#297]
I am trying to use browser_cookie3 with pyscript but looks like pyscript pip installer is unable to find a wheel file to download.
Is there any workaround for issues similar to this one? 

Here is the complete error message copied from console:
```
Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 183, in install
    transaction = await self.gather_requirements(requirements, ctx, keep_going)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 173, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 286, in add_requirement
    raise ValueError(
ValueError: Couldn't find a pure Python 3 wheel for 'browser_cookie3'. You can use `micropip.install(..., keep_going=True)` to get a list of all packages with missing wheels.
    PythonError error_handling.gen.ts:309
    new_error pyodide.asm.js:14
    method_call_trampoline pyodide.asm.js:14
    callPyObjectKwargs pyproxy.gen.ts:360
    callPyObject pyproxy.gen.ts:384
    wrapper pyodide.asm.js:14
    setTimeout handler*hiwire_call_bound pyodide.asm.js:14
    callPyObjectKwargs pyproxy.gen.ts:360
    callPyObject pyproxy.gen.ts:384
    wrapper pyodide.asm.js:14
    setTimeout handler*hiwire_call_bound pyodide.asm.js:14
```

**Comment by marimeireles** [comment]
Hey @mallamsripooja can you please update the issue with a minimal reproducible version of your bug?
Thank you =)

**Comment by SCrocky** [comment]
I'm having this issue as well with the pygame package:
```
<html>
    <head>
      <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
      <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
      <py-env>
        - pygame
      </py-env>
    </head>
  <body>
    <py-script>
print("Hello world")
    </py-script>
  </body>
</html>
```

I've tried giving it a whl file as well. But the issue seems to be that there are non-Python dependencies (OS specific deps).
I understand that this may be one of the current limitations of the current project.

But this is not addressed anywhere.

**Comment by mallamsripooja** [comment]
Hi @marimeireles ,

Here is the very basic code I implemented just to know if `browser_cookie3`, `requests` are supported or not:

```
<html>
  <head>
    <title>Cookie Test</title>
    <meta charset="utf-8">

    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
    <py-env>
      - browsercookie
      - requests
    </py-env>
    </head>
    <body>
      <div id="cookietst"></div>
      <py-script output="cookietst">
import browsercookie
import requests
requests.__version__
browsercookie.__version__
      </py-script>
    </body>
</html>
```

It is quite understandable that pyscript is in budding state right now. A simple workaround will be of great help to resolve this issue.

Looking forward to using `pyscript` extensively for many other projects in near future :)

Thank you!

**Comment by marimeireles** [comment]
Hey @mallamsripooja, so the `requests` module is not working because of the way the underlying implementation of the browser, see https://github.com/pyscript/pyscript/issues/91.
But your error `ValueError: Couldn't find a pure Python 3 wheel for 'browser_cookie3'. ` seems like it happens because it's a library that's currently not supported by `pyodide`. I think pyodide is using `micropip`, so currently we only offer support for pure Python packages.
I'll try to find out more about this issue and then come back here with more info.
Thank you for the kind words :) I hope it's a very useful project for you in the future!

**Comment by marimeireles** [comment]
The update on this is we're currently not going to pursue the individual fix of all the packages that are currently failing...
But the `requests` package is on our priority list.
In the meanwhile you can have a look on this example: https://github.com/pyscript/pyscript/pull/151, that offers a work around for requests :) feel free to open a thread in https://discuss.python.org/ if any doubts come up!

**Comment by rth** [comment]
Also see https://pyodide.org/en/latest/usage/faq.html#micropip-can-t-find-a-pure-python-wheel about what to do when a package cannot be installed with micropip which is currently used by pyscript to install packages.
