### ISSUE TITLE
Is it Multithreading?

### ISSUE THREAD

**Issue by chiddekel** [pyscript/pyscript#298]
Pyscritp is support Multithreading?

**Comment by fpliger** [comment]
Multithreading is not [supported by Pyodide ](https://pyodide.org/en/stable/usage/wasm-constraints.html#included-but-not-working-modules)(the only runtime by PyScript at the moment) . It is just different in terms of a python running inside the browser. 

There may be an upstream path for this to work in the future through web-workers but I'm not sure... this would be a question for the upstream projects to answer
