### ISSUE TITLE
How to install libs

### ISSUE THREAD

**Issue by BernardoOlisan** [pyscript/pyscript#299]
So for example, I want to use it but with pytorch and other libs, how can you install them via pip or something like that, are all of them preinstalled?

**Comment by marimeireles** [comment]
Hey @BernardoOlisan you can use the `<py-env></py-env>` tag, like this:

https://github.com/pyscript/pyscript/blob/843b9d09bd714acc7968f30810cc0f06c81cf1b0/pyscriptjs/examples/bokeh_interactive.html#L20-L23

I believe it's picking up stuff from pip.

**Comment by marimeireles** [comment]
Here's a better explanation on it: https://github.com/pyscript/pyscript/blob/main/GETTING-STARTED.md#packages-and-modules
