### ISSUE TITLE
[BUG]Failed to import the json module

### ISSUE THREAD

**Issue by Y97** [pyscript/pyscript#302]
Introduce json in py-env
![image](https://user-images.githubusercontent.com/54340372/167417682-bcd97b5b-204c-46aa-95c9-afc41e5dae0d.png)

Fetch at 'https://pypi.org/pypi/json/json'
![image](https://user-images.githubusercontent.com/54340372/167417964-7071bc85-c4c6-43b0-9124-3e5d86dbf48a.png)

But https://pypi.org/pypi/json/json/ is 404
![image](https://user-images.githubusercontent.com/54340372/167418229-98bb8325-247c-4aac-9013-7954ae56f039.png)

**Comment by JeffersGlass** [comment]
Most of the standard library is [included in Pyodide](https://pyodide.org/en/stable/usage/wasm-constraints.html), so it doesn't need to be specifically added to py-env. Simply use `import json` in your Python script as normal. 

See, for instance, the [Bokeh example](https://github.com/pyscript/pyscript/blob/main/pyscriptjs/examples/bokeh.html).
