### ISSUE TITLE
[FEATURE]REQUEST FOR VS CODE INTELLISENCE FOR pyscript

### ISSUE THREAD

**Issue by Veeresh-R-G** [pyscript/pyscript#304]
### **Request**
<hr>
As a programmer who is into python and javaScript(basically web-dev), I feel its better to have an <strong>IntelliSense</strong> for these python scripts as it would reduce the overall development time and increase the productivity while we work with pyScript.

<br>
<br>
Platform for which IntelliSense would be awesome : <strong>VSC </strong>(V S Code) and may be some of the other popular IDE's that support installing external extensions.

**Comment by pww217** [comment]
Incredibly there's already and extension for VSCode https://marketplace.visualstudio.com/items?itemName=HardeepSingh.pyscript

**Comment by Veeresh-R-G** [comment]
Till yesterday, the version of the extension was not compatible with the vsCode version that I am working on, but when I tried again today, it worked. Although I am still not happy with the extension's behaviour, it's resulting in indentation errors when I have the following lines of code:
` print("Hi there") for i in range(10): print("Hi there", end=" -- ")`

So for me I prefer writing the python code in an external script(.py file) and linking the HTML file to that !!!

Thanks for the reply though !!!!! 
@pww217
