### ISSUE TITLE
Ajax post request

### ISSUE THREAD

**Issue by AdamVarley30** [pyscript/pyscript#306]
Can pyscript be used to create an ajax post request to a server side script, much like you can do in php or in Django/Flask? Sorry I'm using a outdated jquery call here, but hopefully you get the gist??

          $.ajax({
               url:'my_query.py',
               type:'POST',
               dataType: "json",
               data:{
                  input: mydata
               },
          success:function(response){
          console.log(response)
                }.
                error:function(response){
                   console.log(response)
               }
})

Thanks 

Adam

**Comment by John-Schreiber** [comment]
I've been using XMLHttpRequest, I've also seen people using fetch. 

```
from js import XMLHttpRequest
request=XMLHttpRequest.new()
request.open(method,url,async)
req.send()
response = req.responseText
```

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest

**Comment by AdamVarley30** [comment]
Thanks John that's really helpful and appears exactly what I want. Looks a lot more straightforward than JQuery method too. 

I'm just trying to get some understanding where pyScript lies at the minute compared to Django and Flask. It seems to offer the flexibility of php in line scripting, which is awesome, but provides the Data Science bit in the background with Python!! You can tell I only discovered this yesterday, and I'm quite excited.

One final question, and apologies as I know it is a simple one. Similar to php, can I have say a simple stand alone python script in the same directory as the html file in my webserver and call it using the above method with arguments being passed from js to python and then processed and sent back with the response? Does it need something like WGSI running in the background.

I understand the benefit of rendering js graphs etc using predefined python libraries as it saves time coding in js, but I know I'll always reach a position where I want to change something small in the js visualisation myself using javascript. I found this with Shiny and R where you become limited as to how much the libraries have kept up with the js developments. 

I presume there is scope within the pyscript framework work in this manner?

Sorry the essay and I hope you have time to read.

Many thanks

Adam

**Comment by verhulstm** [comment]
*python script in the same directory as the html file in my webserver and call it using the above method with arguments being passed from js to python and then processed and sent back with the response*

yup, that works

**Comment by verhulstm** [comment]
you can also have pyscript apps (with pyscript tags) in HTML call out to flask.

at this time running a flask/django web framework app in pyscript is not supported.

**Comment by marimeireles** [comment]
I think this can be closed as resolved? :)
Thanks for your input @verhulstm
