### ISSUE TITLE
[BUG] Confusing homepage working RE role of Pyodide

### ISSUE THREAD

**Issue by josephrocca** [pyscript/pyscript#308]
The homepage currently says:

* **Python in the browser**: Enable drop-in content, external file hosting (made possible by the [Pyodide project](https://pyodide.org/en/stable/), thank you!), and application hosting without the reliance on server-side configuration
* **Python ecosystem**: Run many popular packages of Python and the scientific stack (such as numpy, pandas, scikit-learn, and more)
* **Python with JavaScript**: Bi-directional communication between Python and Javascript objects and namespaces

To me, this makes it sound like Pyodide is an external file hosting service. I think this could be re-worded to make it clear that Pyodide (IIUC) is helping PyScript by providing the "engine" that runs the Python code, plus the packages in the scientific stack and the bi-directional communication?

(I wasn't able to find a repo for the website to submit a pull request for this, so filing an issue here instead - sorry if there was a better place to file this!)

**Comment by antocuni** [comment]
I agree that the home page is a but confusing. I forwarded your suggestion to the team who takes care of the home page

**Comment by nmstoker** [comment]
Looks like the reference to Pyodide is no longer next to the external file hosting point, so it seems like this has been resolved

**Comment by antocuni** [comment]
I confirm that the home page no longer mentions pyodide. Closing this as resolved. thanks @josephrocca and @nmstoker for helping!

**Comment by josephrocca** [comment]
The home page still mentions Pyodide (which is good!), but now it's clear how Pyodide is involved in the project:

> PyScript is a framework that allows users to create rich Python applications in the browser using HTML's interface and the power of [Pyodide](https://pyodide.org/en/stable/), [WASM](https://webassembly.org/), and modern web technologies.

So this issue is indeed resolved. Thanks!
