### ISSUE TITLE
[FEATURE] Versioned CDN URLs instead of hosting on pyscript.net

### ISSUE THREAD

**Issue by josephrocca** [pyscript/pyscript#309]
Currently the script/CSS are served from `pyscript.net/alpha`. In the web dev community it's common to use a well-known and trusted CDN like [JSDelivr](https://www.jsdelivr.com/) or [Unpkg](https://unpkg.com) for serving libraries. This has several benefits:

1. It means that the PyScript team doesn't need to worry about the security and up-time of their website anywhere near as much. If PyScript becomes popular (which I hope it does!) then it will become increasingly dangerous to make mistakes with hosting the script.
2. Published packages on jsdelivr/unpkg are [semantically versioned](https://semver.org/), and immutable, which is a great contract for developers.
3. It is less likely that jsdelivr/unpkg would shut down in the future, given the vast number of web pages that rely on them. Using a CDN service prevents all the websites that import the file from pyscript.net from breaking if the pyscript.net website for some reason goes offline in the far, far future.

As an example, Pyodide's getting started tutorial directs users to use this jsdelivr URL: https://cdn.jsdelivr.net/pyodide/v0.20.0/full/pyodide.js

It may be that the pyscript.net hosting is simply due to the early nature of the project, and it'll soon move to a CDN. If that's the case, then I'd really recommend moving to a CDN as soon as possible, because some developers may already be using the alpha pyscript.net URL, and (falsely) expecting it to continue to work in perpetuity. Also, it would be great to be able to experiment with PyScript today without worrying about things breaking due to the lack of URL versioning.

Thanks!

**Comment by pww217** [comment]
It's still very much up in the air where things will be hosted ultimately. That decision is likely to be made my maintainers. For my part working on the CI currently, it'll probably be hosted by Anaconda for the time being.

I am generally supportive of moving to a dedicated artifact store - or multiple even - in time. I know the pyscript-cli is uploaded to PyPi already. I think there need to be a discussion and decision made a bit higher up, however. I'll try to put this on the maintainers' radar.

Thanks for getting this discussion going, though.

**Comment by marimeireles** [comment]
We set up a similar system to the one implemented by Pyodide, thanks for the patience here! :)

**Comment by pww217** [comment]
Yep we do have a versioned release system now, and uploading to package hosters/CDNs is likely in the future.

**Comment by josephrocca** [comment]
Any chance this could be re-opened until there's a CDN URL? One option is to publish `pyscript.js` and `pyscript.css` in a `dist` folder in this repo, and then these URLs will work:
```
https://cdn.jsdelivr.net/gh/pyscript/pyscript@2022.12.1/dist/pyscript.css
https://cdn.jsdelivr.net/gh/pyscript/pyscript@2022.12.1/dist/pyscript.js
```
I know some people are squeamish about having a `dist` in the source tree though (but personally I love it when projects do this - often makes my life easier). But to be clear the main point of this comment is to ask if this can be re-opened until we get a CDN URL, rather than to suggest the above approach.
