### ISSUE TITLE
[FEATURE] How to display list elements in HTML tags using for loop?

### ISSUE THREAD

**Issue by lakhdar-blk** [pyscript/pyscript#315]
<html>
        <py-script>
            ls = ['name1', 'name2', 'name3']

            for name in ls : 

                     " how to display for example all names in h1 tag"

        </py-script>            

</html>

**Comment by michavardy** [comment]
the following HTML  works
for some reason it prints  `[None, None, None, None]` at the end if I use list comprehension, 
when I commented the list comprehension out it worked as expected
I based the code off of this reference: https://developer.mozilla.org/en-US/docs/Web/API/Document/createElement

```
<HTML>
    <HEAD>
         <meta name="reference" content="https://developer.mozilla.org/en-US/docs/Web/API/Document/createElement">
         <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
         <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
    </HEAD>
    <BODY>
       <h1 id="title">list elements</h1>

       <py-script>


def add_element(index,messg):
    # create a new div element
    newDiv = document.createElement("div")
    
    # and give it some content
    newContent = document.createTextNode(f'{messg}')
    
    # add the text node to the newly created div
    newDiv.appendChild(newContent)

    # add id
    newDiv.setAttribute("id", f"id_{index}");
    
    # add the newly created element and its content into the DOM
    currentDiv = document.getElementById("title");
    document.body.insertBefore(newDiv, currentDiv);

# list of strings
list = ['computer', 'calculator', 'ruler', 'pencil']
# iterate through list of strings and add them as elements
#[add_element(index,messg) for index,messg in enumerate(list)]
for index,messg in enumerate(list):
        add_element(index,messg)

       </py-script>
    </BODY>
 </HTML>
```

**Comment by John-Schreiber** [comment]
Oddly, if I just use the comprension, I get the same  [None, None, None] as @michavardy, but if its not the last line in my code, it won't appear, so I included a pass as my last line. 

```
from js import document

def createitem(text, id):
    div = document.createElement("H4")
    div.id = id
    div.innerText = text
    document.body.append(div)


[createitem(x, i) for i, x in enumerate(namelist)]
pass
```

**Comment by michavardy** [comment]
weird

**Comment by sugatoray** [comment]
@michavardy @John-Schreiber 

My hunch is the defined behavior to handle a list of html elements is probably not yet created. 

So, perhaps try passing the following and PyScript (hopefully) would know what to do then. 

```python
*[add_element(index,messg) for index,messg in enumerate(list)]
```

**Comment by marimeireles** [comment]
This is a duplicate, but right now I'm not being able to find it, sorry.
If you look a little bit on the issues here you might find it!
If I do find it before you do I'll update it here for you =)

**Comment by JeffersGlass** [comment]
The API has progressed quite a bit since this original issue; to cover the original need, in the current build, one can do:
```python
names = ['lakhdar-blk', 'michavardy', 'sugatory']
for name in names:
    display(names)
```
or use`document.createElement` as [John suggested](https://github.com/pyscript/pyscript/issues/315#issuecomment-1122724189) for more fine-grain control of the HTML elements created.

The issue of `[None, None, None, None]` being printed is also resolved. The pyodide function `runPython()`, which PyScript uses under the hood to evaluate Python code, by default returns the value of the last expression to stdout, much like a REPL. We no longer pass this returned value on to stdout or to the screen.
