### ISSUE TITLE
[FEATURE] input / select onchange event handling

### ISSUE THREAD

**Issue by Muhammadinaam** [pyscript/pyscript#316]
How can we handle input's onchange events?

**Comment by Cerchie** [comment]
Thanks for that example, @JeffersGlass ! It helped me make this simple example repo. https://github.com/Cerchie/pyscript-example/

**Comment by marianoweber** [comment]
Nice work!
I created a quick PR(#467) to add `pys-onInput` and `pys-onChange` to make this a bit easier in the future.

**Comment by JeffersGlass** [comment]
This was implemented by #561 - this issue can probably be closed.

**Comment by marimeireles** [comment]
Thanks for the feedback @JeffersGlass!

**Comment by JeffersGlass** [comment]
Thanks @marimeireles - for anyone finding this issue in the future, as of release 2022.09.1, you can also use the  [add_event_listener utility function](https://pyodide.org/en/stable/usage/api/python-api/ffi.html#pyodide.ffi.wrappers.add_event_listener) from Pyodide 21. It handles proxy creation for you as well.

```python
<py-script>
  from js import document

  from pyodide.ffi.wrappers import add_event_listener
  def say_bye(*args):
    print(f"Goodbye!")
  
  tag = document.getElementById("my-div")
  add_event_listener(tag, "click", say_bye)
</py-script>

```
