### ISSUE TITLE
[BUG] Error: Pyscript not loading when RequireJS is included on the page

### ISSUE THREAD

**Issue by SlendyBoy** [pyscript/pyscript#317]
Hello, I'm coding an activity module on Moodle. This module will allow the analysis of quiz data from Moodle courses. 
 
In Moodle's footer, RequireJS is included and the navigation drawers work thanks to RequireJS.  

- Firefox : version 100.0  
- Moodle : version 3.10.7+ (Build: 20211102)
- RequireJS: version 2.3.5

I'm getting these errors in the console when RequireJS is included :  
<img width="214" alt="loadPyodide" src="https://user-images.githubusercontent.com/71551466/167631902-d68a79f2-b474-4018-baa6-088617801364.PNG">
<img width="513" alt="requirejs" src="https://user-images.githubusercontent.com/71551466/167631923-a632f286-a289-44a8-99d3-b6e24a856638.PNG">

Thanks for your help !

**Comment by antocuni** [comment]
I don't have much JS experience, but it seems to be that `RequireJS` is probably defining a global name which clashes with some other global name used by pyodide?
@SlendyBoy can you please submit a minimal example which reproduces the issue? Ideally a single HTML page which we can just load in the browser and that shows the error, without having to install moodle.

**Comment by imjul1an** [comment]
can you please provide an example, so we can reproduce and play around?

**Comment by rth** [comment]
On the Pyodide side, we had some issues with require.js in the past https://github.com/pyodide/pyodide/issues/2282 . That one was fixed, but since we don't test require.js  integration it is possible there were other issues since. We also generally lack contributors with good knowledge of JS packaging tools. In any case, a minimal example to reproduce would indeed help.

**Comment by imjul1an** [comment]
@rth I'll be happy to look into that!

**Comment by WebReflection** [comment]
Hopefully RequireJS is not used much anymore but right now PyScript is a standard ECMAScript module so this issue does not exist anymore.
