### ISSUE TITLE
Add SRI to hotlinking examples

### ISSUE THREAD

**Issue by mflaxman** [pyscript/pyscript#326]
Given the security implications of pyscript, it makes sense to recommend [SRI](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) when hotlinking `pyscript.js`:

```
<script
    defer
    src="https://pyscript.net/alpha/pyscript.js"
    integrity="sha384-IwRwL1M346tP5zp9BKvjinCQC8x78+d+KCeRonZ6gO4XgSBop4cJegZ+SV++AhMR"
    crossorigin="anonymous"
></script>
```

Integrity check was calculated successfully as follows:
```
$ curl https://pyscript.net/alpha/pyscript.js | openssl dgst -sha384 -binary | openssl base64 -A
IwRwL1M346tP5zp9BKvjinCQC8x78+d+KCeRonZ6gO4XgSBop4cJegZ+SV++AhMR
```

Of course this will create issues when updating `pyscript.js`, so these links really should be version-pinned (I assume that's what `/alpha/` means in this context).

**Comment by verhulstm** [comment]
which  security implications of pyscript?

**Comment by mflaxman** [comment]
An example:
1. Webpage imports `pyscript.js` using only the recommended method:  `<script defer src="https://pyscript.net/alpha/pyscript.js"></script>`
2. pyscript.net has previously been compromised to serve a malware version of `pyscript.js`
3. Code that is believed to do X actually does Y thanks to malware

This is not a theoretical example, let's say you want to build an app that encrypts data. How could you know that you weren't interacting with malware that was stealing your private keys? SRI is built to solve this problem (and many others).

**Comment by ckavidas** [comment]
I think there was an issue related to setting up a CDN (#309) and this should be a requirement underneath that issue no?

**Comment by mflaxman** [comment]
I think you want SRI regardless of whether you use a 3rd party CDN or whether you use pyscript.net as your CDN. From the perspective of the app developer, both are 3rd parties. 

Having an official hash digest is great, because then ultimately developers don't care who serves up that JS. Using SRI nearly eliminates the risk that a third party has tampered with pyscript.js. In other words, even if pyscript.js were published on a CDN (or many), I'd want to get the hash digest directly from the project authors.

**Comment by verhulstm** [comment]
the security implications of pyscript are the same as the security implications of JS and WASM right?

what is special or different about pyscript?

**Comment by verhulstm** [comment]
it seem to be you are saying all new web projects that pull code from a CDN should use SRI?

**Comment by verhulstm** [comment]
i am trying to ask if you know of a specific security implication of pyscript that does not also exist in JS or WASM?

**Comment by ckavidas** [comment]
> the security implications of pyscript are the same as the security implications of JS and WASM right?
> 
> what is special or different about pyscript?

They are the same security implications that would exist with any third party dependency (example: bootstrap). SRI exists to help ensure the integrity of the software aka: 
"This software came from vendor_x because it included hash_y in the official release of the software"

This would certainly make people more comfortable about including pyscript in their websites since it would minimize the impact of the source of the pyscript files being compromised since any compromise would (in 99.999999999999999999999%  of the time) produce a hash different from the one in the website thus failing the integrity check.

**Comment by verhulstm** [comment]
i thinks we should be able to enable SRI

**Comment by fpliger** [comment]
Thanks @mflaxman , this is a great suggestion. It's definitely worth exploring/considering after we get #337 sorted.

**Comment by WebReflection** [comment]
I am not sure why semver or any other versioning would solve the inherent issue described in here, but that decision has been made and we still land on CDN and I think that's the right thing to do.

Closing until further explanations or reasons around this issue ... we're almost CSP complaint too, if the hash for the Worker and the WASM source is enabled, so I *think* this issue can be closed.
