### ISSUE TITLE
Directory recognition problem

### ISSUE THREAD

**Issue by hygorrasec** [pyscript/pyscript#338]
Hello guys, I'm not sure if it's a mistake or if I'm doing something wrong. Can anybody help me?

The function below works well on the console. But when I try to print using PyScript and the Live Server extension, I get the following error:

```
with open(r"C:\Python\readme.txt") as f:
    lines = f.readlines()
    print(lines)
```

Console print: `['Text line 1\n', 'Text line 2\n', 'Text line 3']`

Error on Browser:
JsException(PythonError: Traceback (most recent call last): File "/lib/python3.10/site-packages/_pyodide/_base.py", line 429, in eval_code .run(globals, locals) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 300, in run coroutine = eval(self.code, globals, locals) File "", line 12, in FileNotFoundError: [Errno 44] No such file or directory: 'C:\\Python\\readme.txt' )

**Comment by ckavidas** [comment]
The error you are receiving is that pyscript cannot read your "readme.txt" file. This is a security feature of your web browser (don't want some javascript reading your personal files do you?). 

Please take a look at the image below:
![image](https://user-images.githubusercontent.com/49797382/167935130-471f8ac7-6de5-430f-ac94-68107857f88f.png)
The "file system" is from emscripten (think of it as a web assembly "container") to get your files onto this "container" you need to upload them. One method of achieving this is to create a form on your page and write the raw bytes to a file.

**Comment by hygorrasec** [comment]
@ckavidas can you explain to me why `print(os.listdir("/"))` prints `['tmp', 'home', 'dev', 'proc', 'lib']` ?

**Comment by ckavidas** [comment]
> @ckavidas can you explain to me why `print(os.listdir("/"))` prints `['tmp', 'home', 'dev', 'proc', 'lib']` ?

You can read the emscripten file system API documentation [here](https://emscripten.org/docs/api_reference/Filesystem-API.html#filesystem-api)

As you can see in the architecture above, pyscript is built on top of pyodide which includes the emscripten "container". The file system you are seeing when you run those python commands is the file system of emscripten. 

This file system is ephemeral and lives entirely in your web browser.

**Comment by pnhearer** [comment]
> The error you are receiving is that pyscript cannot read your "readme.txt" file. This is a security feature of your web browser (don't want some javascript reading your personal files do you?).
> 
> Please take a look at the image below: ![image](https://user-images.githubusercontent.com/49797382/167935130-471f8ac7-6de5-430f-ac94-68107857f88f.png) The "file system" is from emscripten (think of it as a web assembly "container") to get your files onto this "container" you need to upload them. One method of achieving this is to create a form on your page and write the raw bytes to a file.

Quick question, what's the utility of the JavaScript Bridge? is this permanent or is there another solution in the works to get rid of this dependency?

**Comment by verhulstm** [comment]
we want interoperability between js and python, but we dont want users to have to use js

**Comment by pnhearer** [comment]
> we want interoperability between js and python, but we dont want users to have to use js

So it's not a dependency, just an interoperability thing?

**Comment by pnhearer** [comment]
> The error you are receiving is that pyscript cannot read your "readme.txt" file. This is a security feature of your web browser (don't want some javascript reading your personal files do you?).
> 
> Please take a look at the image below: ![image](https://user-images.githubusercontent.com/49797382/167935130-471f8ac7-6de5-430f-ac94-68107857f88f.png) The "file system" is from emscripten (think of it as a web assembly "container") to get your files onto this "container" you need to upload them. One method of achieving this is to create a form on your page and write the raw bytes to a file.

Is there a "Blown-up" version of this image that doesn't have the ellipses?

**Comment by ckavidas** [comment]
Maybe the Anaconda guys have one?

https://www.anaconda.com/blog/pyscript-python-in-the-browser

**Comment by verhulstm** [comment]
its a dependency. but you dont need to see or use it.

in other words if you disable js in the browser pyscript wont work

**Comment by verhulstm** [comment]
making a version that runs in a browser that has no JS is very complicated and not on the roadmap at this time

**Comment by ckavidas** [comment]
At the end of the day your browser is a HTML/CSS renderer and a JS interpreter. Without JS none of these things are possible.

**Comment by verhulstm** [comment]
i am fine with re-making the diagram image with a smaller "JS bridge" box. 

yes, in that diagram the JS bridge might be over emphasized

**Comment by pnhearer** [comment]
> its a dependency. but you dont need to see or use it.
> 
> in other words if you disable js in the browser pyscript wont work

Wait, so if you disable JS this thing DOESN'T WORK? What? R.I.P. That sucks.

**Comment by pnhearer** [comment]
> i am fine with re-making the diagram image with a smaller "JS bridge" box.
> 
> yes, in that diagram the JS bridge might be over emphasized

I'd much appreciate it. Thank you verhulstm. I enjoy learning visually.

**Comment by marimeireles** [comment]
We're soon going to have amazing docs on it!
Keep an eye on the work that Domink is doing https://github.com/pyscript/pyscript/issues/595#issuecomment-1265382412
Cheers, folks.
