### ISSUE TITLE
[BUG] Demo pages not (fully) loading

### ISSUE THREAD

**Issue by oaustegard** [pyscript/pyscript#342]
**Describe the bug**
The Demo pages at https://pyscript.net/examples/ partially load but eventually time out waiting for https://pyscript.net:35729/livereload.js

**To Reproduce**
For me (Chrome, Mac OS, both latest, both in regular and incognito mode), load any demo, e.g. https://pyscript.net/examples/matplotlib.html

**Expected behavior**
I expect for the demo page to load and to be wowed

**Screenshots**
<img width="1288" alt="image" src="https://user-images.githubusercontent.com/3268739/167974420-1dc55efa-aec9-4d7b-81c3-e2b459e99b18.png">

**Additional context**
None

**Comment by pnhearer** [comment]
Also there appears to be no link to the Mario game in the demo page, which is sad.
