### ISSUE TITLE
[BUG] pyparsing version in py-env tag is ignored

### ISSUE THREAD

**Issue by ptmcg** [pyscript/pyscript#343]
**Describe the bug**
Adding this entry in the py-env tag does not get the desired version of pyparsing:

    - pyparsing==3.0.9

Still get version 3.0.7.

**To Reproduce**
Use this HTML:

```
<html>
    <head>
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
    <py-env>
        - pyparsing==3.0.9
    </py-env>
    </head>
    <body>
        <py-script>
import pyparsing as pp
print(pp.__version__)
        </py-script>
    </body>
</html>
```

**Expected behavior**
Display of 3.0.9

**Screenshots**
Browser shows 

    3.0.7

**Comment by ckavidas** [comment]
![image](https://user-images.githubusercontent.com/49797382/167984404-df9feab3-e7b7-4d09-8d50-5d5a0ac55e42.png)


I tested in a py-repl and I was able to install a versioned package using `micropip.install('pyparsing==3.0.9')` 

But I also noticed that pyparsing is already installed (as version 3.0.7 from pyodide).

See this table:
![image](https://user-images.githubusercontent.com/49797382/167984538-097b93c8-c1c2-4524-8bc1-ff60e1e9ae9b.png)

After installing however:
![image](https://user-images.githubusercontent.com/49797382/167984615-ed25ef9f-f5c9-4ca7-8441-692c3b63ee5a.png)


Feel free to use micropip package as a workaround until a developer can get to the root why it doesn't work in the py-env tag.

**Comment by ptmcg** [comment]
py-repl does not seem to be equivalent to a browser running code inside `<py-script>` tags:

```
<html>
    <head>
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
    </head>
    <body>
        <py-script>
import micropip
micropip.install("pyparsing==3.0.9")

import pyparsing as pp
print(pp.__version__)
        </py-script>
    </body>
</html>
```

Still shows as 3.0.7, not 3.0.9.

Did I misread or misunderstand your workaround?

**Comment by rth** [comment]
The issue is that micropip requires pyparsing, and loads `3.0.7`. So when you install a different version, it's already imported and what you see is the previously imported version,
```py
>>> import micropip
>>> await micropip.install('pyparsing==3.0.9')
>>> micropip.list()
Name      | Version | Source
--------- | ------- | -------
pyparsing | 3.0.9   | pypi
distutils | 1.0     | pyodide
micropip  | 0.1     | pyodide
packaging | 21.3    | pyodide
>>> import pyparsing
>>> pyparsing.__version__
'3.0.7'
```
you need to explicitly reload the module to update it,
```py
>>> import importlib
>>> importlib.reload(pyparsing)
<module 'pyparsing' from '/lib/python3.10/site-packages/pyparsing/__init__.py'>
>>> pyparsing.__version__
'3.0.9' 
```
And this is what likely happens in pyscript since it uses micropip internally.

So overall it's likely the expected behavior.

**Comment by ptmcg** [comment]
Success! See this gist: https://gist.github.com/ptmcg/09b5be0cb3623a478851100488788821

**Comment by ptmcg** [comment]
Not a terrible workaround. Maybe in the future the `<py-script>` tag handler could do this for me.

**Comment by marimeireles** [comment]
This will soon be outdated by https://github.com/pyscript/pyscript/pull/775, I believe.
