### ISSUE TITLE
[BUG]Empty py-env tags result in error in console

### ISSUE THREAD

**Issue by ptmcg** [pyscript/pyscript#345]
**Describe the bug**
An empty `<py-env></py-env>` tag pair generates this error in the developer console:

```
pyenv.ts:41 
        
       Uncaught TypeError: this.environment is not iterable
    at PyEnv.connectedCallback (pyenv.ts:41:34)
    at main.ts:14:31
    at main.ts:23:2
```

**To Reproduce**
Use this HTML

```
<html>
    <head>
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
    <py-env>
    </py-env>
    </head>
    <body>
        <py-script>
print("Hey there, world!")
        </py-script>
    </body>
</html>
```

**Expected behavior**
Empty tags should do nothing gracefully.

**Additional context**
Not a super high priority issue, the page still displayed the expected message (though nothing's to say that a more complex page wouldn't have a problem).

**Comment by JeffersGlass** [comment]
Looks like this was fixed in PR #271 from May 7- so you'll still see that issue if you're using the alpha release, but not if you build from source, and presumably will be fixed in the next release.
