### ISSUE TITLE
Activate the `Discussions` tab from repository settings

### ISSUE THREAD

**Issue by sugatoray** [pyscript/pyscript#348]
Please activate the discussions tab so questions, announcements, and anything that is strictly not an issue candidate, could live under the discussions tab. You can easily change a discussion topic into an issue or vice versa. 

- https://docs.github.com/en/discussions/quickstart#enabling-github-discussions-on-your-repository

### The backstory of Python on WebAssembly that led to PyScript

The reason behind asking this is I wanted to share this video discussion among some of the python core devs on how all this happened and who were involved in making Python + WASM possible and are maintaining it. 

YouTube: https://youtu.be/Xnl5HC_Tq70/?t=3710

```html
<iframe width="560" height="315" src="https://www.youtube.com/embed/Xnl5HC_Tq70?start=3710" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```

🎁 [LinkedIn post](https://www.linkedin.com/posts/sugatoray_removing-pythons-dead-batteries-talk-python-activity-6930473088933408768-whGv?utm_source=linkedin_share&utm_medium=ios_app)

**Comment by sugatoray** [comment]
cc: @philippjfr @fpliger @verhulstm

**Comment by philippjfr** [comment]
Based on our internal discussions we are not currently considering enabling the discussions tab. For now we have designed the [anaconda.cloud community forum](https://community.anaconda.cloud/c/tech-topics) as the appropriate place for discussions. This probably needs to be communicated better and we may revisit that decision at a later stage.

**Comment by sugatoray** [comment]
@philippjfr Thank you, for the update.

**Comment by marimeireles** [comment]
Yes, I think this is a close for now... We're still using the discourse as a community forum.
But we do have a space for your video @sugatoray, for now we have an awesome list and we'd love to host it there!
Please open a PR on the pyscript-collective and change this file adding yourself there: https://github.com/pyscript/pyscript-collective/blob/main/awesome-pyscript.md
Cheers and thank you for the contribution! ❤️

**Comment by sugatoray** [comment]
@marimeireles Sounds good. Thank you. Will send a PR.
