### ISSUE TITLE
[BUG] HTML Table tag emitted from script accepts some attributes but not "border"

### ISSUE THREAD

**Issue by ptmcg** [pyscript/pyscript#349]
**Describe the bug**
I would like to generate an HTML table as part of my script, and this works mostly. I can specify "cellpadding" attribute, and see the results in the output. But specifying a "border" attribute has no effect.

**To Reproduce**
This HTML code fails, it creates the TABLE and correctly does the cellpadding. But does not display a border.

```
<html>
    <head>
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
    <py-env>
        - pyparsing==3.0.9
        - railroad-diagrams
        - jinja2
    </py-env>
    <py-script>
# force reload of latest pyparsing
import pyparsing
import importlib
importlib.reload(pyparsing)
    </py-script>

    </head>

<body>

<table cellpadding=30 border=10>
<tr>
<td>
<pre>
import pyparsing as pp

integer = pp.Word(pp.nums)
word = pp.Word(pp.alphas, pp.alphas+".")
street_name = pp.Group(word[1, ...])
street_address = (integer + street_name)

pp.autoname_elements()
street_address.create_diagram(output_html="diag.html")

print(street_address.parse_string("123 Main St."))

</pre>
</td>
<td>
<py-script>
import io
import pyparsing as pp

integer = pp.Word(pp.nums)
word = pp.Word(pp.alphas, pp.alphas+".")
street_name = pp.Group(word[1, ...])
street_address = (integer + street_name)

pp.autoname_elements()
diag_html = io.StringIO()
street_address.create_diagram(output_html=diag_html)
print(diag_html.getvalue())
</py-script>
</td>
</tr>
<tr>
<td/>
<td>
<py-script>
print(street_address.parse_string("123 Main St."))
</py-script>
</td>
</tr>
</table>
</body>
</html>
```

**Expected behavior**
Would like the displayed table to show cell borders.

**Comment by JeffersGlass** [comment]
I don't believe this is an error in PyScript - rather, the `border` attribute of the `<table>` tag is deprecated. Preferred usage is now to [use CSS for table borders](https://www.w3schools.com/html/html_table_borders.asp):

- `<table cellpadding=30 style="border:2px solid black;">` for the exterior border of the table
- `<td style="border:2px solid black; border-collapse: collapse;">` for single borders around cells

**Comment by ptmcg** [comment]
HTML features are deprecated for many many years but still supported in browsers. For that matter, I think "cellpadding" is deprecated too.

If I save a raw HTML file containing a simple table, with the "border" attribute on the table tag, all the browsers I've tried render it properly. So what is getting in the way here?

**Comment by JeffersGlass** [comment]
Ah, it's pyscript.css that's doing it. For this example you don't really need it, I suspect - it's mostly there to make some of the components (REPL, button) look good.

Commenting out/removing the line `<link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />` gives me a border.
