### ISSUE TITLE
[FEATURE]write browser extensions/plugins with pyscript

### ISSUE THREAD

**Issue by andrewchenshx** [pyscript/pyscript#350]
As a python programmer, i hope i could write browser extensions/plugins with pyscript.
thanks

**Comment by jezdez** [comment]
There was a Firefox extension back in the day using Pyodide that may be a good inspiration: https://github.com/birdsarah/pyconsole

**Comment by marimeireles** [comment]
I'm not sure this is an actual issue though.
Do we have any actual problems here?
Feel free to re-open with more information!
Thanks.
