### ISSUE TITLE
add examples to home page to show what cool things PyScript is capable of [FEATURE]

### ISSUE THREAD

**Issue by pgbovine** [pyscript/pyscript#352]
**Is your feature request related to a problem? Please describe.**
As a first-time visitor to the PyScript home page, I don't really know what it's capable of doing. All I see is a print("Hello world") example, which is possible already with Pyodide.

**Describe the solution you'd like**
I'd love for some of the [examples in this directory](https://github.com/pyscript/pyscript/tree/main/pyscriptjs/examples) to be live-loaded on the PyScript home page. If load-time performance is an issue, then I'd suggest taking static screenshots of examples and then linking to the examples on separate pages.

**Describe alternatives you've considered**
Taking screenshots of examples and putting them on the home page feels like a lighterweight alternative. D3.js does this *[really well](https://d3js.org/)*

**Additional context**
By browsing through the GitHub repo examples, I am guessing that PyScript is a GUI library that lets you conveniently take your existing Python code and interface it seamlessly with the browser. I'd love for this to shine through more on the home page itself. 

Thanks for your consideration, and best wishes with this project!

**Comment by siddhi** [comment]
To add on to this, I think the documentation on the website in general can be greatly improved. I mean there is no actual doc right now. If the an outline of the docs can be created and the code put on github, I'm sure many would contribute PRs to write up the documentation.
