### ISSUE TITLE
Error while trying to use requests package to consume api

### ISSUE THREAD

**Issue by AdeboyeDN** [pyscript/pyscript#357]
Been try to import requests used the `<py-env>` tag and got this error also imported in a `.py` file same error can i get a example on how to do that 

![image](https://user-images.githubusercontent.com/65312338/168221329-7492a9a8-eead-4073-b6c0-920d22e95585.png)
![image](https://user-images.githubusercontent.com/65312338/168221409-5ab780d0-9dba-4566-9a08-caa616168044.png)
![image](https://user-images.githubusercontent.com/65312338/168221460-41b9fbe2-a77e-4a92-92d4-42a5ebefa201.png)

**Comment by marianoweber** [comment]
I guess #319 could be of interest for you.

**Comment by AdeboyeDN** [comment]
Thanks not so cool that i can't find a way of consuming api pyscript but hope i would be able to in the future
