### ISSUE TITLE
[BUG] Sane output shows up in error box

### ISSUE THREAD

**Issue by marimeireles** [pyscript/pyscript#358]
**Describe the bug**
Sane output shows up in error box if you errored first and then fixed it.

**To Reproduce**
Use `py-repl`, write something that doesn't evaluate, get an error report.
Correct the code and print some output.
The error is not flushed and the output comes out in the same error screen.

**Expected behavior**
The error output should disappear once we fix the code and new code shouldn't show up inside the error box.

**Screenshots**
<img width="1725" alt="Screenshot 2022-05-13 at 11 12 43" src="https://user-images.githubusercontent.com/17600982/168302986-ba937811-d2ca-44c1-b8e5-392810b88f13.png">

**Comment by marimeireles** [comment]
Or maybe that's the desired behavior?

**Comment by pnhearer** [comment]
> Or maybe that's the desired behavior?

To what utility?

**Comment by marimeireles** [comment]
Just opening up space for conversation. Can't really think of anything.
Seems like something that should be fixed.

**Comment by marianoweber** [comment]
Should be fixed with #372.

**Comment by yannickfunk** [comment]
This has been fixed in the meantime
