### ISSUE TITLE
[BUG] pys-onClick attribute does not work, when element has no id

### ISSUE THREAD

**Issue by yannickfunk** [pyscript/pyscript#359]
**Describe the bug**
When you whant to use the pys-onClick attribute to define a python function as the click listener, and the html element has no id, it does not work.

Error:
```
pyodide.asm.js:14 Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 500, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 351, in run_async
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 1, in <module>
  File "<exec>", line 141, in element
JsException: SyntaxError: Failed to execute 'querySelector' on 'Document': '#' is not a valid selector.
```

**To Reproduce**
Using:  
* Chrome Version 101.0.4951.67
* Firefox Version 100.0 (64-bit)

Use this html and click on the button:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
</head>

<body>
	<py-script>
from js import console
def clicked(*args, **kwargs):
	console.log("clicked")
	</py-script>
	
	<button pys-onClick="clicked">Click me!</button>
	
</body>
</html>
```

**Expected behavior**
The message "clicked" should be logged to the console. With an id it works:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
</head>

<body>
	<py-script>
from js import console
def clicked(*args, **kwargs):
	console.log("clicked")
	</py-script>
	
	<button id="click-button" pys-onClick="clicked">Click me!</button>
	
</body>
</html>
```

EDIT: Added chrome, firefox version number

**Comment by yannickfunk** [comment]
I guess this: https://github.com/pyscript/pyscript/blob/a3e86f32b7f0642015c0c991ce49683b59eea47d/pyscriptjs/src/components/pyscript.ts#L139 is the related code, it uses the id to pass it to create an `Element()` and pass it to `pyodide.runPythonAsync(source)`. However, there should be another possibility then the Id to create this Element

**Comment by pnhearer** [comment]
> I guess this:
> 
> https://github.com/pyscript/pyscript/blob/a3e86f32b7f0642015c0c991ce49683b59eea47d/pyscriptjs/src/components/pyscript.ts#L139
> 
> is the related code, it uses the id to create an `Element()` and pass it to `pyodide.runPythonAsync(source)`. However, there should be another possibility than the Id to create this Element

Looks right. Not sure by what other mechanism you can reference the element though other than maybe 'self' if no element id is specified?

**Comment by pauleveritt** [comment]
I'm actually getting this with hello_world.html from a checkout. The checkout worked a few days ago. I can't spot any changes in the commits that might have caused it. Still pointing to 0.20 of Pyodide.

**Comment by pauleveritt** [comment]
As it turns out, I get the exception in Chrome, not in Firefox or Safari:

```JsException: SyntaxError: Failed to execute 'querySelector' on 'Document': '#-509153c5-29df-0d1d-f9fd-c7c688f46911' is not a valid selector.```

As it turns out, I believe that is indeed an invalid selector. A dash can't be followed by a number.

**Comment by nmstoker** [comment]
I'm seeing as well: in Chrome with the basic hello world from [Getting Started](https://github.com/pyscript/pyscript/blob/main/GETTING-STARTED.md#your-first-pyscript-html-file).

I only get it intermittently - I guess that when i'm refreshing and that GUID type Id happens to have a dash followed by a number (as @pauleveritt mentions) then it fails and other times when I'm lucky enough not to get that it succeeds

**Comment by pauleveritt** [comment]
(Sorry for the noise.) A little bit more info. I was using the examples from a `build` directory generated by the `build` npm script. If I use `dev`, then the above has `#PyScript-50` etc.

**Comment by pauleveritt** [comment]
@nmstoker It appears `Element.__init__()` is passed a different `element_id` based on whether you run from a production build or the dev server. The latter is prefixed (correctly) with `PyScript`. The former is an empty string.

Am I looking at it correctly?

**Comment by yannickfunk** [comment]
> As it turns out, I get the exception in Chrome, not in Firefox or Safari:
> 
> `JsException: SyntaxError: Failed to execute 'querySelector' on 'Document': '#-509153c5-29df-0d1d-f9fd-c7c688f46911' is not a valid selector.`
> 
> As it turns out, I believe that is indeed an invalid selector. A dash can't be followed by a number.

But I think this is a different error than mine, here '-509153c5-29df-0d1d-f9fd-c7c688f46911' appears to be the element's id. In my case there is no id at all

**Comment by yannickfunk** [comment]
I can also reproduce the issue using firefox 100.0 (64-bit)

**Comment by yannickfunk** [comment]
I can also reproduce with a locally built pyscript.js

**Comment by yannickfunk** [comment]
One fix would be to actually pass the element to python in the `initHandlers()` like this:

```js
const handlerCode = el.getAttribute('pys-onClick');
const elementGlobals: Map<string, any> = pyodide.globals.toJs()
elementGlobals.set("element", el)
const options = {globals: pyodide.toPy(elementGlobals)};

source = `Element("${el.id}", element).element.onclick = ${handlerCode}`;
output = await pyodide.runPythonAsync(source, options);
```

This way, 
```python
@property
    def element(self):
        """Return the dom element"""
        if not self._element:
            self._element = document.querySelector(f"#{self._id}")
        return self._element
```

doesn't fail, because the python `Element` has the actual dom element attached

**Comment by ptmcg** [comment]
I am seeing this even without a button or onClick method - should I open a separate ticket?

Reproduce by viewing this page: http://[ptmcg.com/dev/pyscript/pyparsing_railroad_diagram.html](http://ptmcg.com/dev/pyscript/pyparsing_railroad_diagram.html)

**Comment by yannickfunk** [comment]
@ptmcg It is already discussed here: https://github.com/pyscript/pyscript/issues/370

**Comment by fpliger** [comment]
@yannickfunk can you try now? #395 should have temporarily fixed it (although we need to investigate to actually come with a better fix)

**Comment by yannickfunk** [comment]
@fpliger The error described by me here initially, is NOT the same error as in #370 and as expected is not fixed by #395

**Comment by fpliger** [comment]
Ok, let me test it locally.

**Comment by yannickfunk** [comment]
I also tested it with a local unminified build on chrome and firefox

**Comment by fpliger** [comment]
Ah! Yeah.. Not the same issue. I think problem here is that we are not properly mapping the `<py-script>` when we generate the output `div`

TY!

**Comment by pauleveritt** [comment]
@fpliger @yannickfunk Fixed it for me.

**Comment by fpliger** [comment]
Nice! @yannickfunk that's exactly what's happening. The initially easy "fix" about this is to add an `id` to the `<py-button>` component. 

In the long term, I think it'd make sense for us to enforce `id` on every element you add PyScript magic. It **is** a good practice anyway that we should encourage and makes a lot of the PyScript easier and more explicit. But this is an important decision and probably needs some thinking. Worth opening a dedicated discussion.

**Comment by fpliger** [comment]
> @fpliger Ok so I just found out it actually makes a difference.
For <py-button> the easiest would be to dynamically add an id as for the <pyscript> element (with the checkID() method):

We are answering at the same time :)

Right. That's very easy to do but I don't think we have it in `<py-button>` yet. That's what I meant with the previous comment

**Comment by yannickfunk** [comment]
Yeah for <button> elements we should just pass the dom Element at python `Element()` creation, if there is no id provided:

> One fix would be to actually pass the element to python in the `initHandlers()` like this:
> 
> ```js
> const handlerCode = el.getAttribute('pys-onClick');
> const elementGlobals: Map<string, any> = pyodide.globals.toJs()
> elementGlobals.set("element", el)
> const options = {globals: pyodide.toPy(elementGlobals)};
> 
> source = `Element("${el.id}", element).element.onclick = ${handlerCode}`;
> output = await pyodide.runPythonAsync(source, options);
> ```
> 
> This way, `Element.element`
> 
> ```python
> @property
> def element(self):
>     """Return the dom element"""
>     if not self._element:
>         self._element = document.querySelector(f"#{self._id}")
>     return self._element
> ```
> 
> doesn't fail, because the python `Element` has the actual dom element attached

**Comment by fpliger** [comment]
So, I think a good fix here would be:

1. add `checkId` in PyButton, just like we do in [PyScript](https://github.com/pyscript/pyscript/blob/ca909b4f6b99515cc19ca7c9fce0685c54c6e148/pyscriptjs/src/components/pyscript.ts#L42) 
2. add  a check [when we init the handlers](https://github.com/pyscript/pyscript/blob/main/pyscriptjs/src/components/pyscript.ts#L138-L139) and not allow users to use `pys-onClick` on  elements without `id` (this should raise an exception

we should also make sure this is clearly stated in the docs (as soon as we merge them this week)

**Comment by yannickfunk** [comment]
@fpliger Sounds good, I could implement this if you want

**Comment by fpliger** [comment]
That'd be great @yannickfunk ! @marimeireles was maybe going to look at this but if she didn't, it'd definitely be a great way to help! TY!

**Comment by fpliger** [comment]
Ok... I don't think @marimeireles started on it yet, @yannickfunk  want to pick it up :)

**Comment by yannickfunk** [comment]
Yeah I would pick it up @fpliger

**Comment by yannickfunk** [comment]
Currently, for the components: The state is the following:

| Component      | Has `checkId()` |
| ----------- | ----------- |
| PyBox      | [ ] |
| PyButton   | [ ]       |
| PyConfig   | [ ]       |
| PyEnv   | [ ]       |
| PyInputBox   | [  ]       |
| PyLoader   | [ ]       |
| PyRepl   | [x]       |
| PyScript   | [x]       |
| PyTitle  | [ ]       |

Do we want to add it to all components where it is missing, or just to `PyButton` so far?

**Comment by fpliger** [comment]
Great question. I think it definitely makes sense for the components that can execute a script and are likely to be mounted. (PyConfig and PyEnv are a bit special and I don't think it's necessary). With that mind, that list above should probably look like this:

| Component      | Has `checkId()` |
| ----------- | ----------- |
| PyBox      | [ ] |
| PyButton   | [x ]       |
| PyConfig   | [ ]       |
| PyEnv   | [ ]       |
| PyInputBox   | [x]       |
| PyLoader   | [ ]       |
| PyRepl   | [x]       |
| PyScript   | [x]       |
| PyTitle  | [ ]       |

**Comment by yannickfunk** [comment]
@fpliger I created a PR

**Comment by fpliger** [comment]
Awesome! I think #400 closes this (tested locally and looks great). TY again @yannickfunk 🚀 

Leaving this for posterity... The same example couple have been achieved with the more "PyScripty" form:

```
<body>
    <py-button id="click_btn" label="Click me!">
        def on_click(evt):
            console.log("clicked")
    </py-button>
</body>
```
