### ISSUE TITLE
[BUG] New Cors Issue when loading pyscript.js (?)

### ISSUE THREAD

**Issue by Data-Mastery** [pyscript/pyscript#360]
**Describe the bug**
Loading the <script defer src="https://pyscript.net/alpha/pyscript.js"></script> tag introduces the following error when I open a dev server on port 5500

Access to fetch at 'https://pyscript.net/alpha/pyscript.py' from origin 'http://localhost:5500' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

This behaviour is new. It worked for the last 2 weeks. I did not change any settings
**To Reproduce**
<html>
  <head>
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
  </head>
  <body> <py-script> print('Hello, World!') </py-script> </body>
</html>

**Expected behavior**
No Error

**Screenshots**

![pyscript1](https://user-images.githubusercontent.com/64363987/168337139-a28fd66a-41ac-4db3-9896-281e17ccdf84.JPG)

**Comment by pww217** [comment]
Thanks for the report! This has to do with migrating to a new hosting service.

I believe I found the issue and resolve it but we're testing currently.

**Comment by Data-Mastery** [comment]
@pww217 : Ok, awesome! I currently solved it by using Flask to serve the html and added CORS there, but I also had to to set an id in the <py-script> tag

**Comment by Data-Mastery** [comment]
@pww217 : It seems to me you have solved it :-)

**Comment by pww217** [comment]
Awesome, thanks for the quick report. Hopefully we're all set!
