### ISSUE TITLE
[BUG] Pyscript examples on examples page do not work

### ISSUE THREAD

**Issue by prescod** [pyscript/pyscript#362]
**Describe the bug**
Pyscript examples on examples page are all busted

**To Reproduce**

Go to this URL:

https://www.anaconda.com/blog/pyscript-python-in-the-browser

Follow the link to:

https://pyscript.net/examples/

Follow any link, such as:

https://pyscript.net/examples/hello_world.html

Note that it refers to: https://pyscript.net/build/pyscript.js

Which is a 404

**Comment by nmstoker** [comment]
@prescod might be handy to give this a slightly descriptive title 🙂

**Comment by fpliger** [comment]
Looks like CI had a glitch and replace the absolute paths with relative ones we have in the repo. Thanks for reporting!

**Comment by pww217** [comment]
The paths in all the examples should have been replaced with the absolute one in https://github.com/pyscript/pyscript/pull/365

Seems to have worked for the most part.

**Comment by fpliger** [comment]
Most part is fixed but still not fully fixed.

**Comment by pww217** [comment]
The styling at https://pyscript.net/examples seems fixed this morning even though I don't think anything changed? Huh...
