### ISSUE TITLE
[BUG] REPL style is broken

### ISSUE THREAD

**Issue by fpliger** [pyscript/pyscript#367]
REPL css seems broken and the play button icon now always show and is placed under the editor.

Additionally, autogenerate seems to be placing the new editor instances between the last editor and the output, creating a weird experience.

**Comment by marianoweber** [comment]
Created PR #372
This should fix the explained behavior.

**Comment by marianoweber** [comment]
@fpliger
This issue can be closed now, right?

**Comment by fpliger** [comment]
as @marianoweber, this issue can now be closed. TY!
