### ISSUE TITLE
[FEATURE]need document on use external python package

### ISSUE THREAD

**Issue by retsyo** [pyscript/pyscript#369]
1. I have a python installation with kinds of package in, for example, e:\prg\py, yes I am on Windows OS. On the other hand, I put pyscript and the html in d:\pyscript, or in other word, they are on different disk

then the question is which is the proper way to tell pyscript how to find my local 3rd party package on different disk?
```html
    <py-env>
      - ///E:/prg/py/lib/site-packages/numpy
      - ///E:/prg/py/lib/site-packages/matplotlib
    </py-env>
```

2. I think this feature should be mentioned: pyscript can use extension for python 2 and python 3, for 32 bits platform and 64 bits platform

**Comment by marimeireles** [comment]
This is a bit outdated, sorry to take so long to get back to you @retsyo.
The new API uses `py-config`, hopefully [the docs](https://docs.pyscript.net/latest/reference/elements/py-config.html) and examples are good enough to give you some clarity, if not feel free to pen a question in the discussions or to reach out in the discord channel.
Sorry again for the long time!
