### ISSUE TITLE
[FEATURE] Disable default styling in CSS

### ISSUE THREAD

**Issue by AstragoDE** [pyscript/pyscript#375]
**Is your feature request related to a problem? Please describe.**
Currently, the imported CSS is applying default styles to the Document (it looks similar to Tailwind CSS Preflight).
Users should only have the styling enabled if they import the Tailwind's Play-CDN or use Tailwind CLI, but not if they only use the CSS provided by py-script. 

**Describe the solution you'd like**
Disable the default styling. 
If the CSS is based on Tailwind CSS:
option 1)
[Adding a custom prefix to the CSS classes](https://tailwindcss.com/docs/configuration#prefix) (for example, the prefix: "pyscriptutil-")
option 2)
[Disabling Preflight](https://tailwindcss.com/docs/preflight#disabling-preflight)

**Describe alternatives you've considered**
Add support for the Tailwind CSS Play-CDN Script tag for configuration, so users can disable preflight, if they want to.

Example:
```html
<script>
    tailwind.config = {
        corePlugins: {
            preflight: false,
        },
    }
</script>
```

**Additional context**
![H1-Tag with current default style](https://user-images.githubusercontent.com/51675359/168426808-e5fad889-fd88-4f14-8b62-0a13e051a319.png)

![H1-Tag how it is supposed to be styled](https://user-images.githubusercontent.com/51675359/168426896-56220d85-0cfd-45fa-b8eb-1b1dc9eae1e9.png)

**Comment by marimeireles** [comment]
Yes, this will be modular in the future.
But it's work that has to be done.
Thanks for opening the issue :)

**Comment by marimeireles** [comment]
Actually, I think this specific issue doesn't make sense anymore as we're not using tailwind.
If you're interested in discussing default styling specifics I'd recommend to either join this [discussion](https://github.com/pyscript/pyscript/discussions/1172) or open your own.
Closing this one because it's outdated.
