### ISSUE TITLE
[BUG] Cannot use socket

### ISSUE THREAD

**Issue by marmig0404** [pyscript/pyscript#377]
**Describe the bug**
Using a socket connection in pyscript is met with a BlockingIOError: Operation in progress

**To Reproduce**
Test REPL page:
```
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Red+Hat+Text:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
    <title>REPL</title>
  </head>
  <body>
    <h1><b>pyscript REPL</b></h1>
    Tip: press Shift-ENTER to evaluate a cell
    <br>
    <div>
      <py-repl id="my-repl" auto-generate="true"> </py-repl>
    </div>
  </body>
</html>
```
Python executed:
```
import socket
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.connect(('localhost', 8080))
```
Error:
```
JsException(PythonError: Traceback (most recent call last): File "/lib/python3.10/site-packages/_pyodide/_base.py", line 429, in eval_code .run(globals, locals) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 300, in run coroutine = eval(self.code, globals, locals) File "", line 4, in BlockingIOError: [Errno 26] Operation in progress )
```
**Expected behavior**
Creating a functional socket connection.

**Related issues**
#129 #214 #288

**Comment by marianoweber** [comment]
#319 
Networking currently does not really work in pyodide.

**Comment by marmig0404** [comment]
> #319 Networking currently does not really work in pyodide.

Python's native socket doesn't work in pyscript, but maybe pyodide's WebSocket?
Trying the following seems to not error sometimes:
```
from js import WebSocket
socket = WebSocket.new('ws://localhost:8080')
```
Other times it errors with `Firefox can’t establish a connection to the server at ws://localhost:8080/.      pyodide.asm.js:14:219877`

Related [issue ](https://github.com/pyodide/pyodide/issues/574)for pyodide

**Comment by marmig0404** [comment]
This seems like more of an issue in pyodide, closing.
