### ISSUE TITLE
[BUG] Browser shows "loading runtime" while visiting html page 

### ISSUE THREAD

**Issue by azas241** [pyscript/pyscript#378]
While running this code, browser shows loading runtime
`<py-env>
 - requests
 - bs4
  </py-env>
<py-script>
import requests
from bs4 import BeautifulSoup as bs
url = "https://www.google.com/"
header = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36', 'Referer': 'https://www.google.com/'}
out = requests.get(url, headers=header)
stx = bs(out.text, 'lxml')
html = stx.find("title")
print(html.text)
</py-script>`

**Comment by marianoweber** [comment]
https://github.com/pyscript/pyscript/issues/319
Networking currently does not really work in pyodide.

**Comment by marimeireles** [comment]
This will eventually be fixed upstream =)
