### ISSUE TITLE
[BUG] Importing JS from a local webserver fails

### ISSUE THREAD

**Issue by tildebyte** [pyscript/pyscript#379]
**Describe the bug**

Importing JS from a **local webserver** fails with pyscript active. I'm using relative URLs here; I don't know if relative URLs from e.g. a CDN would work or not.

The setup here is: I'm serving files from the local filesystem using VSCode + the [Live Server](https://github.com/ritwickdey/vscode-live-server) plugin. I tested with both Chromium and Firefox, but FF seems to have really baroque (and excessive) error messages, so I'll stick with Chromium here.

Trimmed for brevity, complete minimal reproducer below

This

```html
"imports": {
    "three": "https://cdn.jsdelivr.net/npm/three@0.140.2/build/three.module.js"
}
```

when used with

```html
<script src="https://cdn.jsdelivr.net/npm/es-module-shims@1.5.4/dist/es-module-shims.js"></script>
<script type="module">
    import * as three from 'three'

    var color = new three.Color();
    console.log(color)
</script>
<py-script src="import_test.py"></py-script>
```

where "import_test.py" consists solely of

```py
from three import Color

color = Color.new("rgb(240, 192, 128)")
print(f'Color is {color.getHex()}')
```

is perfectly happy. I see `Color {}` (from JS) in the console, and no errors at all, as well as `Color is 15777920` (from pyscript) in the console. I also note that there is a warning about a double-import of 'three'.

OTOH, with this (FWIW the same three.js as above, copied locally),

```html
"imports": {
    "three": "./js/three.js/build/three.module.js"
}
```

I still see the console log from JS about `three.Color`, but the browser is not AT ALL happy:

pyscript.ts:90

```
GET https://pyscript.net/alpha/js/three.js/build/three.module.js net::ERR_ABORTED 404
```
Note carefully the URL ("https://pyscript.net/alpha/js/three.js"), which is OBVIOUSLY ludicrous, as pyscript.net certainly isn't hosting three.js (at least not at that URL :D ).

'pyscript.ts:90' resolves to

```js
// XXX: pyodide doesn't like Module(), failing with
// "can't read 'name' of undefined" at import time
exports = Object.assign({}, (await import(url)));
```

which, OK, seems reasonable, except that **it works for content served from HTTPS URLs**.

**To Reproduce**

#### HTML

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
</head>
<body>
    <script type="importmap">
        {
            "imports": {
                "three": "./js/three.js/build/three.module.js"
            }
        }
    </script>
    <script src="https://cdn.jsdelivr.net/npm/es-module-shims@1.5.4/dist/es-module-shims.js"></script>
    <script type="module">
        import * as three from 'three'

        var color = new three.Color();
        console.log(color)
    </script>
    <py-script src="import_test.py"></py-script>
</body>
</html>
```

#### Python

```py
from three import Color

color = Color.new("rgb(240, 192, 128)")
print(f'Color is {color.getHex()}')
```

**Expected behavior**

Import from a file served locally from a relative URL should work the same as a file served from an HTTPS URL.

### Environment

- pyscript version
  - pyscript.net/alpha/pyscript.js as of 2022-05-14 - no clue as to actual version number
- Windows 11
- VSCode 1.67.1
  - LiveServer 5.7.5
- Browser versions
  - Chromium Ungoogled 101.0.4951.54 64-bit; Firefox 100.0 64-bit
- Any other relevant information
  - three.js version 0.140.2 (from cdn.jsdelivr.net/npm/three@0.140.2/build/three.module.js)

**Comment by tildebyte** [comment]
There seems to be a related issue where attempting to map and import **some** module files from CDN does NOT work for pyscript, but DOES for JS (you have no idea 😐).

e.g. cdn.jsdelivr.net/npm/dat.gui@0.7.9/build/dat.gui.module.js works as a module locally or remotely in JS, but hits the above bug locally, and simply fails to work remotely ("ModuleNotFoundError: No module named 'dat'") (whereas e.g. cdn.jsdelivr.net/npm/three@0.140.2/build/three.module.js works **fine** as-is for **both** (but only remotely for pyscript)).

Anyway, if unrelated, let me know and I'll open a separate issue.

**Comment by marimeireles** [comment]
This is marginally related to https://github.com/pyscript/pyscript/pull/339, but makes me wonder if @mattpap will have an input on what might be happening here?

**Comment by mattpap** [comment]
It looks like the imported module is resolved relative to pyscript's URL, not the current page's, which is an interesting behavior. The original implementation was only tested against absolute URLs.
