### ISSUE TITLE
[BUG] Using MySql with pyscript

### ISSUE THREAD

**Issue by leothewolf** [pyscript/pyscript#381]
**Describe the bug**
I am not able to use mysql with pyscript!

**To Reproduce**
I have two files : index.html, a.py

index.html
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css"/>
</head>
<body>
</body>
<script defer src="https://pyscript.net/alpha/pyscript.js"></script>
<py-env>
    - mysql-connector-python
</py-env>
<py-script src="a.py"></py-script>
</html>
```

a.py

```
import mysql.connector as mb
conn = mb.connect(host="localhost",user="root",password="SAQQAR")
c = conn.cursor()
c.execute("use test")
c.execute("select * from test1")
f = c.fetchall()
print(f)
```

But it gives this error : 
```
APPENDING: True ==> -6cece33c-98af-a521-8e0c-b342074d71ba --> PythonError: Traceback (most recent call last):
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 429, in eval_code
    .run(globals, locals)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 300, in run
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 1, in <module>
  File "/lib/python3.10/site-packages/mysql/connector/__init__.py", line 53, in <module>
    from .connection import MySQLConnection
  File "/lib/python3.10/site-packages/mysql/connector/connection.py", line 44, in <module>
    from .constants import (
  File "/lib/python3.10/site-packages/mysql/connector/constants.py", line 32, in <module>
    import ssl
  File "/lib/python3.10/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'
```

**Expected behavior**
It should print out : [('hello',), ('there',), ('how',), ('are',)]

**Comment by marianoweber** [comment]
https://github.com/pyodide/pyodide/issues/529

This has to do with pyodide, not pyscript. Please take a look at the issue that I linked above.

**Comment by leothewolf** [comment]
> [pyodide/pyodide#529](https://github.com/pyodide/pyodide/issues/529)
> 
> This has to do with pyodide, not pyscript. Please take a look at the issue that I linked above.

First of all thanks for the reply!
I went through the link you gave me but tbh am new to github like not that new but couldn't make out much of the comments on that issue

Can you give me a way to fix it?

**Comment by marianoweber** [comment]
Hey,
the following comment should be of interest:

> Note though that ssl passes only 46/168 tests, anything that tries to touch a socket just returns an ENOSYS or similar.
> 
> _Originally posted by @hoodmane in https://github.com/pyodide/pyodide/issues/529#issuecomment-1068524592_

From my understanding, networking is not supported due to WASM(used by pyiodide) limitations. I am pretty sure MySQL will not work with the current technical limitations. As well as other networking-related modules. (e.g. urllib3 or requests)

Another thing to think about when using MySQL in this situation would be security risks.

Kind regards
Mariano Weber

**Comment by leothewolf** [comment]
@marianoweber so as per what you said I shouldn't use MySQL from client side?

**Comment by nmstoker** [comment]
It's less "shouldn't" and more "cannot" - you can only do things that the browser can do and if you pull in a Python package that tries to do more than that, it will fail.

Perhaps you aren't aware but when using the package mysql-connector-python on your local computer (ie not within PyScript / Pyodide) it would be making a network connection to the MySQL server of a kind that isn't available within the browser "sandbox" that PyScript/Pyodide run in.

**Comment by marianoweber** [comment]
> @marianoweber so as per what you said I shouldn't use MySQL from client side?

You would have to authenticate against the MySQL database. To do that, you would have to store your credentials in the client-side code. That is bad practice. 
Please correct me here, if I am wrong.

And for pyscript (or rather pyioide) specifically, it currently just does not work.

**Comment by leothewolf** [comment]
> > @marianoweber so as per what you said I shouldn't use MySQL from client side?
> 
> You would have to authenticate against the MySQL database. To do that, you would have to store your credentials in the client-side code. That is bad practice. Please correct me here, if I am wrong.
> 
> And for pyscript (or rather pyioide) specifically, it currently just does not work.

Umm thats true I never thought of that possibility but yea thats true and will ofc lead to issues umm lets hope we soon have some kind of security measure taken by PyScript team to use database with it! Well thanks @marianoweber I think I got my answer!

Ill close this issue!
