### ISSUE TITLE
[FEATURE]Possible to use Pytube in Pyscript?

### ISSUE THREAD

**Issue by dominicdev** [pyscript/pyscript#386]
**Is your feature request related to a problem? Please describe.**
I'm trying to get info from different type of youtube channel and using pytube module, there is no problem adding pytube inside the pyscript, but getting when tying to use Channels for get infrom from pytube, not sure if this was limitation from from pyscript or from pytube error, my code was already working using colab, but need to convert using pyscript

**Comment by marimeireles** [comment]
Can you please paste the error here and a minimal reproducible example?
Otherwise is hard to diagnose your issue.
Thank you!
