### ISSUE TITLE
[FEATURE] Discord server for PyScript

### ISSUE THREAD

**Issue by leothewolf** [pyscript/pyscript#387]
**Is your feature request related to a problem? Please describe.**
Nope its not related to a problem! I just wanted to suggest making a discord server where people can chat and solve their doubts kinda community for them

**Describe the solution you'd like**
Umm make a discord server! Or I already created one for me and my friends for PyScript I can give you the admin roles and stuff that you require

**Describe alternatives you've considered**
Umm alternative is to wait and wait on github after submitting issue for people to help us out!

**Additional context**
Well additionally I can give you my discord server link : https://discord.gg/TynfPGRwda where I can give you admin roles! 

**Hoping for an affirmative reply from your side**

**Comment by marimeireles** [comment]
Hey @leothewolf , that's great that initiatives like this started to take shape, it's very exciting to see communities emerging around PyScript!
However, the latest discussion with the team is that we currently don't have enough people to both administrate Github + other communication channels (see the number of issues and PRs open here). So we decided to take our time and attend to a few urgent issues first before taking over the responsibility of coordinating a discord channel. (At least that was the point we were Friday, the discussion should be settled [here](https://github.com/pyscript/pyscript/pull/390)).
But please feel free to create your own communities around PyScript :) once we have enough time in our hands (or enough people) we'll definitely create something like this and it'll be advertised on twitter, etc.

**Comment by leothewolf** [comment]
> Hey @leothewolf , that's great that initiatives like this started to take shape, it's very exciting to see communities emerging around PyScript! However, the latest discussion with the team is that we currently don't have enough people to both administrate Github + other communication channels (see the number of issues and PRs open here). So we decided to take our time and attend to a few urgent issues first before taking over the responsibility of coordinating a discord channel. (At least that was the point we were Friday, the discussion should be settled [here](https://github.com/pyscript/pyscript/pull/390)). But please feel free to create your own communities around PyScript :) once we have enough time in our hands (or enough people) we'll definitely create something like this and it'll be advertised on twitter, etc.

First of all thanks for the reply! Well ik it's a bit hectic atm so I am settled with out own small PyScript community and when the time comes I'll be more than happy to handover the server we have currently to the main PyScript team so you guys don't have to start from start....Till then I'll try my best to keep up the discord server!

**Once again thanks for the wonderful work you guys are doing and thanks for keeping it free!**
