### ISSUE TITLE
[BUG] Pygame not importing?

### ISSUE THREAD

**Issue by shinysocks** [pyscript/pyscript#388]
Pyscript index.html loads endlessly for python library pygame.

**To Reproduce**
Attempted to import pygame

**Expected behavior**
Expected pygame to load and import instead it continued to say :

`Loading runtime...`
`Runtime created...`
`Initializing components...`

seemingly forever...

**Screenshots**
![Screenshot from 2022-05-15 22-59-48](https://user-images.githubusercontent.com/91911303/168517584-70209916-5239-4e6a-9e60-063fe200ebbf.png)

**Comment by yannickfunk** [comment]
Only packages from [this List](https://pyodide.org/en/stable/usage/packages-in-pyodide.html) can be imported directly via the `<py-env>` tag

**Comment by shinysocks** [comment]
Oh. Do you know if this list will be expanded over time?

**Comment by dopplershift** [comment]
It's always possible to [add packages to pyodide](https://pyodide.org/en/stable/development/new-packages.html) by making Pull Requests on GitHub. However, for pure python libraries, you can always add them under `py-env` (or a url to a custom pure python wheel file) and it should work fine.

**Comment by NotShrirang** [comment]
There are many library will can't be imported right now. PyScript is still in early stages of development, these issues will be resolved soon.

**Comment by yannickfunk** [comment]
@marimeireles this can also be closed :)
