### ISSUE TITLE
[BUG] <py-script> fails inbetween two <p> Tags

### ISSUE THREAD

**Issue by manand881** [pyscript/pyscript#391]
**Describe the bug**
when <py-script> is run to print a few lines derived between 2 <p> tags, the script fail. It works well however everytime the script has no <p> tag that is positioned after the <py-script>tag

```
**To Reproduce**
<body>
    <p>Hello Html</p>
    <py-script>
        for x in range(0, 10):
            print(x)
    </py-script>
    <p>Hello Html</p>
</body>
```

**Expected behavior**
Hello Html
0
1
2
3
4
5
6
7
8
9
Hello Html

**Screenshots**
![image](https://user-images.githubusercontent.com/28252539/168540480-20d0a0a3-0235-4674-8543-dbe41875ace0.png)

**Additional context**

**Comment by marianoweber** [comment]
Please take a look at #370
