### ISSUE TITLE
not able to execute

### ISSUE THREAD

**Issue by krrish-v** [pyscript/pyscript#392]
when I apply pyscript with flask and open the webpage in chromium browser it loading(showing "loading runtime") and it is taking a very long, can't able to know why it is happening. By the way my computer is not slow

 
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/pyscript.css') }}">
    <script defer src="{{ url_for('static',filename='script/pyscript.js') }}"></script>

![loading](https://user-images.githubusercontent.com/87867238/168616259-9abc3d95-e17d-4711-b924-b3d82e437588.png)

**Comment by krrish-v** [comment]
> I assume the problem is you're using flask. Flask uses networking and networking is currently not supported by pyscript / pyodide. (See #364) If you're just using flask to serve the html, it shouldn't be a problem.
> 
> Could you please post your code here which reproduces the error, and post the error showing up in the dev tools console?

This is what I just added in head tag in base.html file and then tried to print "Hello World", nothing extra

    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/pyscript.css') }}">
    <script defer src="{{ url_for('static',filename='script/pyscript.js') }}"></script>

**Comment by yannickfunk** [comment]
could you show your browser console output?

**Comment by yannickfunk** [comment]
Do you have a local `pyscript.js` file available and serve it with flask? It seems like it can not find `pyscript.js` under `static/script/pyscript.js`

**Comment by krrish-v** [comment]
> Do you have a local `pyscript.js` file available and serve it with flask? It seems like it can not find `pyscript.js` under `static/script/pyscript.js`

**Comment by krrish-v** [comment]
let me if the issue is with my code or something else by using pyscript.js locally

**Comment by krrish-v** [comment]
> And could you share your full code which reproduces the error?

here is the code of base.html

    <!DOCTYPE html>
    <html>
    <head>
    <meta name="viewport" content="with=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/style.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/pyscript.css') }}">
    <script defer src="{{ url_for('static',filename='script/pyscript.js') }}"></script>
    
    </head>

    <body bgcolor="black">
    <section class="header">
        <nav>
            <div class="nav-links">
                <ul class="nav-links">
                    <li class="nav-links"><a href="/login">LOGIN</a></li>
                </ul>
            </div>
        </nav>

    {% block body %}

    {% endblock body %}

    </body>
    </html>

in flask.py

    from flask import Flask, request, render_template, url_for, redirect
    app = Flask(__name__)
    @app.route('/user/uname=<uname>')
    def user(uname):
        return render_template("user.html")

here the user.html

    {% extends 'base.html' %}
    {% block body %}

    <py-script>
    print('heelo user')
    </py-script>
    <section class="text-box">
    <div>
        <form>
            <button type="button"  id="2" class="hero-bin">button1</button>
            <button type="button" id="1" class="hero-bin">button2</button>
        </form>
    </div>
    <br>
    </section>>
    {% endblock body %}

**Comment by krrish-v** [comment]
> > And could you share your full code which reproduces the error?
> 
> here is the code of base.html
> 
> ```
> <!DOCTYPE html>
> <html>
> <head>
> <meta name="viewport" content="with=device-width, initial-scale=1.0">
> <title></title>
> <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/style.css') }}">
> <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/pyscript.css') }}">
> <script defer src="{{ url_for('static',filename='script/pyscript.js') }}"></script>
> 
> </head>
> 
> <body bgcolor="black">
> <section class="header">
>     <nav>
>         <div class="nav-links">
>             <ul class="nav-links">
>                 <li class="nav-links"><a href="/login">LOGIN</a></li>
>             </ul>
>         </div>
>     </nav>
> 
> {% block body %}
> 
> {% endblock body %}
> 
> </body>
> </html>
> ```
> 
> in flask.py
> 
> ```
> from flask import Flask, request, render_template, url_for, redirect
> app = Flask(__name__)
> @app.route('/user/uname=<uname>')
> def user(uname):
>     return render_template("user.html")
> ```
> 
> here the user.html
> 
> ```
> {% extends 'base.html' %}
> {% block body %}
> 
> <py-script>
> print('heelo user')
> </py-script>
> <section class="text-box">
> <div>
>     <form>
>         <button type="button"  id="2" class="hero-bin">button1</button>
>         <button type="button" id="1" class="hero-bin">button2</button>
>     </form>
> </div>
> <br>
> </section>>
> {% endblock body %}
> ```

the other file static/css/style.css in head tag is completely working as pyscript is not

**Comment by krrish-v** [comment]
this is error i am getting from flask
    
    127.0.0.1 - - [16/May/2022 20:54:15] "GET /static/script/pyscript.py HTTP/1.1" 404 -

can i get to know why it is asking for pyscript.py instead of pyscript.js

**Comment by yannickfunk** [comment]
Ah I see your problem now. Where do you have your pyscript.js from?

**Comment by krrish-v** [comment]
> Ah I see your problem now. Where do you have your pyscript.js from?

sorry i didn't get

**Comment by yannickfunk** [comment]
Do you have the pyscript.js file in your static folder?

**Comment by krrish-v** [comment]
yes , I have the file pyscript.js in static/script  directory
just randomly saved or download it from (https://pyscript.net/alpha/pyscript.js) by right clicking on browser page and the save as option

**Comment by krrish-v** [comment]
> The problem is that the pyscript.js file has a relative dependency on pyscript.py file. If you directly use https://pyscript.net/alpha/pyscript.js it uses https://pyscript.net/alpha/pyscript.py. But if you download https://pyscript.net/alpha/pyscript.js you also have to download https://pyscript.net/alpha/pyscript.py

thankyou so much the problem is solved, really appreciate your work

**Comment by yannickfunk** [comment]
Glad to help!
