### ISSUE TITLE
[FEATURE] can't open a file with python in the directory that I want

### ISSUE THREAD

**Issue by donnynja** [pyscript/pyscript#399]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. As a user, I'd like to [...]

**Describe the solution you'd like**
A clear and concise description of what you expect to happen.

**Describe alternatives you've considered**

**Additional context**

**Comment by donnynja** [comment]
in reality, this isn't a request of a feature, but i wanted to ask why if I try to open a new file, I can't select the directory i want to open it but saves it in thiese folders no matter what: /home/pyodide/my_file.my_extension.

**Comment by NotShrirang** [comment]
As this is still in early stages of development, these issues will be solved soon. These features will be added shortly.

**Comment by marianoweber** [comment]
That is because pyodide uses an in-memory file system. One of the maintainers of pyodide answered this on StackOverflow.

**Comment by donnynja** [comment]
Ok, i looked up the answer but I still can't figure out how to access this in-memory file system

**Comment by ckavidas** [comment]
Here is a rough example from a project I am working on.

![image](https://user-images.githubusercontent.com/49797382/170834907-adeba275-f8bc-432f-8bf1-024215eabac6.png)

![image](https://user-images.githubusercontent.com/49797382/170834929-f0be66a1-1874-4f31-83fd-a052eb6900ad.png)

**Comment by ckavidas** [comment]
Update:

Got all the code to fit into a single repl cell



`#Imports
from js import document
import glob
import micropip
import asyncio
import pandas as pd

upload_elem = document.getElementById("upload")

async def process_file(upload):
  for file in upload.files:
    file_name = file.name
    array_buffer = file.arrayBuffer()
    await asyncio.sleep(0.5)
    raw_bytes = array_buffer.result().to_bytes()
    with open(file_name, "wb") as file_handle:
      file_handle.write(raw_bytes)
      file_handle.close()
    pass

async def list_files():
  for file in glob.glob('/home/pyodide/*'):
    print(file)

file_bytes = await process_file(upload_elem)
await list_files()`

**Comment by marimeireles** [comment]
Closing it as dup. please redirect any questions related to the topic to the [documentation issue](https://github.com/pyscript/pyscript/issues/146#756).
If you're facing a different problem or think might have encountered a bug please feel free to open a new issue.
If I misinterpreted your issue and you think it should still be open please reply here and we'll reopen it.
Thank you!
