### ISSUE TITLE
[BUG] antigravity.html never loads

### ISSUE THREAD

**Issue by Karan9bhat** [pyscript/pyscript#408]
I'm new to the pyscript community and was running the example files. When I tried running the antigravity.html file in chrome, it never loads. I'm using an Ubuntu system with 6 GB RAM with Ryzen 5 3450u and 2 GB Radeon Graphics Card.
The terminal shows the following output
![Screenshot from 2022-05-18 08-59-31](https://user-images.githubusercontent.com/52777124/168951414-c579ccaf-dc4c-40cf-b5a1-b9aaaad39f0d.png)
The python file should have executed while running the html file but it never loads. So is there something that I might be missing? Is my system not compatible to run this?

**Comment by rayjolt** [comment]
Could you share the method or command you are using to load antigravity.html?
