### ISSUE TITLE
[BUG] Broken link on https://pyscript.net/

### ISSUE THREAD

**Issue by vbhv** [pyscript/pyscript#410]
This link is broken
<img width="598" alt="Screenshot 2022-05-18 at 2 31 44 PM" src="https://user-images.githubusercontent.com/863674/169001512-c847afa7-d81a-4119-844f-97223678e816.png">

**Comment by marianoweber** [comment]
The link now goes to a Github 404 page. Can you confirm and reopen the issue if needed?

**Comment by vbhv** [comment]
This is closed because it's a duplicate of #405
