### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by DorkYBru** [pyscript/pyscript#411]
I've got this bug : "Element.write: PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 500, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 351, in run_async
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 7, in <module>
TypeError: expected string or buffer
 --> True"
Here's code that i used:
html:
"<!doctype html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="style.css" rel="stylesheet">
  <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
  <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<py-env>
    - micropip
    - regex
    - asyncio
</py-env>
<body>
<div class='rgb title' id>
    <py-script src='getip.py'></py-script>
</div>

</body>
</html>"
python: "
import regex as re
from pyodide.http import pyfetch
import asyncio
url = "https://ip.aruljohn.com/"
oip = pyfetch(url , method="GET")
pattern = re.compile(r'^\d+\.\d+\.\d+\.\d+$')
matched = pattern.finditer(oip)
all = re.search(r'^\d+\.\d+\.\d+\.\d+$',oip)
print(all)
for match in matched:
    print(match)
"

I was expecting printing out two ip's but it didn't work.

OS: Windows 10
Browser's: Chromium, Librewolf(Firefox)

**Comment by marianoweber** [comment]
@DorkYBru 
From what i can see in that unformatted python, you are trying to `print(all)` which seems to be a list. That won't work.

**Comment by JeffersGlass** [comment]
So there are a couple of things going on here. You'll need to `await` pyfetch, since it's meant to be used as a coroutine. If you don't, the `oip` variable points to that coroutine, which `finditer` doesn't know what to do with (since it wants to match a string or buffer).

pyfetch also returns a [FetchResponse object ](https://pyodide.org/en/stable/usage/api/python-api.html#pyodide.http.FetchResponse) - you'll need to do another `await` to get the response's bytes() or json() or string() contents.

If I can whack together a working demo later I'll post it here.

**Comment by DorkYBru** [comment]
Thanks for response! Have I done this right?
```
import regex as re
from pyodide.http import pyfetch
import asyncio
url = "https://ip.aruljohn.com/"
async def oip():
    pyfetch(url , method="GET")
pattern = re.compile(r'^\d+\.\d+\.\d+\.\d+$')
matched = pattern.finditer(oip)
all = re.search(r'^\d+\.\d+\.\d+\.\d+$',oip)
for match in matched:
    print(match)
```

**Comment by fdemmer** [comment]
There is a `pyfetch` example in the Pyodide FAQ: [How can I load external files in Pyodide?](https://pyodide.org/en/stable/usage/faq.html#how-can-i-load-external-files-in-pyodide)

in short: you need to `await` twice: once for the fetch, once for the response:

```
from pyodide.http import pyfetch

response = await pyfetch("https://some_url/...")
if response.ok:
  print(await response.string())
```

**Comment by marimeireles** [comment]
If this is a discussion and not a bug nor a feature request I'd recommend looking for support in the forums @DorkYBru: https://community.anaconda.cloud/c/tech-topics/pyscript
Was your question answered @DorkYBru?
Also, if this is an issue and not a discussion, could you please add a more descriptive title?
Thank you!
