### ISSUE TITLE
[FEATURE]  REPL auto-generate functionality enhancement

### ISSUE THREAD

**Issue by chekoduadarsh** [pyscript/pyscript#412]
**Is your feature request related to a problem? Please describe.**
This issue is an extenction of PR #354 and Issue #188 . 

As discussed with @fpliger and @marianoweber , This Issue is created to understand and discuss auto-generate functionlity of PY-REPL

**Describe the solution you'd like**
Understanding the requirement and general usage of PY-REPL and implementing auto-generate. 

**Describe alternatives you've considered**
None Yet

**Additional context**
Not applicable

**Comment by marimeireles** [comment]
I don't understand this issue.
Can you please explain it further?
Thank you!

**Comment by marimeireles** [comment]
Maybe it's resolved already?

**Comment by marimeireles** [comment]
Closing this issue as REPL changed a lot since it was created and it's been a while since we got a response.
If you feel like your needs weren't met, please feel free to open a discussion :)
