### ISSUE TITLE
PyButton raises exception

### ISSUE THREAD

**Issue by twiecki** [pyscript/pyscript#420]
**Describe the bug**
Clicking on a PyButton produces:

```
pyproxy.gen.ts:237 Uncaught Error: This borrowed proxy was automatically destroyed at the end of a function call. Try using create_proxy or create_once_callable.
The object was of type "function" and had repr "<function on_click_sample_btn at 0x13a8938>"
    at _getPtr (pyproxy.gen.ts:237:11)
    at PyProxyClass.apply (pyproxy.gen.ts:1145:32)
    at Object.apply (pyproxy.gen.ts:1022:18)
```

And does not execute the code.

**To Reproduce**
Go to https://twiecki.io/pymc-in-browser.html and click sample.

**Expected behavior**
One or two days ago this was working fine. I suspect maybe this PR to the culprit: https://github.com/pyscript/pyscript/pull/400

Context: https://github.com/pyscript/pyscript/pull/398

**Comment by jim22k** [comment]
This also is happening for me. The [TODO example](https://pyscript.net/examples/todo-pylist.html) shows the same issue.

Did PyScript updated to pyodide 0.19? Here is a recent issue for the same error which mentions the latest pyodide made a breaking change: https://github.com/pyodide/pyodide/issues/2498

**Comment by marianoweber** [comment]
> This also is happening for me. The [TODO example](https://pyscript.net/examples/todo-pylist.html) shows the same issue.
> 
> Did PyScript updated to pyodide 0.19? Here is a recent issue for the same error which mentions the latest pyodide made a breaking change: [pyodide/pyodide#2498](https://github.com/pyodide/pyodide/issues/2498)

PyScript uses pyodide v0.20.0

**Comment by woxtu** [comment]
@yannickfunk Thank you for pointing that out.

**Comment by twiecki** [comment]
It didn't fix the issue I was facing:
```
pyproxy.gen.ts:237 Uncaught Error: This borrowed proxy was automatically destroyed at the end of a function call. Try using create_proxy or create_once_callable.
The object was of type "function" and had repr "<function on_click_sample_btn at 0xab87e0>"
    at _getPtr (pyproxy.gen.ts:237:11)
    at PyProxyClass.apply (pyproxy.gen.ts:1145:32)
    at Object.apply (pyproxy.gen.ts:1022:18)
```

Ref.: https://github.com/twiecki/pymc-in-browser/issues/1
