### ISSUE TITLE
[BUG] REPL does not work if we are precoding with libraries.

### ISSUE THREAD

**Issue by TusharNautiyal-web** [pyscript/pyscript#423]
**Describe the bug**
REPL does not work when code is already inside it and does not work.
**To Reproduce**
I have attached this screenshot here you can see if i type the same code in repl without pre writing it inside the tags it works.
**Expected behavior**
I have attached this screenshot here you can see if i type the same code in repl without pre writing it inside the tags it works.
It should work similar way as it works when we write code directly in the block.
**Screenshots**
![Untitled](https://user-images.githubusercontent.com/74553737/169243345-f4238593-38fc-48c5-9f40-ca88875efaae.jpg)

**Comment by marianoweber** [comment]
Can you put your code in here for us to be able to reproduce? Thanks!

**Comment by TusharNautiyal-web** [comment]
And here is the video also demonstrating the bug. Thank you.
https://www.youtube.com/watch?v=vZKWB1Qngs4&t=335s 
Timestamp 24:31 . 

***CODE***

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Py-Script</title>
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
<py-env>
    - numpy
    - pandas
    - matplotlib
    - seaborn
</py-env>
</head>
<body>
<p id = 'stri'></p>
<div id = plot></div>
    <py-script output = 'plot'>
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
arr = {'Cars': ['Wagonar','Alto','Maruti 800'],'Price': [4000000,4000000, 2500000]}
df = pd.DataFrame(arr)
fig, ax = plt.subplots(1,2)
sns.barplot(ax = ax[0], x = 'Cars', y='Price', data = df)
sns.lineplot(ax = ax[1], x = 'Cars', y='Price', data = df)
pyscript.write('plot', fig)
string = 'This is tushar project'
pyscript.write('stri', string)
</py-script>
<py-repl>
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
arr = {'Cars': ['Wagonar','Alto','Maruti 800'],'Price': [4000000,4000000, 2500000]}
df = pd.DataFrame(arr)
fig, ax = plt.subplots(1,2)
sns.barplot(ax = ax[0], x = 'Cars', y='Price', data = df)
sns.lineplot(ax = ax[1], x = 'Cars', y='Price', data = df)
</py-repl>
</body>
</html>

**Comment by TusharNautiyal-web** [comment]
One More thing i like to add is this will also not work i tried magic functions 
%matplotlib inline
```
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

arr = {'Cars': ['Wagonar','Alto','Maruti 800'],'Price': [4000000,4000000, 2500000]}
df = pd.DataFrame(arr)
fig, ax = plt.subplots(1,2)
sns.barplot(ax = ax[0], x = 'Cars', y='Price', data = df)
sns.lineplot(ax = ax[1], x = 'Cars', y='Price', data = df)
```
![image](https://user-images.githubusercontent.com/74553737/169248124-02c58bfb-b6d5-4b1f-9fbc-425f9a1fd37b.png)

**Comment by marianoweber** [comment]
If you add
```python
pyscript.write('plot', fig)
string = 'This is tushar project'
pyscript.write('stri', string)
```
to your REPL, it will work exactly the same as in your py-script.

Like this 
```python
<py-repl output="plot">
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
arr = {'Cars': ['Wagonar','Alto','Maruti 800'],'Price': [4000000,4000000, 2500000]}
df = pd.DataFrame(arr)
fig, ax = plt.subplots(1,2)
sns.barplot(ax = ax[0], x = 'Cars', y='Price', data = df)
sns.lineplot(ax = ax[1], x = 'Cars', y='Price', data = df)
pyscript.write('plot', fig)
string = 'This is tushar project'
pyscript.write('stri', string)
</py-repl>
```

**Comment by TusharNautiyal-web** [comment]
Ok got it 😇 but it would be great if it works directly in future versions. Let me try this I'll close the bug then.

**Comment by marianoweber** [comment]
Yes, there is definitely room for improvement here, good point!

**Comment by yannickfunk** [comment]
@marimeireles I think this can be closed for now
