### ISSUE TITLE
[BUG]Problem with import library in html inherited from jinja template.

### ISSUE THREAD

**Issue by hecaiont** [pyscript/pyscript#425]
When I import some library(matplotlib, time) to pyscript inherent as a jinja template, the following message appears. Python built-in functions work fine.

`JsException(PythonError: Traceback (most recent call last): File "/lib/python3.10/site-packages/_pyodide/_base.py", line 429, in eval_code .run(globals, locals) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 300, in run coroutine = eval(self.code, globals, locals) File "", line 4, in AttributeError: module 'time' has no attribute 'clock' )`

I am using pyscript in "some2.html" that received "some.html" as {% block %} in base.html and {% include "some2.html" %}.

I'm a bit clumsy in expressing it using a translator. I hope it helps with good service.

Python 3.713 conda base venv
`<script defer src="https://pyscript.net/alpha/pyscript.js"></script>`

**Comment by yannickfunk** [comment]
Did you include the libraries you want to use via the `<py-env>` tag?
Example: 

```html
<html>
    <head>
      <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
      <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
      <py-env>
        - numpy
        - matplotlib
      </py-env>
    </head>

  <body>
    <h1>Let's plot random numbers</h1>
    <div id="plot"></div>
    <py-script output="plot">
import matplotlib.pyplot as plt
import numpy as np

x = np.random.randn(1000)
y = np.random.randn(1000)

fig, ax = plt.subplots()
ax.scatter(x, y)
fig
    </py-script>
  </body>
</html>
```

**Comment by marimeireles** [comment]
Thanks for chiming in @yannickfunk! 🌸
Does that fix your issue @hecaiont ?

**Comment by hecaiont** [comment]
> Thanks for chiming in @yannickfunk! 🌸 Does that fix your issue @hecaiont ?

@yannickfunk Thanks it worked out well.
