### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by donnynja** [pyscript/pyscript#426]
![da cancellare](https://user-images.githubusercontent.com/96085270/169332700-bbbf7711-699a-4fa5-a3c3-513493d79bf6.PNG)

Uncaught TypeError: subscriber[1] is not a function
    at Object.set (index.mjs:29:34)
    at addInitializer (stores.ts:33:18)
    at pyscript.ts:158:1
    at main.ts:35:2

**Comment by marianoweber** [comment]
Can you put a reproducible code snippet in here, so that others can help? Thanks.

**Comment by marianoweber** [comment]
@fpliger @marimeireles This can be closed I guess.

**Comment by nico-bohlinger** [comment]
I get the same with only the basic example from the README:
```
<html>
  <head>
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
  </head>
  <body> <py-script> print('Hello, World!') </py-script> </body>
</html>```

**Comment by marianoweber** [comment]
This issue is getting fixed right now. Please look at #427. This issue is a duplicate.
