### ISSUE TITLE
How to use my C++ library with PyScript

### ISSUE THREAD

**Issue by nyckmaia** [pyscript/pyscript#434]
I wrote a library entirely in C++17 and I recently added a wrapper for Python through Pybind11, and it works perfectly in my Python environment.

I would like to know if there is any way to use this library in the web browser through PyScript.

Maybe there is some PyScript mechanism to compile my C++ code for WebAssembly?

Please tell me what are the options to enable the use of this library in PyScript.

Thanks

**Comment by marimeireles** [comment]
I think this is a question to upstream. ([Pyodide](https://github.com/pyodide/pyodide))
Currently PyScript only works with `micropip` and micropip only supports Python only packages. I know Roman has some opinions towards that, but I can't really find the comments where he's talking about it.
On the Anaconda side of things we're thinking about it =) it's one of the next big things we're thinking about tackling, but for now we're just focusing on putting PyScript in a more stable situtation.
But thank you for the interest! Hope you're still interested in PyScript by the time we develop the support for C++. =)

**Comment by ilanschnell** [comment]
@marimeireles This is indeed (at least currently) a Pyodide issue.  The directory https://github.com/pyodide/pyodide/tree/main/packages contains recipes for third party C extension packages in Pyodide.
