### ISSUE TITLE
loading screen user experience could be :fearful: for some 

### ISSUE THREAD

**Issue by tonyfast** [pyscript/pyscript#436]
y'all, as you do, i just copy/pasted and pasted

```
<link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
<script defer src="https://pyscript.net/alpha/pyscript.js"></script>
```

i took my usual deep breath before i start jamming, and this loading screen scared the :hankey: out of me. _i don't often post issues really, i was legit startled enough to comment._  this second part is on me though. i was scared all over again when i refreshed the page. i'm better now though.

i couldn't find an issue about this feature, but it might warrant some ux discussion. 

i agree that some announcement that pyscript is partying would be :sunglasses:  because the party can take time, but maybe there is a gentler form like toast notifications.

**Comment by siddhi** [comment]
One workaround for now would be to not include the CSS file, and then you can style the loading message as you want

**Comment by RSMuthu** [comment]
For my need, I manually overridden the styling. \
The PyScript will internally generate the below DOM structure for the loader and that loader disappears once its work is done.

```
<div id="pyscript_loading_splash" class="fixed top-0 left-0 right-0 bottom-0 w-full h-screen z-50 overflow-hidden bg-gray-600 opacity-75 flex flex-col items-center justify-center">
  <div class="smooth spinner"></div>
  <div id="pyscript-loading-label" class="label">
    <div id="pyscript-operation-details">
    </div>
  </div>
</div>
```

I manually override the default styling coming with the `<py-loader>` and thus satisfying my need and usecase.
I prefer this, rather than completely not including the stylesheet.

**Comment by egenius01** [comment]
Its still very young though, pyscript will def be faster than jscript and efficient eventually

**Comment by marimeireles** [comment]
Hey I think this can be closed as Fabio introduced a better loading screen now?
LMK if you think this issue is still valid and we can reopen it. Cheers.
