### ISSUE TITLE
can not execute vbs script[BUG]

### ISSUE THREAD

**Issue by thangvc91** [pyscript/pyscript#440]
**Describe the bug**
I tested using pyscript to call my vbs script , but it got the error as below 
`JsException(PythonError: Traceback (most recent call last): File "/lib/python3.10/site-packages/_pyodide/_base.py", line 429, in eval_code .run(globals, locals) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 300, in run coroutine = eval(self.code, globals, locals) File "", line 3, in File "/lib/python3.10/subprocess.py", line 345, in call with Popen(*popenargs, **kwargs) as p: File "/lib/python3.10/subprocess.py", line 966, in __init__ self._execute_child(args, executable, preexec_fn, close_fds, File "/lib/python3.10/subprocess.py", line 1775, in _execute_child self.pid = _posixsubprocess.fork_exec( OSError: [Errno 52] Function not implemented )`

**To Reproduce**
my code :

```
<!DOCTYPE html>

<html lang="en">
    <head>
            <meta charset="UTF-8">
            <title>BOOTSTRAP</title>
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
            <!-- JavaScript Bundle with Popper -->
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
            <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
            <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
    </head>
    <body>
        <h1>Hello World</h1>

        <py-script>
            print("hello World")
            import subprocess
            subprocess.call(['cscript.exe', r'C:\Users\thang\Downloads\bootstrap\SCRIPT_PDF.vbs'])
        </py-script>

    </body>
</html>
```
**Expected behavior**
please help me to address this issue 
**Screenshots**
![error from chrome](https://user-images.githubusercontent.com/28442911/169673196-31aeda86-30b3-4a40-b3e0-89dfeaace606.jpg)
![py can work fine](https://user-images.githubusercontent.com/28442911/169673199-f4ba9027-0c64-47db-ba3d-49e8d9941018.jpg)

**Additional context**

**Comment by marianoweber** [comment]
Please take a look at #338. Pyodide currently does not have access to your local filesystem.

**Comment by philippjfr** [comment]
Thanks for the issue @thangvc91. As @marianoweber says, pyodide and WASM in general operates in a sandbox in your browser and has no access to your local filesystem for security reasons, so this is simply not supported.
