### ISSUE TITLE
[FEATURE] Open Local Files Similar to path-Module.

### ISSUE THREAD

**Issue by TusharNautiyal-web** [pyscript/pyscript#442]
**Is your feature request related to a problem? Please describe.**
A feature that can upload the pickle file locally in browser like how we can define paths we can also load files that are present locally in live server
**Describe the solution you'd like**
A File Reader that can upload the pickle file locally in browser storage like how we can define paths we can also load files that are present locally in live server
**Describe alternatives you've considered**
or maybe another tag for <py-load> which can help u upload local files and let u read inside py-script tag.
**Additional context**
If its already done please do specify the technique because iam having a very hard time to found out a solution to load specifically Pickle file.
![image](https://user-images.githubusercontent.com/74553737/169697825-0960ad4d-055b-45b5-b371-4051e87c6107.png)
```
<body>
<py-env>
    - numpy
    - pandas
    - sklearn
    - path:
        /random_f.pkl
</py-env>
    <py-script>
import pandas as pd 
import numpy as np
import sklearn
import pickle 
import random_f.pkl
model = pickle.load(open('random_f.pkl', 'rb'))
Pclass = 3
Sex = 1
SibSp = 0
Parch = 0
Embarked = 1
Fare_category = 1
Age_category = 1
prediction = model.predict([[Pclass,Sex,SibSp,Parch,Embarked,Fare_category,Age_category]])
pyscript.write('predict', f'The person will survive or not :  {prediction}')

</py-script>
<div id="predict" class="alert alert-primary">
</div>

</body>
```

**Comment by ckavidas** [comment]
Bad idea.

Any file operations should require user interaction so as to prevent malicious pages from accessing files on user's host machines on load of the page.

IE:
- Have an HTML form for the user to fill out and upload the file.

**Comment by TusharNautiyal-web** [comment]
I am not saying upload the file on server I am saying upload the file on browser on client side so that pickle file can run on client machine as right now we need to load pickle file using cloud but it would be great if the pickle file stays on server machine but loads on client side as this will also increase the speed. Its not file operation its just if we want to deploy models we have to load files from cloud drives. We need to access them locally that is my feature request to be able to access such files locally .
Thank you 
Regards.

**Comment by marianoweber** [comment]
Your application will have to load the files via the internet, there is no way around it.
PyScript cannot access the clients filesystem, only your statically hosted files. PyScript uses Pyodide, which only has access to an in memory file.
A short explanation: [Pyodide FAQ](https://pyodide.org/en/stable/usage/faq.html#why-can-t-i-load-files-from-the-local-file-system)

**Comment by TusharNautiyal-web** [comment]
> Your application will have to load the files via the internet, there is no way around it. PyScript cannot access the clients filesystem, only your statically hosted files. PyScript uses Pyodide, which only has access to an in memory file. A short explanation: [Pyodide FAQ](https://pyodide.org/en/stable/usage/faq.html#why-can-t-i-load-files-from-the-local-file-system)

I know pyscript use pyodide to get all these libraries and dependencies work , but i am saying the way we are defining path to import module if in similar fashion we can get local server files (Files that are in the server or basically the same folder where are file is.) So we can open files without need of cloud pickle or some other solutions.

**Comment by marianoweber** [comment]
You can fetch them via pyfetch, if you host them on your server. There is no way to access them locally, that is what I am trying to explain.
[Pyodide FAQ: How to load external files](https://pyodide.org/en/stable/usage/faq.html#how-can-i-load-external-files-in-pyodide)

**Comment by TusharNautiyal-web** [comment]
How to make this work.
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
<script defer src="https://pyscript.net/alpha/pyscript.js"></script>
</head>
<body>
<py-env>
    - numpy
    - pandas
    - cloudpickle
</py-env>
    <py-script>
import numpy as np
import cloudpickle as cp
from urllib.request import urlopen
import pandas as pd
model = cp.load(urlopen("https://drive.google.com/uc?export=download&id=1c2Uwixm-3epbMjPScMWj91iSMVMaTsV9", 'rb'))
Pclass = 3
Sex = 1
SibSp = 0
Parch = 0
Embarked = 1
Fare_category = 1
Age_category = 1
prediction = model.predict([[Pclass,Sex,SibSp,Parch,Embarked,Fare_category,Age_category]])
pyscript.write('predict', f'The person will survive or not :  {prediction}')

</py-script>
<div id="predict" class="alert alert-primary">
</div>

</body>
</html>
```
![image](https://user-images.githubusercontent.com/74553737/169823804-16b39868-e1be-48ff-b17f-3e18ecf421d8.png)

**Comment by TusharNautiyal-web** [comment]
> s on a user's file system with no interactions is just insecure. This



> > I am not saying upload the file on server I am saying upload the file on browser on client side so that pickle file can run on client machine as right now we need to load pickle file using cloud but it would be great if the pickle file stays on server machine but loads on client side as this will also increase the speed. Its not file operation its just if we want to deploy models we have to load files from cloud drives. We need to access them locally that is my feature request to be able to access such files locally . Thank you Regards.
> 
> That doesn't matter, allowing a pyscript application to access files on a user's file system with no interactions is just insecure. This functionality does not exist in the web browser for a reason.

@marianoweber actually was able to clear my dbouts properly as i think i need to read pyodide documentation to find a work around for now. Iam trying to do that pyfetch but still not able to make it work properly if anyone can explain a solution to load pickle files from google drive or any other source it would be helpfull.
