### ISSUE TITLE
[DOCS] Korean translation

### ISSUE THREAD

**Issue by weensy** [pyscript/pyscript#444]
I am ready to translate the docs into Korean. 🇰🇷
I saw the PR of the Japanese translation. If that PR is merged, I will start translating into the same format.

**Comment by marimeireles** [comment]
Hi @weensy, thank you so much for translating the docs!
We're still discussing how we're going to display different languages in the docs and all over the place, I'll bring the topic up to the team again.
Hopefully we have a consensus soon and can merge your PR.
Thank you once again! :)

**Comment by cdrhim** [comment]
@marimeireles Hi, I'm also into translating the docs into Korean. Let us know if there were any consensus up to this point!

**Comment by WebReflection** [comment]
This issue should be moved/re-addressed in here https://github.com/pyscript/docs
