### ISSUE TITLE
Replace Tailwind with Pure CSS

### ISSUE THREAD

**Issue by fpliger** [pyscript/pyscript#446]
Tailwind serves the goal of moving fast towards a first goal of having a minimum usable framework in place but it clearly shows its limitations in serving a framework like PyScript. This is mostly due to PyScript being a Framework and not an application. Here are a few of the problems:

* Tailwind is too big for a framework resulting either in a huge chunk of CSS to load 
* Not all users are interested in the visual components and they are currently paying a (high) cost for something they are not using
* PyScript should focus more on the flexibility of integrating well with applications and other frameworks. Tailwind is too invasive in that sense.

The goal is to replace Tailwind with pure CSS and maintain the overall look and feel of the current PyScript components.

**Comment by leonardas103** [comment]
Won't just creating a [minified version](https://tailwindcss.com/docs/optimizing-for-production) solve this?
