### ISSUE TITLE
[BUG] PyList does not add entries

### ISSUE THREAD

**Issue by marianoweber** [pyscript/pyscript#449]
**Describe the bug**
The PyList component seems to be broken.

If you enter something and click "Add Task!", nothing happens.

**To Reproduce**
Go to [https://pyscript.net/examples/todo-pylist.html](https://pyscript.net/examples/todo-pylist.html) and try to add a task.

**Expected behavior**
There should be a task added to the list after I click the button.

**Comment by marianoweber** [comment]
I just realised, that there's no `py-list` element. Maybe we should remove that example for now.

**Comment by yannickfunk** [comment]
The `py-list` should be registered as a custom element here:
https://github.com/pyscript/pyscript/blob/698478ef95b396a5de4b9b330dbd9bd796d3861f/examples/todo-pylist.html#L16 

The registration is handled here:
https://github.com/pyscript/pyscript/blob/eaacd45672b4bcadc896aa4d9ecc90462e72549b/pyscriptjs/src/components/base.ts#L275

So I would consider this a bug

**Comment by yannickfunk** [comment]
```
pyproxy.gen.ts:237 Uncaught Error: This borrowed proxy was automatically destroyed at the end of a function call. Try using create_proxy or create_once_callable
```
Is the error, It doesn't appear for my local pyscript build, the example works fine there, so I assume this is going to be fixed with the next release.
@pww217 Could you maybe tell which commit on master was the last commit to be included in the currently available pyscript.js?

**Comment by pww217** [comment]
The latest build of Alpha is more than week old at least, so what you've said is entirely possible. We're working on putting out the first release officially that'll ideally contain better change notes and make things more trackable. Unfortunately now it's a bit manual still.

**Comment by marianoweber** [comment]
Thanks for investigating and testing! @yannickfunk 

I will consider this solved, as the build is another topic.
