### ISSUE TITLE
Pyscript vs Brython

### ISSUE THREAD

**Issue by j209** [pyscript/pyscript#453]
Hi.
How to compare pyscript with [Brython](https://brython.info/index.html)?

**Comment by SoullessCookie** [comment]
There is probably a much better response to this, but based on what I see, Brython is more of mixing python with javascript, while pyscript is trying to "replace" javascript altogether. It also seems that Brython has more features than pyscript as of right now.

**Comment by siddhi** [comment]
This was discussed in the pyodide talk (pyscript is built on top of pyodide) at PyCon US 2022. What they mentioned is while other projects have focused on getting python into the browser, pyodide's main aim is to bring the larger python ecosystem into the browser: make it easy to import other packages and use them on the webpage, easy python -> JS bridges and vice-versa, making it easier to do I/O (display on the screen or async fetch) via the browser, porting of popular C based packages (`numpy`, `pandas` etc).

PyScript builds on that by creating an easy learning experience. You can just use `py-script` or `py-env` and start coding in python without needing to know JS code or how to get `numpy` into the browser or Python->JS bridges and proxying data types between the languages. Any data scientist or python coder can get up and running in no time. That is the main goal for pyscript.

**Comment by SoullessCookie** [comment]
> 

Thank you for the in-depth explanation 👍

**Comment by marimeireles** [comment]
An answer more related to Brython:
"Brython is client-side and functions as a semantic on top of Javascript—it is a reimplementation of Javascript without support for packages or a file system. The extraction of a package in normal Python has been replaced completely by something else. You should be able to run code with minimal changes; however, that isn’t possible with Brython."
Feel free to re-open if you still have any questions around that @j209 and thanks for chiming in @siddhi!

**Comment by j209** [comment]
Thank you very much for your prompt and complete reply.
