### ISSUE TITLE
[BUG] Creating new buttons with "pys-onClick" attribute does nothing.

### ISSUE THREAD

**Issue by ckavidas** [pyscript/pyscript#461]
**Describe the bug**
I have a page with a html button using the pys-onClick attribute to call a function which adds another div with a button. The second button has the pys-onClick attribute but does not do anything.

**To Reproduce**
```
<div id="pyscript-header">
<button class="bg-green-500 hover:bg-green-500 text-gray-800 font-bold py-1 px-2 rounded-l" pys-onClick='add_button'>
<py-script>
def add_button(*ags, **kwgs):
    console.log("function is called!")
    parent = document.getElementById("test_div")
    btn = document.createElement("button")
    btn.classList = ["bg-green-500 hover:bg-green-500 text-gray-800 font-bold py-1 px-2 rounded-l"]
    btn.setAttribute('pys-onClick', 'add_button')
    btn.innerText = "new_button"
    parent.append(btn)
</py-script>
</div>
<div id="test_div"></div>
```

**Expected behavior**
new button added that has a working interaction when clicked

**Additional Notes**

Initially I tried creating a div and inserting the button to innerHTML but that also did not seem to work.

I assume this is because the pys-onClick attribute only works on the initial page load but would like some confirmation on that. 
If that is the case, how could I remediate this issue? Would I have to create a javascript function that calls my python function? Please advise.

**Comment by siddhi** [comment]
I have the same issue. 

One workaround is to render all the form elements on the page but set the style to `visbility: hidden` You can then change the style to `visibility: visible` to show the elements at a later time. This works because pyscript will still find the button on the DOM and setup all the event handlers on the initial page load. 

That is still a workaround though, I would still like to dynamically add/remove dom nodes at runtime.

**Comment by ckavidas** [comment]
Would it be possible to create a javascript function that will then go on to call a python function? That way I could use the traditional onClick attribute.

**Comment by marianoweber** [comment]
Here is a snippet on how you can create an event listener from your py-script.
One thing you also need to do: give your initial button an ID, otherwise you will get an error.

``` python
<py-script>
from pyodide import create_proxy

def add_button(*ags, **kwgs):
    console.log("function is called!")
    parent = document.getElementById("test_div")
    btn = document.createElement("button")
    btn.classList = ["bg-green-500 hover:bg-green-500 text-gray-800 font-bold py-1 px-2 rounded-l"]
    btn.setAttribute('pys-onClick', 'add_button')
    btn.innerText = "new_button"

    btn.id = "testbtn"
    Element("testbtn", btn).element.addEventListener("click",  create_proxy(add_button))
    parent.append(btn)
</py-script>
```

**Comment by mudream4869** [comment]
Maybe you can take a look at [TODO example](https://pyscript.net/examples/todo.py) ?
It dynamically generates the checkbox and assigns them by onclick property?

```python
task_html = task_template.clone(task_id, to=task_list)
task_html_content = task_html.select("p")
task_html_content.element.innerText = task["content"]
task_html_check = task_html.select("input")
task_list.element.appendChild(task_html.element)

def check_task(evt=None):
    task["done"] = not task["done"]
    if task["done"]:
        add_class(task_html_content, "line-through")
    else:
        remove_class(task_html_content, "line-through")

new_task_content.clear()
task_html_check.element.onclick = check_task
```

**Comment by Siddharth1India** [comment]
Hey, I checked console and it suggested me to add id attribute. I tested and got output. 
Is this what your code is supposed to do?

Before click:
![image](https://user-images.githubusercontent.com/46651743/170824811-0f20bea1-05d6-4158-a5d1-48e1adaec1dd.png)

After click:
![image](https://user-images.githubusercontent.com/46651743/170824826-82bd28d4-aa83-44ff-84a9-5dbf770f0f0d.png)

Code:
'''
    <div id="pyscript-header">
      <button class="bg-green-500 hover:bg-green-500 text-gray-800 font-bold py-1 px-2 rounded-l" id='btn' pys-onClick='add_button'>
      <py-script>
      def add_button(*ags, **kwgs):
          console.log("function is called!")
          parent = document.getElementById("test_div")
          btn = document.createElement("button")
          btn.classList = ["bg-green-500 hover:bg-green-500 text-gray-800 font-bold py-1 px-2 rounded-l"]
          btn.setAttribute('pys-onClick', 'add_button')
          btn.innerText = "new_button"
          parent.append(btn)
      </py-script>
      </div>
      <div id="test_div"></div>
'''

**Comment by ckavidas** [comment]
> Hey, I checked console and it suggested me to add id attribute. I tested and got output. Is this what your code is supposed to do?


Does your second button create another button when you click it?

**Comment by Siddharth1India** [comment]
> > Hey, I checked console and it suggested me to add id attribute. I tested and got output. Is this what your code is supposed to do?
> 
> Does your second button create another button when you click it?

No, It will not work. Just checked elements carefully, I can see old button is having tag "event" written with that but new button not having same tag. After reading some more articles, I can see is same issue is there with JS. 
It is not PyScript issue I guess.

**Comment by Siddharth1India** [comment]
@ckavidas Issue solved I guess:
Here is Code:

```
  <body>
    <div id="pyscript-header">
      <button class="bg-green-500 hover:bg-green-500 text-gray-800 font-bold py-1 px-2 rounded-l" id='btnx' pys-onClick='add_button'>
        Try
      <py-script>
      def add_button(self):
          console.log("function is called!")
          parent = document.getElementById("test_div")
          btn = document.createElement("button")
          btn.classList = "bg-green-500 hover:bg-green-500 text-gray-800 font-bold py-1 px-2 rounded-l"
          <!-- btn.setAttribute('pys-onClick', 'add_button') -->
          btn.setAttribute('id', 'btnx')          
          btn.innerText = "new_button"
          Element("btnx", btn).element.addEventListener("click",  create_proxy(add_button))
          parent.append(btn)
      </py-script>
      </div>
      <div id="test_div"></div></body>
```
