### ISSUE TITLE
Problems with modules

### ISSUE THREAD

**Issue by nouseramefounded** [pyscript/pyscript#462]
I can't import modules as os, subprocess and so on...some solution?

**Comment by marianoweber** [comment]
Please add an example, so that others can reproduce your error. Thanks

**Comment by nouseramefounded** [comment]
`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />

    <title>PyScript Hello World</title>

    <link rel="icon" type="image/png" href="favicon.png" />
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />

    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
  </head>
  <py-env>
    - os
  </py-env>
  <body>
    <py-script>
os.system("firefox")
    </py-script>
  </body>
</html>
`
I tried to use the server by running the "python3 -m http.server" command and opening the file, but nothing changes.
The error is:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://pypi.org/pypi/os/json. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 301.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://pypi.org/pypi/os/json. (Reason: CORS request did not succeed). Status code: (null).

Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 183, in install
    transaction = await self.gather_requirements(requirements, ctx, keep_going)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 173, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 280, in add_requirement
    metadata = await _get_pypi_json(req.name)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 86, in _get_pypi_json
    return json.loads(await fetch_string(url))
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 58, in fetch_string
    return await (await pyfetch(url, **kwargs)).string()
  File "/lib/python3.10/site-packages/pyodide/http.py", line 231, in pyfetch
    url, await _jsfetch(url, to_js(kwargs, dict_converter=Object.fromEntries))
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
JsException: TypeError: NetworkError when attempting to fetch resource.
    PythonError error_handling.gen.ts:309
    new_error pyodide.asm.js:14
    method_call_trampoline pyodide.asm.js:14
    callPyObjectKwargs pyproxy.gen.ts:360
    callPyObject pyproxy.gen.ts:384
    wrapper pyodide.asm.js:14
    setTimeout handler*hiwire_call_bound pyodide.asm.js:14
    callPyObjectKwargs pyproxy.gen.ts:360
    callPyObject pyproxy.gen.ts:384
    wrapper pyodide.asm.js:14
    setTimeout handler*hiwire_call_bound pyodide.asm.js:14

**Comment by nouseramefounded** [comment]
I also used the syntax <py-script src="/my_own_file.py"></py-script> replacing "/my_own_file.py" with the script, but nothing to do.

**Comment by marianoweber** [comment]
```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>PyScript Hello World</title>

<link rel="icon" type="image/png" href="favicon.png" />
<link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />

<script defer src="https://pyscript.net/alpha/pyscript.js"></script>
</head>
<body>
<py-script>
  import os
  print(os.name)
</py-script>
</body>
</html>
```

You can use `os` by importing it in your `py-script`. Are you trying to spawn a new firefox process with `os.system("firefox")`?
Because that won't work, as pyscript/pyodide does not have access to your actual OS.

**Comment by nouseramefounded** [comment]
okay, how can I get it accessed?

**Comment by marianoweber** [comment]
You can't because pyscript runs in a browser. And the browser will never give the application access to the local OS. 
That would be insanely dangerous.

**Comment by nouseramefounded** [comment]
:)

**Comment by nouseramefounded** [comment]
Thank you for the disponibility

**Comment by Kali95739** [comment]
Yes you can with node lol
