### ISSUE TITLE
Pi character is not being rendered properly on Safari

### ISSUE THREAD

**Issue by IamAbhinav03** [pyscript/pyscript#471]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I was trying out the the below given code from the getting started section and I noticed that the pi character that is to be rendered, is not being rendered properly on safari. I am also attaching the screenshots.
```
<html>
  <head>
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
  </head>
  <body>
      <py-script>
        print("Let's compute π:")
        def compute_pi(n):
            pi = 2
            for i in range(1,n):
                pi *= 4 * i ** 2 / (4 * i ** 2 - 1)
            return pi

        pi = compute_pi(100000)
        s = f"π is approximately {pi:.3f}"
        print(s)
      </py-script>
  </body>
</html>
```

Output(safari)
<img width="1127" alt="Screen Shot 2022-05-28 at 12 41 32 AM" src="https://user-images.githubusercontent.com/66298497/170776065-55d7febc-11b6-48d5-b442-672b018a2981.png">

I know py-script isn't tested on safari, just posting it here for a fix in the future.

**Comment by fdemmer** [comment]
Can reproduce the issue, with Firefox when loading the HTML via local webserver (`python3 -m http.server`); interestingly not when loading directly from filesystem (`file:///...`).

Solutions are:
- tell the browser to use utf-8 via meta-tag: `<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />`
- or configure your webserver to set proper [content-type header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type) in the response

**Comment by IamAbhinav03** [comment]
Thanks @fdemmer. The meta tag solution works in Safari also

**Comment by marimeireles** [comment]
Seems like it was just missing the `utf-8` flag :)
