### ISSUE TITLE
Must run script twice for expected result to happen

### ISSUE THREAD

**Issue by imbev** [pyscript/pyscript#491]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

The expected result of this does not happen when it is run normally
```python
import js

canvas = js.document.createElement("canvas")
js.document.body.appendChild(canvas)
ctx = canvas.getContext("2d")

img = js.document.createElement("img")
img.src = "https://gitlab.com/uploads/-/system/user/avatar/11254452/avatar.png"

ctx.drawImage(img, 10, 10)
```
if i run this in the repl, the same thing happens
however, if i run it more than once in the repl, the result will occur every time except the first run

### What browsers are you seeing the problem on? (if applicable)

Firefox, Chrome

### Console info

```shell
No Errors
```

### Additional Context

Last part of log:

------ loader closed ------ pyconfig.ts:83:20
Collecting nodes... pyscript.ts:111:12
evaluate base.ts:76:16
----> changed out to my-repl-1 true 3 pyodide.asm.js:14:219573
----> changed out to undefined true pyodide.asm.js:14:219573
----> reverted 3 pyodide.asm.js:14:219573
connected pyrepl.ts:142:16
evaluate base.ts:76:16
----> changed out to my-repl-1 true 3 pyodide.asm.js:14:219573
----> changed out to undefined true pyodide.asm.js:14:219573
----> reverted 3 pyodide.asm.js:14:219573

**Comment by JeffersGlass** [comment]
This is caused by the `img` not being fully loaded at the time it's written to the canvas. (This is an issue that also occurs in pure Javascript implementations as well.) This is not a Pyscript bug, but timing challenges like this may be worth noting somewhere, as they're a stumbling block.

You can solve this issue by waiting to draw to the canvas until the `img` is loaded, as in:

```
import js
from pyodide import create_proxy

canvas = js.document.createElement("canvas")
js.document.body.appendChild(canvas)
ctx = canvas.getContext("2d")

img = js.document.createElement("img")
img.src = "https://gitlab.com/uploads/-/system/user/avatar/11254452/avatar.png"

def draw(e):
  ctx.drawImage(img, 10, 10)

img.addEventListener("load", create_proxy(draw))
```

**Comment by marimeireles** [comment]
Thank you @JeffersGlass !
