### ISSUE TITLE
REPL2 not honoring input string

### ISSUE THREAD

**Issue by peterennis** [pyscript/pyscript#492]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

Working through 100 days of python code.

![Screenshot 2022-06-01 184923](https://user-images.githubusercontent.com/140737/171529480-dbedd253-c42e-4369-a76c-f55aa8c58b99.png)

![Screenshot 2022-06-01 185124](https://user-images.githubusercontent.com/140737/171529499-818f157b-35ca-436b-a78c-62b8bb27458a.png)

![Screenshot 2022-06-01 185300](https://user-images.githubusercontent.com/140737/171529511-957bd2b0-f7a7-485c-aea1-babb9f6e5d39.png)

### What browsers are you seeing the problem on? (if applicable)

Chrome, Microsoft Edge

### Additional Context

It would be nice if the input box included the actual question.

Same issue with REPL.html

**Comment by JeffersGlass** [comment]
I believe this is related to Issue #239 - @antocuni gives a pretty detailed response there about[ the upstream Pyodide issues that cause this](https://github.com/pyscript/pyscript/issues/239#issuecomment-1122366501). This might be considered a duplicate of that issue.

**Comment by antocuni** [comment]
Yes, I think it's a duplicate.
Sorry @peterennis for the inconvenience!

**Comment by antocuni** [comment]
Duplicate of #239
