### ISSUE TITLE
Add prettier or some other JS formatted to pre-commit

### ISSUE THREAD

**Issue by fpliger** [pyscript/pyscript#505]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project are area (see the above section)

### What is the idea?

We currently don't have an auto-formatter or even just explicit code style guidelines for TS . This opens up to a series of inconveniences and duplication of works that could be easily avoided such as code style changes during PRs, committers guessing code style and changing code just for personal preferences, etc...

See #503 for reference

### Why is this needed

This is needed in order to have better guidance to our community and better code quality. We could start with documentation guidance but this actually may be faster and will have a faster effect on users/committers since will not require them to read all the documentation (which not everyone do)

### What should happen?

We should add  prettier or some other JS formatted to pre-commit

**Comment by JeffersGlass** [comment]
Would it be good to run ESLint on pre-commit as well? If that's being run as part when a PR is created, might be good to run at commit-time as well.

Or maybe it should be run as a pre-push hook, so it's not an obstacle to commits as part of the dev process, only when creating a PR?

**Comment by tildebyte** [comment]
GitHub actions&workflows (one for `eslint`, one for a formatter) would solve all the issues mentioned here.

They can easily be configured to run on push events[1] - this prevents slowing down _local_ dev work (although it's also easy to use both of those tools locally as part of dev activities; any modern text editor should support this), but makes sure that pushes to branches in GH forks[2] are pretty clean before a PR is ever even opened.

There's the additional advantage of hooking merge events as well, either as "belt-and-suspenders", or for additional automation (but I see existing workflows, so I'm guessing that this is common knowledge :) )

[1] To a topic branch in a contributor's fork: you _are_ encouraging a "fork and PR" model, yes?
[2] Given that actions&workflows travel along with a fork as part of the .github dir
