### ISSUE TITLE
[DOCS] Indonesian Documentation 

### ISSUE THREAD

**Issue by naschimhit** [pyscript/pyscript#508]
Do I need to translate [`read.md`](https://github.com/pyscript/pyscript#readme) into Indonesian?
I think it's not necessary. If you think it's necessary, let's translate together.
@deaaprizal

**Comment by naschimhit** [comment]
> > Do I need to translate [`read.md`](https://github.com/pyscript/pyscript#readme) into Indonesian? I think it's not necessary. If you think it's necessary, let's translate together. @deaaprizal
> 
> it's a nice idea, will tell you when i'm ready 😉

Terimakasih kang or thanks brother.

**Comment by marimeireles** [comment]
Wow!
This is so awesome! 
I'm looking so forward for this. We need to set up a system, but it'd be amazing to have all these languages in our docs.
Thank you so much for offering to help! ❤️

**Comment by WebReflection** [comment]
I believe these discussions should be moved to https://github.com/pyscript/docs
