### ISSUE TITLE
> character is being escaped to &gt; in py-repl

### ISSUE THREAD

**Issue by rod2ik** [pyscript/pyscript#518]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

Hi,

In the `py-repl` tag, the python `>` comparison caracter is being escaped to `&gt;`

For example the following code :

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>  
    <title>Document</title>
</head>
<body>
<div>
<py-repl id="r1" auto-generate=true>
def indice_min(nombres):
    indice = 0
    minimum = nombres[0]
    for i in range(len(nombres)):
        if minimum > nombres[i]:
            minimum = nombres[i]
            indice = i
    return indice
</py-repl>
</div>
</body>
</html>
```

renders as follows :

![pyscript_gt](https://user-images.githubusercontent.com/94541819/173697684-2a60c693-fd04-4565-b2c1-047acfbc1e90.png)

which (obviously) gives the following runtime error :

```python
JsException(PythonError: Traceback (most recent call last): File "/lib/python3.10/site-packages/_pyodide/_base.py", line 421, in eval_code CodeRunner( File "/lib/python3.10/site-packages/_pyodide/_base.py", line 237, in __init__ self.ast = next(self._gen) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 141, in _parse_and_compile_gen mod = compile(source, filename, mode, flags | ast.PyCF_ONLY_AST) File "", line 6 if minimum > nombres[i]: ^ SyntaxError: invalid syntax )
```

### What browsers are you seeing the problem on? (if applicable)

Firefox, Chrome

### Console info

```shell
No errors
```

### Additional Context

On Manjaro Linux
```shell
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.2.6
DISTRIB_CODENAME=Qonos
DISTRIB_DESCRIPTION="Manjaro Linux"
```

**Comment by marimeireles** [comment]
Hum, actually, for you to stop seeing this issue I think you'd have to build it locally @rod2ik

**Comment by marimeireles** [comment]
I'm not sure what's the frequency we're releasing new versions but it's from 2 to 2 weeks?
Once we decide on our versioning system that I think it's still on hold.

Please make sure to test it with the local build to see if you can still reproduce the issue.
Thanks.

**Comment by marimeireles** [comment]
Closed as fixed.
I hope this is correctly handled?
If not, please re-open!
Thank you!

**Comment by rod2ik** [comment]
This issue is solved for me two, replacing `alpha` by the `latest` of course :

```html
<head>
<link rel="stylesheet" href="https://pyscript.net/latest/pyscript.css" />
<script defer src="https://pyscript.net/latest/pyscript.js"></script>
</head>
```

Thanks very much for your reactivity and action  ! :)
