### ISSUE TITLE
Pyscript and Element().write are not available inside child python scripts imported via py-env

### ISSUE THREAD

**Issue by pandian912** [pyscript/pyscript#525]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

On importing a child python script via py-env, the child script is unable to use pyscript and Element().write().
This forces to return the value to main python script and write in the main file.

Alternatively, I could use js.document.getElementById and write through that, but that requires importing js and also I lose out on the formatting MIME conversions done by pyscript.write as mentioned here - https://github.com/pyscript/pyscript/blob/main/pyscriptjs/src/pyscript.py#L49-L104 
https://jeff.glass/post/pyscript-intro/ 

### What browsers are you seeing the problem on? (if applicable)

Chrome, Other

### Console info

```shell
pyodide.asm.js:14 Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "<exec>", line 18, in my_fetch
  File "/home/pyodide/dom_writer.py", line 55, in visualise
    pyscript.write('pie', fig)
NameError: name 'pyscript' is not defined

    at new_error (pyodide.asm.js:14:238191)
    at pyodide.asm.wasm:0xedbcb
    at pyodide.asm.wasm:0xf1a0e
    at method_call_trampoline (pyodide.asm.js:14:238105)
    at pyodide.asm.wasm:0x134c2c
    at pyodide.asm.wasm:0x217a84
    at pyodide.asm.wasm:0x174a14
    at pyodide.asm.wasm:0x135149
    at pyodide.asm.wasm:0x135243
    at pyodide.asm.wasm:0x1352e6
    at pyodide.asm.wasm:0x1fff83
    at pyodide.asm.wasm:0x1f98b5
    at pyodide.asm.wasm:0x135329
    at pyodide.asm.wasm:0x201f1b
    at pyodide.asm.wasm:0x1ff9ff
    at pyodide.asm.wasm:0x1f98b5
    at pyodide.asm.wasm:0x135329
    at pyodide.asm.wasm:0xf16d8
    at Module.callPyObjectKwargs (pyproxy.gen.ts:360:23)
    at Module.callPyObject (pyproxy.gen.ts:384:17)
    at wrapper (pyodide.asm.js:14:205222)
```

**Comment by marimeireles** [comment]
@madhur-tandon could you please check this one too?

**Comment by JeffersGlass** [comment]
Since `pyscript.py` has been moved to a module as of #961, it is now possible to use `import pyscript` or `from pyscript import...` inside other modules ("child scripts").

Closing as complete.
