### ISSUE TITLE
Creating dashboards with GH project

### ISSUE THREAD

**Issue by marimeireles** [pyscript/pyscript#533]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a duplication
- [X] I already searched in Google and didn't find any good information or help

### What is the issue/comment/problem?

We want to have a neat and open interface to our users and us on the development of the project.
We decided to adopt GH project because it's easy to use, it's integrated with the rest of the PyScript environment (because it's all on GH) and we've seen it being successful in [other projects](https://github.com/orgs/conda/projects/2/views/13).
This board will separate our issues into categories and will also hold a tab for our weekly sprints.

TODO:

- [x] Copy tabs that make sense from Conda's interface to our project
  - [x] Linked PR col not working, why?
  - [x] We need a secrete key
- [x] Set-up actions that should be related to the `needs-triage` tag, using [this](https://github.com/actions/add-to-project) GHA

Other relevant comments:

- IMO we don't need the review tab bc we don't require users to sign anything, not the sorting either? I don't really see the point of this tab
- maybe we should have something to clean our Closed tab automatically after the end of each sprint

There are many subtasks on the first point of this issue, but I believe that's it!

**Comment by marimeireles** [comment]
Currently on hold because we need a bot to be set-up by the IT team for this to keep going =)

**Comment by marimeireles** [comment]
Oh yeah baby 👼 it works.

We just need to add all the tabs and add new tags too.
If @madhur-tandon can help with the tabs would be great! :D

@fpliger, to have a dashboard that maps well to what conda is doing we need the following tags:
- triage
- backlog
I'd like to propose the `tag: UI/UX` too since we're talking about tags.
How to go about adding these new tags to the pool Fabio?

**Comment by madhur-tandon** [comment]
I have added all the `views` except `review` and `sorting` as discussed.
I have also created the necessary new `labels` such as `sprint`, `backlog`, etc.
I have also created custom fields such as `Quarter` and `Timeframe`

Updated `Planning` project can be seen here: https://github.com/orgs/pyscript/projects/4

**Comment by fpliger** [comment]
That's absolutely awesome!! Thank you @marimeireles  and @madhur-tandon !! 

+1 on `backlog` and `tag:UI/UX` (and maybe we should remove `tag: style`?  I'm not sure. For sure we need to better define our labels..

**Comment by marimeireles** [comment]
Okay, now we need to do work towards tagging these issues :D
Like all the backlog ones, etc.
Should we have an extra meeting to do these things in preparation or start it with our daily @fpliger?

**Comment by marimeireles** [comment]
#560

**Comment by marimeireles** [comment]
Linked PR col *is* working, the problem is the automatic linking system from GH doesn't work *sometimes?*.
You can go to the development option on the right of a PR and set it manually there anyway. =)
So this is closed as completed 🥳 thanks for all the work @madhur-tandon and @fpliger and @pww217!
