### ISSUE TITLE
Application without py-script tag

### ISSUE THREAD

**Issue by Korijn** [pyscript/pyscript#542]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project are area (see the above section)

### What is the idea?

Is it possible to create an app that runs without a \<py-script\> tag, so that all the python code is contained in python files?

```
      <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
      <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
      <py-env>
        - some_dependency
        - paths:
          - /main.py
      </py-env>
```

### Why is this needed

It would be easier to organize a code base that uses pyscript, if it is possible to split HTML and Python source.

**Comment by tildebyte** [comment]
If I understand your question correctly, this works:

```html
<body>
    <py-script src="foo.py"></py-script>
</body>
```

e.g. see [this demo](https://github.com/tildebyte/file-hosting/tree/main/pages/minimal-demo-pyscript-babylonjs) ([live version](https://tildebyte.github.io/file-hosting/pages/minimal-demo-pyscript-babylonjs/)), which is the "external Python" version of #511

Again, IIUC; I really felt this early on. Trying to debug Python embedded in HTML is 🤢. With this setup, you only have one line in your script tag, and your Python development experience is the same as it would be for any other Python project (e.g. I use VSCode, so all the hints, tooltips, linters etc.)

**Comment by Korijn** [comment]
Yes that's exactly what I was looking for. Perfect! Thanks!
