### ISSUE TITLE
Create versioning and release process announcement

### ISSUE THREAD

**Issue by fpliger** [pyscript/pyscript#544]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a duplication
- [X] I already searched in Google and didn't find any good information or help

### What is the issue/comment/problem?

We now have chosen/implemented a versioning and release process. We need to document it and announce it. This issue is to capture that task.

Acceptance criteria:

- [ ] This information is added to the docs
- [ ] We have post announcing the changes
- [ ] Both above have clear instructions to users on how the process work and how users should upgrade/pin versions

**Comment by marimeireles** [comment]
This is done! :)
