### ISSUE TITLE
PyScript should include version information

### ISSUE THREAD

**Issue by fpliger** [pyscript/pyscript#546]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project are area (see the above section)

### What is the idea?

Each release of PyScript should include a version and make it printable on the console or have it available somewhere 

### Why is this needed

It's important for users to  know what version they are in so they can know what's supported on that version and what not. It can also help with bug reporting, triaging, etc...

### What should happen?

A user should be able to get that information on the console (we can decide if we want to have it by default or ask users to add a flag in <py-config> , like debug: true.

Also, should be able to type `__version__` or `pyscript.__version__` in the REPL and be able to see the current version (or something similar)

**Comment by JeffersGlass** [comment]
Is anyone working on this? I'd be happy to give it a shot.

For access and format, I'd suggest the following, similar to both sys.version_info and [what IPython does](https://github.com/ipython/ipython/blob/c97f6d2ebb9a2eee5bc6531ecaf96dcb0649dadd/IPython/core/release.py#L18-L33): :

`pyscript.version_info()` returns a namedtuple(year, month, day, releaselevel, serial)
`pyscript.__version__` returns a string concatenated with '.', possibly just YYYY.MM.DD?

For example, for a tagged release of version **2023.02.1**:

```python
>>> pyscript.version_info()
version_info(year=2023, month=2, day=1, releaselevel='final', serial=0)
>>> pyscript.__version__
'2023.02.1`
```
 
I've been looking at ways to have these values automatically be set either on pre-release or release, so the tags don't have to be manually updated. The `releaselevel` parameter I imagine would be 'unstable' or 'alpha' in general, so the latest unstable builds can be identified at runtime if needed, and would be 'final' only for tagged releases.

**Comment by marimeireles** [comment]
@JeffersGlass no one is working on this.
If you have the space, please go for it! ☺️
