### ISSUE TITLE
python3.9.6/3.10.0 can't work like this pyscript format

### ISSUE THREAD

**Issue by HakunamatataLeo** [pyscript/pyscript#569]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

<img width="608" alt="image" src="https://user-images.githubusercontent.com/4550421/177097732-cde260f8-7f56-401e-938f-96efe6b9d337.png">
<img width="593" alt="image" src="https://user-images.githubusercontent.com/4550421/177097773-eeed9df9-9b23-47ea-a0c2-d25272437359.png">

**Comment by JeffersGlass** [comment]
Interesting, that code works fine for me:

![image](https://user-images.githubusercontent.com/1931111/177787506-cd83bff8-7998-4804-b4ea-1649c877a77b.png)

From the error message, it looks like both lines are being concatenated into one, as `import time print(time.ctime())`, hence the format error. Seems like something weird is happening with line breaks/line endings. What browser and IDE are you using?

**Comment by HakunamatataLeo** [comment]
> Interesting, that code works fine for me:
> 
> ![image](https://user-images.githubusercontent.com/1931111/177787506-cd83bff8-7998-4804-b4ea-1649c877a77b.png)
> 
> From the error message, it looks like both lines are being concatenated into one, as `import time print(time.ctime())`, hence the format error. Seems like something weird is happening with line breaks/line endings. What browser and IDE are you using?

thx, is format error~
