### ISSUE TITLE
where are asset files?(pyscript.css & pyscript.js)

### ISSUE THREAD

**Issue by j209** [pyscript/pyscript#577]
There in no asset file (pyscript.js & pyscript.css) in download package.

![image](https://user-images.githubusercontent.com/18129232/177709213-9f484c4a-e569-44f2-a004-0e609f393620.png)

**Comment by The-Compiler** [comment]
I agree that the instructions on the page seem rather confusing, though - they don't mention that you need to build anything, and make it seem that you can simply download the zip (step 1), unzip it (step 2), and use the assets (step 3, mentioning `pyscript.css` and `pyscript.js`).
