### ISSUE TITLE
Using h5py

### ISSUE THREAD

**Issue by davidasamy** [pyscript/pyscript#578]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a duplication
- [X] I already searched in Google and didn't find any good information or help

### What is the issue/comment/problem?

It appears that h5py was added in [this pull request](https://github.com/pyodide/pyodide/pull/2411) to Pyodide but not included in the Pyodide version 0.20.0 which py-script uses currently. Is it possible I can use a Pyodide version that includes the support for h5py with Pyscript?

Thanks.

**Comment by nmstoker** [comment]
Hi @davidasamy - sorry, didn't see you'd posted this here too. I gave an answer to your question on the forum, here https://community.anaconda.cloud/t/can-i-use-h5py-with-pyscript/27328/2?u=neil which i think may help you resolve this.

**Comment by davidasamy** [comment]
> Hi @davidasamy - sorry, didn't see you'd posted this here too. I gave an answer to your question on the forum, here https://community.anaconda.cloud/t/can-i-use-h5py-with-pyscript/27328/2?u=neil which i think may help you resolve this.

Hi Neil, thanks for your response. I will check the forum.
