### ISSUE TITLE
Add a line to the makefile that allows people to run the examples on a python server with one line command

### ISSUE THREAD

**Issue by marimeireles** [pyscript/pyscript#585]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project area (see the above section)

### What is the idea?

This comes from a discussion with Fabio.

**Comment by ShirakuGIT** [comment]
Could you assign this to me? I'll try implementing this!

**Comment by marimeireles** [comment]
Hey @ShirakuGIT, thanks for the interest.
This problem was partially addressed by @anirrudh but I'm not sure if they're still on it. @anirrudh, is it okay if @ShirakuGIT take over this issue?
If yes, please feel free to. You can either continue their PR or start one of your own.
Ping me if any doubts arise!
Cheers and thanks.

**Comment by marimeireles** [comment]
Closed by #689
