### ISSUE TITLE
Unable to load excel (xlsx) file in pandas

### ISSUE THREAD

**Issue by do-me** [pyscript/pyscript#588]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I tried to load an excel file from my server (not locally as in #287) with pandas and pyodide's functions but it doesn't work. I know that for `pyodide.open_url(url: str) → _io.StringIO`

> The download of binary files is not supported.

See [here](https://pyodide.org/en/stable/usage/api/python-api.html?highlight=pyfetch#pyodide.http.open_url). (I'm using the function with success for [loading simple csv files](https://geo.rocks/post/pyscript/))
Pyodide's docs claim that I should look into other functions for binary files (like xlsx).

I set up a playground to quickly test it [here](https://geo.rocks/post/pyscript-jupyter-notebook/#working-example), with `test.xlsx` served under `/downloads/test.xlsx`.

I'm coming as far as retrieving the bytes from the response object.

```html
from pyodide.http import pyfetch
import asyncio
import pandas as pd 
import openpyxl
from io import BytesIO

response = await pyfetch(url="https://geo.rocks/downloads/test.xlsx", method="GET")
bytes_response = response.bytes()
BytesIO(bytes_response)
```
But it gives me 

```
JsException(PythonError: Traceback (most recent call last): File "/lib/python3.10/asyncio/futures.py", line 201, in result raise self._exception File "/lib/python3.10/asyncio/tasks.py", line 232, in __step result = coro.send(None) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 500, in eval_code_async await CodeRunner( File "/lib/python3.10/site-packages/_pyodide/_base.py", line 353, in run_async await coroutine File "", line 10, in TypeError: a bytes-like object is required, not 'coroutine' )
```

Afterwards I wanted to read it into a pandas df but I think I'm lacking a tiny piece in the puzzle here. Also the error seems strange as it indeed return the bytes if you leave out the BytesIO function.

`bytes_response` gives 

```
b'PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00A7\x82\xcfn\x01\x00\x00\x04\x05\x00\x00\x13\x00\x08\x02[Content_Types].xml \xa2\x04\x02(\xa0\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\ ...
```

Any clue how to load the response into a df?

### What browsers are you seeing the problem on? (if applicable)

Firefox, Chrome, Safari, Microsoft Edge

**Comment by JeffersGlass** [comment]
You'll need to `await` the `reponse.bytes()` call - it returns a promise that resolves to the actual bytes of the response, per the [fetchResponse API](https://pyodide.org/en/stable/usage/api/python-api.html?highlight=pyfetch#pyodide.http.FetchResponse).

```
from pyodide.http import pyfetch
import asyncio
import pandas as pd 
import openpyxl
from io import BytesIO

response = await pyfetch(url="http://127.0.0.1:5501/examples/test.xlsx", method="GET")
bytes_response = await response.bytes()
BytesIO(bytes_response)
df = pd.read_excel(BytesIO(bytes_response))
print(df.head())
```
![image](https://user-images.githubusercontent.com/1931111/178063203-a76b6843-6b60-49fa-ac7f-cb7f965a8213.png)

The loaded data is odd, possibly due to the formatting of the test file, but the data is at least loading.

**Comment by do-me** [comment]
Perfect, it works, thanks a lot! So in the end I was simply missing another await.
Indeed, my test file was slightly malformatted as the columns 1-3 are empty. 
![image](https://user-images.githubusercontent.com/47481567/178067090-f93f9e84-eaa5-4456-93de-ab8057c48f5a.png)

Added some CSS and changed the test file on my blog, so anyone feel free to test [here](https://geo.rocks/post/pyscript-jupyter-notebook/#working-example) with this (slightly modified) code 
```
from pyodide.http import pyfetch
import asyncio
import pandas as pd 
import openpyxl
from io import BytesIO

response = await pyfetch(url="/downloads/test.xlsx", method="GET")
bytes_response = await response.bytes()
df = pd.read_excel(BytesIO(bytes_response))
df
```

printing a nice df: 

![image](https://user-images.githubusercontent.com/47481567/178068619-75c1f0fa-44ad-432a-a84b-8d4d7763e0ee.png)

Closing as solved.
