### ISSUE TITLE
PyScript CSS is too invasive

### ISSUE THREAD

**Issue by radiantone** [pyscript/pyscript#593]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a duplication
- [X] I already searched in Google and didn't find any good information or help

### What is the issue/comment/problem?

The current pyscript CSS is very large and overlaps with other common classes and styles used by apps, creating some rendering problems. Request it either be trimmed down, or a separate minimal css, or css that doesn't override existing classes be used.

**Comment by marimeireles** [comment]
@fpliger the naming is something I wasn't taking into account.

@radiantone did you see that we made quite a few changes into our CSS files?
The version served on pyscript.net is quite different from the current one lying in main. But I imagine you're talking about the files on main, correct?

Thanks for opening the issue.

**Comment by radiantone** [comment]
I will check but in looking at the css it overrides almost every known tag or class that clobbers some of my apps existing classes. It doesn't look like pyscript should need to express every tag or class in its css, just its own. For example .table, .table-column etc. My app has vendor css that use those classes. Rather pyscript should make its own namespace classes and use that. .pyscript-table, .pyscript-table-column to avoid collisions. If it doesn't use that class, then remove it from the .css completely.

**Comment by fpliger** [comment]
@radiantone @marimeireles I'm pretty sure this issue has been fixed by #452 . The issue was related to us basing a lot of the style on Tailwind, that has been removed.

Can you please try using https://pyscript.net/unstable/pyscript.js and https://pyscript.net/unstable/pyscript.css and see if you are still have the same issues?

**Comment by marimeireles** [comment]
Yep.
I'll close this one as fixed.
Thanks Fabio!
