### ISSUE TITLE
Output raw HTML

### ISSUE THREAD

**Issue by madhavajay** [pyscript/pyscript#602]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I noticed this PR talks about outputting HTML and its merged but it doesn't seem to be available with the current version nor is there any clear explanation on how it would work. I get the feeling that maybe its possible already but that I just don't understand the difference between `pyscript` and `pybox` and the other tags.

My question was how can I do this?
```
<py-script>
html = "<div style='color:red;'>aaaa</div>"
html = html.replace("<", "&lt;").replace(">", "&gt;")
document.getElementById("page").innerHTML = html
</py-script>
<div id="page">
</div>
```

https://github.com/pyscript/pyscript/pull/481

Sorry to double post but I realised the other PR is merged so it might not get seen by anyone seeing as its marked as "done".

I think that the page binding is super awesome and powerful, but for something quick and dirty the ability to just generate HTML strings seems like the easiest thing to generate client side output, so it would be awesome if someone can explain how I can do that or, if its just a matter of waiting for the `cdn` version to be updated with the previous merged release?

### Console info

```shell
Chrome
```

**Comment by tedpatrick** [comment]
Within the `unstable` release soon to be `2022.09.1` here is a working example of this bug working.

Example on `unstable`
```html
<html>
<head>
    <link rel="stylesheet" href="https://pyscript.net/unstable/pyscript.css" />
    <script defer src="https://pyscript.net/unstable/pyscript.js"></script>
</head>
<body>
    <div id="out"></div>
    <py-script>
import js

html = "<div><strong>foo</strong></div>"
out = Element("out")
out.element.innerHTML = html
    </py-script>
</body>
</html>
```
