### ISSUE TITLE
PyScript should support rendering text

### ISSUE THREAD

**Issue by fpliger** [pyscript/pyscript#606]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project area (see the above section)

### What is the idea?

This is a proposal about adding a new tag to improve support for formatting and rendering text. It is an extension of #276 (that was proposing support for Markdown) so that we can have one tag that can be used to render text and if can/should support different formats. Basically, instead of creating many tags like `<py-md>`, `<py-asciidoc>`, `<py-text>`, `<py-rest>`, etc... I'm proposing that we have one `<py-text>` that should default to something meaningful (`markdown`? ) but support a `format` attribute that can be set to support other formats

### Why is this needed

This is needed to enable easier and faster content authoring with PyScript.

### What should happen?

We should add a new tag `<py-text>` that supports a `format` attribute, to specify the format, and it should render the formatted text in a new `div`

**Comment by marimeireles** [comment]
How about this one @fpliger? Still relevant?

**Comment by fpliger** [comment]
I think we can close this one.... we have the markdown plugin and this should probably be a plugin, not a core feature (at least not until there's a proven case for it)
