### ISSUE TITLE
Some multi-line pyscripts fail when enabling Auto Minify for HTML on Cloudflare

### ISSUE THREAD

**Issue by miron** [pyscript/pyscript#611]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

This should be an obvious bug, when minifying html, pyscript throws an indentation error. 
But this doesn't happen with every script (see addition al context).

### Console info

```shell
JsException(PythonError: Traceback (most recent call last): File "/lib/python3.10/site-packages/_pyodide/_base.py", line 421, in eval_code CodeRunner( File "/lib/python3.10/site-packages/_pyodide/_base.py", line 237, in __init__ self.ast = next(self._gen) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 141, in _parse_and_compile_gen mod = compile(source, filename, mode, flags | ast.PyCF_ONLY_AST) File "", line 11 label.set_color('blue') ^^^^^ IndentationError: expected an indented block after 'for' statement on line 10 )
```

### Additional Context

Not sure how this can be solved, maybe include the `<py-script>` tag in the next HTML specification and exclute it from minification?
How should I proceed with writing my pyscripts, should I use semicolons instead of indentation when applicable to be on the sure site?   
Sepperate lines seem not to be affected, so should I write my for loops in one line?

This code for example is not affected by minified HTML:
 
```python
   <py-script>
      import datetime as dt
      from random import sample
      pyscript.write('today', dt.date.today().strftime('%A %B %d, %Y'))
      pyscript.write('lotto', f'{sample(range(1,46), 6)}')
    </py-script>
```

Whereas the code below fails when HTML is minified:
```python
    <py-script>
      	import matplotlib.pyplot as plt
	labels = ['1 Mo','3 Mo','6 Mo','1 Yr','2 Yr','3 Yr','5 Yr','7 Yr','10 Yr','20 Yr','30 Yr']
	july16_2007 =[4.75,4.98,5.08,5.01,4.89,4.89,4.95,4.99,5.05,5.21,5.14]
	july16_2020 = [0.12,0.11,0.13,0.14,0.16,0.17,0.28,0.46,0.62,1.09,1.31]
	fig, ax1 = plt.subplots()
	ax1.plot(labels,july16_2007, color='blue', label="july16_2007")
	ax1.set_ylabel("2007", color='blue')
	ax1.spines['left'].set_color('blue')
	ax1.spines['left'].set_linewidth(4)
	for label in ax1.get_yticklabels():
	    label.set_color('blue')
	ax2 = ax1.twinx()
	ax2.plot(labels,july16_2020, color='red', label='july16_2020')
	ax2.set_ylabel("2020", color='red')
	ax2.spines['right'].set_color('red')
	ax2.spines['right'].set_linewidth(4)
	for label in ax2.get_yticklabels():
	    label.set_color('red')
	plt
    </py-script>
```

**Comment by JeffersGlass** [comment]
I suspect Cloudflare's minifier is stripping whitespace out of your python code, while leaving the newlines intact. So your first code block (with everything on the same indentation level) works while your second (which relies on the indented block of `label.set_color('blue')`) doesn't.

Possibly the easiest solution is to make use of the `src` attribute for the pyscript tag to load your script from a separate .py file. So your second example becomes:
```html
<!-- index.html -->
<py-script src="makeaplot.py"></py-script>
```
```python
#makeaplot.py
import matplotlib.pyplot as plt
labels = ['1 Mo','3 Mo','6 Mo','1 Yr','2 Yr','3 Yr','5 Yr','7 Yr','10 Yr','20 Yr','30 Yr']
july16_2007 =[4.75,4.98,5.08,5.01,4.89,4.
...
```
Assuming Cloudflare isn't trying to minify .py files (which would be wild, IMHO), this should solve your issue.,

**Comment by marimeireles** [comment]
@miron could you please confirm Jeffer's assumptions?
This seems very reasonable.
Thanks.

**Comment by marimeireles** [comment]
Closing as non response. But supposing Jeff is correct.

**Comment by miron** [comment]
> @miron could you please confirm Jeffer's assumptions?
> This seems very reasonable.
> Thanks.

Sorry for the non-response, it was either netlify or github pages, but i couldn’t load *.py source files, so it wasn’t a viable solution for me.
