### ISSUE TITLE
Can we use a python server (like in Django manage.py runserver), instead of depending on Node & npm ?

### ISSUE THREAD

**Issue by ksharma20** [pyscript/pyscript#637]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project area (see the above section)

### What is the idea?

This feature will allow the users to work **_independent of node_** and its *respective dependencies*. 
Most of the developers, who work in python (**Django & Flask**) does not like or have node for its poor management of node modules and cache.

### Why is this needed

This is needed so that, Developers who **work primarily in python** (Django/Flask) **_does not have_** to *install node* and *deal with node*.
After all, this was/is the reason, Why Most developers shifted to python Web framework (Django).

### What should happen?

Users, who work in python, will just be working in python, rather than using other dependencies to run the server.
This will remove dependency on *multiple frameworks* and will make it **_reliable and independent_**.

### Additional Context

This WAY **Python** will stay ONLY **Python**

**Comment by dust-to-dust** [comment]
Agree with your point of view, and dependent files(.whl) should be provided by the server instead of CDN(too slow)

**Comment by tedpatrick** [comment]
Within PyScript today, we utilize TypeScript and Rollup which only work when using a NodeJS build process and the node ecosystem of libraries. I believe in using the right tool for the job and here is a clear case where NodeJS adds value to the project. At runtime, there is no NodeJS dependency and any end user can run PyScript with just a browser supporting WASM and Custom Elements.

PyScript Platform developers need NodeJS to build PyScript.
PyScript developers need only HTML to use PyScript.
End users need only HTML to use PyScript.

All of the examples work under any type of web server `python -m http.server`
