### ISSUE TITLE
Error in simple_bioinformatics_tool.html example

### ISSUE THREAD

**Issue by mdlattimore** [pyscript/pyscript#654]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a duplication
- [X] I already searched in Google and didn't find any good information or help

### What is the issue/comment/problem?

Not a bug, but a syntax error in the simple_bioinformatics_tool.html file, found in the examples folder. Lines 52 and 53 attempt to call functions via onClick event attached to the two buttons, "Run" and "Clear". They currently do nothing. The current HTML reads 
```
<div class="control">
            <button id="run" type="button" class="button is-primary" py-onClick="run">Run!</button>
            <button id="clear" type="button" class="button is-danger" py-onClick="clear">Clear</button>
</div>
```
To call the functions, the code should read `pys-onClick="{function}"`

(I spent an hour chasing down the same error in my first PyScript page)

**Comment by madhur-tandon** [comment]
Hi @mdlattimore 

I am not able to reproduce this locally.

It might be possible that you are running the server from the wrong directory.

If you are using `npm run dev`, then probably the command is buggy since it isn't able to locate the `build/pyscript.js` file.

**Comment by antocuni** [comment]
@mdlattimore thanks for the report and sorry for the confusion!
The short version is that as you discovered, our current examples are broken out of the box, see #656 for details.
The easiest way to fix them is to modify the URLs to point to `pyscript.net/unstable/` instead of `pyscript.net/latest/`.

**Comment by mdlattimore** [comment]
Thanks to both of your for your responses.
@antocuni, I did point to `/unstable/` and, of course that did the trick. Thanks for the explanation in #656. It cleared everything up for me.
