### ISSUE TITLE
[py-repl] output-mode="replace" attribute works?

### ISSUE THREAD

**Issue by junnei** [pyscript/pyscript#655]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

In <py-repl> tag, **output-mode="replace"** attribute doesn't work.

In my case,
```
<py-repl output-mode="replace">
print(a)
</py-repl>
```
its output always be appended. how could I change output-mode to "replace" ?

**Comment by JeffersGlass** [comment]
Are you using the alpha release of pyscript, as in the examples? The `output-mode` attribute was introduced in  [#439 - REPL output replacement](https://github.com/pyscript/pyscript/pull/439), and so wasn't present in the alpha versions of pyscript. It appears to be working in the more recent builds.

To make use of the `output-mode` attribute, make sure you're linking to one of the more recent builds, like 

- `https://pyscript.net/releases/2022.06.1/pyscript.js` (most recent pinned release at time of writing) 
- `https://pyscript.net/latest/pyscript.js` (always the most recent pinned release)

**Comment by junnei** [comment]
@JeffersGlass Thx :) 👍🏻 👍🏻

**Comment by AlteriusOmega** [comment]
This should be re-opened as it still isn't working, and py-repl doesn't actually default to resetting but rather defaults to appending

**Comment by JeffersGlass** [comment]
@AlteriusOmega This was fixed in the `2023.05.1` release, and we’re not in the practice of backporting fixes to earlier versions. Do you have issues opened with the things that are blocking you from upgrading to 2023.05.1?

**Comment by AlteriusOmega** [comment]
> we’re not in the practice of backporting fixes to earlier versions
Fair enough. 

>Do you have issues opened with the things that are blocking you from upgrading to 2023.05.1?
Not yet but I will open them soon. I need to get this application working and live before I can start to get into trying suss out the issues with 2023.05.1
