### ISSUE TITLE
Examples should NOT point to /latest/

### ISSUE THREAD

**Issue by antocuni** [pyscript/pyscript#656]
Currently, some of our examples are broken "out of the box".
For example, look at issue #654; to reproduce:
- `git clone git@github.com:pyscript/pyscript.git` (at the time of writing, the latest commit is 2a59ff8)
- open `pyscript/example/simple_bioinformatics_tool.html` *directly* in the browser, without doing `make examples`
- observe that the buttons don't respond.

This specific reproducer was broken by ee9b0960, which changed `pys-onClick` into `py-onClick`. After that commit, the examples work if you do `make examples` and run them using the locally built pyscript, but they don't work with either `pyscript.net/alpha` or `pyscript.net/latest`.

The underlying fundamental problem is that we are trying to use `examples/` in two contradictory ways:

1. as a tool to check that our code works. In this sense, for a given checkout we want examples to work with the pyscript version living in that checkout. This is what `make examples` and our CI is currently testing.
2. as an entry point for beginners to start playing with pyscript: in this sense, we _would like_ that if you `git clone` pyscript and open a random HTML file, it will work out of the box; but to work out of the box, it must point to a globablly available pyscript version, which is what we have been trying to do by pointing them to `pyscript.net/alpha/`, `/latest/` and/or `/unstable/`.

The two statements are contradictory because (1) points to a very precise and fixed-in-stone version of pyscript (the one corresponding to the given checkout) while (2) points to a variable version: for a given checkout, if I point the examples to `/latest/` or `/unstable/`, maybe they will work *today*, but eventually they will break for sure.
This is basically the equivalent of cloning the repository of a random python project and hope that the tests in the `master` branch pass against the latest released version on PyPI: sometimes they will, sometimes they won't.

I think we already discussed IRL with @fpliger and we have two different opinions:
- @fpliger would like people to be able to `git clone` the repo, open the examples in the browser, and play with them (Fabio, please correct me in case I am reporting your thoughts wrongly);
- I think that keeping the dual nature of the examples is fundamentally impossible and will lead to inevitable confusion. So I would like to add some logic which actively *prevents* examples to be opened from a git checkout

If we really want to try to keep them working, the best we can do is to point the examples to `/unstable/`, which points to the latest published git commit. This ensures that if I do a `git clone` and *immediately* open the examples, they will work. However, this is a very partial solution, because it might happen the following:
1. I clone pyscript at commit N
2. at this point in time, `pyscript/examples` point to `/unstable/` which is version N, and they work
3. a certain time `T` passes
4. someone merges a PR with an incompatible change, commit N+1
5. I open the examples: now `/unstable/` points to version N+1, and my examples no longer work unless I `git pull`.

Of course, the more time passes in point (2), the higher is the possibility that someone merges a backwards-incompatible commit. If you are unlucky, it might happen only a few minutes, which makes it *very* confusing for beginners.

This is related to #624, which attempted to fix the problem, but now the examples point to `/latest/` which is already incompatible with the current `main`.

/cc @marimeireles and @pww217

**Comment by antocuni** [comment]
> Should we move the examples to https://github.com/pyscript/pyscript-collective?

this might be a good idea. We could write that the main `pyscript` repo is ONLY for people who wants to modify pyscript itself, and that if you just want to play with it, you should clone `pyscript-collective` and start from the examples.

But I'm not in the position of doing such a call. Let's wait for @fpliger opinions.

**Comment by marimeireles** [comment]
Okay, that makes total sense, thank you so much @antocuni and @madhur-tandon for jumping into this :)

I agree with everything you said here @antocuni, I have some things to add, but I don't think they're going against your points.

What I've been thinking about the examples for a while now (and that's part of the reason we started the collective, thanks Madhur) is that the examples we're using for testing are too complex, they have too many moving parts and a lot of them are repetitive (in the sense of testing the same parts of the code).
We should decided:
a) which examples we want to have as tests
b) which examples should stay in this repo as an introduction to pyscript to people who clone the repo and want to try them
c) permanently move some examples from here to the pyscript collective (the ones who don't fit A and B

**Comment by antocuni** [comment]
> What I've been thinking about the examples for a while now (and that's part of the reason we started the collective, thanks Madhur) is that the examples we're using for testing are too complex, they have too many moving parts and a lot of them are repetitive (in the sense of testing the same parts of the code).

Yes, I agree. Currently we are using the examples as tests because it's the only thing that we have, but eventually we should write proper and smaller tests.

**Comment by marimeireles** [comment]
Yeah, I'm slowly making progress on it!
I hope to post something today by the end of the day.

**Comment by pww217** [comment]
I think that all makes sense. If we had proper tests that made show examples worked properly instead of simply loaded at all, then pointing them to latest would probably work. For now unstable is probably the right way to go.

**Comment by antocuni** [comment]
> I think that all makes sense. If we had proper tests that made show examples worked properly instead of simply loaded at all, then pointing them to latest would probably work. For now unstable is probably the right way to go.

I don't understand. Why having proper tests would make `latest` work? 
My point is that `latest` can never reliably work because `latest` and the `main` branch inevitably drift away.

Tests would help to detect that they stopped working, but then we would not really have any solution for that, because in case of a breaking change, we have to decide: either we keep them working with `/latest/`, or we keep them working with the current checkout.

**Comment by pww217** [comment]
I guess I should have said they'd be more likely to catch broken tests when they occur, but yes they would not provide a fix and therefore block deployments.

So I'm 100% fine moving them to unstable. I think they'll still break with unstable but it'll be easier to track why it broke, at least.

**Comment by fpliger** [comment]
Wow, a lot to chime here :) 

I think the fundamental problem here is that we are not looking at the examples as having the same purpose. Before we align on what we should do with the examples, we should align what is their purpose. 

Initially, the examples were implemented pointing locally and that's it. To run them you'd need to clone the repo and build and run the examples. After feedback from others (that there's value for people to just download and open a file to understand the example, without having to build) and the evolution of things (we also created pyscript.net, where we host examples, etc...) things evolved to the current state of things, where we are trying to accommodate different needs with the same tool.

First, we need to understand the purpose of the examples and if/how it serves each single problem: a dev, pyscript.net and tests. 

My personal opinion is that examples should serve as display of the basic functionality of the latest released of the framework to end users. For this reason (in order):

1. the first goal is that they are displayed somewhere (today is in pyscript.net/examples) correctly and work [bonus points if the users can see the code that is generating that example]
2. they are tested and work when we release a new version (so that they work on pyscript.net)
3. They should not be considered the main source of testing but merely as smoke tests
4. The examples tests right now are basically just a quick and dirty way to mitigate our lack of tests, they are not the solution. The quality problem will only be solved when we add more tests.

[Omitting the fact that they are not a good or comprehensive test suite] The fact that they are serving as tests on every PR is mainly a way for us to understand upfront if a changes broken something at a higher level (consider it as smoke tests) and identifying breaks earlier can help us avoid issues when releasing. Even when we add more tests, I'd advocate that we should still test if we broke our examples as smoke tests...

Now, to answer some of the comments above specifically:

> @fpliger would like people to be able to git clone the repo, open the examples in the browser, and play with them (Fabio, please correct me in case I am reporting your thoughts wrongly);

Not really. My need is listed above. That is a nice to have that I'm happy to drop if we can get the list above ✅  ( @pzwang may have different opinions here though)

>  Should we move the examples to https://github.com/pyscript/pyscript-collective?

> this might be a good idea. We could write that the main pyscript repo is ONLY for people who wants to modify pyscript itself, and that if you just want to play with it, you should clone pyscript-collective and start from the examples.

We may want to move some of the examples to the collective but i strongly believe that, as core team, should have a set of  meaningful examples that serve our users and we guarantee will work on each release

>  My point is that latest can never reliably work because latest and the main branch inevitably drift away.

As I mentioned above, depends on the points of view and what we need. From the pyscript.net/examples point of view `/latest` is the **only** reliable build (and examples should be deployed there and aligned to latest when we release, not when we merge a PR). From the repository and testing point of view, `local build` (and eventually `/unstable`) is the only reliable source since is examples should be in sync with the source.

**Comment by pww217** [comment]
Thank you @fpliger, I agree with all of that. I forgot the fact that we had changed the example sync to pyscript.net  https://github.com/pyscript/pyscript/pull/623 and that the publicly-hosted examples there should update in lockstep with stable releases. So in that sense we want the base files to point to /latest/.

The other use cases (being local runs and not-so-robust tests) can be accomplished by using the Makefile `make example` command which uses `sed` to replace /latest/ with local files which I _believe_ is what we're doing here:

https://github.com/pyscript/pyscript/blob/5b927a70c207a66639865286795e8d790cc63028/pyscriptjs/Makefile#L64

And when we point the pytest execution at those local files either in CI or locally, that is accomplishing what we intend I believe.

However the main theme of this whole discussion is: these are not real tests and we need real tests :P

Until we have real tests we really can't guarantee that examples won't break even  _if_  they're upgraded in lockstep with /latest/.

Does all of that sound correct to everybody?

**Comment by fpliger** [comment]
> However the main theme of this whole discussion is: these are not real tests and we need real tests :P

![Cheers](https://media.giphy.com/media/2wYYlHuEw1UcsJYgAA/giphy.gif)

> Until we have real tests we really can't guarantee that examples won't break even if they're upgraded in lockstep with /latest/.

I'm not sure I understand this statement. Can you clarify?

**Comment by pww217** [comment]
Well the tests as they exist currently don't actually make sure examples work correctly, just that they've rendered in some way or another. So it'll allow deployments to go ahead even if they're broken sometimes.

Basically just means for now we should verify they work after stable releases on pyscript.net.

**Comment by fpliger** [comment]
Ah, yeah, gotcha. We can improve these examples tests (by testing some of the functionality for instance) to be a bit more confident that they "work" through playwright but I think it'll be best practice to always manually check/smoke test them before we roll out a new release.

**Comment by marimeireles** [comment]
I think I agree with everything here. Just reiterating that some tests should be moved e.g the Mario one has too many dependencies and things we don't really care about, it's just hard to maintain (cause we'll be maintaining other work that's not relevant to pyscript).

**Comment by antocuni** [comment]
> My personal opinion is that examples should serve as display of the basic functionality of the latest released of the framework to end users. For this reason (in order):
> 
> 1. the first goal is that they are displayed somewhere (today is in pyscript.net/examples) correctly and work [bonus points if the users can see the code that is generating that example]
> 2. they are tested and work when we release a new version (so that they work on pyscript.net)
> 3. They should not be considered the main source of testing but merely as smoke tests
> 4. The examples tests right now are basically just a quick and dirty way to mitigate our lack of tests, they are not the solution. The quality problem will only be solved when we add more tests.

I agree with all of the above. The point which IMHO causes troubles is this:

> there's value for people to just download and open a file to understand the example, without having to build

I agree it would be nice, but it causes more troubles than it solves. To start with, only the very simple examples work out of the box: all the examples which reference external files don't work, so the hypotetical user will be very confused because half of them work and half don't.

Moreover, as I explained above, there is a fundamental tension between the need of being "self consistent in the repo" (i.e., I expect the examples to work with the pyscript in the same checkout) and "work out of the box with an external URL which changes over time".

Moreover, cloning the git repo is for developers, not casual users. I agree that we want some nice tutorial/getting started for people to start playing with pyscript, but it does not belong to the main pyscript repo, in the same way that python courses are not in the main CPython repo.

I propose the following:

- the `examples` should point to a local url, like `build/pyscript.js`.
- the main entry point for playing with them is `make dev`, which builds the local copy and starts a local webserver 
- we add a small JS logic at the top of each file which checks whether they are being opened locally and warns the user in that case, explaining what's going on and pointing them to the proper resources for "Getting started with PyScript".
- when we do a release, we run a CI which fixes the URL, removes the JS custom logic and push them to pyscript.net.

This way, we are still friendly to the casual user which just open the HTML file, we ensure that examples pushed to pyscrpt.net always work, and we save a lot of headaches.


> > Should we move the examples to https://github.com/pyscript/pyscript-collective?
> 
> > this might be a good idea. We could write that the main pyscript repo is ONLY for people who wants to modify pyscript itself, and that if you just want to play with it, you should clone pyscript-collective and start from the examples.
> 
> We may want to move some of the examples to the collective but i strongly believe that, as core team, should have a set of meaningful examples that serve our users and we guarantee will work on each release

as @marimeireles says, some of the examples like Mario don't really belong to the main repo but I don't have any strong opinion.


> As I mentioned above, depends on the points of view and what we need. From the pyscript.net/examples point of view `/latest` is the **only** reliable build (and examples should be deployed there and aligned to latest when we release, not when we merge a PR). From the repository and testing point of view, `local build` (and eventually `/unstable`) is the only reliable source since is examples should be in sync with the source.

Yes I agree, but we can modify the URL when we publish to `pyscript.net`, there is no need to hardcode it in the git files.

**Comment by pww217** [comment]
If it makes more sense, I don't think it would be that hard to hardcode the examples to use local files and then point them to pyscript.net in the CI when they are synced to pyscript.net/examples along with a latest release. Basically just reversing the current sed flow which takes the URL and converts it to a local path.

This kind of flow makes more sense because we can alter the repo files/runtime environment reliably and in any way we like in the CI. That's obviously much harder on someone's local machine. So let's design around that local experience.

I've actually been meaning to generally clean up the Makefile but this has become such a complex topic maybe we need to just review our objectives at our next sync and make sure we implement fixes correctly. I think a lot of these recent issues are due to a misalignment/misunderstanding of our objectives.

**Comment by fpliger** [comment]
Overall agree with both @antocuni and @pww217 above. Only think we need to shave some edges on these parts of the proposal:


> we add a small JS logic at the top of each file which checks whether they are being opened locally and warns the user in that case, explaining what's going on and pointing them to the proper resources for "Getting started with PyScript".

That's a great proposal and we actually talked about this (or something very close) before. I think this should be an extension or something and not too custom to examples. This, actually, doesn't *need* to be a part of "fixing" the current state and could be an enhancement issue on its own.

> when we do a release, we run a CI which fixes the URL, removes the JS custom logic and push them to pyscript.net.

I think there is still value to keep the custom logic the walks the user through what's going on in the example even when deployed on pyscript.net. That said, we can discuss that in a separate issue related to my comment above.

This is a good discussion, I think we are converging towards a better structure :)

**Comment by antocuni** [comment]
re @pww217 
> If it makes more sense, I don't think it would be that hard to hardcode the examples to use local files and then point them to pyscript.net in the CI when they are synced to pyscript.net/examples along with a latest release. Basically just reversing the current sed flow which takes the URL and converts it to a local path.

yes I agree, that's what I was thinking.

---

re @fpliger 

> That's a great proposal and we actually talked about this (or something very close) before. I think this should be an extension or something and not too custom to examples. This, actually, doesn't _need_ to be a part of "fixing" the current state and could be an enhancement issue on its own.

I'm confused. In my proposal, files in the `examples/` directory will have the following (or similar):
```html
    <script defer src="/build/pyscript.js"></script>
```

So, if you open the HTML directly in the browser, `pyscript.js` will not be found and extensions will never work.
The "custom logic" I'm thinking about is something along these lines:
```js
// examples_warning.js
if (window.location.protocol == 'file:') {
    // this is mostly pseudocode because I don't remember JS APIs
    var body = document.getElement('body');
    body.innerHTML = "Hello, you can't open hello.html directly. You should do make dev, or go to pyscript.net/examples/hello.html or have a look to <a href="...">Getting started</a>
}
```

Then, in every examples, we put the following:
```html
<script src="examples_warning.js">
```

And when we deploy to `pyscript.net`, we remove the `<script>` tag above.


> I think there is still value to keep the custom logic the walks the user through what's going on in the example even when deployed on pyscript.net. That said, we can discuss that in a separate issue related to my comment above.

"The custom logic to walk the user through examples" is a very interesting idea, but I don't think it belongs to the main repo. It should be part of a repo "pyscript-tutorial" or similar.

**Comment by fpliger** [comment]
Aaaaaah, gotcha! I think we already had something like that because of cors but, if not, sounds like a plan! 

Cheers!! 🍻🍻

**Comment by marimeireles** [comment]
This is fixed, correct @pww217?

**Comment by pww217** [comment]
What we have now is examples pointing to latest but being synced along-side latest, ie with a tagged release:

https://github.com/pyscript/pyscript/blob/0a7df78770b0e0ac0e9c532070f989d7cdbb5879/.github/workflows/sync-examples.yml#L5

This is what I believe we eventually agreed on. No solution is 100% stable but this should keep our examples up and running pretty well.

**Comment by marimeireles** [comment]
Alright, thank you for your input here.
So I'm closing this one as solved. =)
If folks here disagree, please feel free to reopen and if you think you have a better solution please speak up.
Cheers!
