### ISSUE TITLE
[Py-repl] result being outside of code block

### ISSUE THREAD

**Issue by junnei** [pyscript/pyscript#658]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

<img width="726" alt="image" src="https://user-images.githubusercontent.com/41983244/182694422-561c044b-ad86-4b71-b124-58495fca982e.png">

The code that should be in the block is often out of the block.
Refreshing the page solves the problem, but I'd like to know what's causing the problem because it's a symptom I often experience when I start the first page.
Is there anyone who can help me?

**Comment by JeffersGlass** [comment]
Interesting - the fact that it resolves when refreshing implies to me that perhaps pyscript.js is not loading very quickly the first time, and the second time it resolves from a cached copy. But perhaps it's something else:

A handful of questions:

- What browser are you using?
- What internet speed are you reliably achieving?
- Does this happen for `<py-script>` tags as well, or just `<py-repl>` tags like in your picture?
- How are you viewing the results? Opening via the file explorer, a live server in an IDE or standalone, serving with a js framework? Some frameworks (nextjs, etc) do funky optimizations with page reloading that could complicate this matter.
- Can you share your source (either embedded here if it's short, or in a Pastebin if longer)?

**Comment by junnei** [comment]
Thank you for your insight. It might be resolves from a cached copy.

I'm sorry for replying late even though you answered hard. I'll talk about how I solved the problem.

it's because both use of 'defer' and 'async' in script tag.
<script **defer** src="https://pyscript.net/latest/pyscript.js"></script>

I found out that this simple mistake caused an error. Thanks again.
