### ISSUE TITLE
Higher Level Python API Design

### ISSUE THREAD

**Issue by fpliger** [pyscript/pyscript#659]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project area (see the above section)

### What is the idea?

The pyscript python API is currently rushed and not well thought. A lot of things are in globals and should not pollute the namespace. 

### Why is this needed

Good design, usabillity and best practices :)usability

### What should happen?

Here's a current proposal from @antocuni :

1. move all the content which is currently in the globals inside a proper pyscript module
2. make the pyscript module available by default
3. make a few selected functions/classes of pyscript also available globally.

@antocuni proposes to start from nothing while I think we should start with `Element` for the next release, add a deprecation warning and eventually move it out in the following release.

Other things will be added as we see fit.  E.g., `display()` will surely need to be a global, as soon as we introduce it.

### Additional Context

See reference: https://github.com/pyscript/pyscript/pull/503#issuecomment-1204435027

**Comment by pauleveritt** [comment]
Are there aspects that are out-of-scope for this?

**Comment by marimeireles** [comment]
I guess this one could be closed?
I don't understand this statement so well:
>make the pyscript module available by default

@fpliger is the issue still relevant?

**Comment by fpliger** [comment]
I think it is, yes

**Comment by DanXvo** [comment]
hello

**Comment by WebReflection** [comment]
I am closing this as maintainer duty as all points have recently been addressed.

If there is one thing I am not 100% sure about is:

> make a few selected functions/classes of pyscript also available globally.

The only exception we have right now is `__terminal__` which exists only within a `terminal` flagged script but everything else is confined within `pyscript` or `pydom` namespaces and both are available by default.

If anyone wants to re-open this, please do but maybe also updating the original issue as it's not clear what else we should do these days to satisfy the requirements.
