### ISSUE TITLE
Javascript casts Python's output float into number

### ISSUE THREAD

**Issue by nwatab** [pyscript/pyscript#670]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

Let's say you want to do some calculation. In Python,
0.1 + 0.9 is 1.0
However, in pyscript, float 1.0 is passed to javascript and it interprets as 1 because Javascript shows it as a Number type.
As a user expect to see python's output, 1 seems like int in Python. float + float isn't int in Python. This is supposed to be a bug.

### What browsers are you seeing the problem on? (if applicable)

Chrome

**Comment by tedpatrick** [comment]
The numerical types within JavaScript and Python are different and crossing the language boundary requires type conversion. The example below shows some aspects of the type conversion process from python to js. 

I am going to close the issue. If you have an additional example you want us to review, please reopen the ticket. Thanks.

Example:
```html
<html>
<head>
    <link rel="stylesheet" href="https://pyscript.net/unstable/pyscript.css" />
    <script defer src="https://pyscript.net/unstable/pyscript.js"></script>
</head>
<body>
    <script>
        console.log( 0.1 + 0.9 ) // float math in JS ==> 1
        console.log( typeof( 0.1 + 0.9 )) //==> number
    </script>
    <py-script>
import js

print( 0.1 + 0.9 ) # 1.0
js.console.log( 0.1 + 0.9 ) # 1
js.console.log( str( 0.1 + 0.9 ) ) # 1.0
js.console.log( str( type( 0.1 + 0.9 ) ) ) #<class 'float'>
    </py-script>
</body>
</html>
```
