### ISSUE TITLE
Qiskit does not load

### ISSUE THREAD

**Issue by LosPhilly** [pyscript/pyscript#671]
Qiskit taking a long time to load in the browser

**Comment by nmstoker** [comment]
Title seems to contradict the contents.🙂
Which is it? Does not load or takes a long time to load?

I suspect it's not a pure Python package and if so, hasn't had the work done to get it importing into Pyodide

**Comment by tedpatrick** [comment]
There is no pure python or WASM targeted whl published for qiskit as of today(9/25/2022).

As module publishing is handled outside of the PyScript project by module owners, it is thus a module owner issue.

Example:
```html
<html>
<head>
    <link rel="stylesheet" href="https://pyscript.net/unstable/pyscript.css" />
    <script defer src="https://pyscript.net/unstable/pyscript.js"></script>
</head>
<body>
    <py-env>
 - qiskit
    </py-env>
    <py-script>
import qiskit
print(qiskit.version)
    </py-script>
</body>
</html>
```
