### ISSUE TITLE
Js TypeError: Cannot read properties of undefined (reading 'setAttribute')

### ISSUE THREAD

**Issue by antocuni** [pyscript/pyscript#677]
This is a JS error which is triggered by `examples/panel_stream.html`: it's very likely that it's not a bug in the example but in pyscript itself, so it should be investigated further.

See also the corresponding test in PR #676:
https://github.com/pyscript/pyscript/blob/c308b0679d924a6a4ccdc7b5131f9a28fa0d14ef/pyscriptjs/tests/test_zz_examples.py#L156-L162

This is the full JS traceback:
```
base.ts:169 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'setAttribute')
    at PyScript.evaluate (base.ts:169:79)
    at async PyodideRuntime.initialize (pyconfig.ts:107:13)
```

*NOTE*: in order to properly fix this issue, a PR should:
- add a new test minimal test (e.g. in `test_01_basic.py`) which showcases the problem
- fix the bug :)
- remove the `@pytest.mark.xfail` from `test_panel_stream` and ensure that it passes

**Comment by FabioRosado** [comment]
This was fixed in #747 but github doesn't like when you fix two issues in one 😄  closing now
