### ISSUE TITLE
[EPIC] Improve test coverage

### ISSUE THREAD

**Issue by antocuni** [pyscript/pyscript#679]
This is an open ended issue to encourage to add more tests to improve our coverage.
We recently did a lot of work to improve our test situation:
  - #663 was merged, and added all the necessary machinery to write integration tests 
  - #676 is not merged yet but it's a good starting point to improve tests of examples
  - #661 and #665 will enable to write JS and Python unit tests

PRs to add more tests are very welcome. For new contributors, it's probably a good idea to start by writing integration tests, since they are the "most ready". A good starting point is to look at the (few) existing tests:
https://github.com/pyscript/pyscript/blob/513dfe0b428c70406d40eef3d9851dabdf27bca6/pyscriptjs/tests/test_01_basic.py#L7-L20

And the docs for the testing machinery itself:
https://github.com/pyscript/pyscript/blob/513dfe0b428c70406d40eef3d9851dabdf27bca6/pyscriptjs/tests/support.py#L11-L37

The list of things which we would like to test includes, but it's not limited to:
  - the behavior of `<py-config>` and `<py-env>`
  - the behavior of event handlers (like e.g. `test_py_button.py:test_click`)
  - the behavior of sync vs async `<py-script>`
  - the ability of generating HTML from a `<py-script>` tag
  - the behavior of the various `<py-*>` components

Ideally, a good test should have the following properties:
  - it should be short and self contained; even if they are integration test, we want to test one feature at a time
  - it should not be fragile and flaky: the content of dynamic web pages is changing continuously so it's hard to write robust tests; playwright [auto waiting](https://playwright.dev/python/docs/actionability) should help in this regard.

Moreover, we also want to improve the tests for our examples. Once #676 is merged, there will be many `XXX improve this test` inside `test_zz_examples.py`, e.g.:
https://github.com/pyscript/pyscript/blob/513dfe0b428c70406d40eef3d9851dabdf27bca6/pyscriptjs/tests/test_zz_examples.py#L76-L81

**Comment by marimeireles** [comment]
Quoting your own example:

>         # this is a very ugly way of checking the content of the DOM. If we 
>         # find ourselves to write a lot of code in this style, we will 
>         # probably want to write a nicer API for it.
         
Maybe you can lay out what are your high level ideas for this API?

>Moreover, we also want to improve the tests for our examples. Once https://github.com/pyscript/pyscript/pull/676 is merged, there will be many XXX improve this test inside test_zz_examples.py, e.g.:

Yes! Philipp started with this by improving the `clock` test. It's a model in case anyone wants to give it a try. It's definitely a `good-first-issue`.
Supposing that's the kind of stuff you mean we should do, @antocuni?
On this topic we should define which examples are staying in the repo and which are going. My take is to remove:
- mario
- bokeh_interactive (I don't understand this example, is it broken, or is it really just a slider?)
- panel_deckgl
- panel_stream
- simple_bioinformatics_tool
- handtrack

Maybe remove:
- antigravity (is not even linked in the index page for examples, not sure why)
- panel_kmeans

Keep the rest. The argument being lots of libraries we don't really care about if they break as in, it's not our focus and we shouldn't spend time fixing examples that suffer from the breakage of these dependencies.

Some random comments of me observing the test suit:
- Should we name all test files with numbers preceding their names?
- I feel like the following line
[`self.testname = request.function.__name__.replace("test_", "")`](https://github.com/pyscript/pyscript/blob/fa7a97ca3087d9f5c0a1fe2787a57201a33a6dce/pyscriptjs/tests/integration/support.py#L57)
Should be documented somewhere so users know how to implement test names.

**Comment by marimeireles** [comment]
@antocuni I think this is broad enough and completed enough that we could close this one?

**Comment by antocuni** [comment]
yes, I think our test coverage is pretty good nowadays. Thank you looking into it, closing the issue now.
