### ISSUE TITLE
issue while importing some libraries

### ISSUE THREAD

**Issue by kalanakt** [pyscript/pyscript#681]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I tried to import like a [ heroku3, pymongo ] libraries. but the page is not loading.

### What browsers are you seeing the problem on? (if applicable)

Firefox

### Console info

```shell
Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 183, in install
    transaction = await self.gather_requirements(requirements, ctx, keep_going)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 173, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 286, in add_requirement
    raise ValueError(
ValueError: Couldn't find a pure Python 3 wheel for 'pymongo'. You can use `micropip.install(..., keep_going=True)` to get a list of all packages with missing wheels.
    PythonError error_handling.gen.ts:309
    new_error pyodide.asm.js:14
    method_call_trampoline pyodide.asm.js:14
    callPyObjectKwargs pyproxy.gen.ts:360
    callPyObject pyproxy.gen.ts:384
    wrapper pyodide.asm.js:14

```

### Additional Context

![image](https://user-images.githubusercontent.com/86665964/183974242-86181e9a-4a3e-412e-8ba0-0eca80812f44.png)

**Comment by tiran** [comment]
- [heroku3](https://pypi.org/project/heroku3/#files) is a pure Python package without a wheel. It provides only an sdist (source distribution). Pyscript can only import wheels. Please get in contact with the maintainers and ask them to release Python wheel as well. It's an easy fix.
- pymongo is more complicated and likely does not work on Pyscript. It is currently not possible to create raw network connections from a browser. Only HTTPS and WebSocket works through alternative APIs. https://github.com/pyscript/pyscript/issues/633 has more information.

**Comment by kalanakt** [comment]
> got it!.
