### ISSUE TITLE
Website and README should discuss versioning scheme

### ISSUE THREAD

**Issue by philippjfr** [pyscript/pyscript#683]
In [this blog post](https://anaconda.cloud/announcing-pyscript-versioning) we announced the versioning scheme for PyScript going forward which includes alpha, latest, unstable, and CalVar releases that users can leverage in their application. In trying to remember what the different releases mean I discovered that we do not mention this anywhere else and the website and the README exclusively refer to the alpha release.

### Why is this needed

Most users currently have no idea that there are releases other than the alpha release.

### What should happen?

We should include description about the various types of releases on the website and the readme.

**Comment by marimeireles** [comment]
This is a dup!
Thank you @philippjfr.
