### ISSUE TITLE
`py-on*` event handler code is being executed at load time

### ISSUE THREAD

**Issue by JeffersGlass** [pyscript/pyscript#685]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

Py-event handler code being executed at page-load, which differs from Javascript in which the code is only executed when the event is received. i.e, in JS one would write `<button onClick="foo()">`, but in PysScript one would currently write `<button py-onClick="foo">` This makes it the syntax for passing arguments to event functions different from Javascript in an unintuitive way.

Consider the following examples, first Javascipt ([JSFiddle](https://jsfiddle.net/4xqLenhw/latest)), then in PyScript ([JSFiddle](https://jsfiddle.net/b2se6fmx/latest)), which I think the user would expect to do the same thing. (You made need to re-save them to get the JS to run):

```js
// Javascript
<button class="submit" id="hello" type="submit" onClick="sayHello('Jeff')">Say Hi</button>
<div id= "greeting"></div>
<script>
    function sayHello(name) {
        document.getElementById('greeting').innerHTML = "Hello, " + name
    }
</script>
```

```js
//PyScript
<button class="submit" id="hello" type="submit" py-onClick="sayHello('Jeff')">Say Hi</button>
<div id="greeting"></div>
<py-script>
    def sayHello(name):
        Element("greeting").write(f"Hello, {name}")
</py-script>
```

The problem is, these two do not do the same thing. The py-onClick code is executed immediately on page-load, [as the value of the py-on* attribute is evaluated directly](https://github.com/pyscript/pyscript/blob/817d0edc69955936cfc69b620a56c27882d6fb05/pyscriptjs/src/components/pyscript.ts#L227-L233).

After the page loads and the PyScript runtime initializes:
![image](https://user-images.githubusercontent.com/1931111/184413467-e712b1c9-7ef7-41ab-9286-7a6648250f06.png)

## Proposed Solution

I suggest changing the behavior of py-on* events to match the Javascript syntax. 

### Additional Context

This was spotted by user mark.d.lattimore [on the Anaconda forums](https://community.anaconda.cloud/t/pys-onclick-function-firing-without-click/31031).

**Comment by marimeireles** [comment]
Hey @fpliger, bringing your attention to this because it's a breaking change.
If I understand it correctly this behavior is wrong and we should change it to match JS. Thanks to @JeffersGlass there's a #686 opened for that.
If you agree with this I can rebase and merge it.
Thanks!

**Comment by fpliger** [comment]
Yup, agree PyScript should not surprise [JS] users. +1

That said, the only issue with the fix is that it'll break previous code... We could use a `deprecation` cycle here. Iirc, the `py-on*` events were not included in the latest release. If not, we could add this correct behaviour only to these attributes and deprecate `pys-on` on the next release and add a deprecation warning when users use `pys-on` in favor to `py-on`.

**Comment by JeffersGlass** [comment]
Makes sense to me - and yeah it looks like the py-on* events were added in [f2955d](https://github.com/pyscript/pyscript/commit/ee9b0960f75dfc8ac4cf538c79813787bdf2955d), a couple days after the 2022.06.1 release.

I'll adjust the PR to change the behavior for the `py-on` events, but leave it unchanged (but deprecated) for `pys-on` events and use the warning to point them to the `py-on` style.
