### ISSUE TITLE
Please provide an installation process that will work for pythonistas

### ISSUE THREAD

**Issue by MarcSkovMadsen** [pyscript/pyscript#69]
I know of experience that a lot of pythonistas don't know about node js etc. And that for example in an enterprise environment it can be very hard to get installed for pythonistas unless you realise that it can be installed via `conda`.

Please provide installation instructions that a newbee pythonista would be able to follow based on a basic familiarity with python tools and terminology.

**Comment by MarcSkovMadsen** [comment]
My suggestion would be something along the lines of

```bash
conda create --name name-of-env -c conda-forge python=3.9 nodejs
conda activate name-of-env
git clone https://github.com/pyscript/pyscript.git
cd pyscript
cd pyscriptjs
npm install
npm run dev
```

where `name-of-env` is something user specific.

Would it be an idea to have seperate installation instructions for `pyscript.js` developers and for pythonista `example` developers?

**Comment by erkin98** [comment]
> My suggestion would be something along the lines of
> 
> ```shell
> conda create --name name-of-env -c conda-forge python=3.9 nodejs
> conda activate name-of-env
> git clone https://github.com/pyscript/pyscript.git
> cd pyscript
> cd pyscriptjs
> npm install
> npm run dev
> ```
> 
> where `name-of-env` is something user specific.
> 
> Would it be an idea to have seperate installation instructions for `pyscript.js` developers and for pythonista `example` developers?

Agree with that, possible solution is to create a *.sh file with installation commands

**Comment by fpliger** [comment]
Yeah, that makes sense.
