### ISSUE TITLE
Consider replacing SimpleHTTPServer with Playwright interceptor

### ISSUE THREAD

**Issue by pauleveritt** [pyscript/pyscript#693]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a duplication
- [X] I already searched in Google and didn't find any good information or help

### What is the issue/comment/problem?

(I discussed this with @fpliger and said I would make a ticket here.)

PyScript Playwright tests could run faster and easier without running an HTTP server.

I was doing a prototype for the PyScript Collective and made use of [Playwright's interceptor approach](https://playwright.dev/python/docs/network#modify-responses). Here is [the purest fixture I wrote](https://github.com/pauleveritt/psc/blob/main/src/psc/fixtures.py#L50) that wires it up.

In essence, no HTTP request is made from the test. Instead, I pick apart the route and serve a static directory from disk. It made things much, much easier. Tests were faster. Most of all, I got tired of my test run hanging because the Python thread died during test debugging.

This idea could be a LOT better than what I did. Here [are some notes](https://pscdemo.readthedocs.io/en/latest/building/playwright.html) I took during the process.

I'm willing to do some of the work in this repo if there's interest.

**Comment by tedpatrick** [comment]
Working on both of these Playwright issues to speed up the test and remove the sporadic test failures.

**Comment by pauleveritt** [comment]
@tedpatrick  Over the weekend I did some "Diary Driven Development" to refactor the Playwright interceptor and get its test code up a good bit. I can share if it is useful.

**Comment by fpliger** [comment]
I was (am) sure @pauleveritt and @tedpatrick  would have many opinions in common 😉

**Comment by pauleveritt** [comment]
Indeed! I did a bit more on the interceptor and locator stuff. Eager to help, but if you have it sorted, feel free to close this issue.

**Comment by pauleveritt** [comment]
Let's drop this. @tedpatrick covered it in #829
