### ISSUE TITLE
Use Playwright's wait_for_selector to delay until Pyodide loads and renders

### ISSUE THREAD

**Issue by pauleveritt** [pyscript/pyscript#694]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a duplication
- [X] I already searched in Google and didn't find any good information or help

### What is the issue/comment/problem?

(I discussed this with @fpliger and said I would make a ticket here.)

The PyScript examples tests when I last looked had to do a timing dance to look at the console logs and see when things should have loaded.

Playwright has a nice [wait_for_selector](https://playwright.dev/python/docs/api/class-elementhandle#element-handle-wait-for-selector) that will wait until something appears on a page, with a configurable timeout. I [used it successfully](https://github.com/pauleveritt/psc/blob/main/tests/examples/test_hello_world.py#L49) in my Collective prototype.

**Comment by tedpatrick** [comment]
Working on both of these Playwright issues to speed up the test and remove the sporadic test failures.

**Comment by antocuni** [comment]
Sorry, I overlooked this issue and seeing it only now.

> The PyScript examples tests when I last looked had to do a timing dance to look at the console logs and see when things should have loaded.
> 
> Playwright has a nice [wait_for_selector](https://playwright.dev/python/docs/api/class-elementhandle#element-handle-wait-for-selector) that will wait until something appears on a page, with a configurable timeout. 

We are already using something similar, introduced by PR #663 .
After running all the scripts in the page, we print a magic string to the console:
https://github.com/pyscript/pyscript/blob/6023c413ab1762e0a1bb2476ed46eb4be2af7944/pyscriptjs/src/runtime.ts#L177-L180

and then all the tests automatically wait for it:
https://github.com/pyscript/pyscript/blob/6023c413ab1762e0a1bb2476ed46eb4be2af7944/pyscriptjs/tests/integration/support.py#L178-L193

**Comment by antocuni** [comment]
That said, some of the test in `test_zz_examples.py` seems to be flaky: some are marked as `xfail` because of that, and I also saw `test_d3` failing here and there.
And also #747 contains a discussion about a test which seem to require a `time.sleep` but we don't understand why.

**Comment by antocuni** [comment]
> FWIW, I went in a different direction than using the console for sending flags. The idea: set a `data-ps-status` attribute in a well-known location (e.g. `<body>`). This lets any other script, such as an app or plugin, know where PyScript's loading is at.

this looks like an interesting idea.
I don't know much about web technologies, is this a standard practice?

**Comment by pauleveritt** [comment]
Not a standard practice, as people like using all-encompassing JS frameworks these days instead of the web platform.

Compared to using `console.log` as a message broker though...it might be more standard. 😀

Think about it, let me know if there's interest. I have a simple writeup, code, tests...outside PyScript.

**Comment by marimeireles** [comment]
> FWIW, I went in a different direction than using the console for sending flags. The idea: set a data-ps-status attribute in a well-known location (e.g. <body>). This lets any other script, such as an app or plugin, know where PyScript's loading is at. https://github.com/pyscript/pyscript/issues/694#issuecomment-1240605084

Ah, this is interesting.
I wonder if it could be incorporated here: https://github.com/pyscript/pyscript/issues/763#issuecomment-1246195260 :)

**Comment by pauleveritt** [comment]
Crap, I didn't see that. I didn't realize I wasn't subscribed to all activity.

I think I might need to bow out on plugins. I have too many opinions on this topic and it's going to be disruptive.

**Comment by pauleveritt** [comment]
Let's drop this also. I'll keep using it for collective stuff.
