### ISSUE TITLE
A small request

### ISSUE THREAD

**Issue by Prakash1124** [pyscript/pyscript#700]
Kindly can you seniors replace `<py-script>` with `<pyscript>`

**Comment by JeffersGlass** [comment]
@Prakash1124 I think maybe you have some html-like tags in your question that GitHub is hiding. For a tag like `<py-script>` to be visible, either surround it with backtick \` characters to put it in a code tag, or put a backslash \\ in front of each of the \<\> characters.

**Comment by marimeireles** [comment]
Hey @Prakash1124 why would you like this change?
Cheers.

**Comment by tedpatrick** [comment]
[Custom Element Standard](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-element-conformance) requires that all valid custom elements contain a hyphen. Since PyScript uses this standard, we must use `<py-` for any valid custom element.

```
They contain a hyphen, used for namespacing and to ensure forward compatibility (since no elements will be added to HTML, SVG, or MathML with hyphen-containing local names in the future).
```
