### ISSUE TITLE
inJest utils throws ReferenceError: process is not defined when using npm run dev

### ISSUE THREAD

**Issue by FabioRosado** [pyscript/pyscript#722]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

Pulled main into my fork and tried to run the py button integration test with pytest, it failed with a ` ReferenceError: process is not defined`. Then I tried to run the examples to see, and they didn't load. The console shows the following error coming from `inJest utils.ts`

```
Uncaught (in promise) ReferenceError: process is not defined
```

Looking briefly into this and trying different things, seems like we can't access `process` when rollup builds, also using the [--environment flag](https://rollupjs.org/guide/en/#--environment-values) didn't help as well.

### Console info

```shell
adding initializer 
async function mountElements()
stores.ts:22:12
added initializer 
async function mountElements()
stores.ts:24:12
adding post initializer 
async function initHandlers()
stores.ts:27:12
added post initializer 
async function initHandlers()
stores.ts:29:12
RUNTIME READY pyenv.ts:8:12
initializers set runtime.ts:9:12
post initializers set runtime.ts:14:12
scripts queue set runtime.ts:19:12
config set! runtime.ts:28:12
scripts queue set runtime.ts:19:12
connected pyscript.ts:56:16
config set! runtime.ts:28:12
config set 
Object { autoclose_loader: true, runtimes: (1) […] }
pyconfig.ts:46:16
Initializing runtimes... pyconfig.ts:58:16
creating pyodide runtime pyodide.ts:14:16
Uncaught (in promise) ReferenceError: process is not defined
    inJest utils.ts:81
    loadInterpreter pyodide.ts:18
    initialize runtime.ts:55
    loadRuntimes pyconfig.ts:63
utils.ts:81:4
```

### Additional Context

I tried two things, both seem to fix the issue where `process` is undefined, but another issue cropped up:
- wrapping [`return process.env.JEST_WORKER_ID !== undefined;`](https://github.com/pyscript/pyscript/blob/7aa25712d95fc764f9a84ccd842c2d4d992e8a7a/pyscriptjs/src/utils.ts#L91) in a try/catch
- Using  the `rollup-plugin-inject-process-env` plugin 

```
adding initializer 
async function mountElements()
stores.ts:22:12
added initializer 
async function mountElements()
stores.ts:24:12
adding post initializer 
async function initHandlers()
stores.ts:27:12
added post initializer 
async function initHandlers()
stores.ts:29:12
RUNTIME READY pyenv.ts:8:12
initializers set runtime.ts:9:12
post initializers set runtime.ts:14:12
scripts queue set runtime.ts:19:12
config set! runtime.ts:28:12
scripts queue set runtime.ts:19:12
connected pyscript.ts:56:16
config set! runtime.ts:28:12
config set 
Object { autoclose_loader: true, runtimes: (1) […] }
pyconfig.ts:46:16
Initializing runtimes... pyconfig.ts:58:16
creating pyodide runtime pyodide.ts:14:16
Loading module from “http://localhost:8080/build/pyodide.asm.js” was blocked because of a disallowed MIME type (“”). 
Loading failed for the module with source “http://localhost:8080/build/pyodide.asm.js”. hello_world.html:12:1
Uncaught (in promise) TypeError: error loading dynamically imported module
Uncaught (in promise) Error: Failed to load 'http://localhost:8080/build/pyodide_py.tar': request failed.
    loadBinaryFile pyodide.mjs:1
pyodide.mjs:1:8015
```

Not sure if it's worth to mention, but the plugin worked because it's simply try/catching `process.env` and if `process` is undefined, it's adding it to `globalThis` ([relevant code](https://github.com/badcafe/rollup-plugin-inject-process-env/blob/master/src/index.ts#L53-L60))

**Comment by madhur-tandon** [comment]
Closing because https://github.com/pyscript/pyscript/pull/721 is merged.

**Comment by FabioRosado** [comment]
Ah awesome! Apologies I missed that PR 😄
