### ISSUE TITLE
Correctly handle HTML entities inside <py-script> source code

### ISSUE THREAD

**Issue by antocuni** [pyscript/pyscript#735]
Follow up of this conversation: https://github.com/pyscript/pyscript/pull/684#discussion_r957047621

This is best explained by a simple example:
```html
<script type="text/javascript">
console.log("js: a &amp; b");
</script>
<py-script>
import js
js.console.log("py: a &amp; b");
</py-script>
```

This produces the following:
```
js: a &amp; b
py: a & b
```

This is even worse if we use `&quot;` or `&apos;`, because currently they are interpreted as quotes and thus they can easily trigger Python syntax errors; e.g. the following trigger a `SyntaxError`:
```html
<py-script>
import js
js.console.log("py: a &quot; b");
</py-script>
```

By reading the code, it seems that the interpretation of HTML entities happens here:
https://github.com/pyscript/pyscript/blob/6cb81b5c3d21ca8f71431c079ce83103154fabc9/pyscriptjs/src/utils.ts#L17-L24

I don't really understand what's going on: inside `htmlDecode` `input` seems to be the raw string of text that we want; then we put it inside `DOMParser()`, only to extract the text back.
PR #684 mitigates the issue by escaping angle brackets, but why do we need to call `DOMParser` in the first place?

/cc @philippjfr who worked on this recently and @fpliger who might remember what was the original idea

**Comment by fpliger** [comment]
I think this is part of the bigger redesign work we need to do in #622, so putting it as a subtask there...

To your question. @antocuni I think this was due to behavior when you want the output to be inserted back in the DOM and things for mixed up. Definitely needs to be rethought, and either put behind an option flag or removed.

**Comment by philippjfr** [comment]
>I think this was due to behavior when you want the output to be inserted back in the DOM and things for mixed up. Definitely needs to be rethought, and either put behind an option flag or removed.

I don't think that's the reason. I might be wrong but without the DOMParser approach we couldn't handle any of the special characters `>`, `<` and `&`, e.g. see https://github.com/pyscript/pyscript/pull/481

**Comment by philippjfr** [comment]
Ah I see what you're getting at now @fpliger, yes that sounds right.

**Comment by antocuni** [comment]
> To your question. @antocuni I think this was due to behavior when you want the output to be inserted back in the DOM and things for mixed up.

I still don't understand.
According to grep, `htmlDecode` is used to decode the source code inside `<py-script>`, `<py-button>` and it's never used for the output.

**Comment by antocuni** [comment]
Moreover, it seems that `htmlDecode` is called *twice*, unless I'm mistaken.
First, it is called when we set `this.code`:
https://github.com/pyscript/pyscript/blob/6cb81b5c3d21ca8f71431c079ce83103154fabc9/pyscriptjs/src/components/pyscript.ts#L33-L37

Later, it is called inside `getSourceElement()`:
https://github.com/pyscript/pyscript/blob/6cb81b5c3d21ca8f71431c079ce83103154fabc9/pyscriptjs/src/components/pyscript.ts#L111-L114

If I apply this patch:
```diff
diff --git a/pyscriptjs/src/components/pyscript.ts b/pyscriptjs/src/components/pyscript.ts
index 19ac005..4aa19d7 100644
--- a/pyscriptjs/src/components/pyscript.ts
+++ b/pyscriptjs/src/components/pyscript.ts
@@ -32,7 +32,8 @@ export class PyScript extends BaseEvalElement {
 
     connectedCallback() {
         this.checkId();
-        this.code = htmlDecode(this.innerHTML);
+        //this.code = htmlDecode(this.innerHTML);
+        this.code = this.innerHTML;
         this.innerHTML = '';
 
         const mainDiv = document.createElement('div');
@@ -110,7 +111,8 @@ export class PyScript extends BaseEvalElement {
     }
 
     getSourceFromElement(): string {
-        return htmlDecode(this.code);
+        //return htmlDecode(this.code);
+        return this.code;
     }
 }
```

I confirm that `<py-script>console.info("a &amp; b") </py-script>` correctly prints `a &amp; b`.

Moreover, `<py-repl>console.info("a &amp; b") </py-repl>` has a similar problem, which seems to be *not* fixed by the patch above
![image](https://user-images.githubusercontent.com/344507/187499589-f0e0818e-43c7-4044-ac2e-8f00c22d8d54.png)

**Comment by fpliger** [comment]
It does look like it's being called twice (and it's a bug). Still, it's something that will be taken care as part of the bigger redesign work in https://github.com/pyscript/pyscript/issues/622

**Comment by antocuni** [comment]
> It does look like it's being called twice (and it's a bug). Still, it's something that will be taken care as part of the bigger redesign work in https://github.com/pyscript/pyscript/issues/622

if you say so 😅.
I still think this is a problem of *reading* the py-script source code and thus it's orthogonal to how we handle the *output* produced by executing the scripts, but I suppose we can just wait and see whether #622 will fix the problem :)

**Comment by marimeireles** [comment]
I talked to @antocuni about it and agree with redesigning it as part of #622 efforts.

**Comment by antocuni** [comment]
> I talked to @antocuni about it and agree with redesigning it as part of #622 efforts.

@marimeireles make sure to add the relevant tests ;)

**Comment by marimeireles** [comment]
I think this is related...
https://github.com/pyscript/pyscript/issues/518
We should at least investigate if this is still reproducible or what's up =)

**Comment by marimeireles** [comment]
Adding a snippet of an example of things that don't work:
```
    def test_display_line_break(self):
        self.pyscript_run(
            r"""
            <py-script>
            display('hello\nworld')
            </py-script>
        """
        )
        inner_text = self.page.inner_text("html")
        # XXX fixme
        assert "hello\nworld" == inner_text
```
White spaces in `divs` but they do work on `pre`s so, maybe that's a solution? (Don't trust me though, I don't know web)

**Comment by WebReflection** [comment]
Oooops, re-opening in case this wasn't meant to be closed, as @FabioRosado approved and I've seen also others are flagging main thread tests "*to be skipped*" for workers, as workers won't see that code outside the main thread anyway.

Feel free to re-close if we want to provide the `<script type="py">` as solution for these weird cases, but also we should likely use the same for all tests that are currently running SVG as those are kinda broken in the real world, as Hood reviously spotted already (the browser throws errors around `<circle>` elements and others within a generic HTMLElement).

**Comment by antocuni** [comment]
Workers have nothing to do with discussions, so I think we can just mark this a closed.
Closing it now, feel free to reopen in case I missed anything
