### ISSUE TITLE
Unable to use pyscript in a sveltekit app

### ISSUE THREAD

**Issue by fcrozatier** [pyscript/pyscript#744]
### Checklist

- [x] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

The `py-script` custom element works fine in the `app.html` but not in a `+page.svelte`

Reproduction https://github.com/fcrozatier/kit_pyscript

### What browsers are you seeing the problem on? (if applicable)

Firefox, Chrome, Safari, Microsoft Edge

**Comment by JeffersGlass** [comment]
I'm not particularly familiar with how svelte does page rendering, but here's a couple observations that might be helpful:

The PyScript is indeed being executed in the +page.svelte context - if you add the following PyScript in that page, you can see the results in the dev console:
```python
from js import console
console.log("Hello from +page.svelte")
```
---
Output error handling was changed somewhat between the alpha release your linking to and the latest release (2022.06.1). Pointing the script tag to `https://pyscript.net/latest/pyscript.js` we can see an error about "NoneType object [having] no attribute "childElementCont" in the dev console:
![image](https://user-images.githubusercontent.com/1931111/188156932-d65daf31-10b8-40ba-b704-45e8ab01b784.png)
Which implies that the \<py-script\> tag is being removed from the DOM before the Pyscript runtime runs - by default, [PyScript tries to create a new div](https://github.com/pyscript/pyscript/blob/01b64e18aba963283678919cbdfc111844086e67/pyscriptjs/src/pyscript.py#L160-L164) as a child of the \<py-script\> tag and send output from stdout there. If you uncoment the <py-script> tag in app.html and inspect the DOM, you can see this happening.

So maybe svelte is stripping the \<py-script\> tag itself from the DOM, sometime after PyScript retrieves its contents as code but before it executes? Does svelte remove unknown custom HTML elements inside routes/.svelte? Perhaps someone with deeper svelte knowledge can go further.

**Comment by fcrozatier** [comment]
I've updated pyscript to the `lastest`version and fixed vite version to avoid having to force the install in the reproduction.

> So maybe svelte is stripping the <py-script> tag itself from the DOM, sometime after PyScript retrieves its contents as code but before it executes?

This could be some kind of race condition?

**Comment by fcrozatier** [comment]
To make it work I can bypass the hydration step by waiting `onMount` to load pyscript. This has some consequences (FOUC etc.) for the user. 

Will close in favor of https://github.com/pyscript/pyscript/issues/746
