### ISSUE TITLE
Add docs for opening/saving files 

### ISSUE THREAD

**Issue by marimeireles** [pyscript/pyscript#756]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a duplication
- [X] I already searched in Google and didn't find any good information or help

### What is the issue/comment/problem?

This is an umbrella issue to take care of all issues related to how to open files from your file system using PyScript.

This is not necessarily a responsibility of our framework (or at least not yet since we don't have this in our API) but there are so many requests about it, I think it'd be very beneficial to add a page in our "How to" section of the docs.

Please, correct me if I'm wrong @antocuni but I guess this is still the best solution we have? 
https://github.com/pyscript/pyscript/issues/179#issuecomment-1119616160

I think it's also fair to say the PyScript team is working on something that might offer users a kind of solution for that. This feature should be done by the end of the month of sept. 2022 and we'll announce it broadly.

Issue where we track the actual API development to fix this issue rather than using a workaround: https://github.com/pyscript/pyscript/issues/558

Related issues:
https://github.com/pyscript/pyscript/issues/595

Closes issues:
https://github.com/pyscript/pyscript/issues/558
https://github.com/pyscript/pyscript/issues/146
https://github.com/pyscript/pyscript/issues/399
https://github.com/pyscript/pyscript/issues/748
https://github.com/pyscript/pyscript/issues/179
https://github.com/pyscript/pyscript/issues/146
https://github.com/pyscript/pyscript/issues/124
https://github.com/pyscript/pyscript/issues/111

**Comment by antocuni** [comment]
> Please, correct me if I'm wrong @antocuni but I guess this is still the best solution we have?
> [#179 (comment)](https://github.com/pyscript/pyscript/issues/179#issuecomment-1119616160)

yes it is

**Comment by WebReflection** [comment]
It looks like https://github.com/pyscript/pyscript/issues/595 is the only opened one but the final solution should work even on main thread on latest PyScript, not just classic ... that solution *is* how download links are created on the Web too but it looks like some documentation or modern example might be still needed or beneficial ... and I wonder if @JeffersGlass by any chance wrote already something related to files upload/download from either DOM input file fields or the virtual FS.

**Comment by WebReflection** [comment]
this has been fixed and explained with the latest documentation which should be live ASAP ... in there we explain how to load files from users, save in the virtual FS, eventually read or download these from there, and so on.

There is not much activity in here so I am closing it ahead of time as I know we and Jeff both documented the "circus" around files. We can re-open this if needed in the future.
