### ISSUE TITLE
Make pyscript.write replace content instead of append

### ISSUE THREAD

**Issue by MarcSkovMadsen** [pyscript/pyscript#76]
I believe `<py-script output="plot">...</py-script>` should replace the contents of the `plot` element instead of appending.

That would make it easy to display a loading indicator as content until pyscript has loaded and run the script.

**Comment by MarcSkovMadsen** [comment]
## Example

Here is an example where I would like `pyscript.write` to replace content.

```html
<html>
  <head>
    <!-- The link to the pyscript files are to be replaced official files when they are available at a CDN -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/MarcSkovMadsen/awesome-pyscript@master/assets/pyscript/pyscript.css" />
    <script defer src="https://cdn.jsdelivr.net/gh/MarcSkovMadsen/awesome-pyscript@master/assets/pyscript/pyscript.js"></script>
    <py-env>
    - numpy
    - matplotlib
    </py-env>
  </head>
  <body>
    <h1>Let's plot random numbers</h1>
    <div id="plot">...loading</div>
<py-script output="plot">
import matplotlib.pyplot as plt
import numpy as np

x = np.random.randn(1000)
y = np.random.randn(1000)

fig, ax = plt.subplots()
ax.scatter(x, y)
fig
</py-script>
    </body>
</html>
```

**Comment by MarcSkovMadsen** [comment]
Looking at the pyscript code, I think it actually should append, but for some reason does not.

![image](https://user-images.githubusercontent.com/42288570/166130432-ef8d7e88-ab2c-4e2c-8fea-0f56afed842a.png)

**Comment by MarcSkovMadsen** [comment]
Is can see in the typescript code that an `output-mode` attribute is thought of but right now its not used for anything

![image](https://user-images.githubusercontent.com/42288570/166130664-84bc1239-06a7-45a3-9fd6-8b8efb74abb5.png)

**Comment by MarcSkovMadsen** [comment]
For now the way to go if I want append is using `pyscript.write('plot', fig)`.

**Comment by fpliger** [comment]
This is a bug. I've added `output-mode` because I don't think there's a "right" or "wrong" use case. There's a "what you'd expect for this use case" and probably any options won't make everyone happy.

With that said, the attribute is not fully hooked to the Python layer as it should.

**Comment by marimeireles** [comment]
This issue is going to be completely resolved by https://github.com/pyscript/pyscript/pull/749.
Currently `pyscript.write` is deprecated and the `display` method will be the default way of showing elements in the UI, if you're interested in joining the discussion to help shape the API design feel free to jump in: https://github.com/pyscript/pyscript/issues/769
I'm closing this issue because it's not relevant anymore, but please feel free to voice opinions/concerns in the pointed issue.
Cheers and thanks!
