### ISSUE TITLE
problems with joblib, keras and tensorflow in pyscript

### ISSUE THREAD

**Issue by linuxesdios** [pyscript/pyscript#765]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a duplication
- [X] I already searched in Google and didn't find any good information or help

### What is the issue/comment/problem?

problems with joblib, keras and tensorflow.

When I run the following code, the system crashes and doesn't allow me to see anything. Could it be a capacity problem?

If I run it as a local code the application works perfectly

```
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import numpy as np
import joblib
import keras
import tensorflow
import pandas
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
model=joblib.load('modelo_v1.pkl')
predictions= model.predict([[[4495358.3334], [373583.4977], [55.25], [1], [3], [2022], [0], [5], [169.69]]]).flatten()
print('Predicción: ', predictions)
```
![image](https://user-images.githubusercontent.com/2717922/189951016-7fe1bd36-5260-4a0e-873d-ecfb0031f5e8.png)

add complete code
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Sine Wave</title>
  <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
  <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
</head>
<body>
  <py-env>
    - joblib
    - numpy
    - pandas
    - keras
    - os
    - tensorflow
    - paths:
        - ./modelo_v1.pkl

  </py-env>
  <py-script>
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import numpy as np
import joblib
import keras
import tensorflow
import pandas
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
model=joblib.load('modelo_v1.pkl')
predictions= model.predict([[[4495358.3334], [373583.4977], [55.25], [1], [3], [2022], [0], [5], [169.69]]]).flatten()
print('Predicción: ', predictions)
  </py-script>
</body>
</html>
```
Thanks

**Comment by marimeireles** [comment]
>When I run the following code, the system crashes and doesn't allow me to see anything. Could it be a capacity problem?

What's the error message?

**Comment by rth** [comment]
As far as I know tensorflow (and keras) has not yet been packaged for WASM (at least the tensorflow Python package != tensorflow.js) so it is expected that this would not work.

**Comment by tedpatrick** [comment]
There is no pure python or WASM targeted whl published for tensorflow as of today(9/25/2022). 

As module publishing is handled outside of the PyScript project by module owners, it is thus a module owner issue.
