### ISSUE TITLE
[Discussion] Examples and their use for pyscript.net, locally, and for testing

### ISSUE THREAD

**Issue by pww217** [pyscript/pyscript#766]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a duplication
- [X] I already searched in Google and didn't find any good information or help

### What is the issue/comment/problem?

The way we've handled examples thus far has been a bit messy.

**Current state of examples** is that they exist in the root directory and point to `pyscript.net/latest`.

There are two issues to separate out here:

## Where should the examples directory live?

The is the question that needs answering.

Originally it was in `pyscriptjs/` or `pyscriptjs/build/` - I don't recall now - and was moved to the root directory to be more obvious to users who wouldn't necessarily expect to find it nested further down. It also made for cleaner CI. 

Once this move was made however `make examples` was created in the [Makefile](https://github.com/pyscript/pyscript/blob/1c0be16f30961c234f0529b189e8ae685ece1474/pyscriptjs/Makefile#L61) to essentially create a local copy to run tests against, among other things. `make examples` is complex and prone to breaking though because it uses a `sed` command to accomplish all this. Later came `run examples`.

In my opinion this has all led to more confusion than anything. I also have a question:

- Do examples have to live in `pyscriptjs/` or be in the `build/` directory? Why can't we use relative pathing to point the local build of pyscript to examples in directories above like `../../examples/`? Particularly if those examples are similarly pointing back to that same local build (see below)? Or am I missing something?

## Should example point to a local build or to pyscript.net?

This question has been resolved but is here for context.

There are 3 use cases for examples at the moment:

1. Show off pyscript on pyscript.net/examples 
2. Run examples against a branch locally from a cloned repo
3. Run tests against examples in a CI environment

Currently they point to pyscript.net/latest/ but this only makes sense for the examples published on pyscript.net via [this workflow.](https://github.com/pyscript/pyscript/blob/main/.github/workflows/sync-examples.yml). This is purely so that the website can function.

But case # 2 and 3 require the example to point to a locally built file, typically built from the `main` branch or a feature branch. That's why I had create this [PR](https://github.com/pyscript/pyscript/pull/696) which would make local builds the "default" path to find `pyscript.js` and `pyscript.css`. 

I hoped by that doing this we would **be able to remove `make examples`** and simplify the `Makefile`. To [publish](https://github.com/pyscript/pyscript/blob/main/.github/workflows/sync-examples.yml) examples to the website I would then change the local path to `pyscript.net/latest/pyscript.js` via CI automation, which is an easier and more predictable piece of automation than trying to control what local users or tests are doing.

**Comment by marimeireles** [comment]
>Where should the examples directory live?

Maybe they should be inside of `build` to make a distinction on the raw examples we have on the root of the directory? I really don't have strong opinions on this anymore. If they live on `pyscriptjs` or `pyscriptjs/build` I think both are a fine place. If we make any change, it's important to check all the commands that are interacting with it on the `Makefile`, and also the `yml` files for the CI.

So I guess I'm +0 for this.

I don't see such a problem in using `sed`. What would be a way of doing it differently?

Thanks for opening this Peter. =)

**Comment by pauleveritt** [comment]
FWIW the Collective anticipates moving the examples out of the core, but that decision is still underway. I have a prototype for a new approach on examples that I wrote up over the summer.

**Comment by marimeireles** [comment]
I guess we finally settled on these questions.
There's still space to change though if anyone ever thinks differently :)
Closing for now.
