### ISSUE TITLE
GitHub Pages deployment error

### ISSUE THREAD

**Issue by giswqs** [pyscript/pyscript#77]
When deploying the pyscript html to GitHub Pages, I got the following error. Any advice?

https://github.com/giswqs/pyscript-demo/blob/master/folium.html
> github-pages 226 | Error:  No such file or directory @ rb_check_realpath_internal - /github/workspace/priviate/toga/static/pyscript

https://github.com/giswqs/pyscript-demo/runs/6244144855?check_suite_focus=true#step:4:70

**Comment by verhulstm** [comment]
sure,

look at this
https://github.com/verhulstm/pyscript-demo
https://verhulstm.github.io/pyscript-demo/

**Comment by verhulstm** [comment]
i sent you pr

https://github.com/giswqs/pyscript-demo/pull/

**Comment by verhulstm** [comment]
you have to have index.html 

and you need the ".nojekyll" file in the branch you build the site from

**Comment by verhulstm** [comment]
and you need

<!DOCTYPE html>

at the top of your html file.

gh-pages is picky

**Comment by giswqs** [comment]
@verhulstm It works now. Many thanks for helping out.
