### ISSUE TITLE
Write docs on how to contribute a PR and remove linting commands from Makefile

### ISSUE THREAD

**Issue by marimeireles** [pyscript/pyscript#770]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project area (see the above section)

### What is the idea?

To improve the quality of the PRs.

Good practices:

To start from scratch:

- fork the repo
- have your local fork as origin
- have the upstream project as upstream
`git remote add upstream git@github.com:pyscript/pyscript.git`

if you already have it forked make sure your personal fork is up to date with the upstream repository
`git pull upstream main`
`git push origin main`

for every new issue create a new branch:
`git checkout -b branch-name`

...
make your changes
...

run:
`pre-commit`
to have all of your changes linted

run:
`make tests`
to make sure your changes are passing changes

If you have a conflict in your code:

`git rebase -i main`

fix all conflicts

`git rebase --continue`

force push the fixed commits:

`git push -f origin branch_name`

It'd be nice if someone can pick this up and add it to our `CONTRIBUTING.md` file with a more comprehensible, friendly format.

Also in a side note, I think we should remove the commands on our `Makefile` to lint things, it's confusing. We should only use the `pre-commit` tool.

Both of these could be in the same PR :+1:

**Comment by sumahadevan** [comment]
I think the above information is very helpful when preparing a new PR. In particular, not being fully aware of the specific requirements of this repository, I would very likely have missed the additional steps for running 'pre-commit' and 'make tests'.

And of course, clearly specifying the other standard good practices to be followed is also extremely helpful.
