### ISSUE TITLE
Js import doc failure

### ISSUE THREAD

**Issue by 21Turtles** [pyscript/pyscript#771]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

JsException(PythonError: Traceback (most recent call last): File "/lib/python3.10/site-packages/_pyodide/_base.py", line 429, in eval_code .run(globals, locals) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 300, in run coroutine = eval(self.code, globals, locals) File "", line 4, in File "/lib/python3.10/subprocess.py", line 345, in call with Popen(*popenargs, **kwargs) as p: File "/lib/python3.10/subprocess.py", line 966, in __init__ self._execute_child(args, executable, preexec_fn, close_fds, File "/lib/python3.10/subprocess.py", line 1775, in _execute_child self.pid = _posixsubprocess.fork_exec( OSError: [Errno 52] Function not implemented )

**Comment by marimeireles** [comment]
Hi, Coups you please offer more context on what you were trying to achieve? what's the command you were trying to run?

**Comment by marimeireles** [comment]
Closing this as no response was given.
Feel free to re-open it with more info.
Cheers.
