### ISSUE TITLE
Make it really easy to make to control the layout of output like height, width or responsiveness.

### ISSUE THREAD

**Issue by MarcSkovMadsen** [pyscript/pyscript#78]
One of the things that makes applications hard a layouts. A simple thing like achieving *responsiveness* can be hard.

I can see that `pyscript.write` does not provide me anyway to control the layout of the `value`. I would like to have that including options for `responsiveness`.

For example in the below example there should be an easy way for the matplotlib figure to just scale to 100% of its container height and width (the `mpl` element).

```html
<html>
  <head>
    <!-- The link to the pyscript files are to be replaced official files when they are available at a CDN -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/MarcSkovMadsen/awesome-pyscript@master/assets/pyscript/pyscript.css" />
    <script defer src="https://cdn.jsdelivr.net/gh/MarcSkovMadsen/awesome-pyscript@master/assets/pyscript/pyscript.js"></script>
    <py-env>
    - numpy
    - matplotlib
    </py-env>
  </head>
  <body>
    <h1>Let's plot random numbers</h1>
    <div id="plot" style="height:400px;width:100%;background:whitesmoke">...loading</div>
    <!-- output="plot" id="script-id" output-mode="replace" -->
<py-script>
import matplotlib.pyplot as plt
import numpy as np

x = np.random.randn(1000)
y = np.random.randn(1000)

fig, ax = plt.subplots()
ax.scatter(x, y)
pyscript.write('plot', fig)
</py-script>
    </body>
</html>
```

**Comment by marimeireles** [comment]
Is this a feature that we're expecting to develop and offer as a basis for the framework?
I guess so, right? :)
I think this will take a while for us to tackle @MarcSkovMadsen but thank you for opening the issue.

**Comment by pauleveritt** [comment]
It's a good question IMO whether PyScript is an application or a framework. I've kind of felt that PyScript shouldn't ship a CSS file, as it should be a framework for others to make apps with a certain UI. Just my outsider opinion though.

In that direction, it would make sense for PyScript to also ship with at least one killer app, like a HyperCard thingy or something.

**Comment by marimeireles** [comment]
Yeah, we've picked up on this discussion of app vs. framework thanks to your awesome walk through, thanks @pauleveritt!
I think it makes sense to offer some kind of base functionalities for most users (that are optional). I think it makes sense that the core pyscript has no CSS file, but I also see the value of offering a basic framework for users to just play.
Let's see how it develops!
(It'd be so cool to have HyperCard 😄)

**Comment by marimeireles** [comment]
Closing here because we're centralizing the discussion on #340.
