### ISSUE TITLE
how to use open_url with headers?

### ISSUE THREAD

**Issue by zoreu** [pyscript/pyscript#785]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a duplication
- [X] I already searched in Google and didn't find any good information or help

### What is the issue/comment/problem?

how to use open_url with headers?

o know just:
from pyodide.http import open_url
how to use open_url with headers?

**Comment by tedpatrick** [comment]
Per the Pyodide documentation open_url does not support headers, but [pyodide.http.pyfetch](https://pyodide.org/en/stable/usage/api/python-api/http.html?highlight=open_url#pyodide.http.pyfetch) does.

Example:
```html
<html>
<head>
    <link rel="stylesheet" href="https://pyscript.net/unstable/pyscript.css" />
    <script defer src="https://pyscript.net/unstable/pyscript.js"></script>
</head>
<body>
    <py-script>
from pyodide.http import pyfetch
import json

response = await pyfetch('https://dummyjson.com/products', headers={'foo':'bar'} )
products = await response.json()
print( json.dumps(products,indent=4) )
    </py-script>
</body>
</html>
```

**Comment by zoreu** [comment]
but I don't want json output I want web scrap, read() doesn't work

**Comment by tedpatrick** [comment]
`pyfetch` can load anything the browser is allowed to load, It is not limited to JSON.

example loading html
```html
<html>
<head>
    <link rel="stylesheet" href="https://pyscript.net/unstable/pyscript.css" />
    <script defer src="https://pyscript.net/unstable/pyscript.js"></script>
</head>
<body>
    <py-script>
from pyodide.http import pyfetch

response = await pyfetch('https://pyscript.net' )
data = await response.string()
print( data )
    </py-script>
</body>
</html>
```

**Comment by tedpatrick** [comment]
Yes see https://developer.mozilla.org/en-US/docs/Web/API/fetch#parameters

```python
response = await pyfetch('https://dummyjson.com/products', method="POST" )
```

**Comment by zoreu** [comment]
how unblock cors? example: https://google.com

Access to fetch at 'https://google.com/' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by tedpatrick** [comment]
CORS is set and controlled on google's servers and PyScript is limited to the browser's security model (CSP and CORS).
