### ISSUE TITLE
How to add video player with pyscript?

### ISSUE THREAD

**Issue by zoreu** [pyscript/pyscript#786]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a duplication
- [X] I already searched in Google and didn't find any good information or help

### What is the issue/comment/problem?

How to add video player with pyscript?

I'm trying to add player code to a div and I can't.
the player code is this: https://videojs.com/getting-started

**Comment by tedpatrick** [comment]
The [video element ](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video) is fully supported within HTML. To interact with the video element from PyScript, you need to obtain a reference to the element via the id.

Example:
```html
<html>
<head>
    <link rel="stylesheet" href="https://pyscript.net/unstable/pyscript.css" />
    <script defer src="https://pyscript.net/unstable/pyscript.js"></script>
</head>
<body>
    <video id="my_video_id" controls width="250">
        <source src="https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4" type="video/mp4">
    </video>
    <py-script>
my_video = Element("my_video_id")
print(my_video.element.videoWidth)
    </py-script>
</body>
</html>
```
