### ISSUE TITLE
No module named 'utils' on simple_clock.html

### ISSUE THREAD

**Issue by darabos** [pyscript/pyscript#788]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

This is not a duplicate of #641. In that case the issue was reported on a local installation. But this also happens by simply visiting https://pyscript.net/examples/simple_clock.html. It depends on chance. Out of 20 reloads of the page I've got the error 3 times. (Chrome 105.0.5195.125 (Official Build) (arm64) M1 MacBook Air MacOS 12.4)

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/1268018/192113362-005ebc92-9948-4008-b78e-d35795ee3c88.png">

Looking at the Network tab in Dev Tools would be interesting, but I never get the error if I have Dev Tools open during page load. (Whether or not I disable cache.) I must have tried a hundred times. No idea how this is possible. I don't think it's a network issue. Dev Tools shows all but the HTML request as served from cache.

### What browsers are you seeing the problem on? (if applicable)

Chrome

### Console info

```shell
Python exception:
Traceback (most recent call last):
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 429, in eval_code
    .run(globals, locals)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 300, in run
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 3, in <module>
ModuleNotFoundError: No module named 'utils'
```
```


### Additional Context

_No response_

**Comment by tedpatrick** [comment]
The html on [the example](https://pyscript.net/examples/simple_clock.html) is pointed to the `/alpha/` release not `/latest/`. This example now points to `/latest/` within the main branch [here](https://github.com/pyscript/pyscript/blob/main/examples/simple_clock.html#L12) . I have tested this against both `/latest/` and `/unstable/` and it looks to be resolved. Once we release `2022.09.1` next week, this will address the error.

Thanks!
