### ISSUE TITLE
Share a similar vision project: Lively

### ISSUE THREAD

**Issue by wwj718** [pyscript/pyscript#79]
pyscript is an exciting project, I was deeply touched by the vision described in [the article](https://engineering.anaconda.com/):

> create a new way of programming, building, sharing, and deploying applications.

> make programming and the web a friendly and hackable place where anyone can create interesting things and still have fun.

The vision descriptions reminded me of [Lively](https://lively-next.org/)：

>  lively.next is a personal programming kit. It emphasizes liveness, directness and interactivity.

Lively is a project by [Dan Ingalls](https://en.wikipedia.org/wiki/Dan_Ingalls) who is a pioneer of object-oriented computer programming and the principal architect, designer and implementer of five generations of Smalltalk environments.

Smalltalk is also one of the spiritual origins of **Scratch** and they was created by the same group of people.

Since pyscript admires Scratch, it might also be able to learn from [Lively's decade-long exploration](http://hirschfeld.org/writings/media/IngallsFelgentreffHirschfeldKrahnLinckeRoederTaivalsaariMikkonen_2016_AWorldOfActiveObjectsForWorkAndPlayTheFirstTenYearsOfLively_AuthorsVersion.pdf), which is why I'm sharing Lively here.

I know pyscript and Lively are different, pyscript is mostly about Python, but they have a similar spiritual core about supporting the creative spirit of a single individual and providing fun.

Looking forward to the imaginative future of pyscript !

**Comment by fpliger** [comment]
Thank you so much for the kind words and for taking your time to point us to a project that we can learn from. Definitely worth exploring. 

I'll close the issue to keep things clean and since there are no direct actions on the repo but consider the note taken. Thank you!
