### ISSUE TITLE
Logging seems overly verbose in 2022.09.1.RC2

### ISSUE THREAD

**Issue by tedpatrick** [pyscript/pyscript#799]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

Seeing lots of logging within the JS console from PyScript runtime like so:
![image (2)](https://user-images.githubusercontent.com/35942272/192917095-420da3e5-eb36-4736-be4a-3243d5b5726a.png)

### What browsers are you seeing the problem on? (if applicable)

Firefox, Chrome, Safari, Microsoft Edge

### Console info

```shell
Just lots of logging
```

**Comment by antocuni** [comment]
most of those logs are caused by `OutputCtxManager`, which will be removed as soon as we merge https://github.com/pyscript/pyscript/pull/749

**Comment by philippjfr** [comment]
Will the `OutputCtxManager` removal be in 2022.09.1 or is that the next release?

**Comment by marimeireles** [comment]
@philippjfr next release :)

**Comment by madhur-tandon** [comment]
Should we close this now @tedpatrick?

**Comment by tedpatrick** [comment]
Closed by https://github.com/pyscript/pyscript/pull/809
