### ISSUE TITLE
Support for auxclick events

### ISSUE THREAD

**Issue by filyp** [pyscript/pyscript#800]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I'd like to bind python function to "auxclick" events, but to no effect. For "click" event it works fine.

Minimal steps to reproduce:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
</head>
<body>

<py-script>
from js import document 
from pyodide import create_proxy

def run(event):
    print(event)

function_proxy = create_proxy(run)

document.addEventListener("click", function_proxy)
document.addEventListener("auxclick", function_proxy)
</py-script>

</body>
</html>
```

I verified that with JS I'm able to bind auxclick normally.

### What browsers are you seeing the problem on? (if applicable)

Chrome

**Comment by JeffersGlass** [comment]
I'm not seeing the same behavior you're seeing - for example, the following prints "CLICK" when clicking the left mouse button and "AUXCLICK" when clicking other mouse buttons:
```python
<py-script>
  from js import document 
  from pyodide import create_proxy
  
  def click_func(event):
      print("CLICK")
  
  def auxclick_func(event):
      print("AUXCLICK")
        
  document.addEventListener("click", create_proxy(click_func))
  document.addEventListener("auxclick", create_proxy(auxclick_func))
</py-script>
```
This works for me in _alpha_, in _latest_ at time of writing (2022.06.1), and in _unstable_ (as of commit 00ab9a8). This is with Chrome v105 on Windows 10. 

If you try the sample above, what behavior do you see? If it's not what we'd expect, I'd be curious what browser you're using.

**Comment by filyp** [comment]
Ah, turns out it works correctly.

On brave, when I have the console open the auxclicks aren't registered for some reason, but when I close the console it works fine. Also on firefox they are always registered no matter if the console is open.

Sorry, I should have tested it better. Thanks!
