### ISSUE TITLE
 arrow functions in pyscript

### ISSUE THREAD

**Issue by captainwycliffe** [pyscript/pyscript#804]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project area (see the above section)

### What is the idea?

okay.i am a javascript developer and i would really like to implement the use of arrow function in pyscript.Arrow function is one of the features introduced in the ES6 version of JavaScript. It allows you to create functions in a cleaner way compared to regular functions.
This function

// function expression
let x = function(x, y) {
   return x * y;
}
can be written as

// using arrow functions
let x = (x, y) => x * y;
using an arrow function.

### Why is this needed

Arrow functions shine best with anything that requires this to be bound to the context, and not the function itself.

Despite the fact that they are anonymous, I also like using them with methods such as map and reduce, because I think it makes my code more readable. 

### What should happen?

It is worth taking into consideration the variety of syntax we covered earlier. With regular functions, people know what to expect. With arrow functions, it may be hard to decipher what you are looking at straightaway.

**Comment by pauleveritt** [comment]
Out of curiosity, what is it in PyScript that prevents you from using arrow functions in your JS?

**Comment by marimeireles** [comment]
That's a good question! 
But also doesn't work for me locally.
Will investigate for a bit.

**Comment by marimeireles** [comment]
Variables can't be declared in the js side and arrow functions also not working.
Seems like it's a no-fix for pyodide and for now we're pretty dependent on them... https://github.com/pyodide/pyodide/issues/2526
Don't think we'll have a fix any time soon... But Hood offers some work arounds in the linked issue.
If you're interested in tackling this I'd recommend opening an issue upstream.
Thank you for letting us know about it though!

**Comment by captainwycliffe** [comment]
> Variables can't be declared in the js side and arrow functions also not working.
> Seems like it's a no-fix for pyodide and for now we're pretty dependent on them... https://github.com/pyodide/pyodide/issues/2526
> Don't think we'll have a fix any time soon... But Hood offers some work arounds in the linked issue.
> If you're interested in tackling this I'd recommend opening an issue upstream.
> Thank you for letting us know about it though!

Nice..i appreciate it
