### ISSUE TITLE
[!] Error: Cannot find module 'rollup-plugin-svelte'

### ISSUE THREAD

**Issue by imcda** [pyscript/pyscript#81]
node : v17.9.0
npm: 8.5.5

I have installed the rollup-plugin-svelte, why got this error when I run the `npm run dev`

**Comment by verhulstm** [comment]
this might be the same as

https://github.com/pyscript/pyscript/issues/100

**Comment by fpliger** [comment]
@imcda Thank you for reporting. can you please include instructions to reproduce and os/architecture you are running on?
