### ISSUE TITLE
Don't hide undefined elements in the CSS

### ISSUE THREAD

**Issue by antocuni** [pyscript/pyscript#810]
Currently we have this CSS rule:
https://github.com/pyscript/pyscript/blob/8f8b4b1d39c6472a390fae5ae1e4589b2f39a349/pyscriptjs/src/styles/pyscript_base.css#L1-L3

I imagine that its goal is to make sure that the various `<py-*>` tags are not displayed until the various `customElements.define(...)` calls are made.

However, this opens the door to a lot of potential headaches: if an user make a typo and write e.g. `<py-scrpt>` or similar, they will get ignored *and* hidden, so the user will have a very hard time to understand what's happening.

A similar problem might happen with plugins/custom widgets: if an user uses `<py-foo>` but forgets to enable the `foo` plugin, the tag will be silently ignored.

I think that a better solution would be to write explicit `:not(:defined)` clauses for every tag that we want to actively hide.

**Comment by tedpatrick** [comment]
The only PyScript element we need to hide is `<py-config>`, let's simply list the tags that need to be hidden i the css.

<py-script> elements currently generate child elements within <py-script> tag and thus setting it to display:none results in all child DOM elements being hidden from view.
