### ISSUE TITLE
Malformed TOML causes browser hang

### ISSUE THREAD

**Issue by pauleveritt** [pyscript/pyscript#812]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

With the new release and shift to TOML, I'm having some issues if the TOML is malformed. For example:

```html
<html lang="en">
<head>
    <title>Demo</title>
    <link rel="stylesheet" href="https://pyscript.net/latest/pyscript.css"/>
    <script defer src="https://pyscript.net/latest/pyscript.js"></script>
</head>
<body>
<h1>Demo</h1>
<py-config>
[[
</py-config>
</body>
</html>
```

Opening this in Firefox causes the tab to never load, displaying `This page is slowing down Firefox. To speed up your browser, stop this page.` Similar for Chrome and Safari.

The only entry in the console log: `[py-config] config set from inline`

### What browsers are you seeing the problem on? (if applicable)

Firefox, Chrome, Safari

### Console info

```shell
[py-config] config set from inline
```

**Comment by madhur-tandon** [comment]
Seems like the TOML parser doesn't error out and hangs instead. CC: @tedpatrick

**Comment by madhur-tandon** [comment]
Looking in https://github.com/pyscript/pyscript/pull/813, still in discovery phase though

**Comment by tedpatrick** [comment]
Valid. Looks like rollup packaging mangled the errors coming out of TOML lib.
