### ISSUE TITLE
About the hand tracking example

### ISSUE THREAD

**Issue by Sreerag-ibtl** [pyscript/pyscript#82]
Hi, I found that there is a hand tracking example in the repository. But I couldn't find the same when I ran the node server. Wondering if there's any way I can try this. TIA. @fpliger

**Comment by verhulstm** [comment]
hi,

i think the main index,html file in examples does not include a link to the hand track example right now.

you should be able to try out the hand track example by navigating to the hand track file directly in your browser

pyscriptjs/examples/handtrack/say_hello.html

**Comment by mrkito** [comment]
> 



> hi,
> 
> i think the main index.html file in examples does not include a link to the hand track example right now.
> 
> you should be able to try out the hand track example by navigating to the hand track file directly in your browser
> 
> pyscriptjs/examples/handtrack/say_hello.html

if http://localhost:8080/handtrack/say_hello.html
i have
JsException(PythonError: Traceback (most recent call last): File "/lib/python3.10/asyncio/futures.py", line 201, in result raise self._exception File "/lib/python3.10/asyncio/tasks.py", line 232, in __step result = coro.send(None) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 500, in eval_code_async await CodeRunner( File "/lib/python3.10/site-packages/_pyodide/_base.py", line 237, in __init__ self.ast = next(self._gen) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 141, in _parse_and_compile_gen mod = compile(source, filename, mode, flags | ast.PyCF_ONLY_AST) File "", line 10 modelParams = { IndentationError: unexpected indent )

**Comment by fpliger** [comment]
Thanks for opening this. That example was very very rushed and definitely needs some love. We should clean that up, make it more user friendly, improve the UI and add it to the index, with better documentation

**Comment by cclauss** [comment]
I believe that this issue can be closed.

**Comment by fpliger** [comment]
Thanks for the heads up @cclauss . Agreed, should have been fixed with #130 .
