### ISSUE TITLE
<py-config> should NOT go to <head>

### ISSUE THREAD

**Issue by antocuni** [pyscript/pyscript#820]
Custom elements are not allowed in `<head>`. For example, if you run this in [w3c validator](https://validator.w3.org/nu/#textarea) it passes:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Hello</title>
  </head>
  <body>
    <py-config></py-config>
  </body>
</html>
```

But this fails:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Hello</title>
    <py-config></py-config>
  </head>
  <body>
  </body>
</html>
```
![image](https://user-images.githubusercontent.com/344507/193830417-cb6dc0a3-aaba-4574-8300-7f1fea23a682.png)

We should:
1. Fix all our examples, e.g.:
https://github.com/pyscript/pyscript/blob/c75f885cb4661b25cd37fa52c7cf20dbffaf307b/examples/simple_clock.html#L3-L18

2. Fix the docs: https://github.com/pyscript/pyscript/blob/c75f885cb4661b25cd37fa52c7cf20dbffaf307b/docs/tutorials/getting-started.md#L150

**Comment by JeffersGlass** [comment]
I wonder if this is a normative issue with the validator, or an actual violation of [the spec](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements). I can't see anything in the spec that forbids the use of custom elements in `<head>`, but I confess this isn't my area of expertise. Maybe @tedpatrick can shed some light?
