### ISSUE TITLE
New PyScript Maintainer: Paul Everitt

### ISSUE THREAD

**Issue by tedpatrick** [pyscript/pyscript#824]
We are pleased to announce the addition of [Paul Everitt](https://github.com/pauleveritt) as a PyScript Maintainer. Paul has been very influential within the [PyScript Collective](https://github.com/pyscript/pyscript-collective). He brings much Web knowledge to the team's architecture discussions, and his proposed architectures are inspirational and pythonic. His work on PyScript extends a long history of contribution to the Web, Python, and Open Source Software. His leadership will bring great value to PyScript.

On behalf of the entire PyScript Team, Paul, Thank you!

![avatar](https://user-images.githubusercontent.com/35942272/193841957-a8ef1786-16c8-452a-9617-5abab0bb1985.jpg)

**Comment by antocuni** [comment]
welcome to the team @pauleveritt ! And thanks for all your contributions so far! 🎉

**Comment by tedpatrick** [comment]
Paul, I truly enjoy our conversations and hope we can enable your vision on PyScript. Thank you. Onward! 🚀

**Comment by marimeireles** [comment]
Welcome! 😄

**Comment by pzwang** [comment]
Thank you, Paul! And welcome!

**Comment by ntoll** [comment]
Welcome @pauleveritt, looking forward to collaborating.

**Comment by madhur-tandon** [comment]
Welcome @pauleveritt :)

**Comment by ayirpconda** [comment]
Welcome @pauleveritt !!!

**Comment by JeffersGlass** [comment]
Excited to work with you @pauleveritt!

**Comment by fpliger** [comment]
Welcome @pauleveritt ! Really excited... and thank you for all the contributions!! 🎉 🎉
