### ISSUE TITLE
New PyScript Maintainer: Jeff Glass

### ISSUE THREAD

**Issue by tedpatrick** [pyscript/pyscript#825]
We are pleased to announce the addition of [Jeff Glass](https://github.com/JeffersGlass) as a PyScript Maintainer. Jeff has been very active within the PyScript community ([PyScript Discord](https://discord.gg/xrWa4wdd)). Jeff recently published an excellent summary of the [PyScript 2022.09.1 release](https://jeff.glass/post/whats-new-pyscript-2022-09-1/) and his work on [Rich with PyScript](https://jeff.glass/project/richdemo/) is worth recognition. He has provided several significant contributions to the core of PyScript, and his involvement in architectural decisions has been excellent.

On behalf of the entire PyScript Team, Jeff, Thank you!

![avatar](https://user-images.githubusercontent.com/35942272/193841957-a8ef1786-16c8-452a-9617-5abab0bb1985.jpg)

**Comment by antocuni** [comment]
welcome to the team @JeffersGlass! I look forward to work more with you 🎉

**Comment by tedpatrick** [comment]
Jeff, Thank you. Onward! 🚀

**Comment by JeffersGlass** [comment]
Thanks @tedpatrick, @antocuni et al! Looking forward to working more with everyone.

**Comment by marimeireles** [comment]
Yesss! Welcome @JeffersGlass!

**Comment by pzwang** [comment]
Congrats and welcome, Jeff!

**Comment by ntoll** [comment]
:wave: @JeffersGlass

**Comment by madhur-tandon** [comment]
Welcome @JeffersGlass :)

**Comment by fpliger** [comment]
Welcome @JeffersGlass  ! Really excited... and thank you for all the contributions!! 🎉 🎉
