### ISSUE TITLE
pre-commit CI is failing

### ISSUE THREAD

**Issue by JeffersGlass** [pyscript/pyscript#834]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

Starting with commit c75f885c, the pre-commit CI check is failing for all commits and PRs. Neither `eslint` nor `tsc` seem to show those errors when building locally, for either me nor @antocuni (as of a few days ago).

**Comment by tedpatrick** [comment]
ESLINT       ==> Strict
TypeScript ==> Not Strict

This is the source of the ESLint warnings. In strict, Typescript shows 200+ warnings. Once things settle a bit, we will address in a PR.

**Comment by JeffersGlass** [comment]
I think there must be something about how the pre-commit CI action works that I don't understand. eslint warnings shouldn't fail the build step - we've had a few hundred warnings for months and months, symptom of a rapidly evolving codebase.. Now it seems like in GitHub CI it's actually _erroring out_...

But running  `pre-commit run --all-files` locally has lots of _warnings_ locally, but no errors. Isn't the CI pipeline using the same hooks that would get executing with `pre-commit run`? There must be something I'm missing.

**Comment by madhur-tandon** [comment]
Is it possible to SSH into the runners to investigate? It could be done with circleCI, but I am not sure with Github Actions.

**Comment by tedpatrick** [comment]
I do not think anything is wrong with CICD or ESLint, this is highlighting that we lack TypeScript types in many areas. If we fix this root cause, everything improves.

**Comment by antocuni** [comment]
For reference, I reported it upstream:
https://github.com/pre-commit/pre-commit/issues/2537

The author seems to think that it's a problem of my local environment, although I don't think it's the case. Do you confirm that `pre-commit run --all-files` passes on all your machines?

I still think it's a bug of pre-commit: if it passes locally, it should passes on CI. It it fails on CI, it should fail locally.

> This is the source of the ESLint warnings.

yes, but this is only part of the problem. ESLint used to pass and then it started to fail suddenly out of the blue
