### ISSUE TITLE
PyScript Community Call - October 18, 2022 11AM CST

### ISSUE THREAD

**Issue by tedpatrick** [pyscript/pyscript#836]
On October 18, 2022, at 11 AM CST, the PyScript Core Team will host our 1st PyScript Community Call.

<img src="https://user-images.githubusercontent.com/35942272/194639665-a9279824-bfab-4a14-9c05-f499a9d4447e.svg" width="200">

## PyScript Community Call
- Status Report
- Highlights
- Q&A

We will be organizing the Q&A from questions posted to this issue, please ask questions in advance below.

Meeting Details:
Date: October 18, 2022, at 11 AM CST (1 hour)
URL: https://anaconda.zoom.us/j/92425103164?pwd=M0FFY0FJZ21EK1V5NUc2RDkwVFhhZz09

**Comment by marimeireles** [comment]
We should also post it on:
- twitter
- anaconda nucleos
- discord channel 
:)

**Comment by tedpatrick** [comment]
Community Call Meeting Details:
Date: October 18, 2022, at 11 AM CST (1 hour)
URL: https://anaconda.zoom.us/j/92425103164?pwd=M0FFY0FJZ21EK1V5NUc2RDkwVFhhZz09

**Comment by marimeireles** [comment]
Created a post on the nucleos. 👍
Can you or someone post it on the discord? :)

**Comment by marimeireles** [comment]
Passcode: 785650
