### ISSUE TITLE
<py-button> needs reference docs

### ISSUE THREAD

**Issue by kathatherine** [pyscript/pyscript#848]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a duplication
- [X] I already searched in Google and didn't find any good information or help

### What is the issue/comment/problem?

The `<py-button>` tag needs a reference doc that explains what the tag is for and any attributes related to it.

The doc file should be at `source/reference/py-button.md` and referenced in `source/reference/index.md`.

**Comment by marimeireles** [comment]
Hey @kathatherine 
About all these issues you opened do you need support from our side or do you have everything you need?
I talked to someone that pointed me to [how to contribute to tech writers](https://anaconda.atlassian.net/wiki/spaces/DOCS/pages/2463170577/Tech+Writing+Guide+for+Engineers). I'll be happy to assist here.
Cheers.

**Comment by kathatherine** [comment]
Yes, some support would be great! Ted asked that these issues be created so we could have better references for each of the PyScript tags. We also figured that if these issues were put out there, maybe a community member might pick it up, but if not, Idan or I will need to find some time.

What would be really good for these reference docs is text on "this is what X tag does", "these are all the attributes that are required or optional for this tag", and probably an example of the tag in use.

**Comment by tedpatrick** [comment]
Closing this issue as <py-button> has high odds of depreciation
