### ISSUE TITLE
Should we really use Codespell?

### ISSUE THREAD

**Issue by marimeireles** [pyscript/pyscript#855]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a duplication
- [X] I already searched in Google and didn't find any good information or help

### What is the issue/comment/problem?

I've just ran into an annoying issue in codespell where it didn't allow me to write the test the way I'd like to because I mistyped the function call (behavior that was expected on the test scenario).
I had to change my code for it to pass.

Codespell doesn't allow you to deactivate it only for one line of code, only for the whole file. (See https://github.com/codespell-project/codespell/issues/1212)

I personally don't like that and wonder if we need all these linters?
We run a lot of them!

Thanks.

**Comment by dopplershift** [comment]
You probably want to look at the `-x` or `--exclude-file` [option for codespell](https://github.com/codespell-project/codespell#usage), which lets you list a matching line not to check.

**Comment by marimeireles** [comment]
@dopplershift thanks for chiming in!
Yeah, but that's my exact problem with it, I don't want to exclude the whole file, I want to exclude this one line.
And my other point is I'm not sure if we need all these formatters. Codespell is probably useful for us as many of us don't have english as first language... But sometimes it does silly mistakes that we can't surpass with "ignore one line" kind of stuff.

**Comment by dopplershift** [comment]
Right, so if you read the docs I linked to, the `--exclude-file` option doesn't exclude a specific file, it allows you to give a file of *individual lines* to exclude. It sounds exactly like what you're looking for. You can see the [file](https://github.com/Unidata/MetPy/blob/main/.codespellignore) we use on my MetPy project, as well as the [config](https://github.com/Unidata/MetPy/blob/7fbe39f9faa1e6b54a56ea413cc1312644859829/setup.cfg#L136-L138).

**Comment by marimeireles** [comment]
Ahhhn, sorry for that!
I didn't click the link.
Thank you @dopplershift :-)

**Comment by marimeireles** [comment]
Okay that's cool. So I'm gonna close this one since this is fine =)
Thank you for the patience to explain.
