### ISSUE TITLE
Runtimes must be specified after packages and paths

### ISSUE THREAD

**Issue by rjschave** [pyscript/pyscript#859]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a duplication
- [X] I already searched in Google and didn't find any good information or help

### What is the issue/comment/problem?

When specifying a runtime in `<py-config>`, it must be specified after packages and paths.  If it is specified before, the packages and paths will not be loaded.  I don't see this mentioned in the documentation.

<img width="588" alt="PyScript - Runtime specified first - code" src="https://user-images.githubusercontent.com/11916949/196211590-b4ac18a1-b901-4314-bb0c-db0e19b45928.png">

<img width="1387" alt="PyScript - Runtime specified first - console" src="https://user-images.githubusercontent.com/11916949/196212147-e38ab0b2-45e4-419c-a9e8-95b2afeded53.png">

vs

<img width="584" alt="PyScript - Runtime specified last - code" src="https://user-images.githubusercontent.com/11916949/196212432-9f0799c2-9855-4331-937f-2e0a727556e5.png">

<img width="1346" alt="PyScript - Runtime specified last - console" src="https://user-images.githubusercontent.com/11916949/196212448-f7267b0e-a74c-4e6f-af28-a7db5277346e.png">

**Comment by JeffersGlass** [comment]
I believe this is not so much a bug in PyScript but a [behavior of TOML Tables](https://toml.io/en/v1.0.0#array-of-tables). Table (and arrays of tables that use the double-brackets syntax) extend their definition to the End of File or until the next header defining another array or table. So the following are equivalent TOML and JSON:

```TOML
[[runtimes]]
name = "pyodide"

paths = "file.py"
packages = "numpy"
```
```json
{
  "runtimes": [
    {
      "name": "pyodide",
      "packages": "numpy",
      "paths": "file.py"
    }
  ]
}
```

Whereas we require the following data structure (followed by JSON equivalent, for clarity):
```TOML
paths = "file.py"
packages = "numpy"

[[runtimes]]
name = "pyodide"

```
```json
{
  "packages": "numpy",
  "paths": "file.py",
  "runtimes": [
    {
      "name": "pyodide"
    }
  ]
}
```
That said, it's a stumbling point, and I could surely see it being a helpful note in the docs.

**Comment by rjschave** [comment]
I could have been more clear - I didn't think this was a bug so much as unspecified/unexpected behavior (at least to me).  

My approach was to specify the runtime before specifying the packages and paths I wanted that runtime to load.  When that didn't work, I swapped the order on a whim and it worked.  I wasn't able to reason about this behavior.  I'm unfamiliar with TOML tables so I appreciate your explanation.

I chose the TOML format simply because it was the 1st format used in the docs.  There are no examples that combine runtimes with packages or paths, so the order was not clear.

I confirmed the order doesn't matter when using the JSON format.

Updating the docs could help someone in the future.

Thank you.

**Comment by JeffersGlass** [comment]
Thanks @rjschave! I didn't mean to sound critical - you're totally right that it's nonintuitive, and we could be more helpful about that in the docs. Thanks for pointing it out!

**Comment by tedpatrick** [comment]
+1 for adding this to docs

**Comment by tedpatrick** [comment]
Need 1 approval here: https://github.com/pyscript/pyscript/pull/861
