### ISSUE TITLE
Files missing from fresh installation

### ISSUE THREAD

**Issue by jusce17** [pyscript/pyscript#86]
Following the instructions showing on the website, I download the ziped file and unzip, only to found that that the following files are missing:

- pyscript.css
- pyscript.js

**Comment by verhulstm** [comment]
hi

thanks for your interest :)

yes we are working to create more and better documentation

take a look at this

https://community.anaconda.cloud/t/introducing-pyscript-py/20190/6


i think you might have downloaded the zip. next, you have to build from source with nodejs.
use nvm to install nodejs, then run “nvm install 16; nvm use 16”
cd into the dir with the “package.json” file and run “npm install”
then run “npm run dev”

**Comment by verhulstm** [comment]
then you should find a new "build" dir in "examples"

**Comment by fpliger** [comment]
This should be fixed since `/examples` have been moved to the root of the repo
