### ISSUE TITLE
py-repl creating duplicate ids

### ISSUE THREAD

**Issue by tedpatrick** [pyscript/pyscript#864]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

Within generated DOM elements, the py-repl element creates duplicate ids.

Note: my-repl-2 is denoted 2 times
<img width="597" alt="Screen Shot 2022-10-18 at 5 51 11 AM" src="https://user-images.githubusercontent.com/35942272/196411247-4eafdec3-795d-4876-8448-c45e1a962d6f.png">

This is causing this test to fail:
pytest tests/integration/test_zz_examples.py::TestExamples::test_repl

### What browsers are you seeing the problem on? (if applicable)

Firefox, Chrome, Safari, Microsoft Edge

**Comment by marimeireles** [comment]
On it :)

**Comment by marimeireles** [comment]
The bug isn't there. It was in the way we write elements, was hard to find because I didn't introduce it 😅
But yeah, let's discuss on the PR :)

**Comment by marimeireles** [comment]
This was fixed by Antonio's PR actually, before I landed mine!
Fixing a different bug, that also happened to fix this behavior.
As an extra step to remove all of these nested ids I have https://github.com/pyscript/pyscript/pull/912 on the way.
