### ISSUE TITLE
Panel example is broken

### ISSUE THREAD

**Issue by meshachjackson** [pyscript/pyscript#867]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

When viewing the Panel demo from the Examples page, the page loads the following error.

`/lib/python3.10/site-packages/pyodide/__init__.py:74: FutureWarning: pyodide.create_proxy has been moved to pyodide.ffi.create_proxy Accessing it through the pyodide module is deprecated. warn(
/lib/python3.10/site-packages/pyodide/__init__.py:74: FutureWarning: pyodide.to_js has been moved to pyodide.ffi.to_js Accessing it through the pyodide module is deprecated. warn(`

<img width="955" alt="Screen Shot 2022-10-18 at 9 16 59 AM" src="https://user-images.githubusercontent.com/624763/196456286-5e1be4cf-931a-4418-8865-21bb7d32725c.png">

### What browsers are you seeing the problem on? (if applicable)

Chrome

**Comment by marimeireles** [comment]
This is due to PyScript not being equal to the main. 
This issue was fixed and will be release on the next version. But I'd argue this is not good.
@tedpatrick was talking about releasing a new version, should we? :)

**Comment by meshachjackson** [comment]
Thanks for the quick reply, @marimeireles 

Is there a known workaround in the meantime?

**Comment by marimeireles** [comment]
Hey @meshachjackson np, happy to help.
Depends on what you're doing, if you're running it locally you can build pyscript locally on your machine and link to it:
```
    <link rel="stylesheet" href="../build/pyscript.css" />

    <script defer src="../build/pyscript.js"></script>
```

**Comment by marimeireles** [comment]
Closing because fixed and just waiting for next version release.
+ workaround is posted above =)
by the end of october next version should come!
