### ISSUE TITLE
pyscript.net landing page does not lead to other useful content

### ISSUE THREAD

**Issue by mwaskom** [pyscript/pyscript#872]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

*This is a pure documentation issue but I didn't see a separate category for that.*

The [pyscript.net](https://pyscript.net) landing page does not lead to other useful content.

First, the "Project home" link at the bottom of the page goes to https://github.com/anaconda/pyscript, which 404s. I had to guess that the repo was moved into a `pyscript` organization.

Second, while poking around for the source to that page so that I could submit a simple fix, I discovered that there is an entire https://docs.pyscript.net subdomain. Unless I'm totally missing something (possible; it's early here), the landing page does not link to the docs. There is just https://pyscript.net/examples/, which seems to be separate. (And also not that intuitive; is the idea that you're supposed to do *View source* in a browser to see how the examples are created? I got there eventually, but there weren't any affordances on the page that led me to it.)

### What browsers are you seeing the problem on? (if applicable)

Safari

**Comment by pauleveritt** [comment]
It would also be nice to link to the Awesome PyScript page: https://github.com/pyscript/pyscript-collective/blob/main/awesome-pyscript.md

**Comment by FabioRosado** [comment]
Perhaps we can close this issue, we have pyscript.net that links to the examples, documentation and tells you how to install pyscript. It also has a quick section explaining what is pyscript.

Yesterday I opened up https://github.com/pyscript/pyscript.net/pull/36 that will add a link to the awesome list  😄 

Please let me know if you think we should do something else or if we can improve the page even further (also feel free to reopen if needed 😄 )
