### ISSUE TITLE
I can't seem to get PyScript to load.

### ISSUE THREAD

**Issue by piotr25691** [pyscript/pyscript#89]
This is the error:
```js
Uncaught (in promise) ReferenceError: WebAssembly is not defined
    at abort (pyodide.asm.js:14:193482)
    at pyodide.asm.js:14:182734
    at pyodide.ts:285:9
    at Generator.next (<anonymous>)
    at fulfilled (tslib.es6.js:73:58)
 ```
 
 I need help to get it to work.

**Comment by SNDST00M** [comment]
Could you give browser name and version?
Sillier question - can you open your dev tools console and check that WebAssembly is defined?

**Comment by piotr25691** [comment]
> Could you give browser name and version? Sillier question - can you open your dev tools console and check that WebAssembly is defined?

I am using Microsoft Edge 100 with it, and I don't know if WebAssembly even exists on it.

**Comment by piotr25691** [comment]
Also seems like the "Enhance your privacy" or whatever feature was preventing WebAssembly from being defined.
I have fixed the issue.
