### ISSUE TITLE
Deprecate <py-title> <py-inputbox> <py-button> <py-box>

### ISSUE THREAD

**Issue by tedpatrick** [pyscript/pyscript#897]
Within the next release, we plan to deprecate the following custom elements:

`<py-title>`
`<py-inputbox>`
`<py-button>`
`<py-box>`

These elements will be removed in a release following.

Currently we are looking to see if these make sense as PyScript plugins that can be optional added within `<py-config>`

**Comment by tedpatrick** [comment]
Fixes #854

**Comment by FabioRosado** [comment]
As part of this effort we also should update all the examples to stop using these elements and use the 'new' style 

This might be a silly question, but I'm curious about the deprecation cycle, should we create a visual warning if someone is using one of these elements and telling users to use  `<button py-click="foo()">Click Me</button>` instead? I'm guessing just using a console warning might not be best since its easy to miss when things seem to work 🤔

**Comment by tedpatrick** [comment]
Deprecation Cycle Plan
1. Remove all example use of deprecated items
2. Add warnings to all elements marked for deprecation. (See py-env)
3. Release with deprecated items
4. Release + 1 - deprecated items removed

**Comment by tedpatrick** [comment]
We need to write the Deprecation Cycle down somewhere in permanent ink.

**Comment by antocuni** [comment]
> This might be a silly question, but I'm curious about the deprecation cycle, should we create a visual warning if someone is using one of these elements and telling users to use `<button py-click="foo()">Click Me</button>` instead? I'm guessing just using a console warning might not be best since its easy to miss when things seem to work thinking

yes! This is something which I have been desiring since a while: a `showWarning` utility function which by default shows a big yellow warning in the page, but it's also customizable so that you can hide it and/or silence specific warnings.

**Comment by JeffersGlass** [comment]
@antocuni there's always the venerable [showError()](https://github.com/pyscript/pyscript/blob/95430193364b533e353c24a1cdcf5e0ee186b78c/pyscriptjs/src/utils.ts#L47-L57) - I would also love to see it become customizable/hideable, that's a great area for improvement.

**Comment by FabioRosado** [comment]
I'll hack something to show an alert on the page, I'm thinking maybe an alert banner that can be closed? Will toy around with the idea and open a draft PR with a proposal.

This might be a bit out of scope of this issue, but should we add dev-related documentation to our main docs? So we could have a page about the deprecation cycle and maybe a few other things that could be useful? 🤔

**Comment by JeffersGlass** [comment]
+1 to dev docs idea!

**Comment by antocuni** [comment]
> @antocuni there's always the venerable [showError()](https://github.com/pyscript/pyscript/blob/95430193364b533e353c24a1cdcf5e0ee186b78c/pyscriptjs/src/utils.ts#L47-L57) - I would also love to see it become customizable/hideable, that's a great area for improvement.

Yes, basically the `showWarning` that I have in mind would be very similar to the current `showError`.
For example, here we are using it both as an error (first case, the execution stops) and as a warning (second case, the execution continue):
https://github.com/pyscript/pyscript/blob/214e39537bf18e1bec65153fdaa2fce355999693/pyscriptjs/src/main.ts#L98-L107

In my next refactoring, I plan to tackle the way we deal with errors; I would like to be able to use JS exceptions to express "I would like to stop the execution here but also show a nice error message to the user". So for example the code above could be something like this:
```typescript
        logger.info('Initializing runtime');
        if (this.config.runtimes.length == 0)
            throw new UserError("config.runtimes is empty");

        if (this.config.runtimes.length > 1) {
            showWarning("Multiple runtimes are not supported yet. " +
                      "Only the first will be used");
        }
```

and then of course we need to structure code in a way that `UserError` is caught and handled appropriately, of couse.
