### ISSUE TITLE
New PyScript Maintainer: Fabio Rosado

### ISSUE THREAD

**Issue by tedpatrick** [pyscript/pyscript#898]
We are pleased to announce the addition of [Fabio Rosado](https://github.com/FabioRosado) as a PyScript Maintainer. Fabio has been active within the PyScript community and has contributed several significant additions to PyScript. His PRs adding TypeScript types to the PyScript codebase have been great.

On behalf of the entire PyScript Team, Fabio, Thank you!

![193841957-a8ef1786-16c8-452a-9617-5abab0bb1985](https://user-images.githubusercontent.com/35942272/198676152-9df344bf-8038-4819-be03-faf7ded6f1dc.jpg)

@FabioRosado

**Comment by tedpatrick** [comment]
Welcome, Fabio!

**Comment by ntoll** [comment]
Welcome @FabioRosado 🎉

**Comment by FabioRosado** [comment]
Thank you everyone! Looking forward to keeping contributing to ALL the things! 😄

**Comment by JeffersGlass** [comment]
Welcome Fabio! 🥳

**Comment by marimeireles** [comment]
Yip yip!

**Comment by antocuni** [comment]
Welcome 🎉

**Comment by madhur-tandon** [comment]
Welcome Fabio 🎈

**Comment by fpliger** [comment]
Welcome @FabioRosado !! 

![Alt Text](https://media.giphy.com/media/l36kU80xPf0ojG0Erg/giphy-downsized.gif)

**Comment by marimeireles** [comment]
Closing this one!
Welcome again Fabio! :)
