### ISSUE TITLE
Add option to allow disabling splash screen in py-config

### ISSUE THREAD

**Issue by lwcorp** [pyscript/pyscript#900]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project area (see the above section)

### What is the idea?

#279 added a splash screen every time someone enters a webpage with PyScript.
How about adding a way not to use it via `<py-config>`?

![image](https://user-images.githubusercontent.com/1773306/198738927-af10115a-b371-4371-92e0-1975d0b3f998.png)

### Why is this needed

Some pages only call PyScript after filling a html form, etc. so it is be assumed PyScript will finish loading by the time the user fills the form.

### What should happen?

Allow not to use the splash screen by adding a setting in `<py-config>`.

**Comment by marimeireles** [comment]
This makes sense to me.
I believe making this optional shouldn't be terribly complicated, specially if one looks into the linked PR.
If you or anyone wants to tackle this and needs help, please ping me either on the issue or on our [discord channel](https://discord.gg/yTErrw93)!

**Comment by albertas** [comment]
It would be great if there was a way to define a callback, which is called when py-script finishes loading. It would be possible to enable form button or perform similar action, when the py-script is ready. I think `py-config` tag would also be a suitable place to set the callback.

**Comment by JeffersGlass** [comment]
@albertas As of PyScript 2022.12.1, you can do this with a Plugin - see the new [Guide to Custom Plugins](https://docs.pyscript.net/unstable/guides/custom-plugins.html) that was recently added to the docs.

Fair warning - that document references using either JavaScript or Python to write plugins. Version 2022.12.1 (the latest stable release at the moment) _only_ allows for including Python plugins, while JS plugins will be included in the next stable release.

**Comment by albertas** [comment]
> you can do this with a Plugin

It came to me that it can be done using any py-script code, since it will work only when py-script is ready :smiley: Its not necessary to use a Plugin.

**Comment by albertas** [comment]
If I am not mistaken, the splash screen can be removed by simply adding `<div id="loading-indicator"></div>` to the html body. It is empty and it is used instead of the default splash screen with a spinner. I took this idea from this example: https://github.com/pyscript/pyscript/issues/80#issuecomment-1114131102

**Comment by marimeireles** [comment]
It seems like this issue can be closed?

**Comment by albertas** [comment]
I still think, that having `py-config` option for the splash screen would be a good option. It was the first place I searched, when I needed this functionality.
