### ISSUE TITLE
[Tracking issue] Improve usability and provide better diagnostics for common mistakes

### ISSUE THREAD

**Issue by antocuni** [pyscript/pyscript#904]
Sometimes I see PyScript users asking for help because they encounter an unexpected error or because their intuition about PyScript behavior was wrong.
I think we should learn from these requests and use them as a way to improve the general usability and user-friendliness: 
  - sometimes the solution might be to intercept the original error and provide an explanation and/or a link to a possible solution
  - sometimes the solution might be to change the defaults and/or the API to remove the source of confusion
  - sometimes the solution might not exists, but it still useful to know about common problems.

I encourage other maintainers and contributors which encounter "common mistakes" to open a corresponding issue and add a link to it here.

---
### List of issues
- #905
- #906
- #911

**Comment by antocuni** [comment]
@JeffersGlass I have a feeling that you probably have more anecdotes to add to this list :)

**Comment by WebReflection** [comment]
all the linked issue has been resolved ... for the sake of keeping new issues related to current state I think I can close this and, if there's any specific issue still relevant to current PyScript state, let's have a single issue per each of them, thanks!
