### ISSUE TITLE
[User-friendliness] Event handler without the `event` parameter

### ISSUE THREAD

**Issue by antocuni** [pyscript/pyscript#905]
See the Tracking issue #904 for the context.

[Original question on discord](https://discord.com/channels/972017612454232116/972020206538997822/1035751331534753913)

The mistake it this:
```python
async def fetch_data():
    ...
document.getElementById('btn-test').addEventListener('click', create_proxy(fetch_data))
```

The error is this:
```
Uncaught PythonError: TypeError: fetch_data() takes 0 positional arguments but 1 was given
```

One related issue/discussion is #835 .
This could be solved by providing, documenting and encouraging the use of a higher level API. For example:
```python
@event('btn-test', 'click')
async def fetch_data():
    ...
```
In this case, the decorator would automatically call `create_proxy` and `addEventListener`, but most importantly it could also introspect the function signature and raise an user friendly error in case the actual signature doesn't match the expected one.

**Comment by Cheukting** [comment]
I like this suggestion. The original syntax is very JS-like (as it supposes to be) and for people who are not familiar with JS, this is an easy mistake to make. With the decorator, it can help to make it easier for beginners.

**Comment by tedpatrick** [comment]
+1 The @event decorator can also detect arguments support and optionally not pass the event.

**Comment by marimeireles** [comment]
This is being under dev [here](https://github.com/pyscript/pyscript/pulls)

**Comment by JeffersGlass** [comment]
After some discussion, this morphed into the `@when` decorator which was added in #1428 .
