### ISSUE TITLE
[User-friendliness] It's not clear that <py-config> does NOT contain python code

### ISSUE THREAD

**Issue by antocuni** [pyscript/pyscript#906]
See the Tracking issue https://github.com/pyscript/pyscript/issues/904 for the context.

[Original discord question](https://discord.com/channels/972017612454232116/972020206538997822/1031194328086876190)

This user thought that the content of `<py-config>` is Python code.
And to be honest, I think it's a "reasonable" mistake to do. For example, consider the very simple example:

```html
<py-config>
packages = ['numpy', 'panel']
</py-config>
```

That code *is* valid python code.
Maybe a possible solution is to always use a named section, which would make it visually clear that it's not python code:

```html
<py-config>
[pyscript]
packages = ['numpy', 'panel']
</py-config>
```

(the exact name of the `pyscript` section can be discussed, of course).

Any thought?

**Comment by Cheukting** [comment]
I feel indifferent to this one. The documentation clearly states that py-config uses TMOL by default. So either way, I feel it's ok.

**Comment by antocuni** [comment]
> I feel indifferent to this one. The documentation clearly states that py-config uses TMOL by default. So either way, I feel it's ok.

I think you are missing my point.
My point is that if we can find a way to make it clear(er) *without* requiring to read the docs, it helps.
