### ISSUE TITLE
No requests?

### ISSUE THREAD

**Issue by MaLin1997** [pyscript/pyscript#91]
<img width="578" alt="image" src="https://user-images.githubusercontent.com/31839662/166149833-67703d5f-2457-4de4-9fac-3d2998b48a41.png">

**Comment by philippjfr** [comment]
Correct, pyodide does not yet support requests or in fact urllib3 because the entire networking stack does not translate to a browser environment very well. This is something we are looking at but you can also track similar issues on the pyodide repo: https://github.com/pyodide/pyodide/issues/398

**Comment by amitsaha** [comment]
@MaLin1997 You may find my blog post helpful: https://echorand.me/posts/py-script-monkey-patch-requests/ - essentially monkey patch `requests` to use the Pyiodide functionality that's available. It's only useful for GET requests though.

**Comment by marimeireles** [comment]
No requests yet. We will be tackling this in the future. But we have awesome documentation thanks to @emirkmo!
So, I'm closing this for now but we have this in mind.
Thank you for the issue.

**Comment by marimeireles** [comment]
Forgot to add the links to the docs: https://docs.pyscript.net/latest/howtos/http-requests.html

**Comment by FabioRosado** [comment]
> Link now gies 404 @marimeireles. I suppose this is the one now https://docs.pyscript.net/latest/guides/http-requests.html

Hello @andeplane the docs suffered from a big update since this issue was closed. This is the correct link: https://docs.pyscript.net/latest/guides/http-requests.html

Please let us know if this helps

**Comment by pquentin** [comment]
urllib3 2.2.0 supports Pyodide: https://urllib3.readthedocs.io/en/stable/reference/contrib/emscripten.html. Which means requests supports it too.
