### ISSUE TITLE
[IUser-friendliness] Provide Context/Help around Unusable Pacakges

### ISSUE THREAD

**Issue by JeffersGlass** [pyscript/pyscript#911]
See the Tracking issue https://github.com/pyscript/pyscript/issues/904 for the context.

Currently, if a user provides a package name to `<py-config>` that either doesn't exist on PyPI, or doesn't have a pure-Python wheel, the on-screen loader never closes, nor does it show any on-screen error. Though the error is shown in the console, it is not the most understandable if you don't know to look for the `micropip.install(...)` error:

![image](https://user-images.githubusercontent.com/1931111/199010371-c4002a82-d8fe-4bcb-a02c-530b3ad33cac.png)

We have an opportunity, I think, to be better about showing the user: (1) What part of the PyScript process failed (loading a package), (2) which package caused it and (3) why.

**Comment by Cheukting** [comment]
I agree, it takes some experience to know how long the wheel should be spinning and when something doesn't look right and should check the console. If the error can be more obvious it would be great.
