### ISSUE TITLE
PyScript 2022.09.01 has stronger opinions about InvalidVersions in Python wheels

### ISSUE THREAD

**Issue by ross-spencer** [pyscript/pyscript#916]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

2022.09.01 now complains about a version number I was using in a `whl` file that is descriptive for me (and users) of the wheel's status, but it now isn't accepted by Pyscript - the version `2.0.0rc3_demystify_lite` raises:

```
Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 548, in install
    await transaction.gather_requirements(requirements)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 305, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 315, in add_requirement
    wheel = WheelInfo.from_url(req)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 75, in from_url
    name, version, build, tags = parse_wheel_filename(file_name)
  File "/lib/python3.10/site-packages/packaging/utils.py", line 102, in parse_wheel_filename
    version = Version(parts[1])
  File "/lib/python3.10/site-packages/packaging/version.py", line 266, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '2.0.0rc3_demystify_lite'
```

In this case the `whl` is a binary loaded from disk as I haven't published `pyscript` specific changes to pypi for this code yet as I understand what's needed as pyscript evolves. 

Maybe others are in the same boat? - Is there guidance on what a valid version number is expected to be?

### What browsers are you seeing the problem on? (if applicable)

Chrome

**Comment by prettybits** [comment]
> Is there guidance on what a valid version number is expected to be?

At least since the `micropip` changes in `pyodide >= 0.21.0` which Pyscript  now uses versions are properly parsed by Python's `packaging` module which expects them to fully adhere to PEP 440, in this case specifically to the rules for [Local version identifiers](https://peps.python.org/pep-0440/#local-version-identifiers). A valid version identifier for what you intended would be `2.0.0rc3+demystify.lite`, although testing locally with Python 3.10.8 `2.0.0rc3+demystify_lite` is also accepted counter to the specification which only allows ASCII letters & digits and periods - the underscore is interpreted as a period.

So in my view there is nothing Pyscript needs to change in this regard.

**Comment by antocuni** [comment]
I think that @prettybits nailed it: this is probably due to an upstream change in pyodide/micropip and it's not something that we can fix on our side.
I'm going to close it as "invalid" but feel free to reopen in case I understood it wrongly and you think it's still a PyScript bug.
