### ISSUE TITLE
Documentation contains references to py-env tag

### ISSUE THREAD

**Issue by mdlattimore** [pyscript/pyscript#921]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a duplication
- [X] I already searched in Google and didn't find any good information or help

### What is the issue/comment/problem?

The guide "How to make HTTP requests using `PyScript` , in pure Python" contains references to the `py-env` tag. See (https://github.com/pyscript/pyscript/blob/main/docs/guides/http-requests.md#py-env-tag-for-importing-our-python-code). `py-env` has, if I'm not mistaken (and very well could be), been deprecated in favor of `py-config`. I'm certain it's not at the top of anyone's list, but I didn't want it to go unnoticed.

**Comment by antocuni** [comment]
I think that @madhur-tandon did some work on those docs recently, so he probably knows whether this issue is valid or has already been fixed

**Comment by mdlattimore** [comment]
If it still needs work, I have made what I think are the appropriate corrections, if that helps.

**Comment by madhur-tandon** [comment]
Hi @mdlattimore It's currently being fixed in PR #914. These docs were written by an external contributor. This will get fixed today most probably.

Thanks for noticing.

**Comment by madhur-tandon** [comment]
Fixed in #914
