### ISSUE TITLE
[[Fetch]] from: should not escape '&' in URLs

### ISSUE THREAD

**Issue by JeffersGlass** [pyscript/pyscript#925]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

Currently, a fetch configuration like
```html
<py-config>
  [[fetch]]
  from = 'https://datausa.io/api/data?drilldowns=Nation&measures=Population'
  to_file = './population_data.json'
</py-config>
```
is parsed with a source URL of `'https://datausa.io/api/data?drilldowns=Nation&amp;measures=Population'` (notice the & has been escaped as **\&amp;**). Trying to fetch from this endpoint fails, since it is, in fact, a different URL.

Not sure if "&" is the only character that's being escaped, but it looks like it's happened as soon as `extractFromInline()` or `extractFromSource()` grab the `innerHTML` of the py-config element, so it may be something that's happening as the DOM is being constructed? That's a little beyond be, if I"m being honest.

Either way, it would be nice to be able to use URL's that contain "&". @madhur-tandon the new [[fetch]] mechanisms are your brainchild - any chance you have a clean solution here?

**Comment by antocuni** [comment]
we probably need to call `htmlDecode` on it, as we do for `<py-script>`:
https://github.com/pyscript/pyscript/blob/a80c5f7eced0e7a1246e9741ec6e21ac546785d7/pyscriptjs/src/components/pyscript.ts#L25-L27

**Comment by madhur-tandon** [comment]
Thanks @antocuni, I have opened a PR fixing this.
@JeffersGlass I have checked the fix from my end but I could appreciate if you could confirm as well.

**Comment by JeffersGlass** [comment]
Thanks for the swift PR all!
