### ISSUE TITLE
target_id is overwritten when id is specified by the user

### ISSUE THREAD

**Issue by marimeireles** [pyscript/pyscript#932]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

Seems like the `async` nature of our `runtime` is not functioning the way we expect to. (This is a guess, I describe the bug after giving some context).

I found this bug while trying to remove the dependency on `ids` with this [PR](https://github.com/pyscript/pyscript/pull/912).
I don't intend to remove all of our `id` generation but just prune it a little bit, removing its overuse.

Here's an example that clarifies what I mean by overuse, consider the following code:

```
<py-script id="first">
    display('hello 1')
</py-script>
```

* This is the DOM it generates:

```
<py-script id='first'> 
  <div id='first-1'>hello 1</div>
</py-script> 
```

My thinking is that having a top `id` for the `py-script` tag + a generated `id` for the new `div` is too much. We should have only one for the `py-script` tag and none for its children. IIRC that's also @tedpatrick's take on `id` usage . (At least for now that's the plan, we can also think about completely extinguishing them, but that's a different discussion).

Okay. So that was the context, let's dive in to the problem I'm seeing. If you have the following code:

```
<py-script id="first">
    display('hello 1')
</py-script>
    <p>hello in between 1 and 2</p>
<py-script id="second">
    display('hello 2')
</py-script>
<py-script id="third">
    display('hello 3')
</py-script>
```

You will get the following DOM tree:

```
<py-script id="first"></py-script>
<p>hello in between 1 and 2</p>
<py-script id="second"></py-script>
<py-script id="third">
  <div id="third-1">hello 1</div>
  <div id="third-2">hello 2</div>
  <div id="third-3">hello 3</div>
</py-script>
```

And this is just wrong.

So, again, I found out about this bug on my work about `id` removal. In the case of my WIP PR something like this causes the page to just overwrite all the printed context since the `id` it focuses is always `third`, to the opposite of `third-1`, `third-2`, `third-3`.

You see, the problem is not necessarily the way we select the output tag, the problem is that once we reach `Element.write()` in the `pyscript.py` file, our dynamic `id` captured in the following line https://github.com/pyscript/pyscript/blob/06a5a54103ae3e23470dcde85911d307ad61edbd/pyscriptjs/src/pyexec.ts#L9 of `pyexec.ts` was overwritten.

I'm not entirely sure of what's happening here, but my guess is that it's related to the nature of `async`?
https://github.com/pyscript/pyscript/blob/06a5a54103ae3e23470dcde85911d307ad61edbd/pyscriptjs/src/pyexec.ts#L14

Very happy to hear your thoughts on this because I'm a bit lost.
Cheers folks!

**Comment by antocuni** [comment]
I think this is a duplicate of #878

**Comment by JeffersGlass** [comment]
You're right that (at least part of) the problem relates to awaiting the evaluation of the Python source. Running your example against the branch for #928 (which reverts to `runPython()` and doesn't await) gives the expected output:

```html
<div id="first-1">hello 1</div>
<py-script id="first">
    <div id="first-1">hello 1</div>
</py-script>
<p>hello in between 1 and 2</p>
<py-script id="second">
    <div id="second-1">hello 2</div>
</py-script>
<py-script id="third">
    <div id="third-1">hello 3</div>
</py-script>
```
----

I think what's going on there is something like the following pseudocode - :
```python
customElements.define("py-script") triggers connectedCallbacks():

    pyExec(first_src):
        set_target_id('first')
        await runPythonAsync(first_src) -> defer execution and move on...

    pyExec(second_src):
        set_target_id('second')
        await runPythonAsync(second_src) -> defer execution and move on...

    pyExec(third_src):
        set_target_id('third')
        await runPythonAsync(third_src) -> defer execution and move on...

    runPythonAsync(first_src) gets to resolve, but target_id is 'third', so "hello 1" outputs to "third"
    runPythonAsync(first_src) gets to resolve, but target_id is 'third', so "hello 2" outputs to "third"
    runPythonAsync(first_src) gets to resolve, target_id is 'third', so "hello 1" outputs to "third"

    ...pyExec(first_src) sets target_id to None
    ...pyExec(second_src) sets target_id to None 
    ...pyExec(third_src) sets target_id to None
```

Check out this dev console screenshot, which includes logging from some parts of the lifecycle in a way that i hope is self-explanatory, and that mirrors the order above:

![image(4)](https://user-images.githubusercontent.com/1931111/200933922-66c47b7e-b377-4a89-b230-484214634214.png)

----

By not awaiting the execution, we'll ensure that each call to `runPython()` is surrounded by `set_target_id(id)` and `set_target_id(None)` in the appropriate order.

As a side effect, and coroutines scheduled within a \<py-script\> tag won't run until _after_ pyExec() has finished, i.e. when `current_target` is None again. So coroutines will need to use `display(..., target=...)`. Which I can live with, and I think is was @antocuni wants 😄

**Comment by marimeireles** [comment]
I think it's a similar issue but here I'm advocating for how the use of user generated `id`s specifically is broken.
If I just allow the automatic `id` generation to do its thing than this issue is not reproducible.
But, I do agree that Jeff's PR will fix both 😊

**Comment by marimeireles** [comment]
Not reproducible!
