### ISSUE TITLE
Error banner now shown if we fail to fetch path with a live server

### ISSUE THREAD

**Issue by FabioRosado** [pyscript/pyscript#934]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a duplication
- [X] I already searched in Google and didn't find any good information or help

## Context

This was reported by @antocuni  in our [community discord](https://discord.com/channels/972017612454232116/1024755729820811334/1039992352267317288).

You can run our tests using the `--dev` flag which will use a real server and should be close enough to running the tests in production.  

While working on a different thing, Antonio noticed that the test `test_py_config.py::test_paths_that_do_not_exist` fails when using `--dev`.

## Debugging

I've ran the test locally using this flag and noticed the following in the console:

```
  | loadFromFile | @ | pyodide.ts:77
  | fetchPaths | @ | main.ts:165
  | setupVirtualEnv | @ | main.ts:152
  | await in setupVirtualEnv (async) |   |  
  | afterRuntimeLoad | @ | main.ts:127
  | setTimeout (async) |   |  
  | hiwire_call_bound | @ | pyodide.asm.js:10
...
```

This looked a bit strange, the first log was coming from `loadFromFile` and not from `fetchPaths` like I would expect. 

https://github.com/pyscript/pyscript/blob/06a5a54103ae3e23470dcde85911d307ad61edbd/pyscriptjs/src/main.ts#L209

So I went to pyodide and looked at `loadFromFile`:

https://github.com/pyscript/pyscript/blob/06a5a54103ae3e23470dcde85911d307ad61edbd/pyscriptjs/src/pyodide.ts#L112

We don't seem to be checking what status code we received before doing things with the response. This makes me think that we aren't handling 404's as we should. 

I'm going to try to raise an exception and this *should* fix the problem

**Comment by antocuni** [comment]
Nice finding!
But now I also would like to understand why it works without --dev, it might indicate another problem in our test machinery

**Comment by FabioRosado** [comment]
That's a good point! I wonder if the test is just a bit wrong? I'm assuming that maybe `fetch` throws the `Unable to fetch` because it doesn't detect a server? 🤔

**Comment by antocuni** [comment]
> I think in this specific case, if we get a FileNotFound error, we shouldn't call `route.abort()` but an equivalent method to throw a 404 but I didn't dig much into it yet

yes, this is exactly what I had in mind
