### ISSUE TITLE
Generate config file that contains all the modules from the standard lib you need and load it. 

### ISSUE THREAD

**Issue by PunchCakee** [pyscript/pyscript#941]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project area (see the above section)

### What is the idea?

Instead of shipping the whole python standard lib why doesn't pyscript go through imports and figure out what libraries this script needs and ship them, For example it would go through the imports and generate a json file that has all the required standard libraries and ship it rather than shipping everything in the stdlib by default. And the json file should be loaded firsthand before anything starts executing. I think it would reduce the time that pyscript takes to load by a lot. And the file should be generated on the dev's machine so pyscript can automatically look for it once the app is deployed.

**Comment by hoodmane** [comment]
This is an upstream Pyodide issue. After @ryanking's work in https://github.com/pyodide/pyodide/pull/3585 the technical hurdles for this have been cleared. A prototype of the requested feature exists here: https://github.com/pyodide/pyodide-pack

**Comment by JeffersGlass** [comment]
The work going on on this exact thought in the Pyodide sphere is super cool! For cleanliness, I'm going to close this as `upstream` here, and encourage those who find this in the future to follow the Pyodide issue that Hood posted.
