### ISSUE TITLE
kill the global `runtime` export in main.ts

### ISSUE THREAD

**Issue by antocuni** [pyscript/pyscript#942]
copy&paste of the original discussion from here:
https://github.com/pyscript/pyscript/pull/868#issuecomment-1311584643

>I agree that we should have a way to interact with the underlying runtime, but I think this solution is conceptually wrong man_shrugging .
> 
> We just introduced a global variable which will is valid/initialized only "at some point": this means that without a synchronization mechanism, your `logFromPython` function might work or not. One of the goals of my recent refactorings was to get rid of global state, and make sure that things are always passed around explicitly, in particular the `runtime` object: with this, we are back to square one.
> 
> One possible solution is to use a [deferred](https://stackoverflow.com/a/34637436):
> 
> ```ts
> export const globalRuntimePromise = Deferred();
> 
> class PyScriptApp {
>     ...
>     async afterRuntimeLoad(runtime: Runtime): Promise<void> {
>         globalRuntimePromise.resolve(runtime);
>     }
> }
> ```
> 
> but this creates other kind of problems: for example, what does it mean that the "runtime" is available? It could mean many different things:
> 
> 1. that `loadPyodide()` has returned something
> 2. that the virtualenv is ready
> 3. that the other scripts on the page have finished to execute
> 4. etc. etc.
> 
> And depending on the context, you want to synchronize with one or the other.
> 
> So, maybe a better solution is to be more explicit; something like this:
> 
> ```
> <button onclick="logFromPython()">Click Me to Run Some Python</button>
> <script>
>     async function logFromPython(){
>         const runtime = await globalApp.waitForRuntimeLoaded();
>         runtime.interpeter.runPython(`
>             animal = "Python"
>             sound = "sss"
>             console.warn(f"{animal}s go " + sound * 5)
>         `)
>     }
> </script>
> ```
> 
> And of course we will have various methods `waitForRuntimeLoaded`, `waitForVirtualenvReady`, etc. This is very connected and related to the work I'm currently doing for plugins; an early concept is this, but more hooks will be added:
> 
> https://github.com/pyscript/pyscript/blob/f26eb637e9fc6aee3d9ea0ef3129be0619646bff/pyscriptjs/src/plugin.ts#L5-L42
> 
> probably we will need a `waitFor...` method for every hook, or something like that.
> 
> **NOTE**: the exact naming of the `waitForRuntimeLoaded` etc, is open for discussion, of course. And the same for `globalApp`: I have the feeling that its name should just be `PyScript`.

**Comment by JeffersGlass** [comment]
Just to move my two cents of the conversation in here from #868:

> All very good points @antocuni - my solution here [in #868] is a pretty blunt sledgehammer to solve a longstanding feature request, but with your work on refactoring, eliminating globals and lifecycle, it can be made better.
> 
> My goal in "re-globalizing" the runtimes object (making it an instance variable of globalApp) was simply to have a way to export a reference to the runtime, but not to undo all your good work passing that object around by reference in the rest of the codebase. Walking that change back, I think, should be straightforward when the time comes, since (as far as I'm aware) the only usage of it as an instance variable of a PyScriptApp instance is exporting it at the end of main.ts.
> 
> The synchronization problem is one I'm familiar with, and I regret not highlighting (or it seems, mentioning at all 😳) in the new docs. See, for example, the [Exporting Objects](https://docs.pyscript.net/latest/guides/passing-objects.html#exporting-all-global-python-objects) sections of the JS/Python objects docs, which I wrote. But as you say, those are user-supplied workarounds for functionality we should provide someohow.
> 
> I too would love to see either a promise-based or event-based system for signaling the status of the PyScript lifecycle (or both - the later could probably be a plugin).

**Comment by WebReflection** [comment]
I think we're all good now with *hooks* but I wonder if *classic* issues should still be opened these days.

**Comment by JeffersGlass** [comment]
Yeah this was very specific to the architecture in _classic_. This can close.
