### ISSUE TITLE
Android WebView support

### ISSUE THREAD

**Issue by LoreBadTime** [pyscript/pyscript#943]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project area (see the above section)

### What is the idea?

Basically PyScript can be run through the android WebView.loadurl("url"). 

The problem comes when trying to inject pyscript code via 

pyscript.runtime.interpreter.runPython("python code") 
from Java/kotlin interface, for some kind of reasons the variable pyscript it's always undefined(i also copied and pasted the pyscript.js code without any result).

I noticed that the code inside pyscript tags runs well, the problems comes from 
Java when it's called

WebView.evaluatejavascript('pyscript.runtime.interpreter.runPython(python_code)',null);

### Why is this needed

This would potentially port the full python interpreter on Android, without requiring big projects like Kivy ecc.

### What should happen?

Should happen the python code evaluation.

**Comment by JeffersGlass** [comment]
What version of PyScript are you using? (`/latest`, `/unstable`, `/releases/version_number?`)?

The ability to access the runtime via `pyscript.runtime...` was only [added recently](https://github.com/pyscript/pyscript/pull/868) (October 23), and hasn't been included into a release. If you're using to `/latest` or `/releases/2022.09.1`, you won't be able to access that object yet.

I suspect the confusion comes from the fact that that that methodology is already in our released docs, but not present in any release yet - we've been releasing docs on every merge to the main branch, which is caused the published docs to get ahead of the published releases. This has come up a few times recently - there's [an open issue](https://github.com/pyscript/pyscript/issues/937) to hopefully rectify this soon.

**Comment by LoreBadTime** [comment]
I used latest available from standard html inclusion, I'll wait to before testing and reporting again.

**Comment by LoreBadTime** [comment]
After a little testing PyScript on Android WebView works like charm, with enough string conversion objects can be passed easily from Python to Java.
Also funny enough in this way Python could be run on real multiple threads from the Java Threads class with multiple WebView.

**Comment by antocuni** [comment]
> if pyscrpt doesn't load fast enough that variable it's undefined, the only workaround working now it's to add a little delay before calling the runPython(like 100 ms).

yes, this is a known problem, see https://github.com/pyscript/pyscript/issues/942

@JeffersGlass see? I told you that this would happen! 😂

**Comment by JeffersGlass** [comment]
How much cash changed hands to make this happen? 😛

Seriously though, you're totally right - having an attribute attribute that's sometimes valid and sometimes not is not great behavior. 

@LoreBadTime In the meantime, if you want to be a little more deterministic about knowing when PyScript has loaded and is ready to run, you can use a setup like the following:

```html
<script>
  document.addEventListener('pyscript-running', () => {
      pyscript.runtime.interpreter.runPython(...)
    }
  )
</script>
<py-script>
   import js
   js.document.dispatchEvent(js.Event.new('pyscript-running'))
</py-script>
```
To be clear, this is a kludge for now - we'll work on a better API for `pyscript.runtime`, and there's multiple proposals in the works for a callback or event-based system of signaling when PyScript is loaded (or both), but for now, may be useful to you.

**Comment by LoreBadTime** [comment]
hi there, i successfully made a native android app working along with pyscript core.
Unfortunately i needed to use webview as running core, however its possible to inject dinamically python code 
via a tiny library i made in java (im not an expert), if you want to try here is the repo https://github.com/LoreBadTime/PyScript-On-Android/tree/main  
its better if you run the project in debug to see how the code is running(i will comment it if needed)

**Comment by WebReflection** [comment]
I think these days are different yet I hope the final result still works ... we also added support for workers lately, and I hope that works well too.
