### ISSUE TITLE
Loading py-script deferred

### ISSUE THREAD

**Issue by javierluraschi** [pyscript/pyscript#95]
This script will load `py-script` properly

```html
<html>
  <body>
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>

    <script>
      var pyscript = document.createElement('py-script');

      pyscript.innerHTML = `
from datetime import datetime
now = datetime.now()

now.strftime("%m/%d/%Y %H:%M:%S")
      `
      document.body.appendChild(pyscript);
    </script>
  </body>
</html>
```

However, this won't load

```html
<html>
  <body>
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>

    <script>
      setTimeout(function() {
        var pyscript = document.createElement('py-script');

        pyscript.innerHTML = `
from datetime import datetime
now = datetime.now()

now.strftime("%m/%d/%Y %H:%M:%S")
        `
        document.body.appendChild(pyscript);
      }, 5000)
    </script>
  </body>
</html>
```

The document won't render, but it seems like the `py-script` is being processed since the tag has been partially expanded into:

```html
<py-script id="PyScript-7ce3dac1-7e77-eca6-81a0-6a387f9aa644">
  <div class="parentBox flex flex-col mx-8">
    <div id="PyScript-7ce3dac1-7e77-eca6-81a0-6a387f9aa644"></div>
  </div>
</py-script>

Any suggestions or workarounds to make the `py-script` work with `setTimeout()`?
```

**Comment by OdinTech3** [comment]
Maybe you should wrap the `setTimeout` in a document.ready or something similar.

**Comment by javierluraschi** [comment]
I can't since the document might change with after loaded. This will be needed to implement something like `jsfiddle` where the user can change the scripts arbitrarily, we could reload everything in an iframe, but loading pyodide takes a few seconds and will make the experience clunky.

If I get a code pointer, I can investigate more. I'll probably debug more anyways, but figured the first step is to open a issue and get feedback.

Also, notice that the element is being processed since it expands to `<py-script>` to `<py-script id="">...`; however, the contents are incomplete and the output is not being rendered.

Any other suggestions?

**Comment by javierluraschi** [comment]
Looks like when the code loads, the `py-scripts` get added to a scrip's queue which then gets executed I'm assuming during some load even.

However, with a timeout, the script gets added here:

https://github.com/pyscript/pyscript/blob/1f2c2420bde7ac99da8ff6146200527005bfbe80/pyscriptjs/src/components/pyscript.ts#L87

But never executed. If I force execution in console with `this.evaluate()` this gets fixed, so I think we just need to execute the scripts queue when more `py-scripts` are added to the DOM.

**Comment by javierluraschi** [comment]
I see, looks like that script queue is only called when pyiodide initializes: https://github.com/pyscript/pyscript/blob/1f2c2420bde7ac99da8ff6146200527005bfbe80/pyscriptjs/src/App.svelte#L38

We would need a change to run the scripts after initialization.

**Comment by fpliger** [comment]
@javierluraschi , can you please provide more information about your use case and what you are trying to do?

**Comment by tedpatrick** [comment]
Here id 2022.09.1 using setTimeout and setInterval

```html
<html>
<head>
    <link rel="stylesheet" href="https://pyscript.net/unstable/pyscript.css" />
    <script defer src="https://pyscript.net/unstable/pyscript.js"></script>
</head>
<body>
    <py-script>
import js
from pyodide.ffi import create_proxy

def foo():
    js.console.log("foo")

def bar():
    js.console.log("bar")

js.setTimeout(create_proxy(foo))
js.setInterval(create_proxy(bar),1000)
    </py-script>
</body>
</html>
