### ISSUE TITLE
get/set functions to get code from REPL

### ISSUE THREAD

**Issue by cruncher12** [pyscript/pyscript#954]
It's possible to fetch the code from a REPL tag as described by Jeff in the [comment](https://github.com/pyscript/pyscript/issues/954#issuecomment-1316203134), but it'd be ideal to have an official API implemented.

Original issue:
I know this is not something directly PyScript related, but is there a way of getting the current code in a py-repl via JS? I am working on something and that is needed. I understand it would probably be as simple as getting the text in an element, but what element would that be? Another thing: can you preload code into a REPL so it is not needed to be typed out every time you load the page?

**Comment by marimeireles** [comment]
@cruncher12 does Jeff's reply answer your question?
If yes, please feel free to close the issue.
Cheers!

**Comment by antocuni** [comment]
well, I'm not sure it's a good idea closing this issue. Jeff's answer might work but it's basically a workaround, and @cruncher12 's request seems very reasonable: py-repl should have an official API to get/set the code in the editor.
I think it's perfectly find to leave this issue open until we have a proper fix (or maybe open a new one with a better name and description, happy to let you decide :))

**Comment by marimeireles** [comment]
If you think this makes sense to add in the API :) I'm pro.

**Comment by radeeyate** [comment]
Hey 👋
I'm sorry it's taken so long to respond to this. (I'm on this account now.) I was wondering if this is still planned/in the works as I'm going to need it for sparkshell.dev (a coding website I'm making.)

**Comment by WebReflection** [comment]
As we don't have `py-repl` at all anymore, and I think both terminal and editor allows this issue to be solved, I *think* this issue can be closed.
