### ISSUE TITLE
Add error code to exceptions raised by PyScript

### ISSUE THREAD

**Issue by FabioRosado** [pyscript/pyscript#956]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a duplication
- [X] I already searched in Google and didn't find any good information or help

### What is the issue/comment/problem?

While chatting with Antonio today, he mentioned that adding an error code to our custom exceptions would be great so we would have different types of `UserError`, `FechError`, etc.   

With these error codes, we can create documentation for each of the so our users can refer to if needed when they are creating their PyScript apps. Ideally, the error messages would also point to the relevant documentation links.

The proposal is to make this code required, so any developer working on the PyScript core, would have to include the appropriate code or create a new one and write docs for it. The code could be something along the lines of:

```js
export class UserError extends Error {
  messageType: MessageType;

  constructor(errorCode: string, message: string, t: MessageType = "text") {
    super(message);
    this.errorCode: errorCode
    this.name = "UserError";
    this.messageType = t;
  }
}
```

We can then create an UserError with `throw new UserError("PY422", "Bad thing happened!")` 

@antocuni  Just wanted to ping you here to confirm that this is what you had in mind?

**Comment by madhur-tandon** [comment]
This sounds like a really good idea!

**Comment by antocuni** [comment]
> This may be a terrible idea, but we could allow numbers as errorCode and then use switch statements that would attribute the right enum, the default would be raising an error saying that we couldn't find that code thinking

this looks strictly worse that than the "union of literals" idea, because it has the same pros/cons, but it does the check at runtime instead of compile time, unless I'm missing something

**Comment by FabioRosado** [comment]
> > This may be a terrible idea, but we could allow numbers as errorCode and then use switch statements that would attribute the right enum, the default would be raising an error saying that we couldn't find that code thinking
> 
> this looks strictly worse that than the "union of literals" idea, because it has the same pros/cons, but it does the check at runtime instead of compile time, unless I'm missing something

Yeah it's not a great solution, it was mostly a way to tr an avoid doing the double imports 🤔  Oh... on typing I guess we could do `valueOf enums` and that *should* work?  Let me try that 😄

**Comment by FabioRosado** [comment]
After thinking a bit more about this I'm +1 on the Enums idea, after searching online it seems we can do some typescript magic to do something like this:

```ts
throw new UserError("Blah", UserError.ErrorCode.BAD_CONFIG)
```

I'm not keen on the `UserError.ErrorCode` but maybe that's okay if we dont have to explicitly import it. 
I'll keep on hacking at this and open a draft PR later today :D 


Also I'm thinking to add specific error code range for different things, something like:

0001 - Deprecation
1xxx - Config related
2xxx - something else
