### ISSUE TITLE
Repl Output is replaced even if it shouldn't (i.e. loops)

### ISSUE THREAD

**Issue by limitcracker** [pyscript/pyscript#975]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

In latest version when I have a loop inside a `<py-repl>` I get the output replaced each time instead of appended.

i.e.
```
<py-repl id="my-repl-11nov22-1333" auto-generate="true"> 
for i in range(10):
    print(i)
</py-repl>
```

### What browsers are you seeing the problem on? (if applicable)

Chrome

**Comment by limitcracker** [comment]
is there an option for the repl tag in order to **not** reload like it did in the `alpha` version?

**Comment by marimeireles** [comment]
Yep! Good catch, I'm looking into it.
Thanks @limitcracker :)
Also if you want to dive into debugging feel free to!

**Comment by limitcracker** [comment]
Merry Christmas, @marimeireles !
I see that the loops output has been fixed and now it been appended.
But is there a way to have a setting in order to be replaced if we need to?
i.e.
`<py-repl id="my-repl1" auto-replace-output="true"> </py-repl>`

Any ideas?

**Comment by marimeireles** [comment]
Yes! The output support was removed but it's soon to be reintroduced by Jeff's PR #1063!
So just keep an eye for when that change roll in I guess :)
Thanks for the feedback and hope you had nice holidays!
