### ISSUE TITLE
Shift+Enter in py-repl inserts a newline

### ISSUE THREAD

**Issue by antocuni** [pyscript/pyscript#984]
if you press Shift+Enter in a `py-repl`, it does two things:
1. execute the code (as expected)
2. insert a newline (this is wrong).

See e.g. the example below (I pressed Shift+Enter when the cursor was on the `d`):
![image](https://user-images.githubusercontent.com/344507/203973101-f9cdcece-6827-43d9-9890-6bce30405750.png)

**Comment by antocuni** [comment]
For reference, this is the code which setups the keybindings:
https://github.com/pyscript/pyscript/blob/a6280268383d92fe180f32b500a7829aeac7f877/pyscriptjs/src/components/pyrepl.ts#L63-L84

**Comment by FabioRosado** [comment]
Thanks for this! I was wondering if my keyboard was acting up when it was just inserting a new line haha
