### ISSUE TITLE
Push different pyscript versions of examples

### ISSUE THREAD

**Issue by FabioRosado** [pyscript/pyscript#987]
Basically, I don't care too much about the exact naming, but I care a lot about being consistent between all the various things which we publish. Another of this is `examples`: currently they are published here:
https://pyscript.net/examples/

ideally, I would like to be able to have published examples for every version of pyscript (including unstable): something like:

https://pyscript.net/examples/     <=== redirect to the latest release, 2022.09.1
https://pyscript.net/examples/2022.09.1/
https://pyscript.net/examples/2022.06.1/
https://pyscript.net/examples/unstable/

And of course, it is important to have consistent names between releases, docs and examples.

_Originally posted by @antocuni in https://github.com/pyscript/pyscript/issues/937#issuecomment-1324876967_

**Comment by WebReflection** [comment]
this repo no longer has anything to do with `pyscript.net` so I *think* this issue can be closed.
