### ISSUE TITLE
Add Plugin Lifecycle Hooks/Events Before and After Each Py-Repl Evaluation

### ISSUE THREAD

**Issue by JeffersGlass** [pyscript/pyscript#988]
A user in the discord recently have asked if it's possible to do the following:
```python
<py-repl>
print("Hello, world")
</py-repl>
```
And take some action based on what's output to standard out. 

Another would like to be able to do:
```python
<py-repl>
x = 42
</py-repl>
```
And to have a Event or callback to allow for JS to react to possible changes in Python variables in the REPL, and to react accordinly.

Both seem reasonable - it would be nice to have a callback before each REPL executes, with some information passed to the callback about which REPL or what's about to be executed. (Does it get the src about to be executed? The REPL ID? Not sure on the details here). This would allow devs to write REPLs in-page that do some pre-processing or analysis on the code prior to its execution.

It would also be nice to have a callback and/or event after each REPL evaluation - also with some kind of indication of what was just run, and possibly being passed the result of the evaluation. Again, not sure exactly what the specifics would be.

(I'm not sure it makes sense to dispatch an event _before_ the REPL evaluates - due to synchronization in the event loop, you wouldn't be guaranteed that any code triggered would run before the REPL starts evaluating. I could be wrong though).

Similar (but not covered by) #944.

**Comment by antocuni** [comment]
This reminds me of the recent post made on discord by @mchilvers: https://discord.com/channels/972017612454232116/1024755729820811334/1044541611046080542

In the Envisage plugin system that he described, each plugin can define additional "extension points" and hooks to be used by other plugins.

Probably there are many possible solution to this problem; I think the following two are at the opposite extremes of a continuum:
1. introduce ad-hoc hooks/events for py-repl
2. introduce a completely generic system similar to the one used by Envisage

I genuinely don't know what is the approach which fits best pyscript goals. Could be (1), (2) or anything in between, but I think it's a good idea to start thinking about it.
