### ISSUE TITLE
Intermittent Failure to Load Plugin Files

### ISSUE THREAD

**Issue by JeffersGlass** [pyscript/pyscript#989]
An intermittent fatal  issue is popping up when trying to load plugin files using the machinery in #961 . It feels timing-related to me - given that it seems to fail only intermittently and changing where the JS is sourced from seems to change the outcome (!).

- Create a new html file in the `examples` folder with the content:
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <script defer src="../pyscriptjs/build/pyscript.js"></script>
  <link rel="stylesheet" href="../pyscriptjs/build/pyscript.css">
</head>
<body>
  <py-config>
    plugins = ['first_plugin.py']
  </py-config>
  <py-script>
    display("Hello, world")
  </py-script>
</body>
</html>
```
- Create a second file in the same folder named `first_plugin.py` with the contents:
```python
from pyscript import Plugin

class my_first_plugin(Plugin):
    def configure(*args):
        print("Plugin being configrued")

plugin = my_first_plugin("myFirstPlugin")
```
- Load the HTML file via a server (tested with `python3 -m http.server` and VS Code's live server).

Approximately one out of every three times the page is reloaded, 'first_plugin' fails to import, with the error:

```
(PY0001): PyScript encountered an error while loading from file:
 Traceback (most recent call last): File "/lib/python3.10/importlib/__init__.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "",
line 1050, in _gcd_import File "",
 line 1027, in _find_and_load File "",
 line 1004, in _find_and_load_unlocked ModuleNotFoundError:
 No module named 'first_plugin'
```

## Notes 

- Sourcing the js from `https://pyscript.net/unstable/pyscript.js`, the issue does not occur. **Update - The integration tests failed on merging #961, so /unstable has fallen behind the current /main branch**
- Tested on Ubuntu 22.04 (Chromium) and Windows 10 (Chrome) with similar results

**Comment by FabioRosado** [comment]
Still haven't figured what's happening, but it seems that the tests pass is the flakiness.
Looking into `test_paths_from_packages` and using `pytest-repeat` the test seems to fail 8 out of 2 times. The failure is also misleading.

The failure is related to the expected console log not found, but when using the `--dev` flag, it seems that the issue is caused by `pkg` not being found.

**Comment by antocuni** [comment]
Leaving this comment for posterity: it seems very likely that the root cause was this pyodide/emscripten issue:
https://github.com/pyodide/pyodide/issues/3311
