### ISSUE TITLE
pandas please

### ISSUE THREAD

**Issue by Lodimup** [pyscript/pyscript#99]
It would be super great if pandas is included!

**Comment by verhulstm** [comment]
it should be included already

use this tag above your pyscript tag

  <py-env>
    - pandas
  </py-env>

**Comment by verhulstm** [comment]
<html>
  <head>
    <title>pandas</title>
    <meta charset="utf-8">

    <link rel="stylesheet" href="../build/pyscript.css" />
    <script defer src="../build/pyscript.js"></script>
    <py-env>
      - pandas
    </py-env>
    </head>
    <body>
      <py-script>
import pandas as pd
dates = pd.date_range("20130101", periods=6)
dates
      </py-script>
    </body>
</html>

**Comment by Lodimup** [comment]
Thanks! Holycrap, even input() works. This is game changer.

**Comment by Lodimup** [comment]
Thanks! Holycrap, even input() works. This is game changer.
