### ISSUE TITLE
pyscript module not available

### ISSUE THREAD

**Issue by pmerienne** [pyscript/pyscript#993]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

While trying example code from https://docs.pyscript.net/latest/reference/modules/pyscript.html :
```js
<script defer onload="console.log(`${pyscript.version}`)" src="https://pyscript.net/latest/pyscript.js"></script>
```

I got an error in the brower : `Uncaught ReferenceError: pyscript is not defined`
It seems that the pyscript module is not exported to the browser as `pyscript`.

Here's a simple example to reproduce this issue : 
```html

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />

    <title>REPL</title>
    <link rel="stylesheet" href="https://pyscript.net/latest/pyscript.css" />
    <script defer onload="console.log(`Pyscript version: ${pyscript.version}`)" src="https://pyscript.net/latest/pyscript.js"></script>
    <script>
        function showVersion() {
            alert('Pyscript version: ' + pyscript.version);
        }
    </script>

  </head>

  <body>
    Hello world! <br>
   Clicking this button will also fail :
    <button onclick="showVersion()">Click me to know pyscript version</button>
  </body>
</html>
```

### What browsers are you seeing the problem on? (if applicable)

Chrome

### Console info

```shell
Uncaught ReferenceError: pyscript is not defined
    at HTMLScriptElement.onload (index.html:12:160)
```

**Comment by pmerienne** [comment]
In another documentation page (https://docs.pyscript.net/latest/guides/passing-objects.html#javascript-to-pyscript), I saw this example : 
```html
<html>
    <head>
      <link rel="stylesheet" href="https://pyscript.net/latest/pyscript.css" />
      <script defer src="https://pyscript.net/latest/pyscript.js"></script>
    </head>

    <body>
        <!-- Click this button to log 'Apple', 'Banana', 'Candy', 'Donut' by sorting in Python-->
        <button onclick="sortInPython(['Candy', 'Donut', 'Apple', 'Banana'])">Sort In Python And Log</button>
        <script>
            function sortInPython(data){
                js_sorted = PyScript.runtime.globals.get('sorted') //grab python's 'sorted' function
                const sorted_data = js_sorted(data) //apply the function to the 'data' argument
                for (const item of sorted_data){
                    console.log(item)
                }
            }
        </script>
    </body>
</html>
```

This time, the pyscript module has a different name `PyScript` but it's still not working as expected. Indeed I have the error : `Uncaught ReferenceError: PyScript is not defined`

**Comment by JeffersGlass** [comment]
Hi @pmerienne - there are two things going on here. 

First, until quite recently, we had been pushing updates documentation to the default (`/latest`) section _on every merge to the main branch_, so documentation was being released for features that had not been released yet. As of #977, that has been fixed - docs.pyscript.net (which redirects to /latest) will only be updated during a new release, and docs.pyscript.net/unstable will receive updates with each merge.

This all to say - accessing the `pyscript` js module is not available in the current release, but will be in the upcoming release.

The second issue (`PyScript` vs `pyscript` as a name for the js module) is a typo of mine when I was originally writing that page of the documentation. The correct name of the js module is `pyscript` (all lowercase). @FabioRosado's got a PR open to fix that (#982), that I imagine we'll get merged quite soon.

**Comment by pmerienne** [comment]
Hi @JeffersGlass ,

Thank you for your quick answer, I will wait for the next release for this feature to be available.

In the meantime : 
- Is there a way to access old release pyscript.js without having to build it ?
- Is there another way to pass objects between javascript and pythin runtimes ?

Anywa, great job with this project !

**Comment by JeffersGlass** [comment]
If you want to play with the new features in development, you can source the bleeding-edge build at `https://pyscript.net/unstable/pyscript.js`. Fair warning, it truly is bleeding edge, and some things may as yet be broken.

If you want to link to the current or previous stable releases, they're available at:

- https://pyscript.net/releases/2022.05.1/pyscript.js (_alpha_)
- https://pyscript.net/releases/2022.06.1/pyscript.js
- https://pyscript.net/releases/2022.09.1/pyscript.js (latest stable release)

As for passing objects between JS and Python, [this section of the docs outlines some methods](https://docs.pyscript.net/latest/guides/passing-objects.html). In summary: `from js import ...` imports objects from the javascript global scope into Python. If you want to create/update a JavaScript global variable from a Python variable, one of the cleanest ways is:

```html
<py-script>
    import js
    my_python_variable = 43
    js.my_js_variable = my_python_variable
</pyscript>
```

Of course, js has no way of "knowing" that variable has been created, and since PyScript loads `defer`'d (i.e. after most scripts on the page have run), you may want to use an Event or other method to signal JS to take action with that variable.

**Comment by pmerienne** [comment]
Again, thank you @JeffersGlass that exactly what I needed !

Have a nice day and best wishes for your work.

**Comment by madhur-tandon** [comment]
Should we close this @JeffersGlass ?

**Comment by JeffersGlass** [comment]
Yes let's!
